// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	isovalentcomv1 "github.com/cilium/cilium/pkg/k8s/apis/isovalent.com/v1"
)

// BGPAutoDiscoveryApplyConfiguration represents a declarative configuration of the BGPAutoDiscovery type for use
// with apply.
type BGPAutoDiscoveryApplyConfiguration struct {
	Mode       *isovalentcomv1.BGPAutoDiscoveryMode `json:"mode,omitempty"`
	Unnumbered *BGPUnnumberedApplyConfiguration     `json:"unnumbered,omitempty"`
}

// BGPAutoDiscoveryApplyConfiguration constructs a declarative configuration of the BGPAutoDiscovery type for use with
// apply.
func BGPAutoDiscovery() *BGPAutoDiscoveryApplyConfiguration {
	return &BGPAutoDiscoveryApplyConfiguration{}
}

// WithMode sets the Mode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Mode field is set to the value of the last call.
func (b *BGPAutoDiscoveryApplyConfiguration) WithMode(value isovalentcomv1.BGPAutoDiscoveryMode) *BGPAutoDiscoveryApplyConfiguration {
	b.Mode = &value
	return b
}

// WithUnnumbered sets the Unnumbered field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Unnumbered field is set to the value of the last call.
func (b *BGPAutoDiscoveryApplyConfiguration) WithUnnumbered(value *BGPUnnumberedApplyConfiguration) *BGPAutoDiscoveryApplyConfiguration {
	b.Unnumbered = value
	return b
}
