// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// BGPVRFApplyConfiguration represents a declarative configuration of the BGPVRF type for use
// with apply.
type BGPVRFApplyConfiguration struct {
	VRFRef    *string  `json:"vrfRef,omitempty"`
	ConfigRef *string  `json:"configRef,omitempty"`
	RD        *string  `json:"rd,omitempty"`
	ImportRTs []string `json:"importRTs,omitempty"`
	ExportRTs []string `json:"exportRTs,omitempty"`
}

// BGPVRFApplyConfiguration constructs a declarative configuration of the BGPVRF type for use with
// apply.
func BGPVRF() *BGPVRFApplyConfiguration {
	return &BGPVRFApplyConfiguration{}
}

// WithVRFRef sets the VRFRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the VRFRef field is set to the value of the last call.
func (b *BGPVRFApplyConfiguration) WithVRFRef(value string) *BGPVRFApplyConfiguration {
	b.VRFRef = &value
	return b
}

// WithConfigRef sets the ConfigRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ConfigRef field is set to the value of the last call.
func (b *BGPVRFApplyConfiguration) WithConfigRef(value string) *BGPVRFApplyConfiguration {
	b.ConfigRef = &value
	return b
}

// WithRD sets the RD field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RD field is set to the value of the last call.
func (b *BGPVRFApplyConfiguration) WithRD(value string) *BGPVRFApplyConfiguration {
	b.RD = &value
	return b
}

// WithImportRTs adds the given value to the ImportRTs field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ImportRTs field.
func (b *BGPVRFApplyConfiguration) WithImportRTs(values ...string) *BGPVRFApplyConfiguration {
	for i := range values {
		b.ImportRTs = append(b.ImportRTs, values[i])
	}
	return b
}

// WithExportRTs adds the given value to the ExportRTs field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ExportRTs field.
func (b *BGPVRFApplyConfiguration) WithExportRTs(values ...string) *BGPVRFApplyConfiguration {
	for i := range values {
		b.ExportRTs = append(b.ExportRTs, values[i])
	}
	return b
}
