// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	metav1 "github.com/cilium/cilium/pkg/k8s/slim/k8s/apis/meta/v1"
)

// EgressGroupApplyConfiguration represents a declarative configuration of the EgressGroup type for use
// with apply.
type EgressGroupApplyConfiguration struct {
	NodeSelector    *metav1.LabelSelector `json:"nodeSelector,omitempty"`
	Interface       *string               `json:"interface,omitempty"`
	EgressIP        *string               `json:"egressIP,omitempty"`
	MaxGatewayNodes *int                  `json:"maxGatewayNodes,omitempty"`
}

// EgressGroupApplyConfiguration constructs a declarative configuration of the EgressGroup type for use with
// apply.
func EgressGroup() *EgressGroupApplyConfiguration {
	return &EgressGroupApplyConfiguration{}
}

// WithNodeSelector sets the NodeSelector field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NodeSelector field is set to the value of the last call.
func (b *EgressGroupApplyConfiguration) WithNodeSelector(value metav1.LabelSelector) *EgressGroupApplyConfiguration {
	b.NodeSelector = &value
	return b
}

// WithInterface sets the Interface field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Interface field is set to the value of the last call.
func (b *EgressGroupApplyConfiguration) WithInterface(value string) *EgressGroupApplyConfiguration {
	b.Interface = &value
	return b
}

// WithEgressIP sets the EgressIP field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EgressIP field is set to the value of the last call.
func (b *EgressGroupApplyConfiguration) WithEgressIP(value string) *EgressGroupApplyConfiguration {
	b.EgressIP = &value
	return b
}

// WithMaxGatewayNodes sets the MaxGatewayNodes field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxGatewayNodes field is set to the value of the last call.
func (b *EgressGroupApplyConfiguration) WithMaxGatewayNodes(value int) *EgressGroupApplyConfiguration {
	b.MaxGatewayNodes = &value
	return b
}
