// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// IsovalentBGPNodeConfigPeerOverrideApplyConfiguration represents a declarative configuration of the IsovalentBGPNodeConfigPeerOverride type for use
// with apply.
type IsovalentBGPNodeConfigPeerOverrideApplyConfiguration struct {
	Name          *string                             `json:"name,omitempty"`
	LocalAddress  *string                             `json:"localAddress,omitempty"`
	AutoDiscovery *BGPAutoDiscoveryApplyConfiguration `json:"autoDiscovery,omitempty"`
	LocalPort     *int32                              `json:"localPort,omitempty"`
}

// IsovalentBGPNodeConfigPeerOverrideApplyConfiguration constructs a declarative configuration of the IsovalentBGPNodeConfigPeerOverride type for use with
// apply.
func IsovalentBGPNodeConfigPeerOverride() *IsovalentBGPNodeConfigPeerOverrideApplyConfiguration {
	return &IsovalentBGPNodeConfigPeerOverrideApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *IsovalentBGPNodeConfigPeerOverrideApplyConfiguration) WithName(value string) *IsovalentBGPNodeConfigPeerOverrideApplyConfiguration {
	b.Name = &value
	return b
}

// WithLocalAddress sets the LocalAddress field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LocalAddress field is set to the value of the last call.
func (b *IsovalentBGPNodeConfigPeerOverrideApplyConfiguration) WithLocalAddress(value string) *IsovalentBGPNodeConfigPeerOverrideApplyConfiguration {
	b.LocalAddress = &value
	return b
}

// WithAutoDiscovery sets the AutoDiscovery field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AutoDiscovery field is set to the value of the last call.
func (b *IsovalentBGPNodeConfigPeerOverrideApplyConfiguration) WithAutoDiscovery(value *BGPAutoDiscoveryApplyConfiguration) *IsovalentBGPNodeConfigPeerOverrideApplyConfiguration {
	b.AutoDiscovery = value
	return b
}

// WithLocalPort sets the LocalPort field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LocalPort field is set to the value of the last call.
func (b *IsovalentBGPNodeConfigPeerOverrideApplyConfiguration) WithLocalPort(value int32) *IsovalentBGPNodeConfigPeerOverrideApplyConfiguration {
	b.LocalPort = &value
	return b
}
