// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// IsovalentBGPNodeSpecApplyConfiguration represents a declarative configuration of the IsovalentBGPNodeSpec type for use
// with apply.
type IsovalentBGPNodeSpecApplyConfiguration struct {
	BGPInstances []IsovalentBGPNodeInstanceApplyConfiguration `json:"bgpInstances,omitempty"`
}

// IsovalentBGPNodeSpecApplyConfiguration constructs a declarative configuration of the IsovalentBGPNodeSpec type for use with
// apply.
func IsovalentBGPNodeSpec() *IsovalentBGPNodeSpecApplyConfiguration {
	return &IsovalentBGPNodeSpecApplyConfiguration{}
}

// WithBGPInstances adds the given value to the BGPInstances field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the BGPInstances field.
func (b *IsovalentBGPNodeSpecApplyConfiguration) WithBGPInstances(values ...*IsovalentBGPNodeInstanceApplyConfiguration) *IsovalentBGPNodeSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithBGPInstances")
		}
		b.BGPInstances = append(b.BGPInstances, *values[i])
	}
	return b
}
