// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// IsovalentBGPNodeConfigOverrideSpecApplyConfiguration represents a declarative configuration of the IsovalentBGPNodeConfigOverrideSpec type for use
// with apply.
type IsovalentBGPNodeConfigOverrideSpecApplyConfiguration struct {
	BGPInstances []IsovalentBGPNodeConfigInstanceOverrideApplyConfiguration `json:"bgpInstances,omitempty"`
}

// IsovalentBGPNodeConfigOverrideSpecApplyConfiguration constructs a declarative configuration of the IsovalentBGPNodeConfigOverrideSpec type for use with
// apply.
func IsovalentBGPNodeConfigOverrideSpec() *IsovalentBGPNodeConfigOverrideSpecApplyConfiguration {
	return &IsovalentBGPNodeConfigOverrideSpecApplyConfiguration{}
}

// WithBGPInstances adds the given value to the BGPInstances field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the BGPInstances field.
func (b *IsovalentBGPNodeConfigOverrideSpecApplyConfiguration) WithBGPInstances(values ...*IsovalentBGPNodeConfigInstanceOverrideApplyConfiguration) *IsovalentBGPNodeConfigOverrideSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithBGPInstances")
		}
		b.BGPInstances = append(b.BGPInstances, *values[i])
	}
	return b
}
