// Copyright (C) Isovalent, Inc. - All Rights Reserved.
//
// NOTICE: All information contained herein is, and remains the property of
// Isovalent Inc and its suppliers, if any. The intellectual and technical
// concepts contained herein are proprietary to Isovalent Inc and its suppliers
// and may be covered by U.S. and Foreign Patents, patents in process, and are
// protected by trade secret or copyright law.  Dissemination of this information
// or reproduction of this material is strictly forbidden unless prior written
// permission is obtained from Isovalent Inc.

package connectionlog

import (
	flowpb "github.com/cilium/cilium/api/v1/flow"
	"github.com/cilium/cilium/pkg/lock"
)

// flowstatkey defines how Hubble flows are aggregated into different
// connections.
type flowstatkey struct {
	srcIP, dstIP string
	srcID, dstID uint32
}

// flowstatval hold statistics from a "connection edge" (in the IPA graphV1 API
// sense, not necessarily a 1:1 mapping to a networking connection). It include
// a sample Hubble flow as a shortcut to hold the necessary info to build the
// connection's graphV1 vertices.
type flowstatval struct {
	// flow is a sample Hubble flow from which we can extract the endpoints and
	// networking layers information to build source and destination
	// graphV1.Vertex at export time.
	flow *flowpb.Flow
	// the following values match distinct flowpb.Verdict and are mapped as a
	// graphV1.EdgeTypeRoutingTelemetry message at export time.
	//
	// Not sure how useful are socketlb related flows as they describe a
	// translation from a service ip to a backend pod ip but there is no way to
	// express that in graphV1. Ideally, we would keep track of a pod -> svc ->
	// backend chain and report the connection with both the svc and backend as
	// destination.
	//
	// policy verdict events are translated into hubble flows a
	// verdict=forwarded, we probably want to either handle them specifically
	// or ignore them completely.
	forwarded  uint64
	dropped    uint64
	errored    uint64 // only generated from accesslog (proxy)
	audited    uint64 // only generated from policy verdict
	redirected uint64 // only generated from policy verdict
	traced     uint64 // only generated by socketlb
	translated uint64 // only generated by socketlb
}

type connLogDB struct {
	mu    lock.Mutex
	store map[flowstatkey]flowstatval
}

func newConnLogDB() *connLogDB {
	return &connLogDB{
		store: make(map[flowstatkey]flowstatval),
	}
}

// add updates the database to account for the given flow. It is safe to call
// add() and reset() concurrently.
func (db *connLogDB) add(flow *flowpb.Flow) {
	// NOTE: add() is the "hot codepath" of the Hubble ConnLogger as it is
	// called for every Hubble flow, so keep it fast.
	k := flowstatkey{
		srcIP: flow.GetIP().GetSource(),
		dstIP: flow.GetIP().GetDestination(),
		srcID: flow.GetSource().GetIdentity(),
		dstID: flow.GetDestination().GetIdentity(),
	}

	db.mu.Lock()
	defer db.mu.Unlock()

	v := db.store[k]
	// ignoring flowpb.Verdict_VERDICT_UNKNOWN
	switch flow.GetVerdict() {
	case flowpb.Verdict_FORWARDED:
		v.forwarded += 1
	case flowpb.Verdict_DROPPED:
		v.dropped += 1
	case flowpb.Verdict_ERROR:
		v.errored += 1
	case flowpb.Verdict_AUDIT:
		v.audited += 1
	case flowpb.Verdict_REDIRECTED:
		v.redirected += 1
	case flowpb.Verdict_TRACED:
		v.traced += 1
	case flowpb.Verdict_TRANSLATED:
		v.translated += 1
	}
	v.flow = flow
	db.store[k] = v
}

// reset returns the current map store and reset it. It is safe to call add()
// and reset() concurrently.
func (db *connLogDB) reset() map[flowstatkey]flowstatval {
	// reset() is not called often, but it has to stay fast to avoid lock
	// contention with add() as both need to hold the db mutex.
	db.mu.Lock()
	defer db.mu.Unlock()

	ret := db.store
	db.store = make(map[flowstatkey]flowstatval)
	return ret
}
