{{- if and
  .Values.hubble.timescape.enabled
  (or
    (not .Values.hubble.timescape.clustermesh.primary.id)
    (eq (int64 .Values.hubble.timescape.clustermesh.primary.id) (int64 .Values.cluster.id))
  )
}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hubble-timescape-config
  namespace: {{ include "cilium.namespace" . }}
  {{/* The timescape labels already contain the .Values.commonLabels */}}
  labels: {{ include "hubble.timescape.labels" . | nindent 4 }}
data:
  config.yaml: |
    log-level: {{ .Values.hubble.timescape.logLevel | quote }}
    {{- if .Values.hubble.timescape.metrics.enabled }}
    prometheus-serve-addr: ":9090"
    {{- end }}
    pprof: true
    pprof-address: "localhost"
    pprof-port: "6060"
    gops: true
    gops-port: "9898"
    flows-ttl: {{ include "hubble.timescape.ttl" . }}
    k8s-ttl: {{ include "hubble.timescape.ttl" . }}
    use-distributed-tables: false
    use-distributed-ddl: false
    enable-clickhouse-server-logs: false
    log-query-progress: false
    health-listen-address: ":8083"
    server:
      {{- if .Values.hubble.rbac.enabled }}
      listen-address: localhost:4244
      {{- else }}
      listen-address: :4244
      {{- end }}
      {{- if and (not .Values.hubble.rbac.enabled) ( eq (include "hubble.timescape.tls.enabled" .) "true" )}}
      enable-tls: true
      tls-cert-file: /var/lib/hubble-timescape/tls/server.crt
      tls-key-file: /var/lib/hubble-timescape/tls/server.key
      {{- end }}
      enable-experimental-api: true
    ingester:
      batch-size: 10000
      cluster-name: {{ .Values.cluster.name | quote }}
      enable-flows-ingestion: true
      enable-fgs-events-ingestion: false
      enable-k8s-events-ingestion: true
      report-interval: 60s
      enable-stream-api: true
      stream-api-flush-interval: {{ .Values.hubble.timescape.ingester.streamAPI.flushInterval }}
      enable-push-api: true
      push-api-listen-address: :4260
      {{- if eq (include "hubble.timescape.tls.enabled" .) "true" }}
      stream-api-tls-enabled: true
      stream-api-tls-cert-file: /var/lib/hubble-timescape/tls/server.crt
      stream-api-tls-key-file: /var/lib/hubble-timescape/tls/server.key
      stream-api-tls-client-ca-files:
        - /var/lib/hubble-timescape/tls/ca.crt
      push-api-tls-enabled: true
      push-api-tls-cert-file: /var/lib/hubble-timescape/tls/server.crt
      push-api-tls-key-file: /var/lib/hubble-timescape/tls/server.key
      push-api-tls-client-ca-files:
        - /var/lib/hubble-timescape/tls/ca.crt
      {{- end }}
      push-api-async-insert: "true"
      push-api-async-insert-busy-timeout: 2s
      push-api-async-insert-max-data-size: 104857600
      filter-batch-size: 100
      filter-batch-window: 10s
      {{- if .Values.hubble.timescape.ingester.k8sImporter.enabled }}
      enable-k8s-importer: true
      k8s-importer-cluster-name: {{ .Values.cluster.name | quote }}
      k8s-importer-flush-interval: {{ .Values.hubble.timescape.ingester.k8sImporter.flushInterval | quote }}
      k8s-importer-k8s-endpoints: false
      k8s-importer-cilium-endpoints: false
      k8s-importer-cilium-identities: true
      {{- end }}
    migrate:
      clickhouse-nodes-count: "0"
    trimmer:
      flows-count: {{ .Values.hubble.timescape.trimmer.flowsCount }}
      trim-interval: {{ printf "%.fm" .Values.hubble.timescape.trimmer.intervalMinutes }}
      timeout: {{ .Values.hubble.timescape.trimmer.timeout | default (printf "%.fm" .Values.hubble.timescape.trimmer.intervalMinutes) }}
    enable-analyzer: {{ .Values.hubble.timescape.analyzer.enabled }}
    {{- if .Values.hubble.timescape.analyzer.enabled }}
    analyzer:
      schedule-interval: {{ .Values.hubble.timescape.analyzer.scheduleInterval }}
    {{- end }}
    enable-ui: {{ .Values.hubble.timescape.ui.enabled }}
    {{- if .Values.hubble.timescape.ui.enabled }}
    ui:
      http-address: ":8080"
      {{- if .Values.hubble.rbac.enabled }}
      timescape-address: "localhost:4245"
      {{- else }}
      timescape-address: "localhost:4244"
      {{- end }}
      {{- if eq (include "hubble.timescape.tls.enabled" .) "true" }}
      timescape-enable-tls: true
      timescape-ca-files: /var/lib/hubble-timescape/tls/ca.crt
      {{- else }}
      timescape-enable-tls: false
      {{- end }}
      {{- if (eq (include "hubble.timescape.ui.auth.enabled" .) "true") }}
      oauth2:
        enabled: true
        oidc:
          {{- $clientID := .Values.hubble.timescape.ui.auth.oidc.clientID | default .Values.hubble.rbac.auth.oidc.clientID }}
          {{- if not $clientID }}
          {{ fail "Invalid configuration, .hubble.timescape.ui.auth.oidc.clientID needs to be set when authentication is enabled." }}
          {{- end }}
          client-id: {{ $clientID }}
          client-assertion-type: {{ .Values.hubble.timescape.ui.auth.oidc.clientAssertionType }}
          client-assertion-file: {{ .Values.hubble.timescape.ui.auth.oidc.clientAssertionFile }}

          {{- $issuerURL := .Values.hubble.timescape.ui.auth.oidc.issuerURL | default .Values.hubble.rbac.auth.oidc.issuerUrl }}
          {{- if not $issuerURL }}
          {{ fail "Invalid configuration, .hubble.timescape.ui.auth.oidc.issuerURL needs to be set when authentication is enabled." }}
          {{- end }}
          issuer-url: {{ $issuerURL }}
          {{- $oidcRedirectURL := .Values.hubble.timescape.ui.auth.oidc.redirectURL }}
          {{- if and (not $oidcRedirectURL) .Values.hubble.timescape.ui.ingress.enabled .Values.hubble.timescape.ui.ingress.hosts }}
          {{- if .Values.hubble.timescape.ui.ingress.tls }}
          {{- $oidcRedirectURL = printf "https://%s/oauth2/callback" (index .Values.hubble.timescape.ui.ingress.hosts 0) }}
          {{- else }}
          {{- $oidcRedirectURL = printf "http://%s/oauth2/callback" (index .Values.hubble.timescape.ui.ingress.hosts 0) }}
          {{- end }}
          {{- end }}
          {{- if not $oidcRedirectURL }}
          {{ fail "Invalid configuration, .hubble.timescape.ui.auth.oidc.redirectURL needs to be set to to URI_USED_TO_ACCESS_TIMESCAPE_UI/oauth2/callback, when authentication is enabled." }}
          {{- end }}
          redirect-url: {{ $oidcRedirectURL }}
          scopes: {{- .Values.hubble.timescape.ui.auth.oidc.scopes | toYaml | nindent 10 }}
          {{- if or .Values.hubble.timescape.ui.auth.oidc.issuerCA.configMap.name .Values.hubble.rbac.auth.oidc.ca.configMap.name }}
          issuer-ca: /var/lib/hubble-timescape/tls/oidc-provider-ca.pem
          {{- end }}
          id-token-user-claim: {{ .Values.hubble.timescape.ui.auth.oidc.idTokenUserClaim | quote }}
          {{- with .Values.hubble.timescape.ui.auth.oidc.extraFields }}
          {{- $extraFields := list }}
          {{- range . }}
            {{- if not .key }}
            {{ fail "Invalid configuration, .Values.hubble.timescape.ui.auth.oidc.extraFields[].key is required and cannot be empty." }}
            {{- end }}
            {{- $extraField := printf "%s=%s" .key (.value | default "") }}
            {{- $extraFields = append $extraFields $extraField }}
          {{- end }}
          extra-fields: {{ join "," $extraFields | quote }}
          {{- end }}
      {{- end }}
    {{- end }}
{{- end }}
