{{- define "hubble.timescape.labels" }}
k8s-app: hubble-timescape
app.kubernetes.io/name: hubble-timescape
app.kubernetes.io/part-of: cilium
app.kubernetes.io/component: hubble-timescape
{{ with .Values.commonLabels }}
{{- toYaml . }}
{{- end }}
{{- end }}

{{/*
Converts a Go time.Duration into an integer number of seconds
*/}}
{{- define "durationSeconds" -}}
{{/* The value of `before` doesn't matter, we just need a date object to work with so we can extract a duration from it */}}
{{- $before := mustToDate "2006-01-02" "2017-12-31" }}
{{- $after := ($before | mustDateModify .) }}
{{- sub (unixEpoch $after) (unixEpoch $before) }}
{{- end }}

{{- define "hubble.timescape.ttl" -}}
{{- $defaultTTL := "6h0m0s" }}
{{- if not .Values.hubble.timescape.persistence.enabled -}}
{{/* use even lower default ttl if there is no persistent clickhouse database */}}
{{- $defaultTTL = "1h0m0s" }}
{{- end }}
{{- .Values.hubble.timescape.ttl | default $defaultTTL }}
{{- end }}

{{/*
system-status TTL must be at least 24h, therefore compute the max between
the default and computed value.
*/}}
{{- define "hubble.timescape.system-status-ttl" -}}
{{- $minTTL := "24h0m0s" }}
{{- $minTTLSeconds := (include "durationSeconds" $minTTL) }}
{{- $ttl := (include "hubble.timescape.ttl" .) }}
{{- $ttlSeconds := (include "durationSeconds" $ttl) }}
{{- gt $ttlSeconds $minTTLSeconds | ternary $ttl $minTTL | quote }}
{{- end }}

{{ if .Values.hubble.timescape.enabled }}

{{- if and
  .Values.hubble.timescape.clustermesh.primary.namespace
  .Values.hubble.timescape.clustermesh.primary.createNamespace
  (not (eq (int64 .Values.hubble.timescape.clustermesh.primary.id) (int64 .Values.cluster.id)))
}}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.hubble.timescape.clustermesh.primary.namespace }}
{{- end }}
---
# Service exposing the Timescape server and ingester push/stream API
apiVersion: v1
kind: Service
metadata:
  name: hubble-timescape
  {{- if .Values.hubble.timescape.clustermesh.primary.namespace }}
  namespace: {{ .Values.hubble.timescape.clustermesh.primary.namespace }}
  {{- else }}
  namespace: {{ include "cilium.namespace" . }}
  {{- end }}
  labels: {{ include "hubble.timescape.labels" . | nindent 4 }}
  {{- if .Values.hubble.timescape.clustermesh.primary.id }}
  annotations:
    service.cilium.io/global: "true"
    {{- if not (eq (int64 .Values.hubble.timescape.clustermesh.primary.id) (int64 .Values.cluster.id)) }}
    service.cilium.io/shared: "false"
    {{- end }}
  {{- end }}
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      name: push
      targetPort: push
      port: 4260
    - protocol: TCP
      name: stream
      targetPort: stream
      port: 4261
    - protocol: TCP
      name: grpc
      port: {{ eq (include "hubble.timescape.tls.enabled" .) "true" | ternary 443 80 }}
      targetPort: server-grpc
    {{- if .Values.hubble.timescape.ui.enabled }}
    - protocol: TCP
      name: ui
      port: 8080
      targetPort: ui
    {{- end }}
    {{- if .Values.hubble.timescape.metrics.enabled }}
    - name: metrics
      port: 9090
      targetPort: metrics
      protocol: TCP
    {{- end }}
    {{- if .Values.hubble.timescape.metrics.clickhouse.enabled }}
    - name: ch-metrics
      port: 8001
      targetPort: ch-metrics
      protocol: TCP
    {{- end }}
  selector:
    k8s-app: hubble-timescape
    app.kubernetes.io/name: hubble-timescape
    app.kubernetes.io/part-of: cilium
{{- if or
  (not .Values.hubble.timescape.clustermesh.primary.id)
  (eq (int64 .Values.hubble.timescape.clustermesh.primary.id) (int64 .Values.cluster.id))
}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "hubble-timescape"
  namespace: {{ include "cilium.namespace" . }}
  labels: {{ include "hubble.timescape.labels" . | nindent 4 }}
---
# Required for the StatefulSet
apiVersion: v1
kind: Service
metadata:
  name: hubble-timescape-headless
  namespace: {{ include "cilium.namespace" . }}
  labels: {{ include "hubble.timescape.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  selector: {{ include "hubble.timescape.labels" . | nindent 4 }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hubble-timescape
  namespace: {{ include "cilium.namespace" . }}
  labels: {{ include "hubble.timescape.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "hubble.timescape.selectorLabels" . | nindent 6 }}
  serviceName: timescape
  template:
    metadata:
      {{- with include "hubble.timescape.podAnnotations" . }}
      annotations:
        {{- . | nindent 8 }}
      {{- end }}
      {{- with include "hubble.timescape.podLabels" . }}
      labels:
        {{- . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: "hubble-timescape"
      securityContext:
        {{- toYaml .Values.hubble.timescape.podSecurityContext | nindent 10 }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      priorityClassName: {{ .Values.hubble.timescape.priorityClassName }}
      {{- with .Values.hubble.timescape.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.hubble.timescape.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.hubble.timescape.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: clickhouse
          image: {{ include "cilium.image" .Values.hubble.timescape.clickhouse.image | quote }}
          imagePullPolicy: {{ .Values.hubble.timescape.clickhouse.image.pullPolicy }}
          terminationMessagePolicy: FallbackToLogsOnError
          securityContext: {{- toYaml .Values.hubble.timescape.clickhouse.securityContext | nindent 12 }}
          resources:
            {{- toYaml .Values.hubble.timescape.clickhouse.resources | nindent 12 }}
          volumeMounts:
          - mountPath: "/etc/clickhouse-server/config.d/"
            name: clickhouse-config
            readOnly: true
          - mountPath: "/etc/clickhouse-server/profiles.d/"
            name: clickhouse-profile
            readOnly: true
          - mountPath: "/etc/clickhouse-server/users.d/"
            name: clickhouse-user
            readOnly: true
          - name: clickhouse-data
            mountPath: /var/lib/clickhouse
          readinessProbe:
            httpGet:
              path: /ping
              port: ch-http
              scheme: HTTP
          livenessProbe:
            httpGet:
              path: /ping
              port: ch-http
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 3
          ports:
          - containerPort: 8123
            name: ch-http
            protocol: TCP
          {{- if .Values.hubble.timescape.metrics.clickhouse.enabled }}
          - containerPort: 8001
            name: ch-metrics
            protocol: TCP
          {{- end }}
        - name: timescape
          image: {{ include "cilium.image" .Values.hubble.timescape.image | quote }}
          imagePullPolicy: {{ .Values.hubble.timescape.image.pullPolicy }}
          terminationMessagePolicy: FallbackToLogsOnError
          securityContext:
            {{- toYaml .Values.hubble.timescape.securityContext | nindent 12 }}
          command:
            - /usr/bin/hubble-timescape
          args:
            - run
          env:
            - name: HUBBLE_TIMESCAPE_DSN
              value: "clickhouse://localhost:9000/hubble?dial_timeout=10s"
          {{- if and .Values.hubble.timescape.ui.enabled (eq (include "hubble.timescape.ui.auth.enabled" .) "true") }}
          {{- if not .Values.hubble.timescape.ui.auth.oidc.clientAssertionFile }}
            - name: HUBBLE_TIMESCAPE_UI__OAUTH2__OIDC__CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.hubble.timescape.ui.auth.oidc.clientSecret.secretName }}
                  key:  {{ .Values.hubble.timescape.ui.auth.oidc.clientSecret.secretKey }}
          {{- end }}
            - name: HUBBLE_TIMESCAPE_UI__SESSION_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.hubble.timescape.ui.auth.sessionKey.secretName }}
                  key:  {{ .Values.hubble.timescape.ui.auth.sessionKey.secretKey }}
          {{- end }}
          ports:
            - name: health-grpc
              containerPort: 8083
              protocol: TCP
            - name: server-grpc
              containerPort: 4244
              protocol: TCP
            - name: push
              containerPort: 4260
              protocol: TCP
            - name: stream
              containerPort: 4261
              protocol: TCP
            {{- if .Values.hubble.timescape.ui.enabled }}
            - name: ui
              containerPort: 8000
              protocol: TCP
            {{- end }}
            {{- if .Values.hubble.timescape.metrics.enabled }}
            - name: metrics
              containerPort: 9090
              protocol: TCP
            {{- end }}
            - name: pprof
              containerPort: 6060
              protocol: TCP
          startupProbe:
            {{- include "hubble.timescape.probe" . | nindent 12 }}
            # The Timescape server implement a retry logic to connect to
            # ClickHouse with a timeout of 10s retrying 30 times before giving
            # up and crashing. Thus, it is expected to exit on its own after 5
            # minutes if it can't be ready. Since the default k8s periodSeconds
            # is 10s, a failureThreshold of 32 leave to the container a little
            # over 5m. See https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#when-should-you-use-a-startup-probe
            failureThreshold: 32
          readinessProbe:
            {{- include "hubble.timescape.probe" . | nindent 12 }}
          livenessProbe:
            {{- include "hubble.timescape.probe" . | nindent 12 }}
          resources:
            {{- toYaml .Values.hubble.timescape.resources | nindent 12 }}
          volumeMounts:
          - mountPath: "/etc/hubble-timescape"
            name: config
            readOnly: true
          {{- if eq (include "hubble.timescape.tls.enabled" .) "true" }}
          - mountPath: "/var/lib/hubble-timescape/tls"
            name: tls
            readOnly: true
          {{- end }}
          {{- if .Values.hubble.rbac.enabled }}
          - name: rbac
            mountPath: /var/lib/hubble-timescape/rbac
            readOnly: true
          {{- end }}
      volumes:
      - name: config
        configMap:
          name: hubble-timescape-config
          items:
          - key: config.yaml
            path: config.yaml
      {{- if eq (include "hubble.timescape.tls.enabled" .) "true" }}
      - name: tls
        projected:
          defaultMode: 0400
          sources:
          - secret:
              name: {{ .Values.hubble.timescape.tls.server.existingSecret | default "hubble-timescape-server-certs" }}
              items:
              - key: tls.crt
                path: server.crt
              - key: tls.key
                path: server.key
          {{- if not .Values.tls.caBundle.enabled }}
              - key: ca.crt
                path: ca.crt
              {{- else }}
          - {{ .Values.tls.caBundle.useSecret | ternary "secret" "configMap" }}:
              name: {{ .Values.tls.caBundle.name }}
              optional: true
              items:
              - key: {{ .Values.tls.caBundle.key }}
                path: ca.crt
          {{- end }}
          {{- $oidcCAConfigMapName := .Values.hubble.rbac.auth.oidc.ca.configMap.name }}
          {{- $oidcCAConfigMapKey := .Values.hubble.rbac.auth.oidc.ca.configMap.key }}
          {{- if .Values.hubble.timescape.ui.auth.oidc.issuerCA.configMap.name }}
          {{- $oidcCAConfigMapName = .Values.hubble.timescape.ui.auth.oidc.issuerCA.configMap.name }}
          {{- $oidcCAConfigMapKey = .Values.hubble.timescape.ui.auth.oidc.issuerCA.configMap.key }}
          {{- end }}
          {{- if $oidcCAConfigMapName }}
          - configMap:
              name: {{ $oidcCAConfigMapName }}
              items:
              - key: {{ $oidcCAConfigMapKey }}
                path: oidc-provider-ca.pem
          {{- end -}}
      {{- end }}
      {{- if .Values.hubble.rbac.enabled }}
      - name: rbac
        projected:
          defaultMode: 0400
          sources:
          - configMap:
              name: {{ .Values.hubble.rbac.policy.configMap.name }}
          {{- if .Values.hubble.rbac.auth.oidc.ca.configMap.name }}
          - configMap:
              name: {{ .Values.hubble.rbac.auth.oidc.ca.configMap.name }}
              items:
              - key: {{ .Values.hubble.rbac.auth.oidc.ca.configMap.key }}
                path: oidc-provider-ca.pem
          {{- end }}
      {{- end }}
      - name: clickhouse-config
        configMap:
          name: hubble-timescape-clickhouse-settings
          items:
          - key: clickhouse-settings.xml
            path: clickhouse-settings.xml
      - name: clickhouse-profile
        configMap:
          name: hubble-timescape-clickhouse-settings
          items:
          - key: clickhouse-profiles.xml
            path: clickhouse-profiles.xml
      - name: clickhouse-user
        configMap:
          name: hubble-timescape-clickhouse-settings
          items:
          - key: clickhouse-users.xml
            path: clickhouse-user.xml
      - name: clickhouse-data
        {{- if .Values.hubble.timescape.persistence.enabled }}
        persistentVolumeClaim:
          claimName: hubble-timescape-clickhouse-data
        {{- else }}
        emptyDir:
          sizeLimit: 5Gi
        {{- end }}
{{- if .Values.hubble.timescape.persistence.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hubble-timescape-clickhouse-data
  namespace: {{ include "cilium.namespace" . }}
  labels: {{ include "hubble.timescape.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.hubble.timescape.persistence.volumeSize }}
  {{- with .Values.hubble.timescape.persistence.storageClassName }}
  storageClassName: {{ . }}
  {{- end }}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hubble-timescape-k8s-importer
  labels: {{ include "hubble.timescape.labels" . | nindent 4 }}
rules: {{- include "hubble.timescape.ingester.k8sImporter.clusterRole.rules" . | nindent 2 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: hubble-timescape-k8s-importer
  labels: {{ include "hubble.timescape.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: hubble-timescape-k8s-importer
subjects:
- kind: ServiceAccount
  name: hubble-timescape
  namespace: {{ include "cilium.namespace" . }}
{{- if .Values.hubble.timescape.ui.enabled }}
{{- if .Values.hubble.timescape.ui.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hubble-timescape-ui
  namespace: {{ include "cilium.namespace" . }}
  labels: {{ include "hubble.timescape.labels" . | nindent 4 }}
  {{- with .Values.hubble.timescape.ui.ingress.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.hubble.timescape.ui.ingress.className }}
  ingressClassName: {{ .Values.hubble.timescape.ui.ingress.className }}
  {{- end }}
  {{- with .Values.hubble.timescape.ui.ingress.tls }}
  tls: {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
  {{- range .Values.hubble.timescape.ui.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: hubble-timescape
                port:
                  name: ui
  {{- end }}
{{- end }}
{{- if .Values.hubble.timescape.ui.route.enabled }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: hubble-timescape-ui
  namespace: {{ include "cilium.namespace" . }}
  labels: {{ include "hubble.timescape.labels" . | nindent 4 }}
  {{- with .Values.hubble.timescape.ui.route.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.hubble.timescape.ui.route.parentRefs }}
  parentRefs:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.hubble.timescape.ui.route.hostnames }}
  hostnames:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
  rules:
    {{- if .Values.hubble.timescape.ui.route.additionalRules }}
    {{- tpl (toYaml .Values.hubble.timescape.ui.route.additionalRules) $ | nindent 4 }}
    {{- end }}
    - backendRefs:
        - name: hubble-timescape
          port: 8080
      {{- with .Values.hubble.timescape.ui.route.filters }}
      filters:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.hubble.timescape.ui.route.matches }}
      matches:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
