{{- define "cilium.vector.labels" }}
k8s-app: cilium-vector
app.kubernetes.io/name: cilium-vector
app.kubernetes.io/part-of: cilium
{{- end }}

{{- if .Values.hubble.timescape.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cilium-vector
  namespace: {{ include "cilium.namespace" . }}
  labels: {{ include "cilium.vector.labels" . | nindent 4 }}
automountServiceAccountToken: false
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cilium-vector
  namespace: {{ include "cilium.namespace" . }}
  labels: {{ include "cilium.vector.labels" . | nindent 4 }}
data:
  vector.yaml: |
    api:
      address: 127.0.0.1:8686
      enabled: true
      playground: false
    data_dir: /vector-data-dir
    sinks:
      http_push_timescape:
        batch:
          max_size: 50MB
          timeout_secs: 5
        encoding:
          codec: raw_message
        framing:
          method: newline_delimited
        inputs:
        - hubble_logs
        type: http
        uri: http://hubble-timescape.{{ .Release.Namespace }}.svc.cluster.local:4260/push
      prom_exporter:
        address: 0.0.0.0:9090
        inputs:
        - internal_metrics
        type: prometheus_exporter
    sources:
      hubble_logs:
        include:
        - /var/run/cilium/hubble/hubble.log
        - /var/run/cilium/hubble/k8s-events.log
        type: file
      internal_metrics:
        type: internal_metrics
---
apiVersion: v1
kind: Service
metadata:
  name: cilium-vector-headless
  namespace: {{ include "cilium.namespace" . }}
  labels: {{ include "cilium.vector.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - name: api
      port: 8686
      protocol: TCP
      targetPort: 8686
    - name: prom-exporter
      port: 9090
      protocol: TCP
      targetPort: 9090
  selector: {{ include "cilium.vector.labels" . | nindent 4 }}
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: cilium-vector
  namespace: {{ include "cilium.namespace" . }}
  labels: {{ include "cilium.vector.labels" . | nindent 4 }}
spec:
  ports:
    - name: api
      port: 8686
      protocol: TCP
      targetPort: 8686
    - name: prom-exporter
      port: 9090
      protocol: TCP
      targetPort: 9090
  selector: {{ include "cilium.vector.labels" . | nindent 4 }}
  type: ClusterIP
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cilium-vector
  namespace: {{ include "cilium.namespace" . }}
  labels: {{ include "cilium.vector.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels: {{ include "cilium.vector.labels" . | nindent 8 }}
  minReadySeconds: 0
  template:
    metadata:
      labels: {{ include "cilium.vector.labels" . | nindent 10 }}
    spec:
      serviceAccountName: cilium-vector
      dnsPolicy: ClusterFirst
      containers:
        - name: vector
          image: {{ include "cilium.image" .Values.hubble.timescape.vector.image | quote }}
          imagePullPolicy: {{ .Values.hubble.timescape.vector.image.pullPolicy }}
          args:
            - --config-dir
            - /etc/vector/
          env:
            - name: VECTOR_LOG
              value: "info"
            - name: VECTOR_SELF_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: VECTOR_SELF_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: VECTOR_SELF_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: PROCFS_ROOT
              value: "/host/proc"
            - name: SYSFS_ROOT
              value: "/host/sys"
          ports:
            - name: api
              containerPort: 8686
              protocol: TCP
            - name: prom-exporter
              containerPort: 9090
              protocol: TCP
          resources: {{ .Values.hubble.timescape.vector.resources | toYaml | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: "/vector-data-dir"
            - name: config
              mountPath: "/etc/vector/"
              readOnly: true
            - mountPath: /var/log/
              name: var-log
              readOnly: true
            - mountPath: /var/lib
              name: var-lib
              readOnly: true
            - mountPath: /host/proc
              name: procfs
              readOnly: true
            - mountPath: /host/sys
              name: sysfs
              readOnly: true
            - mountPath: /var/run/cilium/hubble
              name: hubble-logs
              readOnly: true
      terminationGracePeriodSeconds: 60
      volumes:
        - name: config
          projected:
            sources:
              - configMap:
                  name: cilium-vector
        - name: data
          hostPath:
            path: "/var/lib/vector-cilium"
        - hostPath:
            path: /var/log/
          name: var-log
        - hostPath:
            path: /var/lib/
          name: var-lib
        - hostPath:
            path: /proc
          name: procfs
        - hostPath:
            path: /sys
          name: sysfs
        - hostPath:
            path: /var/run/cilium/hubble
          name: hubble-logs
{{- end }}
