{{- if and
  (eq (include "cilium.vector.enabled" .) "true")
  .Values.hubble.timescape.vector.metrics.enabled
  .Values.hubble.timescape.vector.metrics.serviceMonitor.enabled
}}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cilium-vector
  namespace: {{ .Values.hubble.timescape.vector.metrics.serviceMonitor.namespace | default (include "cilium.namespace" .) }}
  labels:
    {{- include "cilium.vector.labels" . | nindent 4 -}}
    {{/* The vector labels already contain the .Values.commonLabels */}}
    {{- with .Values.hubble.timescape.vector.metrics.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.hubble.timescape.vector.metrics.serviceMonitor.annotations }}
  annotations:
      {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: cilium-vector
      app.kubernetes.io/part-of: cilium
  namespaceSelector:
    matchNames:
    - {{ include "cilium.namespace" . }}
  endpoints:
  {{- include "hubble.timescape.servicemonitor.endpoint" (dict
      "values" .Values.hubble.timescape.vector.metrics.serviceMonitor
      "port" "prom-exporter"
    ) | nindent 2 }}
{{- end }}
