{{- define "cilium.vector.labels" }}
k8s-app: cilium-vector
app.kubernetes.io/name: cilium-vector
app.kubernetes.io/part-of: cilium
{{ with .Values.commonLabels }}
{{- toYaml . }}
{{- end }}
{{- end }}

{{- define "cilium.vector.enabled" -}}
{{- and
  .Values.hubble.timescape.enabled
  (or
    (not .Values.hubble.timescape.useStreamAPI)
    (not .Values.hubble.timescape.ingester.k8sImporter.enabled)
  )
-}}
{{- end }}

{{- if eq (include "cilium.vector.enabled" .) "true" }}
{{- $targetNamespace := (include "cilium.namespace" .) }}
{{- if .Values.hubble.timescape.clustermesh.primary.namespace }}
{{- $targetNamespace = .Values.hubble.timescape.clustermesh.primary.namespace }}
{{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cilium-vector
  namespace: {{ include "cilium.namespace" . }}
  labels: {{ include "cilium.vector.labels" . | nindent 4 }}
automountServiceAccountToken: false
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cilium-vector
  namespace: {{ include "cilium.namespace" . }}
  labels: {{ include "cilium.vector.labels" . | nindent 4 }}
data:
  vector.yaml: |
    api:
      enabled: false
      playground: false
    data_dir: /vector-data-dir
    sinks:
      {{- if not .Values.hubble.timescape.useStreamAPI }}
      http_push_timescape_flow:
        batch:
          max_size: 50MB
          timeout_secs: 5
        encoding:
          codec: raw_message
        framing:
          method: newline_delimited
        inputs:
        - flow_logs
        type: http
        {{- if eq (include "hubble.timescape.tls.enabled" .) "true" }}
        uri: https://hubble-timescape.{{ $targetNamespace }}.svc.cluster.local.:4260/push?object_type=OBJECT_TYPE_FLOW
        tls:
          ca_file: "/var/lib/hubble/tls/ca.crt"
          crt_file: "/var/lib/hubble/tls/client.crt"
          key_file: "/var/lib/hubble/tls/client.key"
          server_name: "hubble-timescape.{{ $targetNamespace }}.svc.cluster.local"
        {{- else }}
        uri: http://hubble-timescape.{{ $targetNamespace }}.svc.cluster.local.:4260/push?object_type=OBJECT_TYPE_FLOW
        {{- end }}
      {{- end }}
      {{- if not .Values.hubble.timescape.ingester.k8sImporter.enabled }}
      http_push_timescape_k8sevent:
        batch:
          max_size: 50MB
          timeout_secs: 5
        encoding:
          codec: raw_message
        framing:
          method: newline_delimited
        inputs:
        - k8sevent_logs
        type: http
        {{- if eq (include "hubble.timescape.tls.enabled" .) "true" }}
        uri: https://hubble-timescape.{{ $targetNamespace }}.svc.cluster.local.:4260/push?object_type=OBJECT_TYPE_K8S_EVENT
        tls:
          ca_file: "/var/lib/hubble/tls/ca.crt"
          crt_file: "/var/lib/hubble/tls/client.crt"
          key_file: "/var/lib/hubble/tls/client.key"
          server_name: "hubble-timescape.{{ $targetNamespace }}.svc.cluster.local"
        {{- else }}
        uri: http://hubble-timescape.{{ $targetNamespace }}.svc.cluster.local.:4260/push?object_type=OBJECT_TYPE_K8S_EVENT
        {{- end }}
      {{- end }}
      {{- if .Values.hubble.timescape.vector.metrics.enabled }}
      prom_exporter:
        address: 0.0.0.0:9090
        inputs:
        - internal_metrics
        type: prometheus_exporter
      {{- end }}
    sources:
      {{- if not .Values.hubble.timescape.useStreamAPI }}
      flow_logs:
        include:
        {{- if and .Values.extraConfig (not (empty (get .Values.extraConfig "export-file-path"))) }}
        - {{ index .Values.extraConfig "export-file-path" }}
        {{- else }}
        - /var/run/cilium/hubble/hubble.log
        {{- end }}
        type: file
      {{- end }}
      {{- if not .Values.hubble.timescape.ingester.k8sImporter.enabled }}
      k8sevent_logs:
        include:
        - {{ .Values.hubble.k8sExporter.export.filePath }}
        type: file
      {{- end }}
      {{- if .Values.hubble.timescape.vector.metrics.enabled }}
      internal_metrics:
        type: internal_metrics
      {{- end }}

{{- if .Values.hubble.timescape.vector.metrics.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: cilium-vector
  namespace: {{ include "cilium.namespace" . }}
  labels: {{ include "cilium.vector.labels" . | nindent 4 }}
spec:
  ports:
    - name: prom-exporter
      port: 9090
      protocol: TCP
      targetPort: 9090
  selector: {{ include "cilium.vector.labels" . | nindent 4 }}
  type: ClusterIP
{{- end }}
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cilium-vector
  namespace: {{ include "cilium.namespace" . }}
  labels: {{ include "cilium.vector.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels: {{ include "cilium.vector.labels" . | nindent 8 }}
  minReadySeconds: 0
  template:
    metadata:
      labels: {{ include "cilium.vector.labels" . | nindent 10 }}
    spec:
      serviceAccountName: cilium-vector
      securityContext:
        {{- toYaml .Values.hubble.timescape.vector.podSecurityContext | nindent 10 }}
      dnsPolicy: ClusterFirst
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      priorityClassName: {{ .Values.hubble.timescape.vector.priorityClassName }}
      {{- with .Values.hubble.timescape.vector.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.hubble.timescape.vector.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.hubble.timescape.vector.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: vector
          image: {{ include "cilium.image" .Values.hubble.timescape.vector.image | quote }}
          imagePullPolicy: {{ .Values.hubble.timescape.vector.image.pullPolicy }}
          args:
            - --config-dir
            - /etc/vector/
          env:
            - name: VECTOR_LOG
              value: "info"
            - name: VECTOR_SELF_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: VECTOR_SELF_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: VECTOR_SELF_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          {{- if .Values.hubble.timescape.vector.metrics.enabled }}
          ports:
            - name: prom-exporter
              containerPort: 9090
              protocol: TCP
          {{- end }}
          resources: {{ .Values.hubble.timescape.vector.resources | toYaml | nindent 12 }}
          securityContext:
            {{- toYaml .Values.hubble.timescape.vector.securityContext | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: "/vector-data-dir"
            - name: config
              mountPath: "/etc/vector/"
              readOnly: true
            - mountPath: /var/run/cilium/hubble
              name: hubble-logs
              readOnly: true
            {{- if eq (include "hubble.timescape.tls.enabled" .) "true" }}
            - mountPath: "/var/lib/hubble/tls"
              name: hubble-tls
              readOnly: true
            {{- end }}
      terminationGracePeriodSeconds: 60
      volumes:
        - name: config
          projected:
            sources:
              - configMap:
                  name: cilium-vector
        - name: data
          hostPath:
            path: "/var/lib/vector-cilium"
        - hostPath:
            path: /var/run/cilium/hubble
          name: hubble-logs
        {{- if eq (include "hubble.timescape.tls.enabled" .) "true" }}
        - name: hubble-tls
          projected:
            defaultMode: 0400
            sources:
            - secret:
                items:
                - key: tls.crt
                  path: client.crt
                - key: tls.key
                  path: client.key
                - key: ca.crt
                  path: ca.crt
                name: {{ .Values.hubble.timescape.tls.client.existingSecret | default "hubble-timescape-client-certs" }}
        {{- end }}
{{- end }}
