// Code generated by go-swagger; DO NOT EDIT.

// Copyright (C) Isovalent, Inc. - All Rights Reserved.
//
// NOTICE: All information contained herein is, and remains the property of
// Isovalent Inc and its suppliers, if any. The intellectual and technical
// concepts contained herein are proprietary to Isovalent Inc and its suppliers
// and may be covered by U.S. and Foreign Patents, patents in process, and are
// protected by trade secret or copyright law.  Dissemination of this information
// or reproduction of this material is strictly forbidden unless prior written
// permission is obtained from Isovalent Inc.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/cilium/cilium/enterprise/api/v1/models"
)

// GetHealthzOKCode is the HTTP code returned for type GetHealthzOK
const GetHealthzOKCode int = 200

/*
GetHealthzOK Success

swagger:response getHealthzOK
*/
type GetHealthzOK struct {
}

// NewGetHealthzOK creates GetHealthzOK with default headers values
func NewGetHealthzOK() *GetHealthzOK {

	return &GetHealthzOK{}
}

// WriteResponse to the client
func (o *GetHealthzOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) // Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// GetHealthzDisabledCode is the HTTP code returned for type GetHealthzDisabled
const GetHealthzDisabledCode int = 404

/*
GetHealthzDisabled Cilium Enterprise API is not available

swagger:response getHealthzDisabled
*/
type GetHealthzDisabled struct {
}

// NewGetHealthzDisabled creates GetHealthzDisabled with default headers values
func NewGetHealthzDisabled() *GetHealthzDisabled {

	return &GetHealthzDisabled{}
}

// WriteResponse to the client
func (o *GetHealthzDisabled) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) // Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// GetHealthzFailureCode is the HTTP code returned for type GetHealthzFailure
const GetHealthzFailureCode int = 500

/*
GetHealthzFailure Internal server error

swagger:response getHealthzFailure
*/
type GetHealthzFailure struct {

	/*
	  In: Body
	*/
	Payload models.Error `json:"body,omitempty"`
}

// NewGetHealthzFailure creates GetHealthzFailure with default headers values
func NewGetHealthzFailure() *GetHealthzFailure {

	return &GetHealthzFailure{}
}

// WithPayload adds the payload to the get healthz failure response
func (o *GetHealthzFailure) WithPayload(payload models.Error) *GetHealthzFailure {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get healthz failure response
func (o *GetHealthzFailure) SetPayload(payload models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetHealthzFailure) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
