apiVersion: "isovalent.com/v1alpha1"
kind: ClusterwidePrivateNetwork
metadata:
  name: "{{ .Network }}"
  labels:
    app.kubernetes.io/part-of: cilium-cli-privnet
spec:
  {{- if .INBInterface }}
  interface:
    name: "{{ .INBInterface }}"
  {{- end }}
  subnets:
    {{- range $index, $subnet := .Prefixes }}
    - name: subnet-{{ $index }}
      cidrv4: {{ $subnet.CIDRv4 }}
      cidrv6: {{ $subnet.CIDRv6 }}
      {{- if $subnet.Routes }}
      routes:
        {{- range $subnet.Routes }}
        - destination: {{ .Destination }}
          gateway: {{ .Gateway }}
        {{- end }}
      {{- else }}
      routes: []
      {{- end }}
    {{- end }}
  {{- if .INBClusterNames }}
  networkBridges:
    {{- range .INBClusterNames }}
    - cluster: {{ . }}
    {{- end }}
  {{- else }}
  networkBridges: []
  {{- end }}
