apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: "{{ .Name }}"
  namespace: "{{ .TestNamespace }}"
  labels:
    app.kubernetes.io/part-of: cilium-cli-privnet
    {{- if .ID }}
    vmID: {{ .ID }}
    {{- end }}
    {{- with .PlanID }}
    plan: {{ . }}
    {{- end }}
spec:
  runStrategy: Always
  template:
    metadata:
      name: "{{ .Name }}"
      {{- if .NeedsAnnotation }}
      annotations:
        "network.v1alpha1.isovalent.com/network-attachment": '{"network":"{{ .NetName }}","ipv4":"{{ .NetIPv4 }}","ipv6":"{{ .NetIPv6 }}","mac":"{{ .NetMAC }}"}'
      {{- end }}
    spec:
      affinity:
  {{ if eq .Affinity "same-node" }}
        podAffinity:
  {{ else }}
        podAntiAffinity:
  {{ end }}
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: kind
                    operator: In
                    values:
                      - "client"
              topologyKey: kubernetes.io/hostname
      dnsPolicy: None
      dnsConfig:
        nameservers:
        - {{ .NetDNSServer }}
      domain:
        devices:
          disks:
          - disk:
              bus: virtio
            name: containerdisk
          - disk:
              bus: virtio
            name: cloudinitdisk
          interfaces:
          - bridge: {}
            name: default
          rng: {}
        resources:
          requests:
            memory: 1024M
      networks:
      - name: default
        pod: {}
      terminationGracePeriodSeconds: 0
      volumes:
      - containerDisk:
          image: "{{ .VMImage }}"
        name: containerdisk
      - cloudInitNoCloud:
          userData: |-
            #cloud-config
            password: fedora
            chpasswd: { expire: False }
            write_files:
            - content: |
                {{ .Script | indent 16 }}
              path: /run/scripts/echoserver.py
            - content: |
                [Unit]
                Description=Serve http server echoing client ip
                After=cloud-init-local.service
                Before=cloud-config.service
                Before=cloud-final.service

                [Install]
                WantedBy=cloud-init-local.service

                [Service]
                Environment="CILIUM_PRIVNET_NETWORK={{ .NetName }}"
                Environment="CILIUM_PRIVNET_PORT={{ .ServePort }}"
                ExecStart=/usr/bin/env python3 /run/scripts/echoserver.py
                Restart=always
              path: /etc/systemd/system/echoserver.service
            runcmd:
            - [systemctl, enable, --now, echoserver.service]
          networkData: |
            version: 2
            ethernets:
              eth0:
                dhcp4: true
                addresses: [ {{ .NetIPv6 }}/128 ]
                gateway6: {{ .NetIPv6Gateway }}
        name: cloudinitdisk
