apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: "{{ .Name }}"
  namespace: "{{ .TestNamespace }}"
  labels:
    app.kubernetes.io/part-of: cilium-cli-privnet
    {{- if .ID }}
    vmID: {{ .ID }}
    {{- end }}
    {{- with .PlanID }}
    plan: {{ . }}
    {{- end }}
spec:
  runStrategy: Always
  template:
    metadata:
      name: "{{ .Name }}"
      labels:
        name: "{{ .Name }}"
        kind: echo
      {{- if .NeedsAnnotation }}
      annotations:
        "privnet.isovalent.com/network-attachment": '{"network":"{{ .NetName }}","ipv4":"{{ .NetIPv4 }}","ipv6":"{{ .NetIPv6 }}","mac":"{{ .NetMAC }}"}'
      {{- end }}
    spec:
      affinity:
  {{ if eq .Affinity "same-node" }}
        podAffinity:
  {{ else }}
        podAntiAffinity:
  {{ end }}
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: kind
                    operator: In
                    values:
                      - "client"
              topologyKey: kubernetes.io/hostname
      dnsPolicy: None
      dnsConfig:
        nameservers:
        - {{ .NetDNSServer }}
      domain:
        devices:
          disks:
          - disk:
              bus: virtio
            name: containerdisk
          - disk:
              bus: virtio
            name: cloudinitdisk
          interfaces:
          - name: default
            macAddress: {{ .NetMAC }}
            # The subnet is set only if DHCP is enabled. In that case, we want
            # to use the managedTap binding, so that we don't fight against
            # kubevirt's DHCP server.
            {{- if .NetSubnet }}
            binding:
              name: isovalent-networking
            {{- else }}
            bridge: {}
            {{- end }}
          rng: {}
        resources:
          requests:
            memory: 256M
      networks:
      - name: default
        {{- if .NAD }}
        multus:
          networkName: "{{ .TestNamespace }}/{{ .NAD }}"
          default: true
        {{- else }}
        pod: {}
        {{- end }}
      readinessProbe:
        exec:
          command:
          - /run/scripts/ready.sh
        failureThreshold: 3
        periodSeconds: 5
        successThreshold: 1
        timeoutSeconds: 1
      terminationGracePeriodSeconds: 0
      volumes:
      - containerDisk:
          image: "{{ .VMImage }}"
        name: containerdisk
      - cloudInitNoCloud:
          userData: |-
            #cloud-config
            password: alpine
            chpasswd: { expire: False }
            manage_etc_hosts: true
            write_files:
            - content: |
                {{ .Script | indent 16 }}
              path: /run/scripts/echoserver.py
            - content: |
                #!/sbin/openrc-run

                description="Serve http server echoing client IP"
                command="/usr/bin/python3"
                command_args="/run/scripts/echoserver.py"
                pidfile="/run/echoserver.pid"
                supervisor="supervise-daemon"
                command_background="yes"

                depend() {
                    need localmount
                    need net
                }

                start_pre() {
                    export CILIUM_PRIVNET_NETWORK={{ .NetName }}
                    export CILIUM_PRIVNET_PORT={{ .ServePort }}
                }
              path: /etc/init.d/echoserver
              permissions: '0755'
            - content: |
                #! /bin/sh -e

                # Check whether the hostname has been set correctly.
                [ $(hostname) = "{{ .Name }}" ]

                # Check whether the echo server is running.
                curl --fail --max-time 1 localhost:{{ .ServePort }}
              path: /run/scripts/ready.sh
              permissions: '0755'
            runcmd:
            - [rc-service, echoserver, start]
            - [rc-update, add, echoserver]
          networkData: |
            version: 2
            ethernets:
              eth0:
                {{- if .NeedsAnnotation }}
                dhcp4: true
                addresses: [ {{ .NetIPv6 }}/128 ]
                gateway6: {{ .NetIPv6Gateway }}
                {{- else }}
                addresses: [ {{ .NetIPv4 }}/32, {{ .NetIPv6 }}/128 ]
                gateway4: {{ .NetIPv4Gateway }}
                gateway6: {{ .NetIPv6Gateway }}
                nameservers:
                  addresses: [ {{ .NetDNSServer }} ]
                {{- end }}
        name: cloudinitdisk
