name: OpenShift tests
description: Runs OpenShift related tests

inputs:
  working-dir:
    required: true
    description: 'Test cluster configuration directory'
  test-results-dir:
    required: true
    description: 'Test results directory'

runs:
  using: composite
  steps:
    - name: Run Cilium CLI tests
      shell: bash
      working-directory: "${{ inputs.working-dir }}"
      run: |
        # Create the SCC to provide the required priviliges for running the tests
        kubectl apply -f ../common/test-scc.yaml
        mkdir -p ./${{ inputs.test-results-dir }}
        echo "Cilium CLI tests starting at: $(date)"
        set +e
        # SecurityContextConstraints would need to be amended (additional namespaces) to allow TEST_CONCURRENCY=3
        # Disabling both flow validation and hubble is aligned with the EKS conformance tests        # Without it there was 1 unexpected packet drop: "CT: Map insertion failed" that would need investigation
        # Disabling log check as it also considers logs before the tests started and
        # disruptions are expected during the installation process.
        cilium connectivity test -n cilium --flow-validation=disabled --hubble=false --test='!check-log-errors' 2>&1 > ./${{ inputs.test-results-dir }}/cilium-cli-results.txt
        result=$?
        set -e
        cat ./${{ inputs.test-results-dir }}/cilium-cli-results.txt
        if [ $result -eq 0 ]; then
          echo "Result: Success"
          exit 0
        else
          echo "Result: Failure"
          exit 1
        fi

    - name: Run CNI conformance tests
      shell: bash
      working-directory: "${{ inputs.working-dir }}"
      run: |
        make test-cni-conformance

    - name: Run KubeVirt conformance tests
      shell: bash
      working-directory: "${{ inputs.working-dir }}"
      run: |
        if [ "${{ steps.vars.outputs.kubevirt }}" != "true" ]; then
          echo "Provisioning of bare-metal nodes and KubeVirt conformance tests skipped."
          echo "Please create a comment with /ci-openshift {\"kubevirt\":\"true\"} if you want to run them"
        else
          make test-kubevirt-conformance
        fi
