name: OpenShift Service Mesh conformance tests
description: Runs OpenShift Service Mesh conformance tests

inputs:
  working-dir:
    required: true
    description: 'Test cluster configuration directory'

runs:
  using: composite
  steps:
    - name: Run Service Mesh conformance tests
      shell: bash
      working-directory: "${{ inputs.working-dir }}"
      run: |
          make test-mesh-conformance
