name: OpenShift Service Mesh conformance tests
description: Runs OpenShift Service Mesh conformance tests

inputs:
  working-dir:
    required: true
    description: 'Test cluster configuration directory'

runs:
  using: composite
  steps:
    - name: mkdir tests directory
      run: mkdir -p ${{ inputs.working-dir }}/tests

    # The sail-operators repository contains the Service Mesh conformance tests
    - name: Checkout sail-operators repository
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      with:
        repository: istio-ecosystem/sail-operator
        path: ${{ inputs.working-dir }}/tests/sail-operator
        fetch-depth: 0

    - name: Run Service Mesh conformance tests
      shell: bash
      working-directory: "${{ inputs.working-dir }}"
      run: |
          make test-mesh-conformance
