allowed-teams:
  - isovalent

triggers:
  /test\s*:
    workflows:
    - enterprise-clustermesh-mixed-routing.yaml
    - enterprise-clustermesh-overlapping-podcidr.yaml
    - enterprise-fqdn-ha.yaml
    - enterprise-multi-network.yaml
    - enterprise-srv6-datapath.yaml
    - enterprise-multicast.yaml
    - enterprise-conformance-cilium-mesh.yaml
    - enterprise-lb.yaml
    - enterprise-encryption-policy.yaml
    - enterprise-ingress-policy.yaml
    - enterprise-standalone-egress-gateway.yaml
  /ci-clustermesh:
    workflows:
    - enterprise-clustermesh-mixed-routing.yaml
    - enterprise-clustermesh-overlapping-podcidr.yaml
  # `(.+)` is regex capture group that is used as `extra-args` inputs parameter in the CuTE workflow
  # For example: `/cute bloomberg` or `/cute form3/MAKS`
  /cute (.+):
    workflows:
    - enterprise-cute.yaml
  /ci-multi-network:
    workflows:
    - enterprise-multi-network.yaml
  /ci-fqdn-ha:
    workflows:
    - enterprise-fqdn-ha.yaml
  /ci-fqdn-ha-upgrade:
    workflows:
    - enterprise-fqdn-ha-upgrade.yaml
  /ci-srv6-datapath:
    workflows:
    - enterprise-srv6-datapath.yaml
  /ci-cilium-mesh:
    workflows:
    - enterprise-conformance-cilium-mesh.yaml
  /ci-multicast:
    workflows:
    - enterprise-multicast.yaml
  /fqdn-ha-perf:
    workflows:
    - enterprise-fqdn-ha-perf.yaml
  /ci-lb:
    workflows:
    - enterprise-lb.yaml
  /ci-lb-vsphere:
    workflows:
    - enterprise-lb-vsphere.yaml
  /scale-encryption-policy:
    workflows:
    - enterprise-scale-encryption-policy.yaml
  /ci-encryption-policy:
    workflows:
    - enterprise-encryption-policy.yaml
  # `(?:\s*)({.*})?` is regex capture group that is used as `extra-args` inputs parameter in the enterprise conformance OpenShift workflow
  # For example: `/ci-openshift {"kubevirt":"true", "ocp_version":"4.17.14"}`
  /ci-openshift(?:\s*)({.*})?:
    workflows:
    - enterprise-conformance-openshift.yaml
  # `(?:\s*)({.*})?` is regex capture group that is used as `extra-args` inputs parameter in the enterprise conformance OpenShift workflow
  # For example: `/ci-ilb-openshift {"ocp_version":"4.17.14"}`
  /ci-ilb-openshift(?:\s*)({.*})?:
    workflows:
    - enterprise-conformance-ilb-openshift.yaml
  /ci-panda-scale(\s+(?:nodes=[0-9]+)?(?:\s*version=[-+.0-9a-z]+)?(?:\s*sha=[a-f0-9]+)?)?:
    workflows:
    - enterprise-panda-scale.yaml
  /ci-ingress-policy:
    workflows:
    - enterprise-ingress-policy.yaml
  /ci-standalone-egress-gateway:
    workflows:
    - enterprise-standalone-egress-gateway.yaml
  /ci-egress-gateway-ha-eks:
    workflows:
    - enterprise-egress-gateway-ha-eks.yaml
  /ci-egress-gateway-ha-aks:
    workflows:
    - enterprise-egress-gateway-ha-aks.yaml

schedule:
  nightly:
    workflows:
    - conformance-gke.yaml

workflows:
  enterprise-clustermesh-mixed-routing.yaml:
    paths-ignore-regex: ((bpf/complexity-tests|bpf/tests|test|Documentation|hubble|.github/actions/cl2-modules)/|(.github/renovate\.json5|README.rst|CODEOWNERS|stable.txt|.*\.md|.*_test\.go)$)
  enterprise-clustermesh-overlapping-podcidr.yaml:
    paths-ignore-regex: ((bpf/complexity-tests|bpf/tests|test|Documentation|hubble|.github/actions/cl2-modules)/|(.github/renovate\.json5|README.rst|CODEOWNERS|stable.txt|.*\.md|.*_test\.go)$)
  enterprise-fqdn-ha.yaml:
    paths-ignore-regex: ((bpf/complexity-tests|bpf/tests|test|Documentation|hubble|.github/actions/cl2-modules)/|(.github/renovate\.json5|README.rst|CODEOWNERS|stable.txt|.*\.md|.*_test\.go)$)
  enterprise-fqdn-ha-upgrade.yaml:
    paths-ignore-regex: ((bpf/complexity-tests|bpf/tests|test|Documentation|hubble|.github/actions/cl2-modules)/|(.github/renovate\.json5|README.rst|CODEOWNERS|stable.txt|.*\.md|.*_test\.go)$)
  enterprise-multi-network.yaml:
    paths-ignore-regex: ((bpf/complexity-tests|bpf/tests|test|Documentation|hubble|.github/actions/cl2-modules)/|(.github/renovate\.json5|README.rst|CODEOWNERS|stable.txt|.*\.md|.*_test\.go)$)
  enterprise-srv6-datapath.yaml:
    paths-ignore-regex: ((bpf/complexity-tests|bpf/tests|test|Documentation|hubble|.github/actions/cl2-modules)/|(.github/renovate\.json5|README.rst|CODEOWNERS|stable.txt|.*\.md|.*_test\.go)$)
  enterprise-conformance-cilium-mesh.yaml:
    paths-ignore-regex: ((bpf/complexity-tests|bpf/tests|test|Documentation|hubble|.github/actions/cl2-modules)/|(.github/renovate\.json5|README.rst|CODEOWNERS|stable.txt|.*\.md|.*_test\.go)$)
  enterprise-multicast.yaml:
    paths-ignore-regex: ((bpf/complexity-tests|bpf/tests|test|Documentation|hubble|.github/actions/cl2-modules)/|(.github/renovate\.json5|README.rst|CODEOWNERS|stable.txt|.*\.md|.*_test\.go)$)
  enterprise-lb.yaml:
    paths-ignore-regex: ((bpf/complexity-tests|bpf/tests|test|Documentation|hubble|.github/actions/cl2-modules)/|(.github/renovate\.json5|README.rst|CODEOWNERS|stable.txt|.*\.md|.*_test\.go)$)
  enterprise-encryption-policy.yaml:
    paths-ignore-regex: ((bpf/complexity-tests|bpf/tests|test|Documentation|hubble|.github/actions/cl2-modules)/|(.github/renovate\.json5|README.rst|CODEOWNERS|stable.txt|.*\.md|.*_test\.go)$)
  enterprise-lb-vsphere.yaml:
    paths-ignore-regex: ((bpf/complexity-tests|bpf/tests|test|Documentation|hubble|.github/actions/cl2-modules)/|(.github/renovate\.json5|README.rst|CODEOWNERS|stable.txt|.*\.md|.*_test\.go)$)
  enterprise-conformance-openshift.yaml:
    paths-ignore-regex: ((bpf/complexity-tests|bpf/tests|test|Documentation|hubble|.github/actions/cl2-modules)/|(.github/renovate\.json5|README.rst|CODEOWNERS|stable.txt|.*\.md|.*_test\.go)$)
  enterprise-ingress-policy.yaml:
    paths-ignore-regex: ((bpf/complexity-tests|bpf/tests|test|Documentation|hubble|.github/actions/cl2-modules)/|(.github/renovate\.json5|README.rst|CODEOWNERS|stable.txt|.*\.md|.*_test\.go)$)
  enterprise-standalone-egress-gateway.yaml:
    paths-ignore-regex: ((bpf/complexity-tests|bpf/tests|test|Documentation|hubble|.github/actions/cl2-modules)/|(.github/renovate\.json5|README.rst|CODEOWNERS|stable.txt|.*\.md|.*_test\.go)$)
