allowed-teams:
  - isovalent

triggers:
  /test:
    workflows:
    - enterprise-clustermesh-mixed-routing.yaml
    - enterprise-clustermesh-overlapping-podcidr.yaml
    - enterprise-fqdn-ha.yaml
    - enterprise-fqdn-ha-upgrade.yaml
    - enterprise-multi-network.yaml
    - enterprise-srv6-datapath.yaml
    - enterprise-multicast.yaml
    # Disabled until https://github.com/isovalent/cilium/issues/5094
    # TODO: Re-enable once the issue is solved and the workflow is passing.
    #- enterprise-conformance-cilium-mesh.yaml
    - enterprise-lb.yaml
    - enterprise-encryption-policy.yaml
  /ci-clustermesh:
    workflows:
    - enterprise-clustermesh-mixed-routing.yaml
    - enterprise-clustermesh-overlapping-podcidr.yaml
  # `(.+)` is regex capture group that is used as `extra-args` inputs parameter in the CuTE workflow
  # For example: `/cute bloomberg` or `/cute form3/MAKS`
  /cute (.+):
    workflows:
    - enterprise-cute.yaml
  /ci-multi-network:
    workflows:
    - enterprise-multi-network.yaml
  /ci-fqdn-ha:
    workflows:
    - enterprise-fqdn-ha.yaml
  /ci-fqdn-ha-upgrade:
    workflows:
    - enterprise-fqdn-ha-upgrade.yaml
  /ci-srv6-datapath:
    workflows:
    - enterprise-srv6-datapath.yaml
  /ci-cilium-mesh:
    workflows:
    - enterprise-conformance-cilium-mesh.yaml
  /ci-multicast:
    workflows:
    - enterprise-multicast.yaml
  /fqdn-ha-perf:
    workflows:
    - enterprise-fqdn-ha-perf.yaml
  /ci-lb:
    workflows:
    - enterprise-lb.yaml
    - enterprise-lb-vsphere.yaml
  /ci-lb-vsphere:
    workflows:
    - enterprise-lb-vsphere.yaml
  /scale-encryption-policy:
    workflows:
    - enterprise-scale-encryption-policy.yaml
  /ci-encryption-policy:
    workflows:
    - enterprise-encryption-policy.yaml

workflows:
  enterprise-clustermesh-mixed-routing.yaml:
    paths-ignore-regex: (test|Documentation|hubble)/
  enterprise-clustermesh-overlapping-podcidr.yaml:
    paths-ignore-regex: (test|Documentation|hubble)/
  enterprise-fqdn-ha.yaml:
    paths-ignore-regex: (test|Documentation|hubble)/
  enterprise-fqdn-ha-upgrade.yaml:
    paths-ignore-regex: (test|Documentation|hubble)/
  enterprise-multi-network.yaml:
    paths-ignore-regex: (test|Documentation|hubble)/
  enterprise-srv6-datapath.yaml:
    paths-ignore-regex: (Documentation|hubble)/
  enterprise-conformance-cilium-mesh.yaml:
    paths-ignore-regex: (test|Documentation|hubble)/
  enterprise-multicast.yaml:
    paths-ignore-regex: (test|Documentation|hubble)/
  enterprise-lb.yaml:
    paths-ignore-regex: Documentation/
  enterprise-encryption-policy.yaml:
    paths-ignore-regex: (test|Documentation|hubble)/
  enterprise-lb-vsphere.yaml:
    paths-ignore-regex: Documentation/
