/* SPDX-License-Identifier: (GPL-2.0-only OR BSD-2-Clause) */
/* Copyright Authors of Cilium */

#pragma once

#define CILIUM_CALL_IPV4_PRIVNET_UNKNOWN_INGRESS 100
#define CILIUM_CALL_IPV6_PRIVNET_UNKNOWN_INGRESS 101
#define CILIUM_CALL_IPV4_PRIVNET_LXC_EGRESS 102
#define CILIUM_CALL_IPV6_PRIVNET_LXC_EGRESS 103

#undef CILIUM_CALL_SIZE
#define CILIUM_CALL_SIZE 104
