/*
Copyright (C) Isovalent, Inc. - All Rights Reserved.

NOTICE: All information contained herein is, and remains the property of
Isovalent Inc and its suppliers, if any. The intellectual and technical
concepts contained herein are proprietary to Isovalent Inc and its suppliers
and may be covered by U.S. and Foreign Patents, patents in process, and are
protected by trade secret or copyright law.  Dissemination of this information
or reproduction of this material is strictly forbidden unless prior written
permission is obtained from Isovalent Inc.
*/

package helm

import (
	"bytes"
	"fmt"
	"strings"

	"github.com/go-logr/logr"
	"gopkg.in/yaml.v2"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
	"k8s.io/apimachinery/pkg/runtime"

	"k8s.io/cli-runtime/pkg/genericclioptions"
	"k8s.io/cli-runtime/pkg/resource"

	helmaction "helm.sh/helm/v3/pkg/action"
	helmchart "helm.sh/helm/v3/pkg/chart"
	helmchartutil "helm.sh/helm/v3/pkg/chartutil"
	helmkube "helm.sh/helm/v3/pkg/kube"

	ciliumiov1alpha1 "github.com/isovalent/cilium/olm/api/v1alpha1"
)

const (
	ciliumRelease = "cilium-release"
)

// Generate creates the required helm action and makes a dry run of it.
// It then converts the produced manifests into a slice of unstructured.Unstructured references.
func Generate(helmClientGetter genericclioptions.RESTClientGetter, chart *helmchart.Chart, values map[string]interface{}, ccfg *ciliumiov1alpha1.CiliumConfig, ns string, logger logr.Logger) ([]*unstructured.Unstructured, error) {
	actionConfig := new(helmaction.Configuration)
	if err := actionConfig.Init(helmClientGetter, ns, "", func(msg string, v ...interface{}) {
		logger.V(4).Info(msg, "values", v)
	}); err != nil {
		return nil, err
	}
	instAction := helmaction.NewInstall(actionConfig)
	instAction.Namespace = ns
	instAction.ReleaseName = ciliumRelease
	instAction.PostRenderer = postRenderer{
		client:    actionConfig.KubeClient,
		owner:     ccfg,
		version:   chart.AppVersion(),
		namespace: ns,
	}
	// Client only is not suitable as there are lookup functions in install/kubernetes/cilium/templates/_helpers.tpl
	instAction.DryRun = true
	release, err := instAction.Run(chart, values)
	if err != nil {
		return nil, fmt.Errorf("error processing charts: %w", err)
	}
	logger.V(4).Info("update", "manifests", release.Manifest)
	return Decode(strings.NewReader(release.Manifest))
}

// Values extracts the helm values from the CiliumConfig custom resource
func Values(ccfg *ciliumiov1alpha1.CiliumConfig) (helmchartutil.Values, error) {
	hv, err := helmchartutil.ReadValues(ccfg.Spec.Raw)
	if err != nil {
		return nil, fmt.Errorf("helm values cannot be read from CiliumConfig: %w", err)
	}
	return hv, nil
}

type postRenderer struct {
	client    helmkube.Interface
	owner     *ciliumiov1alpha1.CiliumConfig
	version   string
	namespace string
}

// Run apply post rendering modifications to the resources generated by helm
func (pr postRenderer) Run(in *bytes.Buffer) (*bytes.Buffer, error) {
	resources, err := pr.client.Build(in, false)
	if err != nil {
		return nil, err
	}
	result := bytes.Buffer{}

	err = resources.Visit(func(res *resource.Info, err error) error {
		if err != nil {
			return err
		}
		obj, err := runtime.DefaultUnstructuredConverter.ToUnstructured(res.Object)
		if err != nil {
			return err
		}
		u := &unstructured.Unstructured{Object: obj}

		labels := u.GetLabels()
		if labels == nil {
			labels = map[string]string{}
		}
		labels["isovalent.io/managed-by"] = "clife"
		// The chart version is used for secret reconciliation as they are not idempotent
		labels["app.kubernetes.io/version"] = pr.version
		// This is required by the helm library for resource adoption
		labels["app.kubernetes.io/managed-by"] = "Helm"
		u.SetLabels(labels)
		// This is required by the helm library for resource adoption
		annotations := u.GetAnnotations()
		if annotations == nil {
			annotations = map[string]string{}
		}
		annotations["meta.helm.sh/release-name"] = ciliumRelease
		annotations["meta.helm.sh/release-namespace"] = pr.namespace
		u.SetAnnotations(annotations)
		// Owner references cause the child resources to be deleted when the CiliumConfig is deleted.
		// An annotation could be used instead of them to avoid this behavior when desired.
		ownerRef := metav1.NewControllerRef(pr.owner, pr.owner.GetObjectKind().GroupVersionKind())
		ownerRefs := append(u.GetOwnerReferences(), *ownerRef)
		u.SetOwnerReferences(ownerRefs)
		data, err := yaml.Marshal(u.Object)
		if err != nil {
			return err
		}
		if _, err := result.WriteString("---\n" + string(data)); err != nil {
			return err
		}
		return nil
	})
	if err != nil {
		return nil, err
	}
	return &result, nil
}
