apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: clife
    app.kubernetes.io/managed-by: kustomize
    pod-security.kubernetes.io/audit: privileged
    openshift.io/run-level: "0"
    openshift.io/cluster-logging: "true"
    openshift.io/cluster-monitoring: "true"
  name: cilium
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: cilium
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: clife
    app.kubernetes.io/managed-by: kustomize
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: controller-manager
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/arch
                  operator: In
                  values:
                    - amd64
                    - arm64
                - key: kubernetes.io/os
                  operator: In
                  values:
                    - linux
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - command:
        - /clife-manager
        args:
        - --leader-elect
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: controller:latest
        name: manager
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - "ALL"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 49081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 49081
          initialDelaySeconds: 5
          periodSeconds: 10
        ports:
        - containerPort: 49081
          name: probe
          protocol: TCP
        # TODO(user): Configure the resources accordingly based on the project requirements.
        # More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
        resources:
          limits:
            cpu: 1000m
            memory: 768Mi
          requests:
            cpu: 100m
            memory: 768Mi
      serviceAccountName: controller-manager
      terminationGracePeriodSeconds: 10
      # required to run before the CNI plugin is set up
      hostNetwork: true
      # required to run before the nodes are ready
      tolerations:
      - operator: Exists
