{{- if and .Values.agent (eq (include "hubble.timescape.tls.enabled" .) "true") (eq .Values.hubble.tls.auto.method "certmanager") }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hubble-timescape-client-certs
  namespace: {{ include "cilium.namespace" . }}
  {{- with .Values.hubble.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  issuerRef:
    {{- toYaml .Values.hubble.tls.auto.certManagerIssuerRef | nindent 4 }}
  secretName: hubble-timescape-client-certs
  commonName: "hubble-timescape-client"
  dnsNames:
  - "hubble-timescape-client"
  duration: {{ printf "%dh0m0s" (mul .Values.hubble.tls.auto.certValidityDuration 24) }}
  privateKey:
    rotationPolicy: Always
  isCA: false
  usages:
    - signing
    - key encipherment
    - client auth
{{- end }}
