{{- if and
  .Values.hubble.enabled
  (eq (include "hubble.k8s-exporter.enabled" .) "true")
  .Values.serviceAccounts.hubbleK8sExporter.create
  .Values.rbac.create
}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hubble-k8s-exporter
  labels:
    {{- include "hubble.k8s-exporter.labels" . | nindent 4 }}
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
rules:
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cilium.io
  resources:
  - ciliumnetworkpolicies
  - ciliumclusterwidenetworkpolicies
  - ciliumidentities
  verbs:
  - get
  - list
  - watch
{{- end }}
