{{- if and
  .Values.hubble.enabled
  (eq (include "hubble.k8s-exporter.enabled" .) "true")
}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: hubble-k8s-exporter
  namespace: {{ include "cilium.namespace" . }}
  labels:
    {{- include "hubble.k8s-exporter.labels" . | nindent 4 }}
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
data:
  config.yaml: |
    debug: {{ .Values.hubble.k8sExporter.debug | default false }}
    export:
      cluster-name: {{ .Values.cluster.name | quote }}
      file-compression: {{ .Values.hubble.k8sExporter.export.fileCompression | quote }}
      file-path: {{ .Values.hubble.k8sExporter.export.filePath | quote }}
      file-rotation-interval: {{ .Values.hubble.k8sExporter.export.fileRotationInterval | quote }}
      k8s-endpoints: false
      cilium-identities: true
      max-file-backup: {{ .Values.hubble.k8sExporter.export.maxFileBackups | quote }}
      max-file-size: {{ .Values.hubble.k8sExporter.export.maxFileSize | quote }}
{{- end }}
