{{- if and
  .Values.hubble.enabled
  (eq (include "hubble.k8s-exporter.enabled" .) "true")
}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hubble-k8s-exporter
  namespace: {{ include "cilium.namespace" . }}
  labels:
    {{- include "hubble.k8s-exporter.labels" . | nindent 4 }}
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: hubble-k8s-exporter
      app.kubernetes.io/name: hubble-k8s-exporter
      app.kubernetes.io/part-of: cilium
  template:
    metadata:
      {{- with .Values.hubble.k8sExporter.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        k8s-app: hubble-k8s-exporter
        app.kubernetes.io/name: hubble-k8s-exporter
        app.kubernetes.io/part-of: cilium
        {{- with .Values.commonLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ .Values.serviceAccounts.hubbleK8sExporter.name }}
      securityContext:
        {{- toYaml .Values.hubble.k8sExporter.podSecurityContext | nindent 8 }}
      containers:
        - name: hubble-k8s-exporter
          securityContext:
            {{- toYaml .Values.hubble.k8sExporter.securityContext | nindent 12 }}
          image: {{ include "cilium.image" .Values.hubble.k8sExporter.image | quote }}
          imagePullPolicy: {{ .Values.hubble.k8sExporter.image.pullPolicy }}
          command:
            - /usr/bin/hubble-k8s-exporter
          args:
            - export
          resources:
            {{- toYaml .Values.hubble.k8sExporter.resources | nindent 12 }}
          volumeMounts:
            - mountPath: "/etc/hubble-k8s-exporter"
              name: config
              readOnly: true
            - mountPath: /var/run/cilium
              name: cilium-run
      priorityClassName: {{ .Values.hubble.k8sExporter.priorityClassName }}
      {{- with .Values.hubble.k8sExporter.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.hubble.k8sExporter.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.hubble.k8sExporter.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: config
          configMap:
            name: hubble-k8s-exporter
            items:
            - key: config.yaml
              path: config.yaml
        - name: cilium-run
          hostPath:
            path: /var/run/cilium
            type: DirectoryOrCreate
{{- end }}
