{{- if and
  .Values.hubble.enabled 
  (eq (include "hubble.k8s-exporter.enabled" .) "true")
  .Values.serviceAccounts.hubbleK8sExporter.create
}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccounts.hubbleK8sExporter.name | quote }}
  namespace: {{ include "cilium.namespace" . }}
  labels:
    {{- include "hubble.k8s-exporter.labels" . | nindent 4 }}
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.serviceAccounts.hubbleK8sExporter.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
