apiVersion: cilium.io/v2
kind: CiliumNodeConfig
metadata:
  namespace: kube-system
  name: t1-config
spec:
  nodeSelector:
    matchLabels:
      service.cilium.io/node: t1
  defaults:
    bpf-lb-acceleration: native
    bpf-lb-algorithm-annotation: "true"
    bpf-lb-mode-annotation: "true"
    bpf-lb-dsr-dispatch: ipip
    bpf-lb-only: "true"
    enable-ipip-termination: "false"
