apiVersion: cilium.io/v2
kind: CiliumNodeConfig
metadata:
  namespace: kube-system
  name: t1-config
spec:
  nodeSelector:
    matchLabels:
      service.cilium.io/node: t1
  defaults:
    datapath-mode: lb-only
    bpf-lb-acceleration: native
    bpf-lb-algorithm: random
    bpf-lb-mode-annotation: "true"
    bpf-lb-algorithm-annotation: "true"
    bpf-lb-mode: snat
    bpf-lb-dsr-dispatch: ipip
    enable-ipip-termination: "false"
    enable-envoy-config: "false"
