apiVersion: cilium.io/v2
kind: CiliumNodeConfig
metadata:
  namespace: kube-system
  name: t1-config
spec:
  nodeSelector:
    matchLabels:
      service.cilium.io/node: t1
  defaults:
    bpf-lb-algorithm-annotation: "true"
    bpf-lb-mode-annotation: "true"
    bpf-lb-ipip-sock-mark: "true"
    bpf-lb-dsr-dispatch: ipip
    routing-mode: "native"
    enable-pmtu-discovery: "true"
