apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  namespace: default
  name: ssh-to-websocket
spec:
  endpointSelector:
    matchLabels:
      run: ssh-client
  egress:
  - toPorts:
    - ports:
      - port: "22"
        protocol: ANY
      listener:
        envoyConfig:
          name: websocket-encap
        name: cilium-websocket-encap
  - toPorts:
    - ports:
      - port: "53"
        protocol: ANY
      rules:
        dns:
        - matchPattern: "*"
