// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/cilium/cilium/pkg/k8s/apis/isovalent.com/v1alpha1"
	isovalentcomv1alpha1 "github.com/cilium/cilium/pkg/k8s/client/clientset/versioned/typed/isovalent.com/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeIsovalentBGPClusterConfigs implements IsovalentBGPClusterConfigInterface
type fakeIsovalentBGPClusterConfigs struct {
	*gentype.FakeClientWithList[*v1alpha1.IsovalentBGPClusterConfig, *v1alpha1.IsovalentBGPClusterConfigList]
	Fake *FakeIsovalentV1alpha1
}

func newFakeIsovalentBGPClusterConfigs(fake *FakeIsovalentV1alpha1) isovalentcomv1alpha1.IsovalentBGPClusterConfigInterface {
	return &fakeIsovalentBGPClusterConfigs{
		gentype.NewFakeClientWithList[*v1alpha1.IsovalentBGPClusterConfig, *v1alpha1.IsovalentBGPClusterConfigList](
			fake.Fake,
			"",
			v1alpha1.SchemeGroupVersion.WithResource("isovalentbgpclusterconfigs"),
			v1alpha1.SchemeGroupVersion.WithKind("IsovalentBGPClusterConfig"),
			func() *v1alpha1.IsovalentBGPClusterConfig { return &v1alpha1.IsovalentBGPClusterConfig{} },
			func() *v1alpha1.IsovalentBGPClusterConfigList { return &v1alpha1.IsovalentBGPClusterConfigList{} },
			func(dst, src *v1alpha1.IsovalentBGPClusterConfigList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.IsovalentBGPClusterConfigList) []*v1alpha1.IsovalentBGPClusterConfig {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.IsovalentBGPClusterConfigList, items []*v1alpha1.IsovalentBGPClusterConfig) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
