// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/cilium/cilium/pkg/k8s/apis/isovalent.com/v1alpha1"
	isovalentcomv1alpha1 "github.com/cilium/cilium/pkg/k8s/client/applyconfiguration/isovalent.com/v1alpha1"
	typedisovalentcomv1alpha1 "github.com/cilium/cilium/pkg/k8s/client/clientset/versioned/typed/isovalent.com/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeIsovalentSRv6EgressPolicies implements IsovalentSRv6EgressPolicyInterface
type fakeIsovalentSRv6EgressPolicies struct {
	*gentype.FakeClientWithListAndApply[*v1alpha1.IsovalentSRv6EgressPolicy, *v1alpha1.IsovalentSRv6EgressPolicyList, *isovalentcomv1alpha1.IsovalentSRv6EgressPolicyApplyConfiguration]
	Fake *FakeIsovalentV1alpha1
}

func newFakeIsovalentSRv6EgressPolicies(fake *FakeIsovalentV1alpha1) typedisovalentcomv1alpha1.IsovalentSRv6EgressPolicyInterface {
	return &fakeIsovalentSRv6EgressPolicies{
		gentype.NewFakeClientWithListAndApply[*v1alpha1.IsovalentSRv6EgressPolicy, *v1alpha1.IsovalentSRv6EgressPolicyList, *isovalentcomv1alpha1.IsovalentSRv6EgressPolicyApplyConfiguration](
			fake.Fake,
			"",
			v1alpha1.SchemeGroupVersion.WithResource("isovalentsrv6egresspolicies"),
			v1alpha1.SchemeGroupVersion.WithKind("IsovalentSRv6EgressPolicy"),
			func() *v1alpha1.IsovalentSRv6EgressPolicy { return &v1alpha1.IsovalentSRv6EgressPolicy{} },
			func() *v1alpha1.IsovalentSRv6EgressPolicyList { return &v1alpha1.IsovalentSRv6EgressPolicyList{} },
			func(dst, src *v1alpha1.IsovalentSRv6EgressPolicyList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.IsovalentSRv6EgressPolicyList) []*v1alpha1.IsovalentSRv6EgressPolicy {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.IsovalentSRv6EgressPolicyList, items []*v1alpha1.IsovalentSRv6EgressPolicy) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
