// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/cilium/cilium/pkg/k8s/apis/isovalent.com/v1alpha1"
	isovalentcomv1alpha1 "github.com/cilium/cilium/pkg/k8s/client/clientset/versioned/typed/isovalent.com/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeIsovalentBGPAdvertisements implements IsovalentBGPAdvertisementInterface
type fakeIsovalentBGPAdvertisements struct {
	*gentype.FakeClientWithList[*v1alpha1.IsovalentBGPAdvertisement, *v1alpha1.IsovalentBGPAdvertisementList]
	Fake *FakeIsovalentV1alpha1
}

func newFakeIsovalentBGPAdvertisements(fake *FakeIsovalentV1alpha1) isovalentcomv1alpha1.IsovalentBGPAdvertisementInterface {
	return &fakeIsovalentBGPAdvertisements{
		gentype.NewFakeClientWithList[*v1alpha1.IsovalentBGPAdvertisement, *v1alpha1.IsovalentBGPAdvertisementList](
			fake.Fake,
			"",
			v1alpha1.SchemeGroupVersion.WithResource("isovalentbgpadvertisements"),
			v1alpha1.SchemeGroupVersion.WithKind("IsovalentBGPAdvertisement"),
			func() *v1alpha1.IsovalentBGPAdvertisement { return &v1alpha1.IsovalentBGPAdvertisement{} },
			func() *v1alpha1.IsovalentBGPAdvertisementList { return &v1alpha1.IsovalentBGPAdvertisementList{} },
			func(dst, src *v1alpha1.IsovalentBGPAdvertisementList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.IsovalentBGPAdvertisementList) []*v1alpha1.IsovalentBGPAdvertisement {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.IsovalentBGPAdvertisementList, items []*v1alpha1.IsovalentBGPAdvertisement) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
