// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/cilium/cilium/pkg/k8s/apis/isovalent.com/v1alpha1"
	isovalentcomv1alpha1 "github.com/cilium/cilium/pkg/k8s/client/clientset/versioned/typed/isovalent.com/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeIsovalentBFDNodeConfigOverrides implements IsovalentBFDNodeConfigOverrideInterface
type fakeIsovalentBFDNodeConfigOverrides struct {
	*gentype.FakeClientWithList[*v1alpha1.IsovalentBFDNodeConfigOverride, *v1alpha1.IsovalentBFDNodeConfigOverrideList]
	Fake *FakeIsovalentV1alpha1
}

func newFakeIsovalentBFDNodeConfigOverrides(fake *FakeIsovalentV1alpha1) isovalentcomv1alpha1.IsovalentBFDNodeConfigOverrideInterface {
	return &fakeIsovalentBFDNodeConfigOverrides{
		gentype.NewFakeClientWithList[*v1alpha1.IsovalentBFDNodeConfigOverride, *v1alpha1.IsovalentBFDNodeConfigOverrideList](
			fake.Fake,
			"",
			v1alpha1.SchemeGroupVersion.WithResource("isovalentbfdnodeconfigoverrides"),
			v1alpha1.SchemeGroupVersion.WithKind("IsovalentBFDNodeConfigOverride"),
			func() *v1alpha1.IsovalentBFDNodeConfigOverride { return &v1alpha1.IsovalentBFDNodeConfigOverride{} },
			func() *v1alpha1.IsovalentBFDNodeConfigOverrideList {
				return &v1alpha1.IsovalentBFDNodeConfigOverrideList{}
			},
			func(dst, src *v1alpha1.IsovalentBFDNodeConfigOverrideList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.IsovalentBFDNodeConfigOverrideList) []*v1alpha1.IsovalentBFDNodeConfigOverride {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.IsovalentBFDNodeConfigOverrideList, items []*v1alpha1.IsovalentBFDNodeConfigOverride) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
