// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/cilium/cilium/pkg/k8s/apis/isovalent.com/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeLBBackends implements LBBackendInterface
type FakeLBBackends struct {
	Fake *FakeIsovalentV1alpha1
	ns   string
}

var lbbackendsResource = v1alpha1.SchemeGroupVersion.WithResource("lbbackends")

var lbbackendsKind = v1alpha1.SchemeGroupVersion.WithKind("LBBackend")

// Get takes name of the lBBackend, and returns the corresponding lBBackend object, and an error if there is any.
func (c *FakeLBBackends) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.LBBackend, err error) {
	emptyResult := &v1alpha1.LBBackend{}
	obj, err := c.Fake.
		Invokes(testing.NewGetActionWithOptions(lbbackendsResource, c.ns, name, options), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.LBBackend), err
}

// List takes label and field selectors, and returns the list of LBBackends that match those selectors.
func (c *FakeLBBackends) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.LBBackendList, err error) {
	emptyResult := &v1alpha1.LBBackendList{}
	obj, err := c.Fake.
		Invokes(testing.NewListActionWithOptions(lbbackendsResource, lbbackendsKind, c.ns, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.LBBackendList{ListMeta: obj.(*v1alpha1.LBBackendList).ListMeta}
	for _, item := range obj.(*v1alpha1.LBBackendList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested lBBackends.
func (c *FakeLBBackends) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchActionWithOptions(lbbackendsResource, c.ns, opts))

}

// Create takes the representation of a lBBackend and creates it.  Returns the server's representation of the lBBackend, and an error, if there is any.
func (c *FakeLBBackends) Create(ctx context.Context, lBBackend *v1alpha1.LBBackend, opts v1.CreateOptions) (result *v1alpha1.LBBackend, err error) {
	emptyResult := &v1alpha1.LBBackend{}
	obj, err := c.Fake.
		Invokes(testing.NewCreateActionWithOptions(lbbackendsResource, c.ns, lBBackend, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.LBBackend), err
}

// Update takes the representation of a lBBackend and updates it. Returns the server's representation of the lBBackend, and an error, if there is any.
func (c *FakeLBBackends) Update(ctx context.Context, lBBackend *v1alpha1.LBBackend, opts v1.UpdateOptions) (result *v1alpha1.LBBackend, err error) {
	emptyResult := &v1alpha1.LBBackend{}
	obj, err := c.Fake.
		Invokes(testing.NewUpdateActionWithOptions(lbbackendsResource, c.ns, lBBackend, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.LBBackend), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeLBBackends) UpdateStatus(ctx context.Context, lBBackend *v1alpha1.LBBackend, opts v1.UpdateOptions) (result *v1alpha1.LBBackend, err error) {
	emptyResult := &v1alpha1.LBBackend{}
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceActionWithOptions(lbbackendsResource, "status", c.ns, lBBackend, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.LBBackend), err
}

// Delete takes name of the lBBackend and deletes it. Returns an error if one occurs.
func (c *FakeLBBackends) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(lbbackendsResource, c.ns, name, opts), &v1alpha1.LBBackend{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeLBBackends) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionActionWithOptions(lbbackendsResource, c.ns, opts, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.LBBackendList{})
	return err
}

// Patch applies the patch and returns the patched lBBackend.
func (c *FakeLBBackends) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.LBBackend, err error) {
	emptyResult := &v1alpha1.LBBackend{}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceActionWithOptions(lbbackendsResource, c.ns, name, pt, data, opts, subresources...), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.LBBackend), err
}
