// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/cilium/cilium/pkg/k8s/apis/isovalent.com/v1alpha1"
	isovalentcomv1alpha1 "github.com/cilium/cilium/pkg/k8s/client/clientset/versioned/typed/isovalent.com/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeIsovalentSRv6SIDManagers implements IsovalentSRv6SIDManagerInterface
type fakeIsovalentSRv6SIDManagers struct {
	*gentype.FakeClientWithList[*v1alpha1.IsovalentSRv6SIDManager, *v1alpha1.IsovalentSRv6SIDManagerList]
	Fake *FakeIsovalentV1alpha1
}

func newFakeIsovalentSRv6SIDManagers(fake *FakeIsovalentV1alpha1) isovalentcomv1alpha1.IsovalentSRv6SIDManagerInterface {
	return &fakeIsovalentSRv6SIDManagers{
		gentype.NewFakeClientWithList[*v1alpha1.IsovalentSRv6SIDManager, *v1alpha1.IsovalentSRv6SIDManagerList](
			fake.Fake,
			"",
			v1alpha1.SchemeGroupVersion.WithResource("isovalentsrv6sidmanagers"),
			v1alpha1.SchemeGroupVersion.WithKind("IsovalentSRv6SIDManager"),
			func() *v1alpha1.IsovalentSRv6SIDManager { return &v1alpha1.IsovalentSRv6SIDManager{} },
			func() *v1alpha1.IsovalentSRv6SIDManagerList { return &v1alpha1.IsovalentSRv6SIDManagerList{} },
			func(dst, src *v1alpha1.IsovalentSRv6SIDManagerList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.IsovalentSRv6SIDManagerList) []*v1alpha1.IsovalentSRv6SIDManager {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.IsovalentSRv6SIDManagerList, items []*v1alpha1.IsovalentSRv6SIDManager) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
