// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/cilium/cilium/pkg/k8s/apis/isovalent.com/v1alpha1"
	isovalentcomv1alpha1 "github.com/cilium/cilium/pkg/k8s/client/clientset/versioned/typed/isovalent.com/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakePrivateNetworkNodeAttachments implements PrivateNetworkNodeAttachmentInterface
type fakePrivateNetworkNodeAttachments struct {
	*gentype.FakeClientWithList[*v1alpha1.PrivateNetworkNodeAttachment, *v1alpha1.PrivateNetworkNodeAttachmentList]
	Fake *FakeIsovalentV1alpha1
}

func newFakePrivateNetworkNodeAttachments(fake *FakeIsovalentV1alpha1) isovalentcomv1alpha1.PrivateNetworkNodeAttachmentInterface {
	return &fakePrivateNetworkNodeAttachments{
		gentype.NewFakeClientWithList[*v1alpha1.PrivateNetworkNodeAttachment, *v1alpha1.PrivateNetworkNodeAttachmentList](
			fake.Fake,
			"",
			v1alpha1.SchemeGroupVersion.WithResource("privatenetworknodeattachments"),
			v1alpha1.SchemeGroupVersion.WithKind("PrivateNetworkNodeAttachment"),
			func() *v1alpha1.PrivateNetworkNodeAttachment { return &v1alpha1.PrivateNetworkNodeAttachment{} },
			func() *v1alpha1.PrivateNetworkNodeAttachmentList { return &v1alpha1.PrivateNetworkNodeAttachmentList{} },
			func(dst, src *v1alpha1.PrivateNetworkNodeAttachmentList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.PrivateNetworkNodeAttachmentList) []*v1alpha1.PrivateNetworkNodeAttachment {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.PrivateNetworkNodeAttachmentList, items []*v1alpha1.PrivateNetworkNodeAttachment) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
