// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/cilium/cilium/pkg/k8s/apis/isovalent.com/v1alpha1"
	isovalentcomv1alpha1 "github.com/cilium/cilium/pkg/k8s/client/clientset/versioned/typed/isovalent.com/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeLBVIPs implements LBVIPInterface
type fakeLBVIPs struct {
	*gentype.FakeClientWithList[*v1alpha1.LBVIP, *v1alpha1.LBVIPList]
	Fake *FakeIsovalentV1alpha1
}

func newFakeLBVIPs(fake *FakeIsovalentV1alpha1, namespace string) isovalentcomv1alpha1.LBVIPInterface {
	return &fakeLBVIPs{
		gentype.NewFakeClientWithList[*v1alpha1.LBVIP, *v1alpha1.LBVIPList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("lbvips"),
			v1alpha1.SchemeGroupVersion.WithKind("LBVIP"),
			func() *v1alpha1.LBVIP { return &v1alpha1.LBVIP{} },
			func() *v1alpha1.LBVIPList { return &v1alpha1.LBVIPList{} },
			func(dst, src *v1alpha1.LBVIPList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.LBVIPList) []*v1alpha1.LBVIP { return gentype.ToPointerSlice(list.Items) },
			func(list *v1alpha1.LBVIPList, items []*v1alpha1.LBVIP) { list.Items = gentype.FromPointerSlice(items) },
		),
		fake,
	}
}
