// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/cilium/cilium/pkg/k8s/apis/isovalent.com/v1alpha1"
	isovalentcomv1alpha1 "github.com/cilium/cilium/pkg/k8s/client/clientset/versioned/typed/isovalent.com/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeIsovalentVRFs implements IsovalentVRFInterface
type fakeIsovalentVRFs struct {
	*gentype.FakeClientWithList[*v1alpha1.IsovalentVRF, *v1alpha1.IsovalentVRFList]
	Fake *FakeIsovalentV1alpha1
}

func newFakeIsovalentVRFs(fake *FakeIsovalentV1alpha1) isovalentcomv1alpha1.IsovalentVRFInterface {
	return &fakeIsovalentVRFs{
		gentype.NewFakeClientWithList[*v1alpha1.IsovalentVRF, *v1alpha1.IsovalentVRFList](
			fake.Fake,
			"",
			v1alpha1.SchemeGroupVersion.WithResource("isovalentvrfs"),
			v1alpha1.SchemeGroupVersion.WithKind("IsovalentVRF"),
			func() *v1alpha1.IsovalentVRF { return &v1alpha1.IsovalentVRF{} },
			func() *v1alpha1.IsovalentVRFList { return &v1alpha1.IsovalentVRFList{} },
			func(dst, src *v1alpha1.IsovalentVRFList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.IsovalentVRFList) []*v1alpha1.IsovalentVRF {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.IsovalentVRFList, items []*v1alpha1.IsovalentVRF) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
