// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/cilium/cilium/pkg/k8s/apis/isovalent.com/v1alpha1"
	isovalentcomv1alpha1 "github.com/cilium/cilium/pkg/k8s/client/applyconfiguration/isovalent.com/v1alpha1"
	typedisovalentcomv1alpha1 "github.com/cilium/cilium/pkg/k8s/client/clientset/versioned/typed/isovalent.com/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeIsovalentClusterwideNetworkPolicies implements IsovalentClusterwideNetworkPolicyInterface
type fakeIsovalentClusterwideNetworkPolicies struct {
	*gentype.FakeClientWithListAndApply[*v1alpha1.IsovalentClusterwideNetworkPolicy, *v1alpha1.IsovalentClusterwideNetworkPolicyList, *isovalentcomv1alpha1.IsovalentClusterwideNetworkPolicyApplyConfiguration]
	Fake *FakeIsovalentV1alpha1
}

func newFakeIsovalentClusterwideNetworkPolicies(fake *FakeIsovalentV1alpha1) typedisovalentcomv1alpha1.IsovalentClusterwideNetworkPolicyInterface {
	return &fakeIsovalentClusterwideNetworkPolicies{
		gentype.NewFakeClientWithListAndApply[*v1alpha1.IsovalentClusterwideNetworkPolicy, *v1alpha1.IsovalentClusterwideNetworkPolicyList, *isovalentcomv1alpha1.IsovalentClusterwideNetworkPolicyApplyConfiguration](
			fake.Fake,
			"",
			v1alpha1.SchemeGroupVersion.WithResource("isovalentclusterwidenetworkpolicies"),
			v1alpha1.SchemeGroupVersion.WithKind("IsovalentClusterwideNetworkPolicy"),
			func() *v1alpha1.IsovalentClusterwideNetworkPolicy {
				return &v1alpha1.IsovalentClusterwideNetworkPolicy{}
			},
			func() *v1alpha1.IsovalentClusterwideNetworkPolicyList {
				return &v1alpha1.IsovalentClusterwideNetworkPolicyList{}
			},
			func(dst, src *v1alpha1.IsovalentClusterwideNetworkPolicyList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.IsovalentClusterwideNetworkPolicyList) []*v1alpha1.IsovalentClusterwideNetworkPolicy {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.IsovalentClusterwideNetworkPolicyList, items []*v1alpha1.IsovalentClusterwideNetworkPolicy) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
