// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/cilium/cilium/pkg/k8s/apis/isovalent.com/v1alpha1"
	isovalentcomv1alpha1 "github.com/cilium/cilium/pkg/k8s/client/applyconfiguration/isovalent.com/v1alpha1"
	typedisovalentcomv1alpha1 "github.com/cilium/cilium/pkg/k8s/client/clientset/versioned/typed/isovalent.com/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeIsovalentBGPPeerConfigs implements IsovalentBGPPeerConfigInterface
type fakeIsovalentBGPPeerConfigs struct {
	*gentype.FakeClientWithListAndApply[*v1alpha1.IsovalentBGPPeerConfig, *v1alpha1.IsovalentBGPPeerConfigList, *isovalentcomv1alpha1.IsovalentBGPPeerConfigApplyConfiguration]
	Fake *FakeIsovalentV1alpha1
}

func newFakeIsovalentBGPPeerConfigs(fake *FakeIsovalentV1alpha1) typedisovalentcomv1alpha1.IsovalentBGPPeerConfigInterface {
	return &fakeIsovalentBGPPeerConfigs{
		gentype.NewFakeClientWithListAndApply[*v1alpha1.IsovalentBGPPeerConfig, *v1alpha1.IsovalentBGPPeerConfigList, *isovalentcomv1alpha1.IsovalentBGPPeerConfigApplyConfiguration](
			fake.Fake,
			"",
			v1alpha1.SchemeGroupVersion.WithResource("isovalentbgppeerconfigs"),
			v1alpha1.SchemeGroupVersion.WithKind("IsovalentBGPPeerConfig"),
			func() *v1alpha1.IsovalentBGPPeerConfig { return &v1alpha1.IsovalentBGPPeerConfig{} },
			func() *v1alpha1.IsovalentBGPPeerConfigList { return &v1alpha1.IsovalentBGPPeerConfigList{} },
			func(dst, src *v1alpha1.IsovalentBGPPeerConfigList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.IsovalentBGPPeerConfigList) []*v1alpha1.IsovalentBGPPeerConfig {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.IsovalentBGPPeerConfigList, items []*v1alpha1.IsovalentBGPPeerConfig) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
