// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/cilium/cilium/pkg/k8s/apis/isovalent.com/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeLBFrontends implements LBFrontendInterface
type FakeLBFrontends struct {
	Fake *FakeIsovalentV1alpha1
	ns   string
}

var lbfrontendsResource = v1alpha1.SchemeGroupVersion.WithResource("lbfrontends")

var lbfrontendsKind = v1alpha1.SchemeGroupVersion.WithKind("LBFrontend")

// Get takes name of the lBFrontend, and returns the corresponding lBFrontend object, and an error if there is any.
func (c *FakeLBFrontends) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.LBFrontend, err error) {
	emptyResult := &v1alpha1.LBFrontend{}
	obj, err := c.Fake.
		Invokes(testing.NewGetActionWithOptions(lbfrontendsResource, c.ns, name, options), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.LBFrontend), err
}

// List takes label and field selectors, and returns the list of LBFrontends that match those selectors.
func (c *FakeLBFrontends) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.LBFrontendList, err error) {
	emptyResult := &v1alpha1.LBFrontendList{}
	obj, err := c.Fake.
		Invokes(testing.NewListActionWithOptions(lbfrontendsResource, lbfrontendsKind, c.ns, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.LBFrontendList{ListMeta: obj.(*v1alpha1.LBFrontendList).ListMeta}
	for _, item := range obj.(*v1alpha1.LBFrontendList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested lBFrontends.
func (c *FakeLBFrontends) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchActionWithOptions(lbfrontendsResource, c.ns, opts))

}

// Create takes the representation of a lBFrontend and creates it.  Returns the server's representation of the lBFrontend, and an error, if there is any.
func (c *FakeLBFrontends) Create(ctx context.Context, lBFrontend *v1alpha1.LBFrontend, opts v1.CreateOptions) (result *v1alpha1.LBFrontend, err error) {
	emptyResult := &v1alpha1.LBFrontend{}
	obj, err := c.Fake.
		Invokes(testing.NewCreateActionWithOptions(lbfrontendsResource, c.ns, lBFrontend, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.LBFrontend), err
}

// Update takes the representation of a lBFrontend and updates it. Returns the server's representation of the lBFrontend, and an error, if there is any.
func (c *FakeLBFrontends) Update(ctx context.Context, lBFrontend *v1alpha1.LBFrontend, opts v1.UpdateOptions) (result *v1alpha1.LBFrontend, err error) {
	emptyResult := &v1alpha1.LBFrontend{}
	obj, err := c.Fake.
		Invokes(testing.NewUpdateActionWithOptions(lbfrontendsResource, c.ns, lBFrontend, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.LBFrontend), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeLBFrontends) UpdateStatus(ctx context.Context, lBFrontend *v1alpha1.LBFrontend, opts v1.UpdateOptions) (result *v1alpha1.LBFrontend, err error) {
	emptyResult := &v1alpha1.LBFrontend{}
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceActionWithOptions(lbfrontendsResource, "status", c.ns, lBFrontend, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.LBFrontend), err
}

// Delete takes name of the lBFrontend and deletes it. Returns an error if one occurs.
func (c *FakeLBFrontends) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(lbfrontendsResource, c.ns, name, opts), &v1alpha1.LBFrontend{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeLBFrontends) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionActionWithOptions(lbfrontendsResource, c.ns, opts, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.LBFrontendList{})
	return err
}

// Patch applies the patch and returns the patched lBFrontend.
func (c *FakeLBFrontends) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.LBFrontend, err error) {
	emptyResult := &v1alpha1.LBFrontend{}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceActionWithOptions(lbfrontendsResource, c.ns, name, pt, data, opts, subresources...), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.LBFrontend), err
}
