{{$actionName := printf "%s objects" .actionName}}
{{$namespaces := .namespaces}}
{{$tuningSet := .tuningSet}}
{{$fixedTuningSet := .fixedTuningSet}}
{{$operationTimeout := .operationTimeout}}
{{$deploymentsPerNamespace := .deploymentsPerNamespace}}
{{$replicasPerDeployment := .replicasPerDeployment}}

# Services
{{$largeServices := .largeServices}}
{{$slicesPerService := .slicesPerService}}
{{$slicesUpdates := .slicesUpdates}}

steps:
- name: {{$actionName}} services and cnps
  phases:
  - namespaceRange:
      min: 1
      max: 1
    replicasPerNamespace: {{$largeServices}}
    tuningSet: {{$fixedTuningSet}}
    objectBundle:
    - basename: service
      objectTemplatePath: service.yaml
  - namespaceRange:
      min: 1
      max: 1
    replicasPerNamespace: {{MultiplyInt $largeServices $slicesPerService}}
    tuningSet: {{$fixedTuningSet}}
    objectBundle:
    - basename: es
      objectTemplatePath: endpointslices.yaml
      templateFillMap:
        ServiceName: "service"
        ServiceNumber: {{$largeServices}}
  - namespaceRange:
      min: 1
      max: {{$namespaces}}
    replicasPerNamespace: 1
    tuningSet: {{$fixedTuningSet}}
    objectBundle:
    - basename: cnp
      objectTemplatePath: cnp.yaml
      templateFillMap:
        Replicas: 1

- name: Starting measurement for '{{$actionName}}'
  measurements:
  - Method: WaitForControlledPodsRunning
    Instances:
    - Identifier: WaitForRunningDeployments
      Params:
        apiVersion: apps/v1
        kind: Deployment
    Params:
      action: start
      checkIfPodsAreUpdated: true
      labelSelector: group = load
      operationTimeout: {{$operationTimeout}}

- name: {{$actionName}}
  phases:
  - namespaceRange:
      min: 1
      max: {{$namespaces}}
    replicasPerNamespace: {{$deploymentsPerNamespace}}
    tuningSet: {{$tuningSet}}
    objectBundle:
    - basename: small-deployment
      objectTemplatePath: deployment.yaml
      templateFillMap:
        Replicas: {{$replicasPerDeployment}}
{{range $i := Loop $slicesUpdates}}
  - namespaceRange:
      min: 1
      max: 1
    replicasPerNamespace: {{MultiplyInt $largeServices $slicesPerService}}
    tuningSet: {{$tuningSet}}
    objectBundle:
    - basename: es
      objectTemplatePath: endpointslices.yaml
      templateFillMap:
        ServiceName: "service"
        ServiceNumber: {{$largeServices}}
{{end}}

- name: Waiting for '{{$actionName}}' to be completed
  measurements:
  - Method: WaitForControlledPodsRunning
    Instances:
    - Identifier: WaitForRunningDeployments
    Params:
      action: gather
