{
 "title": "ILB T1",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "t1",
    "label": "T1 node",
    "query": {
     "query": "label_values(kube_node_labels{label_service_cilium_io_node=\"t1\"},node)"
    }
   },
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(cilium_lb_bytes_total,service)"
    }
   },
   {
    "name": "backend",
    "label": "Backend",
    "query": {
     "query": "label_values(cilium_lb_bytes_total,backend)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "[CT maps] Service BPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (service) (\n    rate(\n        cilium_lb_bytes_total{node=~\"^${t1}$\", service=~\"^${service}$\", backend=~\"^${backend}$\"}[$__rate_interval]\n    ) \n    * on (node) group_left() (\n        kube_node_labels{label_service_cilium_io_node=~\"t1\"}\n    )\n)",
     "legendFormat": "{{vip}}"
    }
   ]
  },
  {
   "title": "[CT maps] Service PPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum by (service) (\n    rate(\n        cilium_lb_packets_total{node=~\"^${t1}$\", service=~\"^${service}$\", backend=~\"^${backend}$\"}[$__rate_interval]\n    ) \n    * on (node) group_left() (\n        kube_node_labels{label_service_cilium_io_node=~\"t1\"}\n    )\n)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "[CT maps] Service BPS by backend",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (backend) (\n    rate(\n        cilium_lb_bytes_total{node=~\"^${t1}$\", service=~\"^${service}$\", backend=~\"^${backend}$\"}[$__rate_interval]\n    ) \n    * on (node) group_left() (\n        kube_node_labels{label_service_cilium_io_node=~\"t1\"}\n    )\n)",
     "legendFormat": "{{backend}}"
    }
   ]
  },
  {
   "title": "[CT maps] Service PPS by backend",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum by (backend) (\n    rate(\n        cilium_lb_packets_total{node=~\"^${t1}$\", service=~\"^${service}$\", backend=~\"^${backend}$\"}[$__rate_interval]\n    ) \n    * on (node) group_left() (\n        kube_node_labels{label_service_cilium_io_node=~\"t1\"}\n    )\n)",
     "legendFormat": "{{backend}}"
    }
   ]
  },
  {
   "title": "[ethtool] BPS (xdp)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (instance) (\n    rate(\n        node_ethtool_received_queue_0_xdp_bytes[$__rate_interval])\n    ) * on (instance) group_left(node) (\n        label_replace(kube_node_status_addresses{node=~\"$t1\"}, \"instance\", \"$1:9100\", \"address\", \"(.*)\"\n    )\n) * on (node) (\n    kube_node_labels{label_service_cilium_io_node=\"t1\"}\n)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "[ethtool] PPS (xdp)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum by (instance) (\n    rate(\n        node_ethtool_received_queue_0_xdp_packets[$__rate_interval])\n    ) * on (instance) group_left(node) (\n        label_replace(kube_node_status_addresses{node=~\"$t1\"}, \"instance\", \"$1:9100\", \"address\", \"(.*)\"\n    )\n) * on (node) (\n    kube_node_labels{label_service_cilium_io_node=\"t1\"}\n)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "[CT map] Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by (node) (\n    rate(\n        cilium_lb_open_connections_metric{node=~\"^${t1}$\"}[$__rate_interval]\n    ) \n    * on (node) group_left() (\n        kube_node_labels{label_service_cilium_io_node=~\"t1\"}\n    )\n)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  { "title": "Healthcheck", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Healthcheck status",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "cilium_lb_healthcheck_status{node=~\"^${t1}$\", service=~\"^${service}$\", backend=~\"^${backend}$\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Healthcheck status",
   "type": "esnet-matrix-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "bottomk by (service,backend) (1,cilium_lb_healthcheck_status{node=~\"^${t1}$\", service=~\"^${service}$\", backend=~\"^${backend}$\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "CPU %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * avg(\n  1 - rate(\n    node_cpu_seconds_total{mode=~\"idle\"}[$__rate_interval]\n    )\n  ) by (instance)\n* on (instance) group_left(node) (\n  label_replace(kube_node_status_addresses{node=~\"^${t1}$\"}, \"instance\", \"$1:9100\", \"address\", \"(.*)\")\n)\n* on (node) group_left() (\n  kube_node_labels{label_service_cilium_io_node=~\"t1\"}\n)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_load1{job=\"node-exporter\"} \n* on (instance) group_left(node) (\n    label_replace(kube_node_status_addresses{node=~\"^${t1}$\"}, \"instance\", \"$1:9100\", \"address\", \"(.*)\")\n) * on (node) group_left() (\n  kube_node_labels{label_service_cilium_io_node=~\"t1\"}\n)",
     "legendFormat": "{{node}}, 1m"
    },
    {
     "expr": "node_load5{job=\"node-exporter\"} \n* on (instance) group_left(node) (\n    label_replace(kube_node_status_addresses{node=~\"^${t1}$\"}, \"instance\", \"$1:9100\", \"address\", \"(.*)\")\n) * on (node) group_left() (\n  kube_node_labels{label_service_cilium_io_node=~\"t1\"}\n)",
     "legendFormat": "{{node}}, 5m"
    },
    {
     "expr": "node_load15{job=\"node-exporter\"} \n* on (instance) group_left(node) (\n    label_replace(kube_node_status_addresses{node=~\"^${t1}$\"}, \"instance\", \"$1:9100\", \"address\", \"(.*)\")\n) * on (node) group_left() (\n  kube_node_labels{label_service_cilium_io_node=~\"t1\"}\n)",
     "legendFormat": "{{node}}, 15m"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(\n  node_memory_MemTotal_bytes{job=\"node-exporter\"}\n-\n  node_memory_MemFree_bytes{job=\"node-exporter\"}\n-\n  node_memory_Buffers_bytes{job=\"node-exporter\"}\n-\n  node_memory_Cached_bytes{job=\"node-exporter\"}\n)\n* on (instance) group_left(node) (\n  label_replace(kube_node_status_addresses{node=~\"^${t1}$\"}, \"instance\", \"$1:9100\", \"address\", \"(.*)\")\n)\n* on (node) group_left() (\n  kube_node_labels{label_service_cilium_io_node=~\"t1\"}\n)\n",
     "legendFormat": "{{node}} used"
    },
    {
     "expr": "node_memory_Buffers_bytes{job=\"node-exporter\"} * on (instance) group_left(node) (\n  label_replace(kube_node_status_addresses{node=~\"^${t1}$\"}, \"instance\", \"$1:9100\", \"address\", \"(.*)\")\n)\n* on (node) group_left() (\n  kube_node_labels{label_service_cilium_io_node=~\"t1\"}\n)",
     "legendFormat": "{{node}} buffers"
    },
    {
     "expr": "node_memory_Cached_bytes{job=\"node-exporter\"} * on (instance) group_left(node) (\n  label_replace(kube_node_status_addresses{node=~\"^${t1}$\"}, \"instance\", \"$1:9100\", \"address\", \"(.*)\")\n)\n* on (node) group_left() (\n  kube_node_labels{label_service_cilium_io_node=~\"t1\"}\n)",
     "legendFormat": "{{node}} cached"
    },
    {
     "expr": "node_memory_MemFree_bytes{job=\"node-exporter\"} * on (instance) group_left(node) (\n  label_replace(kube_node_status_addresses{node=~\"^${t1}$\"}, \"instance\", \"$1:9100\", \"address\", \"(.*)\")\n)\n* on (node) group_left() (\n  kube_node_labels{label_service_cilium_io_node=~\"t1\"}\n)",
     "legendFormat": "{{node}} free"
    }
   ]
  }
 ]
}