{
 "title": "ILB T2",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "T2 node",
    "query": {
     "query": "label_values(kube_node_labels{label_service_cilium_io_node=\"t2\"},node)"
    }
   },
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(envoy_listener_downstream_cx_total,envoy_listener_address)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Listener", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by (envoy_listener_address) (\n    rate(\n        envoy_listener_downstream_cx_total{node=~\"^${node}$\", envoy_listener_address=~\"^${service}$\"}[$__rate_interval]\n    ) \n    * on (node) group_left() (\n        kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n    )\n) != 0",
     "legendFormat": "{{envoy_listener_address}}"
    }
   ]
  },
  {
   "title": "Active connections",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(envoy_listener_downstream_cx_active)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Listener errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by (envoy_listener_address) (rate(\n    envoy_listener_downstream_cx_transport_socket_connect_timeout{node=~\"^${node}$\", envoy_listener_address=~\"^${service}$\"}[$__rate_interval]\n) \n* on (node) group_left() (\n    kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n)) != 0",
     "legendFormat": "cx timeout {{envoy_listener_address}}"
    },
    {
     "expr": "sum by (envoy_listener_address) (rate(\n    envoy_listener_downstream_cx_overflow{node=~\"^${node}$\", envoy_listener_address=~\"^${service}$\"}[$__rate_interval]\n) \n* on (node) group_left() (\n    kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n)) != 0",
     "legendFormat": "cx overflow {{envoy_listener_address}}"
    },
    {
     "expr": "sum by (envoy_listener_address) (rate(\n    envoy_listener_downstream_cx_overload_reject{node=~\"^${node}$\", envoy_listener_address=~\"^${service}$\"}[$__rate_interval]\n) \n* on (node) group_left() (\n    kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n)) != 0",
     "legendFormat": "cx overload reject {{envoy_listener_address}}"
    },
    {
     "expr": "sum by (envoy_listener_address) (rate(\n    envoy_listener_downstream_global_cx_overflow{node=~\"^${node}$\", envoy_listener_address=~\"^${service}$\"}[$__rate_interval]\n) \n* on (node) group_left() (\n    kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n)) != 0",
     "legendFormat": "global cx overflow {{envoy_listener_address}}"
    },
    {
     "expr": "sum by (envoy_listener_address) (rate(\n    envoy_listener_downstream_pre_cx_timeout{node=~\"^${node}$\", envoy_listener_address=~\"^${service}$\"}[$__rate_interval]\n) \n* on (node) group_left() (\n    kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n)) != 0",
     "legendFormat": "pre cx timeout {{envoy_listener_address}}"
    },
    {
     "expr": "sum by (envoy_listener_address) (rate(\n    envoy_listener_extension_config_missing{node=~\"^${node}$\", envoy_listener_address=~\"^${service}$\"}[$__rate_interval]\n) \n* on (node) group_left() (\n    kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n)) != 0",
     "legendFormat": "extension config missing {{envoy_listener_address}}"
    },
    {
     "expr": "sum by (envoy_listener_address) (rate(\n    envoy_listener_network_extension_config_missing{node=~\"^${node}$\", envoy_listener_address=~\"^${service}$\"}[$__rate_interval]\n) \n* on (node) group_left() (\n    kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n)) != 0",
     "legendFormat": "network extension config missing {{envoy_listener_address}}"
    },
    {
     "expr": "sum by (envoy_listener_address) (rate(\n    envoy_listener_no_filter_chain_match{node=~\"^${node}$\", envoy_listener_address=~\"^${service}$\"}[$__rate_interval]\n) \n* on (node) group_left() (\n    kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n)) != 0",
     "legendFormat": "no filter chain match {{envoy_listener_address}}"
    },
    {
     "expr": "sum by (envoy_listener_address) (rate(\n    envoy_listener_downstream_listener_filter_remote_close{node=~\"^${node}$\", envoy_listener_address=~\"^${service}$\"}[$__rate_interval]\n) \n* on (node) group_left() (\n    kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n)) != 0",
     "legendFormat": "filter remote close {{envoy_listener_address}}"
    },
    {
     "expr": "sum by (envoy_listener_address) (rate(\n    envoy_listener_downstream_listener_filter_error{node=~\"^${node}$\", envoy_listener_address=~\"^${service}$\"}[$__rate_interval]\n) \n* on (node) group_left() (\n    kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n)) != 0",
     "legendFormat": "listener filter error {{envoy_listener_address}}"
    }
   ]
  },
  { "title": "TCP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Downstream RX bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (envoy_tcp_prefix) (\n    rate(\n        envoy_tcp_downstream_cx_rx_bytes_total{node=~\"^${node}$\"}[$__rate_interval]\n    ) \n    * on (node) group_left() (\n        kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n    )\n) != 0",
     "legendFormat": "{{envoy_tcp_prefix}}"
    }
   ]
  },
  {
   "title": "Downstream TX bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (envoy_tcp_prefix) (\n    rate(\n        envoy_tcp_downstream_cx_tx_bytes_total{node=~\"^${node}$\"}[$__rate_interval]\n    ) \n    * on (node) group_left() (\n        kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n    )\n) != 0",
     "legendFormat": "{{envoy_tcp_prefix}}"
    }
   ]
  },
  {
   "title": "Downstream connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by (envoy_tcp_prefix) (\n    rate(\n        envoy_tcp_downstream_cx_total{node=~\"^${node}$\"}[$__rate_interval]\n    ) \n    * on (node) group_left() (\n        kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n    )\n) != 0",
     "legendFormat": "{{envoy_tcp_prefix}}"
    }
   ]
  },
  { "title": "Listener TLS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Handshake",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "sum by (envoy_listener_address) (\n    rate(\n        envoy_listener_ssl_handshake{node=~\"^${node}$\", envoy_listener_address=~\"^${service}$\"}[$__rate_interval]\n    ) \n    * on (node) group_left() (\n        kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n    )\n) != 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ciphers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "sum by (cipher_suite, envoy_cluster_name) (envoy_cluster_ssl_ciphers{envoy_cluster_name =~ \"^${service}$\"})",
     "legendFormat": "{{cipher_suite}} {{envoy_cluster_name}}"
    }
   ]
  },
  {
   "title": "TLS errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "sum by (envoy_listener_address) (rate(\n    envoy_listener_ssl_connection_error{node=~\"^${node}$\", envoy_listener_address=~\"^${service}$\"}[$__rate_interval]\n) \n* on (node) group_left() (\n    kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n)) != 0",
     "legendFormat": "cx error {{envoy_listener_address}}"
    },
    {
     "expr": "sum by (envoy_listener_address) (rate(\n    envoy_listener_ssl_fail_verify_no_cert{node=~\"^${node}$\", envoy_listener_address=~\"^${service}$\"}[$__rate_interval]\n) \n* on (node) group_left() (\n    kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n)) != 0",
     "legendFormat": "fail verify no cert {{envoy_listener_address}}"
    },
    {
     "expr": "sum by (envoy_listener_address) (rate(\n    envoy_listener_ssl_fail_verify_error{node=~\"^${node}$\", envoy_listener_address=~\"^${service}$\"}[$__rate_interval]\n) \n* on (node) group_left() (\n    kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n)) != 0",
     "legendFormat": "fail verify error {{envoy_listener_address}}"
    },
    {
     "expr": "sum by (envoy_listener_address) (rate(\n    envoy_listener_ssl_fail_verify_san{node=~\"^${node}$\", envoy_listener_address=~\"^${service}$\"}[$__rate_interval]\n) \n* on (node) group_left() (\n    kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n)) != 0",
     "legendFormat": "fail verify san {{envoy_listener_address}}"
    },
    {
     "expr": "sum by (envoy_listener_address) (rate(\n    envoy_listener_ssl_fail_verify_cert_hash{node=~\"^${node}$\", envoy_listener_address=~\"^${service}$\"}[$__rate_interval]\n) \n* on (node) group_left() (\n    kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n)) != 0",
     "legendFormat": "fail verify cert hash {{envoy_listener_address}}"
    },
    {
     "expr": "sum by (envoy_listener_address) (rate(\n    envoy_listener_ssl_ocsp_staple_failed{node=~\"^${node}$\", envoy_listener_address=~\"^${service}$\"}[$__rate_interval]\n) \n* on (node) group_left() (\n    kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n)) != 0",
     "legendFormat": "ocsp staple failed {{envoy_listener_address}}"
    }
   ]
  },
  { "title": "Envoy TLS inspector", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "envoy_tls_inspector_bytes_processed_sum",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "sum by (node) (\n    rate(\n        envoy_tls_inspector_bytes_processed_sum{node=~\"^${node}$\"}[$__rate_interval]\n    ) \n    * on (node) group_left() (\n        kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n    )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "envoy_tls_inspector_client_hello_too_large",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 52 },
   "targets": [
    {
     "expr": "sum by (node) (\n    rate(\n        envoy_tls_inspector_client_hello_too_large{node=~\"^${node}$\"}[$__rate_interval]\n    ) \n    * on (node) group_left() (\n        kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n    )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "envoy_tls_inspector_tls_not_found",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 52 },
   "targets": [
    {
     "expr": "sum by (node) (\n    rate(\n        envoy_tls_inspector_tls_not_found{node=~\"^${node}$\"}[$__rate_interval]\n    ) \n    * on (node) group_left() (\n        kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n    )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "envoy_tls_inspector_alpn_found",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 52 },
   "targets": [
    {
     "expr": "sum by (node) (\n    rate(\n        envoy_tls_inspector_alpn_found{node=~\"^${node}$\"}[$__rate_interval]\n    ) \n    * on (node) group_left() (\n        kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n    )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "envoy_tls_inspector_alpn_not_found",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 60 },
   "targets": [
    {
     "expr": "sum by (node) (\n    rate(\n        envoy_tls_inspector_alpn_not_found{node=~\"^${node}$\"}[$__rate_interval]\n    ) \n    * on (node) group_left() (\n        kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n    )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "envoy_tls_inspector_tls_found",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 60 },
   "targets": [
    {
     "expr": "sum by (node) (\n    rate(\n        envoy_tls_inspector_tls_found{node=~\"^${node}$\"}[$__rate_interval]\n    ) \n    * on (node) group_left() (\n        kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n    )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "envoy_tls_inspector_sni_not_found",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 60 },
   "targets": [
    {
     "expr": "sum by (node) (\n    rate(\n        envoy_tls_inspector_sni_not_found{node=~\"^${node}$\"}[$__rate_interval]\n    ) \n    * on (node) group_left() (\n        kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n    )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "envoy_tls_inspector_sni_found",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 60 },
   "targets": [
    {
     "expr": "sum by (node) (\n    rate(\n        envoy_tls_inspector_sni_found{node=~\"^${node}$\"}[$__rate_interval]\n    ) \n    * on (node) group_left() (\n        kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n    )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "HTTP connection manager", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 } },
  {
   "title": "Downstream RX bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum by (envoy_http_conn_manager_prefix) (\n    rate(\n        envoy_http_downstream_cx_rx_bytes_total{node=~\"^${node}$\"}[$__rate_interval]\n    ) \n    * on (node) group_left() (\n        kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n    )\n) != 0",
     "legendFormat": "{{backend}}"
    }
   ]
  },
  {
   "title": "Downstream TX bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum by (envoy_http_conn_manager_prefix) (\n    rate(\n        envoy_http_downstream_cx_tx_bytes_total{node=~\"^${node}$\"}[$__rate_interval]\n    ) \n    * on (node) group_left() (\n        kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n    )\n) != 0",
     "legendFormat": "{{backend}}"
    }
   ]
  },
  {
   "title": "Downstream connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by (envoy_http_conn_manager_prefix) (\n    rate(\n        envoy_http_downstream_cx_total{node=~\"^${node}$\"}[$__rate_interval]\n    ) \n    * on (node) group_left() (\n        kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n    )\n) != 0",
     "legendFormat": "{{backend}}"
    }
   ]
  },
  {
   "title": "Downstreal SSL connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (envoy_http_conn_manager_prefix) (\n    rate(\n        envoy_http_downstream_cx_ssl_total{node=~\"^${node}$\"}[$__rate_interval]\n    ) \n    * on (node) group_left() (\n        kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n    )\n)",
     "legendFormat": "{{backend}}"
    }
   ]
  },
  {
   "title": "Downstreal HTTP1 connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (envoy_http_conn_manager_prefix) (\n    rate(\n        envoy_http_downstream_cx_http1_total{node=~\"^${node}$\"}[$__rate_interval]\n    ) \n    * on (node) group_left() (\n        kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n    )\n)",
     "legendFormat": "{{backend}}"
    }
   ]
  },
  {
   "title": "Downstreal upgraded connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (envoy_http_conn_manager_prefix) (\n    rate(\n        envoy_http_downstream_cx_upgrades_total{node=~\"^${node}$\"}[$__rate_interval]\n    ) \n    * on (node) group_left() (\n        kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n    )\n)",
     "legendFormat": "{{backend}}"
    }
   ]
  },
  {
   "title": "Downstreal HTTP2 connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (envoy_http_conn_manager_prefix) (\n    rate(\n        envoy_http_downstream_cx_http2_total{node=~\"^${node}$\"}[$__rate_interval]\n    ) \n    * on (node) group_left() (\n        kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n    )\n)",
     "legendFormat": "{{backend}}"
    }
   ]
  },
  {
   "title": "Downstreal HTTP3 connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (envoy_http_conn_manager_prefix) (\n    rate(\n        envoy_http_downstream_cx_http3_total{node=~\"^${node}$\"}[$__rate_interval]\n    ) \n    * on (node) group_left() (\n        kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n    )\n)",
     "legendFormat": "{{backend}}"
    }
   ]
  },
  {
   "title": "Downstream requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (envoy_http_conn_manager_prefix) (\n    rate(\n        envoy_http_downstream_rq_total{node=~\"^${node}$\"}[$__rate_interval]\n    ) \n    * on (node) group_left() (\n        kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n    )\n) != 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Downstreal requests completed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (envoy_listener_address) (\n    rate(\n        envoy_listener_http_downstream_rq_completed{node=~\"^${node}$\", envoy_listener_address=~\"^${service}$\"}[$__rate_interval]\n    ) \n    * on (node) group_left() (\n        kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n    )\n)",
     "legendFormat": "{{envoy_listener_address}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (envoy_http_conn_manager_prefix) (rate(\n    envoy_http_downstream_cx_protocol_error{node=~\"^${node}$\", envoy_http_conn_manager_prefix =~ \"${service}\"}[$__rate_interval]\n) \n* on (node) group_left() (\n    kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n)) != 0",
     "legendFormat": "protocol error {{envoy_http_conn_manager_prefix}}"
    },
    {
     "expr": "sum by (envoy_http_conn_manager_prefix) (rate(\n    envoy_http_downstream_rq_rejected_via_ip_detection{node=~\"^${node}$\", envoy_http_conn_manager_prefix =~ \"${service}\"}[$__rate_interval]\n) \n* on (node) group_left() (\n    kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n)) != 0",
     "legendFormat": "rq rejected via ip detection {{envoy_http_conn_manager_prefix}}"
    },
    {
     "expr": "sum by (envoy_http_conn_manager_prefix) (rate(\n    envoy_http_downstream_rq_response_before_rq_complete{node=~\"^${node}$\", envoy_http_conn_manager_prefix =~ \"${service}\"}[$__rate_interval]\n) \n* on (node) group_left() (\n    kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n)) != 0",
     "legendFormat": "re response before rq complete {{envoy_http_conn_manager_prefix}}"
    },
    {
     "expr": "sum by (envoy_http_conn_manager_prefix) (rate(\n    envoy_http_downstream_rq_rx_reset{node=~\"^${node}$\", envoy_http_conn_manager_prefix =~ \"${service}\"}[$__rate_interval]\n) \n* on (node) group_left() (\n    kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n)) != 0",
     "legendFormat": "rq rx reset {{envoy_http_conn_manager_prefix}}"
    },
    {
     "expr": "sum by (envoy_http_conn_manager_prefix) (rate(\n    envoy_http_downstream_rq_tx_reset{node=~\"^${node}$\", envoy_http_conn_manager_prefix =~ \"${service}\"}[$__rate_interval]\n) \n* on (node) group_left() (\n    kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n)) != 0",
     "legendFormat": "rq tx reset {{envoy_http_conn_manager_prefix}}"
    },
    {
     "expr": "sum by (envoy_http_conn_manager_prefix) (rate(\n    envoy_http_downstream_rq_too_large{node=~\"^${node}$\", envoy_http_conn_manager_prefix =~ \"${service}\"}[$__rate_interval]\n) \n* on (node) group_left() (\n    kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n)) != 0",
     "legendFormat": "rq too large {{envoy_http_conn_manager_prefix}}"
    },
    {
     "expr": "sum by (envoy_http_conn_manager_prefix) (rate(\n    envoy_http_downstream_rq_idle_timeout{node=~\"^${node}$\", envoy_http_conn_manager_prefix =~ \"${service}\"}[$__rate_interval]\n) \n* on (node) group_left() (\n    kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n)) != 0",
     "legendFormat": "rq idle timeout {{envoy_http_conn_manager_prefix}}"
    },
    {
     "expr": "sum by (envoy_http_conn_manager_prefix) (rate(\n    envoy_http_downstream_rq_max_duration_reached{node=~\"^${node}$\", envoy_http_conn_manager_prefix =~ \"${service}\"}[$__rate_interval]\n) \n* on (node) group_left() (\n    kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n)) != 0",
     "legendFormat": "rq max duration reached {{envoy_http_conn_manager_prefix}}"
    },
    {
     "expr": "sum by (envoy_http_conn_manager_prefix) (rate(\n    envoy_http_downstream_rq_timeout{node=~\"^${node}$\", envoy_http_conn_manager_prefix =~ \"${service}\"}[$__rate_interval]\n) \n* on (node) group_left() (\n    kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n)) != 0",
     "legendFormat": "rq timeout {{envoy_http_conn_manager_prefix}}"
    },
    {
     "expr": "sum by (envoy_http_conn_manager_prefix) (rate(\n    envoy_http_downstream_rq_overload_close{node=~\"^${node}$\", envoy_http_conn_manager_prefix =~ \"${service}\"}[$__rate_interval]\n) \n* on (node) group_left() (\n    kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n)) != 0",
     "legendFormat": "rq overload close {{envoy_http_conn_manager_prefix}}"
    },
    {
     "expr": "sum by (envoy_http_conn_manager_prefix) (rate(\n    envoy_http_downstream_rq_too_many_premature_resets{node=~\"^${node}$\", envoy_http_conn_manager_prefix =~ \"${service}\"}[$__rate_interval]\n) \n* on (node) group_left() (\n    kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n)) != 0",
     "legendFormat": "rq too many premature resets {{envoy_http_conn_manager_prefix}}"
    },
    {
     "expr": "sum by (envoy_http_conn_manager_prefix) (rate(\n    envoy_http_rs_too_large{node=~\"^${node}$\", envoy_http_conn_manager_prefix =~ \"${service}\"}[$__rate_interval]\n) \n* on (node) group_left() (\n    kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n)) != 0",
     "legendFormat": "http rs too large {{envoy_http_conn_manager_prefix}}"
    }
   ]
  },
  { "title": "Network RateLimiting", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 118 } },
  {
   "title": "envoy_local_rate_limit_rate_limited",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 119 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (envoy_tcp_prefix) (\n    rate(\n        envoy_local_rate_limit_rate_limited{node=~\"^${node}$\"}[$__rate_interval]\n    ) \n    * on (node) group_left() (\n        kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n    )\n)",
     "legendFormat": "{{envoy_tcp_prefix}}"
    }
   ]
  },
  { "title": "HTTP RateLimiting", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 127 } },
  {
   "title": "envoy_http_local_rate_limit_enforced",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 128 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (envoy_tcp_prefix) (\n    rate(\n        envoy_http_local_rate_limit_enforced{node=~\"^${node}$\"}[$__rate_interval]\n    ) \n    * on (node) group_left() (\n        kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n    )\n)\n\n",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Network RBAC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 136 } },
  {
   "title": "envoy_rbac_allowed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 137 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by (envoy_listener_address) (\n    rate(\n        envoy_rbac_allowed{node=~\"^${node}$\"}[$__rate_interval]\n    ) \n    * on (node) group_left() (\n        kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n    )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "envoy_rbac_denied",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 137 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by (envoy_listener_address) (\n    rate(\n        envoy_rbac_denied{node=~\"^${node}$\"}[$__rate_interval]\n    ) \n    * on (node) group_left() (\n        kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n    )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "HTTP RBAC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 145 } },
  {
   "title": "envoy_http_rbac_allowed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 146 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by (envoy_listener_address) (\n    rate(\n        envoy_http_rbac_allowed{node=~\"^${node}$\"}[$__rate_interval]\n    ) \n    * on (node) group_left() (\n        kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n    )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "envoy_http_rbac_denied",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 146 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by (envoy_listener_address) (\n    rate(\n        envoy_http_rbac_denied{node=~\"^${node}$\"}[$__rate_interval]\n    ) \n    * on (node) group_left() (\n        kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n    )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Basic Auth", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 154 } },
  {
   "title": "envoy_http_basic_auth_allowed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 155 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by (envoy_listener_address) (\n    rate(\n        envoy_http_basic_auth_allowed{node=~\"^${node}$\"}[$__rate_interval]\n    ) \n    * on (node) group_left() (\n        kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n    )\n)\n\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "envoy_http_basic_auth_denied",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 155 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by (envoy_listener_address) (\n    rate(\n        envoy_http_basic_auth_denied{node=~\"^${node}$\"}[$__rate_interval]\n    ) \n    * on (node) group_left() (\n        kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n    )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 163 } },
  {
   "title": "Upstream connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 164 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by (envoy_cluster_name) (\n    rate(\n        envoy_cluster_upstream_cx_total{node=~\"^${node}$\"}[$__rate_interval]\n    ) \n    * on (node) group_left() (\n        kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n    )\n) != 0",
     "legendFormat": "{{envoy_cluster_name}}"
    }
   ]
  },
  {
   "title": "Upstream connections",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 164 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(envoy_cluster_upstream_cx_total)\n\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Upstream HTTP1 connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 172 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (envoy_cluster_name) (\n    rate(\n        envoy_cluster_upstream_cx_http1_total{node=~\"^${node}$\"}[$__rate_interval]\n    ) \n    * on (node) group_left() (\n        kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n    )\n)",
     "legendFormat": "{{vip}}"
    }
   ]
  },
  {
   "title": "Upstream HTTP2 connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 172 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (envoy_cluster_name) (\n    rate(\n        envoy_cluster_upstream_cx_http2_total{node=~\"^${node}$\"}[$__rate_interval]\n    ) \n    * on (node) group_left() (\n        kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n    )\n)",
     "legendFormat": "{{vip}}"
    }
   ]
  },
  {
   "title": "Upstream HTTP3 connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 180 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (envoy_cluster_name) (\n    rate(\n        envoy_cluster_upstream_cx_http3_total{node=~\"^${node}$\"}[$__rate_interval]\n    ) \n    * on (node) group_left() (\n        kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n    )\n)",
     "legendFormat": "{{vip}}"
    }
   ]
  },
  {
   "title": "Connection errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 188 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by (envoy_cluster_name) (rate(\n    envoy_cluster_upstream_cx_connect_fail{node=~\"^${node}$\"}[$__rate_interval]\n) \n* on (node) group_left() (\n    kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n)) != 0",
     "legendFormat": "upstream_cx_connect_fail {{envoy_cluster_name}}"
    },
    {
     "expr": "sum by (envoy_cluster_name) (rate(\n    envoy_cluster_upstream_cx_connect_timeout{node=~\"^${node}$\"}[$__rate_interval]\n) \n* on (node) group_left() (\n    kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n)) != 0",
     "legendFormat": "upstream_cx_connect_timeout {{envoy_cluster_name}}"
    },
    {
     "expr": "sum by (envoy_cluster_name) (rate(\n    envoy_cluster_upstream_cx_pool_overflow{node=~\"^${node}$\"}[$__rate_interval]\n) \n* on (node) group_left() (\n    kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n)) != 0",
     "legendFormat": "upstream_cx_pool_overflow {{envoy_cluster_name}}"
    },
    {
     "expr": "sum by (envoy_cluster_name) (rate(\n    envoy_cluster_upstream_cx_protocol_error{node=~\"^${node}$\"}[$__rate_interval]\n) \n* on (node) group_left() (\n    kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n)) != 0",
     "legendFormat": "upstream_cx_protocol_error {{envoy_cluster_name}}"
    },
    {
     "expr": "sum by (envoy_cluster_name) (rate(\n    envoy_cluster_upstream_cx_max_requests{node=~\"^${node}$\"}[$__rate_interval]\n) \n* on (node) group_left() (\n    kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n)) != 0",
     "legendFormat": "upstream_cx_max_requests {{envoy_cluster_name}}"
    },
    {
     "expr": "sum by (envoy_cluster_name) (rate(\n    envoy_cluster_upstream_cx_none_healthy{node=~\"^${node}$\"}[$__rate_interval]\n) \n* on (node) group_left() (\n    kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n)) != 0",
     "legendFormat": "upstream_cx_none_healthy {{envoy_cluster_name}}"
    }
   ]
  },
  {
   "title": "Upstream connections RX bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 196 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (envoy_cluster_name) (\n    rate(\n        envoy_cluster_upstream_cx_rx_bytes_total{node=~\"^${node}$\"}[$__rate_interval]\n    ) \n    * on (node) group_left() (\n        kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n    )\n)",
     "legendFormat": "{{vip}}"
    }
   ]
  },
  {
   "title": "Upstream connections TX bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 196 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum by (envoy_cluster_name) (\n    rate(\n        envoy_cluster_upstream_cx_tx_bytes_total{node=~\"^${node}$\"}[$__rate_interval]\n    ) \n    * on (node) group_left() (\n        kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n    )\n)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Request errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 204 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by (envoy_cluster_name) (rate(\n    envoy_cluster_upstream_rq_pending_overflow{node=~\"^${node}$\", envoy_cluster_name=~\"^${service}$\"}[$__rate_interval]\n) \n* on (node) group_left() (\n    kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n)) != 0",
     "legendFormat": "rq pending overflow {{envoy_cluster_name}}"
    },
    {
     "expr": "sum by (envoy_cluster_name) (rate(\n    envoy_cluster_upstream_rq_pending_failure_eject{node=~\"^${node}$\", envoy_cluster_name=~\"^${service}$\"}[$__rate_interval]\n) \n* on (node) group_left() (\n    kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n)) != 0",
     "legendFormat": "rq pending failure eject {{envoy_cluster_name}}"
    },
    {
     "expr": "sum by (envoy_cluster_name) (rate(\n    envoy_cluster_upstream_rq_maintenance_mode{node=~\"^${node}$\", envoy_cluster_name=~\"^${service}$\"}[$__rate_interval]\n) \n* on (node) group_left() (\n    kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n)) != 0",
     "legendFormat": "rq maintenance mode {{envoy_cluster_name}}"
    },
    {
     "expr": "sum by (envoy_cluster_name) (rate(\n    envoy_cluster_upstream_rq_timeout{node=~\"^${node}$\", envoy_cluster_name=~\"^${service}$\"}[$__rate_interval]\n) \n* on (node) group_left() (\n    kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n)) != 0",
     "legendFormat": "rq timeout {{envoy_cluster_name}}"
    },
    {
     "expr": "sum by (envoy_cluster_name) (rate(\n    envoy_cluster_upstream_rq_per_try_timeout{node=~\"^${node}$\", envoy_cluster_name=~\"^${service}$\"}[$__rate_interval]\n) \n* on (node) group_left() (\n    kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n)) != 0",
     "legendFormat": "rq per try timeout {{envoy_cluster_name}}"
    }
   ]
  },
  {
   "title": "Healthcheck successes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 212 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (envoy_cluster_name) (\n    rate(\n        envoy_cluster_health_check_success{node=~\"^${node}$\"}[$__rate_interval]\n    ) \n    * on (node) group_left() (\n        kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n    )\n)",
     "legendFormat": "{{envoy_cluster_name}}"
    }
   ]
  },
  {
   "title": "Healthcheck failures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 212 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by (envoy_cluster_name) (rate(\n    envoy_cluster_health_check_failure{node=~\"^${node}$\", envoy_cluster_name=~\"^${service}$\"}[$__rate_interval]\n) \n* on (node) group_left() (\n    kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n))",
     "legendFormat": "envoy_cluster_health_check_failure {{envoy_cluster_name}}"
    },
    {
     "expr": "sum by (envoy_cluster_name) (rate(\n    envoy_cluster_health_check_passive_failure{node=~\"^${node}$\", envoy_cluster_name=~\"^${service}$\"}[$__rate_interval]\n) \n* on (node) group_left() (\n    kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n))",
     "legendFormat": "envoy_cluster_health_check_passive_failure {{envoy_cluster_name}}"
    },
    {
     "expr": "sum by (envoy_cluster_name) (rate(\n    envoy_cluster_health_check_network_failure{node=~\"^${node}$\", envoy_cluster_name=~\"^${service}$\"}[$__rate_interval]\n) \n* on (node) group_left() (\n    kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n))",
     "legendFormat": "envoy_cluster_health_check_network_failure {{envoy_cluster_name}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 220 } },
  {
   "title": "Node RX bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 221 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (instance) (\n    rate(\n        node_network_receive_bytes_total[$__rate_interval])\n    ) * on (instance) group_left(node) (\n        label_replace(kube_node_status_addresses{node=~\"${node}\"}, \"instance\", \"$1:9100\", \"address\", \"(.*)\"\n    )\n) * on (node) (\n    kube_node_labels{label_service_cilium_io_node=\"t2\"}\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node RX packets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 221 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum by (instance) (\n    rate(\n        node_network_receive_packets_total{device=\"eth0\"}[$__rate_interval])\n    ) * on (instance) group_left(node) (\n        label_replace(kube_node_status_addresses{node=~\"${node}\"}, \"instance\", \"$1:9100\", \"address\", \"(.*)\"\n    )\n) * on (node) (\n    kube_node_labels{label_service_cilium_io_node=\"t2\"}\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 229 } },
  {
   "title": "CPU %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 230 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * avg(\n  1 - rate(\n    node_cpu_seconds_total{mode=~\"idle\"}[$__rate_interval]\n    )\n  ) by (instance)\n* on (instance) group_left(node) (\n  label_replace(kube_node_status_addresses{node=~\"^${node}$\"}, \"instance\", \"$1:9100\", \"address\", \"(.*)\")\n)\n* on (node) group_left() (\n  kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 230 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_load1{job=\"node-exporter\"} \n* on (instance) group_left(node) (\n    label_replace(kube_node_status_addresses{node=~\"^${node}$\"}, \"instance\", \"$1:9100\", \"address\", \"(.*)\")\n) * on (node) group_left() (\n  kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n)",
     "legendFormat": "{{node}}, 1m"
    },
    {
     "expr": "node_load5{job=\"node-exporter\"} *  on (instance) group_left(node) (label_replace(kube_node_status_addresses{type=\"InternalIP\", node=~\"${node}\"}, \"instance\", \"$1:9100\", \"address\", \"(.*)\"))\n* on (node) group_left() (\n  kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n)",
     "legendFormat": "{{node}}, 5m"
    },
    {
     "expr": "node_load15{job=\"node-exporter\"} *  on (instance) group_left(node) (label_replace(kube_node_status_addresses{type=\"InternalIP\", node=~\"${node}\"}, \"instance\", \"$1:9100\", \"address\", \"(.*)\"))\n* on (node) group_left() (\n  kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n)",
     "legendFormat": "{{node}}, 15m"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 238 } },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 239 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(\n  node_memory_MemTotal_bytes{job=\"node-exporter\"}\n-\n  node_memory_MemFree_bytes{job=\"node-exporter\"}\n-\n  node_memory_Buffers_bytes{job=\"node-exporter\"}\n-\n  node_memory_Cached_bytes{job=\"node-exporter\"}\n)\n* on (instance) group_left(node) (\n  label_replace(kube_node_status_addresses{node=~\"^${node}$\"}, \"instance\", \"$1:9100\", \"address\", \"(.*)\")\n)\n* on (node) group_left() (\n  kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n)\n",
     "legendFormat": "{{node}} used"
    },
    {
     "expr": "node_memory_Buffers_bytes{job=\"node-exporter\"} * on (instance) group_left(node) (\n  label_replace(kube_node_status_addresses{node=~\"^${node}$\"}, \"instance\", \"$1:9100\", \"address\", \"(.*)\")\n)\n* on (node) group_left() (\n  kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n)",
     "legendFormat": "{{node}} buffers"
    },
    {
     "expr": "node_memory_Cached_bytes{job=\"node-exporter\"} * on (instance) group_left(node) (\n  label_replace(kube_node_status_addresses{node=~\"^${node}$\"}, \"instance\", \"$1:9100\", \"address\", \"(.*)\")\n)\n* on (node) group_left() (\n  kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n)",
     "legendFormat": "{{node}} cached"
    },
    {
     "expr": "node_memory_MemFree_bytes{job=\"node-exporter\"} * on (instance) group_left(node) (\n  label_replace(kube_node_status_addresses{node=~\"^${node}$\"}, \"instance\", \"$1:9100\", \"address\", \"(.*)\")\n)\n* on (node) group_left() (\n  kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n)",
     "legendFormat": "{{node}} free"
    }
   ]
  }
 ]
}