// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/cilium/cilium/pkg/k8s/apis/isovalent.com/v1"
	isovalentcomv1 "github.com/cilium/cilium/pkg/k8s/client/clientset/versioned/typed/isovalent.com/v1"
	gentype "k8s.io/client-go/gentype"
)

// fakeIsovalentBGPPolicies implements IsovalentBGPPolicyInterface
type fakeIsovalentBGPPolicies struct {
	*gentype.FakeClientWithList[*v1.IsovalentBGPPolicy, *v1.IsovalentBGPPolicyList]
	Fake *FakeIsovalentV1
}

func newFakeIsovalentBGPPolicies(fake *FakeIsovalentV1) isovalentcomv1.IsovalentBGPPolicyInterface {
	return &fakeIsovalentBGPPolicies{
		gentype.NewFakeClientWithList[*v1.IsovalentBGPPolicy, *v1.IsovalentBGPPolicyList](
			fake.Fake,
			"",
			v1.SchemeGroupVersion.WithResource("isovalentbgppolicies"),
			v1.SchemeGroupVersion.WithKind("IsovalentBGPPolicy"),
			func() *v1.IsovalentBGPPolicy { return &v1.IsovalentBGPPolicy{} },
			func() *v1.IsovalentBGPPolicyList { return &v1.IsovalentBGPPolicyList{} },
			func(dst, src *v1.IsovalentBGPPolicyList) { dst.ListMeta = src.ListMeta },
			func(list *v1.IsovalentBGPPolicyList) []*v1.IsovalentBGPPolicy {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1.IsovalentBGPPolicyList, items []*v1.IsovalentBGPPolicy) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
