// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/cilium/cilium/pkg/k8s/apis/isovalent.com/v1"
	isovalentcomv1 "github.com/cilium/cilium/pkg/k8s/client/clientset/versioned/typed/isovalent.com/v1"
	gentype "k8s.io/client-go/gentype"
)

// fakeIsovalentBGPPeerConfigs implements IsovalentBGPPeerConfigInterface
type fakeIsovalentBGPPeerConfigs struct {
	*gentype.FakeClientWithList[*v1.IsovalentBGPPeerConfig, *v1.IsovalentBGPPeerConfigList]
	Fake *FakeIsovalentV1
}

func newFakeIsovalentBGPPeerConfigs(fake *FakeIsovalentV1) isovalentcomv1.IsovalentBGPPeerConfigInterface {
	return &fakeIsovalentBGPPeerConfigs{
		gentype.NewFakeClientWithList[*v1.IsovalentBGPPeerConfig, *v1.IsovalentBGPPeerConfigList](
			fake.Fake,
			"",
			v1.SchemeGroupVersion.WithResource("isovalentbgppeerconfigs"),
			v1.SchemeGroupVersion.WithKind("IsovalentBGPPeerConfig"),
			func() *v1.IsovalentBGPPeerConfig { return &v1.IsovalentBGPPeerConfig{} },
			func() *v1.IsovalentBGPPeerConfigList { return &v1.IsovalentBGPPeerConfigList{} },
			func(dst, src *v1.IsovalentBGPPeerConfigList) { dst.ListMeta = src.ListMeta },
			func(list *v1.IsovalentBGPPeerConfigList) []*v1.IsovalentBGPPeerConfig {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1.IsovalentBGPPeerConfigList, items []*v1.IsovalentBGPPeerConfig) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
