// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/cilium/cilium/pkg/k8s/apis/isovalent.com/v1"
	isovalentcomv1 "github.com/cilium/cilium/pkg/k8s/client/clientset/versioned/typed/isovalent.com/v1"
	gentype "k8s.io/client-go/gentype"
)

// fakeIsovalentBGPAdvertisements implements IsovalentBGPAdvertisementInterface
type fakeIsovalentBGPAdvertisements struct {
	*gentype.FakeClientWithList[*v1.IsovalentBGPAdvertisement, *v1.IsovalentBGPAdvertisementList]
	Fake *FakeIsovalentV1
}

func newFakeIsovalentBGPAdvertisements(fake *FakeIsovalentV1) isovalentcomv1.IsovalentBGPAdvertisementInterface {
	return &fakeIsovalentBGPAdvertisements{
		gentype.NewFakeClientWithList[*v1.IsovalentBGPAdvertisement, *v1.IsovalentBGPAdvertisementList](
			fake.Fake,
			"",
			v1.SchemeGroupVersion.WithResource("isovalentbgpadvertisements"),
			v1.SchemeGroupVersion.WithKind("IsovalentBGPAdvertisement"),
			func() *v1.IsovalentBGPAdvertisement { return &v1.IsovalentBGPAdvertisement{} },
			func() *v1.IsovalentBGPAdvertisementList { return &v1.IsovalentBGPAdvertisementList{} },
			func(dst, src *v1.IsovalentBGPAdvertisementList) { dst.ListMeta = src.ListMeta },
			func(list *v1.IsovalentBGPAdvertisementList) []*v1.IsovalentBGPAdvertisement {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1.IsovalentBGPAdvertisementList, items []*v1.IsovalentBGPAdvertisement) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
