name: OpenShift CNI conformance tests
description: Runs OpenShift CNI conformance tests

inputs:
  working-dir:
    required: true
    description: 'Test cluster configuration directory'

runs:
  using: composite
  steps:
    - name: Run CNI conformance tests
      shell: bash
      working-directory: "${{ inputs.working-dir }}"
      run: |
        make test-cni-conformance
