//  Copyright (C) Isovalent, Inc. - All Rights Reserved.
//
//  NOTICE: All information contained herein is, and remains the property of
//  Isovalent Inc and its suppliers, if any. The intellectual and technical
//  concepts contained herein are proprietary to Isovalent Inc and its suppliers
//  and may be covered by U.S. and Foreign Patents, patents in process, and are
//  protected by trade secret or copyright law.  Dissemination of this information
//  or reproduction of this material is strictly forbidden unless prior written
//  permission is obtained from Isovalent Inc.

package hooks

import (
	"context"
	_ "embed"
	"fmt"

	"github.com/spf13/pflag"

	"github.com/cilium/cilium/cilium-cli/connectivity/builder/manifests/template"
	"github.com/cilium/cilium/cilium-cli/connectivity/check"
	"github.com/cilium/cilium/cilium-cli/enterprise/defaults"
	enterpriseCheck "github.com/cilium/cilium/cilium-cli/enterprise/hooks/connectivity/check"
	"github.com/cilium/cilium/cilium-cli/enterprise/hooks/connectivity/deploy"
	enterpriseTests "github.com/cilium/cilium/cilium-cli/enterprise/hooks/connectivity/tests"
	enterpriseFeatures "github.com/cilium/cilium/cilium-cli/enterprise/hooks/utils/features"
	"github.com/cilium/cilium/cilium-cli/utils/features"
	"github.com/cilium/cilium/pkg/versioncheck"
)

const (
	testNoPolicies = "no-policies"
)

//go:embed manifests/client-egress-icmp.yaml
var clientEgressICMPYAML string

//go:embed manifests/client-egress-l7-http-external-node.yaml
var clientEgressL7HTTPAnywhereYAML string

//go:embed manifests/client-egress-only-dns.yaml
var clientEgressOnlyDNSPolicyYAML string

//go:embed manifests/client-egress-dns-to-echo.yaml
var clientEgressDNSToEchoYAML string

//go:embed manifests/encrypt-client-to-echo-8080.yaml
var encryptClientToEchoYAML string

type EnterpriseConnectivity struct {
	externalCiliumDNSProxyPods map[string]check.Pod
	mixedRoutingScenario       check.Scenario
}

func (ec *EnterpriseConnectivity) addConnectivityTests(cts ...*check.ConnectivityTest) error {
	templates, err := renderTemplates(cts[0])
	if err != nil {
		return fmt.Errorf("cannot render templates: %w", err)
	}

	if err := ec.addHubbleVersionTests(cts...); err != nil {
		return err
	}

	if err := ec.addExternalCiliumDNSProxyTests(cts[0], templates); err != nil {
		return err
	}

	if err := ec.addPhantomServiceTests(cts...); err != nil {
		return err
	}

	if cts[0].Params().IncludeUnsafeTests {
		if err := ec.addEgressGatewayHATests(cts[0], templates); err != nil {
			return err
		}
	}

	if err := ec.addMulticastTests(cts[0]); err != nil {
		return err
	}

	if err := ec.addBGPTests(cts[0]); err != nil {
		return err
	}

	if err := ec.addBFDTests(cts[0]); err != nil {
		return err
	}

	if err := ec.addIngressPolicyTests(cts[0], templates); err != nil {
		return err
	}

	if err := ec.addEncryptionPolicyTests(cts...); err != nil {
		return err
	}

	if err := ec.addOrderedPolicyTests(cts[0], templates); err != nil {
		return err
	}

	// Always keep the mixed routing mode tests last, as they assert that the
	// correct routing mode was used to forward the packets generated by all
	// the other tests.
	if err := ec.addMixedRoutingTests(cts...); err != nil {
		return err
	}

	return nil
}

func (ec *EnterpriseConnectivity) addConnectivityTestFlags(flags *pflag.FlagSet) {
	flags.StringSliceVar(&enterpriseTests.Params.EgressGateway.CIDRs, "egw-ipam-cidrs", nil, "CIDRs to use to allocate Egress IPs in egress gateway ha ipam connectivity tests")
	flags.UintVar(&enterpriseTests.Params.EgressGateway.Retry, "egw-ipam-retry", defaults.EgressGatewayConnectRetryDefault, "Number of retries on connection failure to external targets for egress gateway ha IPAM tests")
	flags.DurationVar(&enterpriseTests.Params.EgressGateway.RetryDelay, "egw-ipam-retry-delay", defaults.EgressGatewayConnectRetryDelayDefault, "Delay between retries to external targets for egress gateway ha IPAM tests")
	flags.Int64Var(&enterpriseTests.Params.EgressGateway.PeerASN, "egw-bgp-asn", defaults.EgressGatewayPeerASN, "Number of peer ASN")
	flags.StringSliceVar(&enterpriseTests.Params.EgressGateway.PeerAddresses, "egw-bgp-peer-addresses", nil, "")
}

func (ec *EnterpriseConnectivity) addHubbleVersionTests(cts ...*check.ConnectivityTest) error {
	mustGetTest(testNoPolicies, cts...).WithScenarios(enterpriseTests.HubbleCLIVersion())
	return nil
}

func (ec *EnterpriseConnectivity) addExternalCiliumDNSProxyTests(ct *check.ConnectivityTest, templates map[string]string) error {
	test := check.NewTest("cilium-dns-proxy-ha", ct.Params().Verbose, ct.Params().Debug)
	ct.AddTest(test).
		WithCiliumPolicy(templates["clientEgressOnlyDNSPolicyYAML"]).
		WithCiliumPolicy(clientEgressDNSToEchoYAML).
		WithFeatureRequirements(features.RequireEnabled(enterpriseFeatures.CiliumDNSProxyHA)).
		WithScenarios(enterpriseTests.ExternalCiliumDNSProxy(ec.externalCiliumDNSProxyPods)).
		WithExpectations(func(a *check.Action) (egress, ingress check.Result) {
			return check.ResultOK.ExpectMetricsIncrease(
					enterpriseTests.ExternalCiliumDNSProxySource(ec.externalCiliumDNSProxyPods),
					"isovalent_external_dns_proxy_policy_l7_total",
				),
				check.ResultNone
		})
	return nil
}

func (ec *EnterpriseConnectivity) addPhantomServiceTests(cts ...*check.ConnectivityTest) (err error) {
	if cts[0].Params().MultiCluster == "" {
		return nil
	}

	if ok, _ := cts[0].Features.MatchRequirements(features.RequireEnabled(enterpriseFeatures.PhantomServices)); !ok {
		return nil
	}

	defer func() {
		if r := recover(); r != nil {
			err = r.(error)
		}
	}()

	mustGetTest("no-policies", cts...).WithSetupFunc(deploy.PhantomService).WithScenarios(enterpriseTests.PodToPhantomService())
	mustGetTest("allow-all-except-world", cts...).WithSetupFunc(deploy.PhantomService).WithScenarios(enterpriseTests.PodToPhantomService())

	// Traffic shall be dropped, because it is subject to the ingress/egress policy.
	mustGetTest("all-ingress-deny", cts...).WithSetupFunc(deploy.PhantomService).WithScenarios(enterpriseTests.PodToPhantomService())
	mustGetTest("all-ingress-deny-knp", cts...).WithSetupFunc(deploy.PhantomService).WithScenarios(enterpriseTests.PodToPhantomService())
	mustGetTest("all-egress-deny", cts...).WithSetupFunc(deploy.PhantomService).WithScenarios(enterpriseTests.PodToPhantomService())
	mustGetTest("all-egress-deny-knp", cts...).WithSetupFunc(deploy.PhantomService).WithScenarios(enterpriseTests.PodToPhantomService())
	mustGetTest("cluster-entity-multi-cluster", cts...).WithSetupFunc(deploy.PhantomService).WithScenarios(enterpriseTests.PodToPhantomService())

	// Traffic shall be allowed, because it matches the cross-cluster policy.
	mustGetTest("client-egress", cts...).WithSetupFunc(deploy.PhantomService).WithScenarios(enterpriseTests.PodToPhantomService())
	mustGetTest("client-egress-knp", cts...).WithSetupFunc(deploy.PhantomService).WithScenarios(enterpriseTests.PodToPhantomService())

	return
}

func (ec *EnterpriseConnectivity) addEgressGatewayHATests(ct *check.ConnectivityTest, templates map[string]string) (err error) {
	newTest := func(ct *check.ConnectivityTest, name string) *enterpriseCheck.EnterpriseTest {
		return enterpriseCheck.NewEnterpriseConnectivityTest(ct).
			NewEnterpriseTest(name).
			WithFeatureRequirements(
				features.RequireEnabled(enterpriseFeatures.EgressGatewayHA),
				features.RequireEnabled(features.NodeWithoutCilium))
	}

	// prefix the test name with `seq-` to run it sequentially
	newTest(ct, "seq-egress-gateway-ha").
		WithIsovalentEgressGatewayPolicy(enterpriseCheck.IsovalentEgressGatewayPolicyParams{
			Name:            "iegp-sample-client",
			PodSelectorKind: "client",
			EgressGroup:     enterpriseCheck.SingleGateway,
		}).
		WithIsovalentEgressGatewayPolicy(enterpriseCheck.IsovalentEgressGatewayPolicyParams{
			Name:            "iegp-sample-echo",
			PodSelectorKind: "echo",
			EgressGroup:     enterpriseCheck.SingleGateway,
		}).
		WithIPRoutesFromOutsideToPodCIDRs().
		WithScenarios(enterpriseTests.EgressGatewayHA())

	if versioncheck.MustCompile(">=1.16.0")(ct.CiliumVersion) {
		// prefix the test name with `seq-` to run it sequentially
		newTest(ct, "seq-egress-gateway-ha-with-l7-policy").
			WithIsovalentEgressGatewayPolicy(enterpriseCheck.IsovalentEgressGatewayPolicyParams{
				Name:            "iegp-sample-client",
				PodSelectorKind: "client",
				EgressGroup:     enterpriseCheck.SingleGateway,
			}).
			WithIsovalentEgressGatewayPolicy(enterpriseCheck.IsovalentEgressGatewayPolicyParams{
				Name:            "iegp-sample-echo",
				PodSelectorKind: "echo",
				EgressGroup:     enterpriseCheck.SingleGateway,
			}).
			WithCiliumPolicy(clientEgressICMPYAML).
			WithCiliumPolicy(templates["clientEgressOnlyDNSPolicyYAML"]). // DNS resolution only
			WithCiliumPolicy(clientEgressL7HTTPAnywhereYAML).             // L7 allow policy with HTTP introspection
			WithIPRoutesFromOutsideToPodCIDRs().
			WithFeatureRequirements(features.RequireEnabled(features.L7Proxy)).
			WithScenarios(enterpriseTests.EgressGatewayHA())
	}

	// prefix the test name with `seq-` to run it sequentially
	newTest(ct, "seq-egress-gateway-ha-excluded-cidrs").
		WithIsovalentEgressGatewayPolicy(enterpriseCheck.IsovalentEgressGatewayPolicyParams{
			Name:            "iegp-sample-client",
			PodSelectorKind: "client",
			EgressGroup:     enterpriseCheck.SingleGateway,
			ExcludedCIDRs:   enterpriseCheck.ExternalNodeExcludedCIDRs,
		}).
		WithIPRoutesFromOutsideToPodCIDRs().
		WithScenarios(enterpriseTests.EgressGatewayExcludedCIDRs())

	// prefix the test name with `seq-` to run it sequentially
	newTest(ct, "seq-egress-gateway-ha-multiple-gateways").
		WithIsovalentEgressGatewayPolicy(enterpriseCheck.IsovalentEgressGatewayPolicyParams{
			Name:            "iegp-sample-client",
			PodSelectorKind: "client",
			EgressGroup:     enterpriseCheck.AllCiliumNodes,
		}).
		WithScenarios(enterpriseTests.EgressGatewayMultipleGateways())

	if versioncheck.MustCompile(">=1.16.0")(ct.CiliumVersion) {
		// prefix the test name with `seq-` to run it sequentially
		newTest(ct, "seq-egress-gateway-ha-multiple-gateways-with-l7-policy").
			WithIsovalentEgressGatewayPolicy(enterpriseCheck.IsovalentEgressGatewayPolicyParams{
				Name:            "iegp-sample-client",
				PodSelectorKind: "client",
				EgressGroup:     enterpriseCheck.AllCiliumNodes,
			}).
			WithCiliumPolicy(clientEgressICMPYAML).
			WithCiliumPolicy(templates["clientEgressOnlyDNSPolicyYAML"]). // DNS resolution only
			WithCiliumPolicy(clientEgressL7HTTPAnywhereYAML).             // L7 allow policy with HTTP introspection
			WithFeatureRequirements(features.RequireEnabled(features.L7Proxy)).
			WithScenarios(enterpriseTests.EgressGatewayMultipleGateways())
	}

	if versioncheck.MustCompile(">=1.14.8")(ct.CiliumVersion) {
		// prefix the test name with `seq-` to run it sequentially
		egwHAAZAffinityTest := newTest(ct, "seq-egress-gateway-ha-az-affinity").
			WithIsovalentEgressGatewayPolicy(enterpriseCheck.IsovalentEgressGatewayPolicyParams{
				Name:            "iegp-sample-client-az-affinity",
				PodSelectorKind: "client",
				EgressGroup:     enterpriseCheck.AllCiliumNodesWithAZAffinity,
				// We update the AZAffinity: "localOnly" setting after topology.kubernetes.io/zone has been set on the
				// Gateway nodes. This prevents error logs about missing node AZs from being emitted.
			})
		egwHAAZAffinityTest.WithScenarios(enterpriseTests.EgressGatewayAZAffinity(egwHAAZAffinityTest.Context().EntClients()))
	}

	newIPAMTest := func(ct *check.ConnectivityTest, name string) *enterpriseCheck.EnterpriseTest {
		et := enterpriseCheck.NewEnterpriseConnectivityTest(ct).
			NewEnterpriseTestWithoutSetup(name).
			WithFeatureRequirements(
				features.RequireEnabled(enterpriseFeatures.EgressGatewayHA),
				features.RequireEnabled(features.NodeWithoutCilium))
		et.WithSetupFunc(func(ctx context.Context, t *check.Test, ct *check.ConnectivityTest) error {
			// get egress CIDRs to be used for IPAM before applying the policies
			egressCIDRs := enterpriseTests.IPAMEgressCIDRs(ctx, t, ct)
			if len(egressCIDRs) == 0 {
				egressCIDRs = defaults.EgressGatewayCIDRsDefault
			}
			t.Logf("Using egress CIDRs %v for IEGP IPAM", egressCIDRs)
			et.WithEgressCIDRsforIEGP("iegp-sample-client", egressCIDRs)
			return et.Setup(ctx)
		})
		return et
	}

	if versioncheck.MustCompile(">=1.16.0")(ct.CiliumVersion) {
		// prefix the test name with `seq-` to run it sequentially
		newIPAMTest(ct, "seq-egress-gateway-ha-ipam").
			WithIsovalentEgressGatewayPolicy(enterpriseCheck.IsovalentEgressGatewayPolicyParams{
				Name:            "iegp-sample-client",
				PodSelectorKind: "client",
				EgressGroup:     enterpriseCheck.SingleGateway,
			}).
			WithIPRoutesFromOutsideToPodCIDRs().
			WithScenarios(enterpriseTests.EgressGatewayHAIPAM())
	}

	if versioncheck.MustCompile(">=1.16.0")(ct.CiliumVersion) {
		// prefix the test name with `seq-` to run it sequentially
		newIPAMTest(ct, "seq-egress-gateway-ha-ipam-multiple-gateways").
			WithIsovalentEgressGatewayPolicy(enterpriseCheck.IsovalentEgressGatewayPolicyParams{
				Name:            "iegp-sample-client",
				PodSelectorKind: "client",
				EgressGroup:     enterpriseCheck.AllCiliumNodes,
			}).
			WithIPRoutesFromOutsideToPodCIDRs().
			WithScenarios(enterpriseTests.EgressGatewayHAIPAMMultipleGateways())
	}

	// This test depends on the Route Reflector feature of the BGP CP, which requires using
	// v1.18.1 or later.
	if versioncheck.MustCompile(">=1.18.1")(ct.CiliumVersion) {
		// prefix the test name with `seq-` to run it sequentially
		newIPAMTest(ct, "seq-egress-gateway-ha-ipam-bgp-advertisement").
			WithFeatureRequirements(
				features.RequireEnabled(enterpriseFeatures.EnterpriseBGPControlPlane),
				features.RequireEnabled(enterpriseFeatures.BFD),
			).
			WithCondition(func() bool { return len(enterpriseTests.Params.EgressGateway.PeerAddresses) != 0 }).
			WithIsovalentEgressGatewayPolicy(enterpriseCheck.IsovalentEgressGatewayPolicyParams{
				Name:            "iegp-sample-client",
				Labels:          map[string]string{"egw": "bgp-advertise"},
				PodSelectorKind: "client",
				EgressGroup:     enterpriseCheck.AllCiliumNodes,
			}).
			WithScenarios(enterpriseTests.EgressGatewayHABGPAdvertisement())
	}

	return nil
}

func (ec *EnterpriseConnectivity) addEncryptionPolicyTests(cts ...*check.ConnectivityTest) (err error) {
	defer func() {
		if r := recover(); r != nil {
			err = r.(error)
		}
	}()

	// Regular encryption related tests cannot be run (neither in sanity nor assert mode) if
	// encryption policies are enabled, as not all traffic in the cluster will be encrypted.
	mustGetTest("pod-to-pod-encryption", cts...).WithFeatureRequirements(
		features.RequireDisabled(enterpriseFeatures.EncryptionPolicy),
		features.RequireDisabled(enterpriseFeatures.RemoteEncryptionPolicy),
	)
	mustGetTest("pod-to-pod-with-l7-policy-encryption", cts...).WithFeatureRequirements(
		features.RequireDisabled(enterpriseFeatures.EncryptionPolicy),
		features.RequireDisabled(enterpriseFeatures.RemoteEncryptionPolicy),
	)
	mustGetTest("node-to-node-encryption", cts...).WithFeatureRequirements(
		features.RequireDisabled(enterpriseFeatures.EncryptionPolicy),
		features.RequireDisabled(enterpriseFeatures.RemoteEncryptionPolicy),
	)
	mustGetTest("pod-to-pod-encryption-v2", cts...).WithFeatureRequirements(
		features.RequireDisabled(enterpriseFeatures.EncryptionPolicy),
		features.RequireDisabled(enterpriseFeatures.RemoteEncryptionPolicy),
	)
	mustGetTest("pod-to-pod-with-l7-policy-encryption-v2", cts...).WithFeatureRequirements(
		features.RequireDisabled(enterpriseFeatures.EncryptionPolicy),
		features.RequireDisabled(enterpriseFeatures.RemoteEncryptionPolicy),
	)

	newTest := func(ct *check.ConnectivityTest, name string) *enterpriseCheck.EnterpriseTest {
		return enterpriseCheck.NewEnterpriseConnectivityTest(ct).
			NewEnterpriseTest(name).
			WithFeatureRequirements(features.RequireEnabled(enterpriseFeatures.EncryptionPolicy)).
			WithCondition(func() bool {
				if ct.Params().MultiCluster != "" {
					if ok, _ := ct.Features.MatchRequirements(features.RequireEnabled(enterpriseFeatures.RemoteEncryptionPolicy)); !ok {
						return false
					}
				}
				return true
			}).
			WithCondition(func() bool { return !ct.Params().SingleNode })
	}

	if versioncheck.MustCompile(">=1.16.0")(cts[0].CiliumVersion) {
		newTest(cts[0], "pod-to-pod-encryption-policy").
			WithIsovalentClusterwideEncryptionPolicy(encryptClientToEchoYAML).
			WithScenarios(enterpriseTests.PodToPodEncryptionPolicy())
	}

	return nil
}

func (ec *EnterpriseConnectivity) addMixedRoutingTests(cts ...*check.ConnectivityTest) (err error) {
	defer func() {
		if r := recover(); r != nil {
			err = r.(error)
		}
	}()

	// Encryption related tests cannot be run (neither in sanity nor assert mode) if
	// the two clusters are configured with different routing modes, because the
	// tcpdump filters to assert no unencrypted packet is leaked would be incorrect.
	mustGetTest("pod-to-pod-encryption", cts...).WithFeatureRequirements(features.RequireDisabled(enterpriseFeatures.MixedRoutingMode))
	mustGetTest("node-to-node-encryption", cts...).WithFeatureRequirements(features.RequireDisabled(enterpriseFeatures.MixedRoutingMode))
	mustGetTest("pod-to-pod-encryption-v2", cts...).WithFeatureRequirements(features.RequireDisabled(enterpriseFeatures.MixedRoutingMode))
	mustGetTest("pod-to-pod-with-l7-policy-encryption-v2", cts...).WithFeatureRequirements(features.RequireDisabled(enterpriseFeatures.MixedRoutingMode))

	// Requirements changes should be additionally applied to the ones guarding
	// the execution of the associated setup function, so that they always match.
	if cts[0].Params().IncludeUnsafeTests {
		// Generate extra traffic from one pod in each cluster to each Cilium
		// HealthIP, to prevent the sanity checks from reporting false positives
		// due to the lack of other traffic flowing in the cluster. The already
		// existing health check test is not sufficient when WireGuard is enabled,
		// because node to pod traffic is not encrypted by default.
		cts[0].AddTest(check.NewTest("mixed-routing-extra-traffic", cts[0].Params().Verbose, cts[0].Params().Debug)).
			WithFeatureRequirements(
				features.RequireEnabled(features.HealthChecking),
				features.RequireEnabled(enterpriseFeatures.FallbackRoutingMode),
			).
			WithScenarios(enterpriseTests.MixedRoutingExtraTraffic())

		cts[0].AddTest(check.NewTest("mixed-routing", cts[0].Params().Verbose, cts[0].Params().Debug)).
			WithFeatureRequirements(features.RequireEnabled(enterpriseFeatures.FallbackRoutingMode)).
			WithSysdumpPolicy(check.SysdumpPolicyNever).
			WithScenarios(ec.mixedRoutingScenario)
	}

	return nil
}

func (ec *EnterpriseConnectivity) addMulticastTests(ct *check.ConnectivityTest) (err error) {
	newTest := func(ct *check.ConnectivityTest, name string) *enterpriseCheck.EnterpriseTest {
		return enterpriseCheck.NewEnterpriseConnectivityTest(ct).
			NewEnterpriseTest(name).
			WithFeatureRequirements(
				features.RequireEnabled(enterpriseFeatures.Multicast),
			)
	}

	// test igmp v2
	igmpv2Test := newTest(ct, "multicast-igmpv2-check").
		WithMulticastDeployment(enterpriseCheck.MulticastDeploymentParams{
			Name: "multicast-source-v2",
			Labels: map[string]string{
				enterpriseTests.MulticastLabelKey: enterpriseTests.SourceLabel,
			},
		}).
		WithMulticastDeployment(enterpriseCheck.MulticastDeploymentParams{
			Name: "multicast-subscriber-v2",
			Labels: map[string]string{
				enterpriseTests.MulticastLabelKey: enterpriseTests.SubscriberLabel,
			},
			IGMPVersion: 2,
		}).
		WithIsovalentMulticastGroup(
			enterpriseCheck.IsovalentMulticastGroupParams{
				Name:            "igmpv2-version-test",
				GroupAddrPrefix: "226.1.0.0",
				Groups:          5,
			})
	igmpv2Test.WithScenarios(enterpriseTests.MulticastGroupCheck(igmpv2Test.Context().EntClients()))

	// test igmp v3 group check
	igmpv3Test := newTest(ct, "multicast-igmpv3-check").
		WithMulticastDeployment(enterpriseCheck.MulticastDeploymentParams{
			Name: "multicast-source-v3",
			Labels: map[string]string{
				enterpriseTests.MulticastLabelKey: enterpriseTests.SourceLabel,
			},
		}).
		WithMulticastDeployment(enterpriseCheck.MulticastDeploymentParams{
			Name: "multicast-subscriber-v3",
			Labels: map[string]string{
				enterpriseTests.MulticastLabelKey: enterpriseTests.SubscriberLabel,
			},
			IGMPVersion: 3,
		}).
		WithIsovalentMulticastGroup(
			enterpriseCheck.IsovalentMulticastGroupParams{
				Name:            "igmpv3-version-test",
				GroupAddrPrefix: "226.2.0.0",
				Groups:          5,
			})
	igmpv3Test.WithScenarios(enterpriseTests.MulticastGroupCheck(igmpv3Test.Context().EntClients()))

	// check multicast connectivity
	mcastConnectivityTest := newTest(ct, "multicast-connectivity").
		WithMulticastDeployment(enterpriseCheck.MulticastDeploymentParams{
			Name: "multicast-source-conn",
			Labels: map[string]string{
				enterpriseTests.MulticastLabelKey: enterpriseTests.SourceLabel,
			},
		}).
		WithMulticastDeployment(enterpriseCheck.MulticastDeploymentParams{
			Name: "multicast-subscriber-conn",
			Labels: map[string]string{
				enterpriseTests.MulticastLabelKey: enterpriseTests.SubscriberLabel,
			},
			IGMPVersion: 3,
		}).
		WithIsovalentMulticastGroup(
			enterpriseCheck.IsovalentMulticastGroupParams{
				Name:            "conn-test",
				GroupAddrPrefix: "226.4.0.0",
				Groups:          5,
			})
	mcastConnectivityTest.WithScenarios(enterpriseTests.MulticastConnectivity(mcastConnectivityTest.Context().EntClients(), 100))

	return nil
}

func (ec *EnterpriseConnectivity) addBGPTests(ct *check.ConnectivityTest) (err error) {
	// disable OSS BGPv2 tests if enterprise BGP CP is enabled (OSS CRDs can not be used if enterprise CP is enabled)
	if ossv2Test, err := ct.GetTest("seq-bgp-control-plane-v2"); err == nil {
		ossv2Test.WithFeatureRequirements(
			features.RequireDisabled(enterpriseFeatures.EnterpriseBGPControlPlane),
		)
	}

	newTest := func(ct *check.ConnectivityTest, name string) *enterpriseCheck.EnterpriseTest {
		return enterpriseCheck.NewEnterpriseConnectivityTest(ct).
			NewEnterpriseTest(name).
			WithFeatureRequirements(
				features.RequireEnabled(enterpriseFeatures.EnterpriseBGPControlPlane),
				features.RequireEnabled(features.BGPControlPlane),
				features.RequireEnabled(features.NodeWithoutCilium),
			)
	}

	// prefix the test name with `seq-` to run it sequentially
	newTest(ct, "seq-enterprise-bgp-control-plane-v2").
		WithScenarios(enterpriseTests.BGPSvcAdvertisements())

	return nil
}

func (ec *EnterpriseConnectivity) addBFDTests(ct *check.ConnectivityTest) (err error) {
	bfdStandaloneTest := func(ct *check.ConnectivityTest) *enterpriseCheck.EnterpriseTest {
		return enterpriseCheck.NewEnterpriseConnectivityTest(ct).
			NewEnterpriseTest("seq-bfd-standalone"). // prefix the test name with `seq-` to run it sequentially
			WithFeatureRequirements(
				features.RequireEnabled(enterpriseFeatures.BFD),
				features.RequireEnabled(features.NodeWithoutCilium),
			)
	}
	bfdStandaloneTest(ct).WithScenarios(
		enterpriseTests.BFDStandAlone(enterpriseTests.BFDStandAloneParams{
			MultiHop:     false,
			EchoFunction: false,
		}),
		enterpriseTests.BFDStandAlone(enterpriseTests.BFDStandAloneParams{
			MultiHop:     false,
			EchoFunction: true,
		}),
		enterpriseTests.BFDStandAlone(enterpriseTests.BFDStandAloneParams{
			MultiHop:     true,
			EchoFunction: false,
		}),
	)

	bfdBGPTest := func(ct *check.ConnectivityTest) *enterpriseCheck.EnterpriseTest {
		return enterpriseCheck.NewEnterpriseConnectivityTest(ct).
			NewEnterpriseTest("seq-bfd-bgp"). // prefix the test name with `seq-` to run it sequentially
			WithFeatureRequirements(
				features.RequireEnabled(enterpriseFeatures.BFD),
				features.RequireEnabled(features.NodeWithoutCilium),
				features.RequireEnabled(enterpriseFeatures.EnterpriseBGPControlPlane),
				features.RequireEnabled(features.BGPControlPlane),
			)
	}
	bfdBGPTest(ct).WithScenarios(enterpriseTests.BFDWithBGP())

	return nil
}

func mustGetTest(testName string, cts ...*check.ConnectivityTest) *check.Test {
	var (
		test *check.Test
		err  error
	)
	for i := range cts {
		if test, err = cts[i].GetTest(testName); err == nil {
			return test
		}
	}
	panic(fmt.Errorf("failed to get test %s: %w", testName, err))
}

func renderTemplates(ct *check.ConnectivityTest) (map[string]string, error) {
	templates := map[string]string{
		"clientEgressOnlyDNSPolicyYAML":       clientEgressOnlyDNSPolicyYAML,
		"clientIngressToEchoOrderedNS":        clientIngressToEchoOrderedNS,
		"clientIngressToEchoOrderedWildcard":  clientIngressToEchoOrderedWildcard,
		"clientIngressToEchoOrderedPortrange": clientIngressToEchoOrderedPortrange,
	}

	renderedTemplates := map[string]string{}
	for key, temp := range templates {
		val, err := template.Render(temp, struct {
			check.Parameters
			ClusterNameLocal  string
			ClusterNameRemote string
		}{
			Parameters:        ct.Params(),
			ClusterNameLocal:  ct.ClusterNameLocal,
			ClusterNameRemote: ct.ClusterNameRemote,
		})
		if err != nil {
			return nil, err
		}
		renderedTemplates[key] = val
	}
	return renderedTemplates, nil
}
