{{$PER_NAMESPACE_CNPS := DefaultParam .CL2_PER_NAMESPACE_CNPS false}}

{{$actionName := printf "%s objects" .actionName}}
{{$namespaces := .namespaces}}
{{$tuningSet := .tuningSet}}
{{$fixedTuningSet := .fixedTuningSet}}
{{$operationTimeout := .operationTimeout}}
{{$deploymentsPerNamespace := .deploymentsPerNamespace}}
{{$replicasPerDeployment := .replicasPerDeployment}}

steps:
- name: Starting measurement for '{{$actionName}}'
  measurements:
  - Method: WaitForControlledPodsRunning
    Instances:
    - Identifier: WaitForRunningDeployments
      Params:
        apiVersion: apps/v1
        kind: Deployment
    Params:
      action: start
      checkIfPodsAreUpdated: true
      labelSelector: group = load
      operationTimeout: {{$operationTimeout}}

- name: {{$actionName}}
  phases:
  - namespaceRange:
      min: 1
      max: {{$namespaces}}
    replicasPerNamespace: {{$deploymentsPerNamespace}}
    tuningSet: {{$tuningSet}}
    objectBundle:
    - basename: small-deployment
      objectTemplatePath: deployment.yaml
      templateFillMap:
        Replicas: {{$replicasPerDeployment}}

- name: Waiting for '{{$actionName}}' to be completed
  measurements:
  - Method: WaitForControlledPodsRunning
    Instances:
    - Identifier: WaitForRunningDeployments
    Params:
      action: gather

 {{if $PER_NAMESPACE_CNPS }}
- name: {{$actionName}}
  phases:
  - namespaceRange:
      min: 1
      max: {{$namespaces}}
    replicasPerNamespace: 1
    tuningSet: {{$fixedTuningSet}}
    objectBundle:
    - basename: cnp
      objectTemplatePath: cnp.yaml
      templateFillMap:
        Replicas: 1
{{ end }}
