{{$MIN_NAMESPACES := DefaultParam .CL2_MIN_NAMESPACES 100}}
{{$PODS_PER_NODE := DefaultParam .CL2_PODS_PER_NODE 10}}
{{$TARGET_IDENTITIES := DefaultParam .CL2_TARGET_IDENTITIES 1000}}

{{$namespaces := MinInt (MaxInt (DivideInt .Nodes 2) $MIN_NAMESPACES) 1500 }}
{{$identities := MaxInt $TARGET_IDENTITIES $namespaces}}
{{$TimeToLoad := 10 }}

{{$largeServices := 5}}
{{$slicesPerService := 50}}
{{$slicesUpdates := 5}}
# In total, we do $largeServices * $slicesPerService * $slicesUpdates updates

{{$totalPods := MultiplyInt .Nodes $PODS_PER_NODE}}
{{$deploymentsPerNamespace := MaxInt (DivideInt $TARGET_IDENTITIES $namespaces) 1}}
{{$deployments := MultiplyInt $deploymentsPerNamespace $namespaces}}
{{$podsPerDeployment := MaxInt (DivideInt $totalPods $deployments) 1}}

name: panda
namespace:
  number: {{$namespaces}}
  deleteAutomanagedNamespaces: {{DefaultParam .CL2_DELETE_AUTOMANAGED_NAMESPACES true}}

tuningSets:
- name: default
  globalQPSLoad:
    qps: 50
    burst: 50
- name: RandomizedSaturationTimeLimited
  RandomizedTimeLimitedLoad:
    timeLimit: {{$TimeToLoad}}m

steps:
- module:
    path: ../../cilium-agent-pprofs.yaml
    params:
      action: start

- module:
    path: /modules/metrics.yaml
    params:
      action: start

- module:
    path: /modules/reconcile-objects.yaml
    params:
      actionName: "create"
      namespaces: {{$namespaces}}
      tuningSet: RandomizedSaturationTimeLimited
      fixedTuningSet: default
      operationTimeout: 15m
      replicasPerDeployment: {{$podsPerDeployment}}
      deploymentsPerNamespace: {{$deploymentsPerNamespace}}
      largeServices: {{$largeServices}}
      slicesPerService: {{$slicesPerService}}
      slicesUpdates: {{$slicesUpdates}}

- name: Sleep After reconcile
  measurements:
  - Identifier: WaitAfterReconcile
    Method: Sleep
    Params:
      duration: 2m

- name: Apply oneoff test
  measurements:
  - Identifier: ExecCommand
    Method: Exec
    Params:
      timeout: 1m
      command:
      - /bin/sh
      - -c
      - "kubectl apply -f ./testing/custom/enterprise/panda/manifests/cloudprober-oneoff.yaml"

- name: Wait for oneoff cloudprober
  measurements:
  - Identifier: ExecCommand
    Method: Exec
    Params:
      timeout: 10m
      command:
      - /bin/sh
      - -c
      - "kubectl rollout status daemonset cloudprober-oneoff"

- name: Sleep after oneoff
  measurements:
  - Identifier: WaitAfterOneOff
    Method: Sleep
    Params:
      duration: 2m

- module:
    path:  /modules/metrics.yaml
    params:
      action: gather

- module:
    path: ../../cilium-agent-pprofs.yaml
    params:
      action: gather

- module:
    path:  /modules/metrics-restart.yaml
    params:
      action: start
      restartName: Agent

- name: Collect sysdump
  measurements:
  - Identifier: ExecCommand
    Method: Exec
    Params:
      timeout: 20m
      command:
      - /bin/sh
      - -c
      - "cilium sysdump --output-filename cilium-sysdump-middle --node-list={{DefaultParam .CL2_SYSDUMP_NODES_LIST ""}}"

- name: Restart Agent
  measurements:
  - Identifier: ExecCommand
    Method: Exec
    Params:
      timeout: 1m
      command:
      - /bin/sh
      - -c
      - "kubectl rollout restart daemonset cilium -n kube-system"

- name: Wait for restarting Agent
  measurements:
  - Identifier: ExecCommand
    Method: Exec
    Params:
      timeout: 25m
      command:
      - /bin/sh
      - -c
      - "kubectl rollout status daemonset cilium -n kube-system"

- name: Sleep Agent
  measurements:
  - Identifier: WaitAfterExec
    Method: Sleep
    Params:
      duration: 10m

- module:
    path:  /modules/metrics-restart.yaml
    params:
      action: gather
      restartName: Agent

- module:
    path:  /modules/metrics-restart.yaml
    params:
      action: start
      restartName: Envoy

- name: Restart Envoy
  measurements:
  - Identifier: ExecCommand
    Method: Exec
    Params:
      timeout: 1m
      command:
      - /bin/sh
      - -c
      - "kubectl rollout restart daemonset cilium-envoy -n kube-system"

- name: Wait for restarting Envoy
  measurements:
  - Identifier: ExecCommand
    Method: Exec
    Params:
      timeout: 10m
      command:
      - /bin/sh
      - -c
      - "kubectl rollout status daemonset cilium-envoy -n kube-system"

- name: Sleep Envoy
  measurements:
  - Identifier: WaitAfterExec
    Method: Sleep
    Params:
      duration: 5m

- module:
    path:  /modules/metrics-restart.yaml
    params:
      action: gather
      restartName: Envoy
