//  Copyright (C) Isovalent, Inc. - All Rights Reserved.
//
//  NOTICE: All information contained herein is, and remains the property of
//  Isovalent Inc and its suppliers, if any. The intellectual and technical
//  concepts contained herein are proprietary to Isovalent Inc and its suppliers
//  and may be covered by U.S. and Foreign Patents, patents in process, and are
//  protected by trade secret or copyright law.  Dissemination of this information
//  or reproduction of this material is strictly forbidden unless prior written
//  permission is obtained from Isovalent Inc.
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: dnsproxy/dnsproxy.proto

package dnsproxy

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// IPCacheVersion establishes which version of the key for
// the IP bpf map is being used. While it is the case that
// the IP bpf map is currently unversioned if the key format
// were to change in the future the proxy would read from
// the bpf map incorrectly.
type IPCacheVersion int32

const (
	IPCacheVersion_Unspecified IPCacheVersion = 0
	IPCacheVersion_One         IPCacheVersion = 1
)

// Enum value maps for IPCacheVersion.
var (
	IPCacheVersion_name = map[int32]string{
		0: "Unspecified",
		1: "One",
	}
	IPCacheVersion_value = map[string]int32{
		"Unspecified": 0,
		"One":         1,
	}
)

func (x IPCacheVersion) Enum() *IPCacheVersion {
	p := new(IPCacheVersion)
	*p = x
	return p
}

func (x IPCacheVersion) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IPCacheVersion) Descriptor() protoreflect.EnumDescriptor {
	return file_dnsproxy_dnsproxy_proto_enumTypes[0].Descriptor()
}

func (IPCacheVersion) Type() protoreflect.EnumType {
	return &file_dnsproxy_dnsproxy_proto_enumTypes[0]
}

func (x IPCacheVersion) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IPCacheVersion.Descriptor instead.
func (IPCacheVersion) EnumDescriptor() ([]byte, []int) {
	return file_dnsproxy_dnsproxy_proto_rawDescGZIP(), []int{0}
}

type UpdateType int32

const (
	UpdateType_UPDATETYPE_UNSPECIFIED UpdateType = 0
	UpdateType_UPDATETYPE_UPSERT      UpdateType = 1
	UpdateType_UPDATETYPE_REMOVE      UpdateType = 2
	UpdateType_UPDATETYPE_BOOKMARK    UpdateType = 3
)

// Enum value maps for UpdateType.
var (
	UpdateType_name = map[int32]string{
		0: "UPDATETYPE_UNSPECIFIED",
		1: "UPDATETYPE_UPSERT",
		2: "UPDATETYPE_REMOVE",
		3: "UPDATETYPE_BOOKMARK",
	}
	UpdateType_value = map[string]int32{
		"UPDATETYPE_UNSPECIFIED": 0,
		"UPDATETYPE_UPSERT":      1,
		"UPDATETYPE_REMOVE":      2,
		"UPDATETYPE_BOOKMARK":    3,
	}
)

func (x UpdateType) Enum() *UpdateType {
	p := new(UpdateType)
	*p = x
	return p
}

func (x UpdateType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UpdateType) Descriptor() protoreflect.EnumDescriptor {
	return file_dnsproxy_dnsproxy_proto_enumTypes[1].Descriptor()
}

func (UpdateType) Type() protoreflect.EnumType {
	return &file_dnsproxy_dnsproxy_proto_enumTypes[1]
}

func (x UpdateType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UpdateType.Descriptor instead.
func (UpdateType) EnumDescriptor() ([]byte, []int) {
	return file_dnsproxy_dnsproxy_proto_rawDescGZIP(), []int{1}
}

type RestoredRulesMap struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Rules         map[uint64]*RestoredRules `protobuf:"bytes,1,rep,name=rules,proto3" json:"rules,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoredRulesMap) Reset() {
	*x = RestoredRulesMap{}
	mi := &file_dnsproxy_dnsproxy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoredRulesMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoredRulesMap) ProtoMessage() {}

func (x *RestoredRulesMap) ProtoReflect() protoreflect.Message {
	mi := &file_dnsproxy_dnsproxy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoredRulesMap.ProtoReflect.Descriptor instead.
func (*RestoredRulesMap) Descriptor() ([]byte, []int) {
	return file_dnsproxy_dnsproxy_proto_rawDescGZIP(), []int{0}
}

func (x *RestoredRulesMap) GetRules() map[uint64]*RestoredRules {
	if x != nil {
		return x.Rules
	}
	return nil
}

type RestoredRules struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rules         map[uint32]*IPRules    `protobuf:"bytes,1,rep,name=rules,proto3" json:"rules,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoredRules) Reset() {
	*x = RestoredRules{}
	mi := &file_dnsproxy_dnsproxy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoredRules) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoredRules) ProtoMessage() {}

func (x *RestoredRules) ProtoReflect() protoreflect.Message {
	mi := &file_dnsproxy_dnsproxy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoredRules.ProtoReflect.Descriptor instead.
func (*RestoredRules) Descriptor() ([]byte, []int) {
	return file_dnsproxy_dnsproxy_proto_rawDescGZIP(), []int{1}
}

func (x *RestoredRules) GetRules() map[uint32]*IPRules {
	if x != nil {
		return x.Rules
	}
	return nil
}

type IPRules struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*IPRule              `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IPRules) Reset() {
	*x = IPRules{}
	mi := &file_dnsproxy_dnsproxy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IPRules) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IPRules) ProtoMessage() {}

func (x *IPRules) ProtoReflect() protoreflect.Message {
	mi := &file_dnsproxy_dnsproxy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IPRules.ProtoReflect.Descriptor instead.
func (*IPRules) Descriptor() ([]byte, []int) {
	return file_dnsproxy_dnsproxy_proto_rawDescGZIP(), []int{2}
}

func (x *IPRules) GetList() []*IPRule {
	if x != nil {
		return x.List
	}
	return nil
}

type IPRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Regex         string                 `protobuf:"bytes,1,opt,name=regex,proto3" json:"regex,omitempty"`
	Ips           []string               `protobuf:"bytes,2,rep,name=ips,proto3" json:"ips,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IPRule) Reset() {
	*x = IPRule{}
	mi := &file_dnsproxy_dnsproxy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IPRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IPRule) ProtoMessage() {}

func (x *IPRule) ProtoReflect() protoreflect.Message {
	mi := &file_dnsproxy_dnsproxy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IPRule.ProtoReflect.Descriptor instead.
func (*IPRule) Descriptor() ([]byte, []int) {
	return file_dnsproxy_dnsproxy_proto_rawDescGZIP(), []int{3}
}

func (x *IPRule) GetRegex() string {
	if x != nil {
		return x.Regex
	}
	return ""
}

func (x *IPRule) GetIps() []string {
	if x != nil {
		return x.Ips
	}
	return nil
}

type EndpointID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EndpointID    uint32                 `protobuf:"varint,1,opt,name=endpointID,proto3" json:"endpointID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndpointID) Reset() {
	*x = EndpointID{}
	mi := &file_dnsproxy_dnsproxy_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndpointID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndpointID) ProtoMessage() {}

func (x *EndpointID) ProtoReflect() protoreflect.Message {
	mi := &file_dnsproxy_dnsproxy_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndpointID.ProtoReflect.Descriptor instead.
func (*EndpointID) Descriptor() ([]byte, []int) {
	return file_dnsproxy_dnsproxy_proto_rawDescGZIP(), []int{4}
}

func (x *EndpointID) GetEndpointID() uint32 {
	if x != nil {
		return x.EndpointID
	}
	return 0
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_dnsproxy_dnsproxy_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_dnsproxy_dnsproxy_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_dnsproxy_dnsproxy_proto_rawDescGZIP(), []int{5}
}

type FQDNRules struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EndpointID    uint64                 `protobuf:"varint,1,opt,name=endpointID,proto3" json:"endpointID,omitempty"`
	DestPort      uint32                 `protobuf:"varint,2,opt,name=destPort,proto3" json:"destPort,omitempty"`
	Rules         *L7Rules               `protobuf:"bytes,3,opt,name=rules,proto3" json:"rules,omitempty"`
	DestProto     uint32                 `protobuf:"varint,4,opt,name=destProto,proto3" json:"destProto,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FQDNRules) Reset() {
	*x = FQDNRules{}
	mi := &file_dnsproxy_dnsproxy_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FQDNRules) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FQDNRules) ProtoMessage() {}

func (x *FQDNRules) ProtoReflect() protoreflect.Message {
	mi := &file_dnsproxy_dnsproxy_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FQDNRules.ProtoReflect.Descriptor instead.
func (*FQDNRules) Descriptor() ([]byte, []int) {
	return file_dnsproxy_dnsproxy_proto_rawDescGZIP(), []int{6}
}

func (x *FQDNRules) GetEndpointID() uint64 {
	if x != nil {
		return x.EndpointID
	}
	return 0
}

func (x *FQDNRules) GetDestPort() uint32 {
	if x != nil {
		return x.DestPort
	}
	return 0
}

func (x *FQDNRules) GetRules() *L7Rules {
	if x != nil {
		return x.Rules
	}
	return nil
}

func (x *FQDNRules) GetDestProto() uint32 {
	if x != nil {
		return x.DestProto
	}
	return 0
}

type L7Rules struct {
	state                     protoimpl.MessageState   `protogen:"open.v1"`
	SelectorRegexMapping      map[string]string        `protobuf:"bytes,1,rep,name=SelectorRegexMapping,proto3" json:"SelectorRegexMapping,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	SelectorIdentitiesMapping map[string]*IdentityList `protobuf:"bytes,2,rep,name=SelectorIdentitiesMapping,proto3" json:"SelectorIdentitiesMapping,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *L7Rules) Reset() {
	*x = L7Rules{}
	mi := &file_dnsproxy_dnsproxy_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *L7Rules) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L7Rules) ProtoMessage() {}

func (x *L7Rules) ProtoReflect() protoreflect.Message {
	mi := &file_dnsproxy_dnsproxy_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L7Rules.ProtoReflect.Descriptor instead.
func (*L7Rules) Descriptor() ([]byte, []int) {
	return file_dnsproxy_dnsproxy_proto_rawDescGZIP(), []int{7}
}

func (x *L7Rules) GetSelectorRegexMapping() map[string]string {
	if x != nil {
		return x.SelectorRegexMapping
	}
	return nil
}

func (x *L7Rules) GetSelectorIdentitiesMapping() map[string]*IdentityList {
	if x != nil {
		return x.SelectorIdentitiesMapping
	}
	return nil
}

type IdentityList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []uint32               `protobuf:"varint,1,rep,packed,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdentityList) Reset() {
	*x = IdentityList{}
	mi := &file_dnsproxy_dnsproxy_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentityList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentityList) ProtoMessage() {}

func (x *IdentityList) ProtoReflect() protoreflect.Message {
	mi := &file_dnsproxy_dnsproxy_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentityList.ProtoReflect.Descriptor instead.
func (*IdentityList) Descriptor() ([]byte, []int) {
	return file_dnsproxy_dnsproxy_proto_rawDescGZIP(), []int{8}
}

func (x *IdentityList) GetList() []uint32 {
	if x != nil {
		return x.List
	}
	return nil
}

type DNSNotification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Time          *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	Endpoint      *Endpoint              `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	EpIPPort      string                 `protobuf:"bytes,3,opt,name=epIPPort,proto3" json:"epIPPort,omitempty"`
	ServerAddr    string                 `protobuf:"bytes,4,opt,name=serverAddr,proto3" json:"serverAddr,omitempty"`
	Msg           []byte                 `protobuf:"bytes,5,opt,name=msg,proto3" json:"msg,omitempty"`
	Protocol      string                 `protobuf:"bytes,6,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Allowed       bool                   `protobuf:"varint,7,opt,name=allowed,proto3" json:"allowed,omitempty"`
	ServerID      uint32                 `protobuf:"varint,8,opt,name=serverID,proto3" json:"serverID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DNSNotification) Reset() {
	*x = DNSNotification{}
	mi := &file_dnsproxy_dnsproxy_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DNSNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DNSNotification) ProtoMessage() {}

func (x *DNSNotification) ProtoReflect() protoreflect.Message {
	mi := &file_dnsproxy_dnsproxy_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DNSNotification.ProtoReflect.Descriptor instead.
func (*DNSNotification) Descriptor() ([]byte, []int) {
	return file_dnsproxy_dnsproxy_proto_rawDescGZIP(), []int{9}
}

func (x *DNSNotification) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *DNSNotification) GetEndpoint() *Endpoint {
	if x != nil {
		return x.Endpoint
	}
	return nil
}

func (x *DNSNotification) GetEpIPPort() string {
	if x != nil {
		return x.EpIPPort
	}
	return ""
}

func (x *DNSNotification) GetServerAddr() string {
	if x != nil {
		return x.ServerAddr
	}
	return ""
}

func (x *DNSNotification) GetMsg() []byte {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *DNSNotification) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *DNSNotification) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *DNSNotification) GetServerID() uint32 {
	if x != nil {
		return x.ServerID
	}
	return 0
}

type IPs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IPs           [][]byte               `protobuf:"bytes,1,rep,name=IPs,proto3" json:"IPs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IPs) Reset() {
	*x = IPs{}
	mi := &file_dnsproxy_dnsproxy_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IPs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IPs) ProtoMessage() {}

func (x *IPs) ProtoReflect() protoreflect.Message {
	mi := &file_dnsproxy_dnsproxy_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IPs.ProtoReflect.Descriptor instead.
func (*IPs) Descriptor() ([]byte, []int) {
	return file_dnsproxy_dnsproxy_proto_rawDescGZIP(), []int{10}
}

func (x *IPs) GetIPs() [][]byte {
	if x != nil {
		return x.IPs
	}
	return nil
}

type FQDN_IP struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IP            []byte                 `protobuf:"bytes,1,opt,name=IP,proto3" json:"IP,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FQDN_IP) Reset() {
	*x = FQDN_IP{}
	mi := &file_dnsproxy_dnsproxy_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FQDN_IP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FQDN_IP) ProtoMessage() {}

func (x *FQDN_IP) ProtoReflect() protoreflect.Message {
	mi := &file_dnsproxy_dnsproxy_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FQDN_IP.ProtoReflect.Descriptor instead.
func (*FQDN_IP) Descriptor() ([]byte, []int) {
	return file_dnsproxy_dnsproxy_proto_rawDescGZIP(), []int{11}
}

func (x *FQDN_IP) GetIP() []byte {
	if x != nil {
		return x.IP
	}
	return nil
}

type Identity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            uint32                 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=Source,proto3" json:"Source,omitempty"`
	Exists        bool                   `protobuf:"varint,3,opt,name=Exists,proto3" json:"Exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Identity) Reset() {
	*x = Identity{}
	mi := &file_dnsproxy_dnsproxy_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Identity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Identity) ProtoMessage() {}

func (x *Identity) ProtoReflect() protoreflect.Message {
	mi := &file_dnsproxy_dnsproxy_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Identity.ProtoReflect.Descriptor instead.
func (*Identity) Descriptor() ([]byte, []int) {
	return file_dnsproxy_dnsproxy_proto_rawDescGZIP(), []int{12}
}

func (x *Identity) GetID() uint32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *Identity) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Identity) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

type FQDNMapping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IP            []byte                 `protobuf:"bytes,1,opt,name=IP,proto3" json:"IP,omitempty"`
	FQDN          string                 `protobuf:"bytes,2,opt,name=FQDN,proto3" json:"FQDN,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FQDNMapping) Reset() {
	*x = FQDNMapping{}
	mi := &file_dnsproxy_dnsproxy_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FQDNMapping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FQDNMapping) ProtoMessage() {}

func (x *FQDNMapping) ProtoReflect() protoreflect.Message {
	mi := &file_dnsproxy_dnsproxy_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FQDNMapping.ProtoReflect.Descriptor instead.
func (*FQDNMapping) Descriptor() ([]byte, []int) {
	return file_dnsproxy_dnsproxy_proto_rawDescGZIP(), []int{13}
}

func (x *FQDNMapping) GetIP() []byte {
	if x != nil {
		return x.IP
	}
	return nil
}

func (x *FQDNMapping) GetFQDN() string {
	if x != nil {
		return x.FQDN
	}
	return ""
}

type SelectorUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FqdnSelector  *FQDNSelectorUpdate    `protobuf:"bytes,1,opt,name=fqdnSelector,proto3" json:"fqdnSelector,omitempty"`
	FqdnIdentity  *FQDNIdentityUpdate    `protobuf:"bytes,2,opt,name=fqdnIdentity,proto3" json:"fqdnIdentity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SelectorUpdate) Reset() {
	*x = SelectorUpdate{}
	mi := &file_dnsproxy_dnsproxy_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelectorUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectorUpdate) ProtoMessage() {}

func (x *SelectorUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_dnsproxy_dnsproxy_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectorUpdate.ProtoReflect.Descriptor instead.
func (*SelectorUpdate) Descriptor() ([]byte, []int) {
	return file_dnsproxy_dnsproxy_proto_rawDescGZIP(), []int{14}
}

func (x *SelectorUpdate) GetFqdnSelector() *FQDNSelectorUpdate {
	if x != nil {
		return x.FqdnSelector
	}
	return nil
}

func (x *SelectorUpdate) GetFqdnIdentity() *FQDNIdentityUpdate {
	if x != nil {
		return x.FqdnIdentity
	}
	return nil
}

type FQDNSelectorUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          UpdateType             `protobuf:"varint,1,opt,name=type,proto3,enum=dnsproxy.UpdateType" json:"type,omitempty"`
	Selector      *FQDNSelector          `protobuf:"bytes,2,opt,name=selector,proto3" json:"selector,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FQDNSelectorUpdate) Reset() {
	*x = FQDNSelectorUpdate{}
	mi := &file_dnsproxy_dnsproxy_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FQDNSelectorUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FQDNSelectorUpdate) ProtoMessage() {}

func (x *FQDNSelectorUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_dnsproxy_dnsproxy_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FQDNSelectorUpdate.ProtoReflect.Descriptor instead.
func (*FQDNSelectorUpdate) Descriptor() ([]byte, []int) {
	return file_dnsproxy_dnsproxy_proto_rawDescGZIP(), []int{15}
}

func (x *FQDNSelectorUpdate) GetType() UpdateType {
	if x != nil {
		return x.Type
	}
	return UpdateType_UPDATETYPE_UNSPECIFIED
}

func (x *FQDNSelectorUpdate) GetSelector() *FQDNSelector {
	if x != nil {
		return x.Selector
	}
	return nil
}

type FQDNSelector struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MatchName     string                 `protobuf:"bytes,1,opt,name=MatchName,proto3" json:"MatchName,omitempty"`
	MatchPattern  string                 `protobuf:"bytes,2,opt,name=MatchPattern,proto3" json:"MatchPattern,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FQDNSelector) Reset() {
	*x = FQDNSelector{}
	mi := &file_dnsproxy_dnsproxy_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FQDNSelector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FQDNSelector) ProtoMessage() {}

func (x *FQDNSelector) ProtoReflect() protoreflect.Message {
	mi := &file_dnsproxy_dnsproxy_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FQDNSelector.ProtoReflect.Descriptor instead.
func (*FQDNSelector) Descriptor() ([]byte, []int) {
	return file_dnsproxy_dnsproxy_proto_rawDescGZIP(), []int{16}
}

func (x *FQDNSelector) GetMatchName() string {
	if x != nil {
		return x.MatchName
	}
	return ""
}

func (x *FQDNSelector) GetMatchPattern() string {
	if x != nil {
		return x.MatchPattern
	}
	return ""
}

type FQDNIdentityUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          UpdateType             `protobuf:"varint,1,opt,name=type,proto3,enum=dnsproxy.UpdateType" json:"type,omitempty"`
	Labels        []*Label               `protobuf:"bytes,2,rep,name=labels,proto3" json:"labels,omitempty"`
	Identity      uint64                 `protobuf:"varint,3,opt,name=identity,proto3" json:"identity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FQDNIdentityUpdate) Reset() {
	*x = FQDNIdentityUpdate{}
	mi := &file_dnsproxy_dnsproxy_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FQDNIdentityUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FQDNIdentityUpdate) ProtoMessage() {}

func (x *FQDNIdentityUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_dnsproxy_dnsproxy_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FQDNIdentityUpdate.ProtoReflect.Descriptor instead.
func (*FQDNIdentityUpdate) Descriptor() ([]byte, []int) {
	return file_dnsproxy_dnsproxy_proto_rawDescGZIP(), []int{17}
}

func (x *FQDNIdentityUpdate) GetType() UpdateType {
	if x != nil {
		return x.Type
	}
	return UpdateType_UPDATETYPE_UNSPECIFIED
}

func (x *FQDNIdentityUpdate) GetLabels() []*Label {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *FQDNIdentityUpdate) GetIdentity() uint64 {
	if x != nil {
		return x.Identity
	}
	return 0
}

type Label struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
	Source        string                 `protobuf:"bytes,3,opt,name=Source,proto3" json:"Source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Label) Reset() {
	*x = Label{}
	mi := &file_dnsproxy_dnsproxy_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Label) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Label) ProtoMessage() {}

func (x *Label) ProtoReflect() protoreflect.Message {
	mi := &file_dnsproxy_dnsproxy_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Label.ProtoReflect.Descriptor instead.
func (*Label) Descriptor() ([]byte, []int) {
	return file_dnsproxy_dnsproxy_proto_rawDescGZIP(), []int{18}
}

func (x *Label) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Label) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Label) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type Success struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        bool                   `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Success) Reset() {
	*x = Success{}
	mi := &file_dnsproxy_dnsproxy_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Success) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Success) ProtoMessage() {}

func (x *Success) ProtoReflect() protoreflect.Message {
	mi := &file_dnsproxy_dnsproxy_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Success.ProtoReflect.Descriptor instead.
func (*Success) Descriptor() ([]byte, []int) {
	return file_dnsproxy_dnsproxy_proto_rawDescGZIP(), []int{19}
}

func (x *Success) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

type Endpoint struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	ID        uint32                 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Identity  uint32                 `protobuf:"varint,2,opt,name=identity,proto3" json:"identity,omitempty"`
	Namespace string                 `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// labels in `foo=bar` format.
	Labels        []string    `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty"`
	PodName       string      `protobuf:"bytes,5,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	Workloads     []*Workload `protobuf:"bytes,6,rep,name=workloads,proto3" json:"workloads,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Endpoint) Reset() {
	*x = Endpoint{}
	mi := &file_dnsproxy_dnsproxy_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Endpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Endpoint) ProtoMessage() {}

func (x *Endpoint) ProtoReflect() protoreflect.Message {
	mi := &file_dnsproxy_dnsproxy_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Endpoint.ProtoReflect.Descriptor instead.
func (*Endpoint) Descriptor() ([]byte, []int) {
	return file_dnsproxy_dnsproxy_proto_rawDescGZIP(), []int{20}
}

func (x *Endpoint) GetID() uint32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *Endpoint) GetIdentity() uint32 {
	if x != nil {
		return x.Identity
	}
	return 0
}

func (x *Endpoint) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Endpoint) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Endpoint) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *Endpoint) GetWorkloads() []*Workload {
	if x != nil {
		return x.Workloads
	}
	return nil
}

type Workload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Workload) Reset() {
	*x = Workload{}
	mi := &file_dnsproxy_dnsproxy_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Workload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Workload) ProtoMessage() {}

func (x *Workload) ProtoReflect() protoreflect.Message {
	mi := &file_dnsproxy_dnsproxy_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Workload.ProtoReflect.Descriptor instead.
func (*Workload) Descriptor() ([]byte, []int) {
	return file_dnsproxy_dnsproxy_proto_rawDescGZIP(), []int{21}
}

func (x *Workload) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Workload) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

var File_dnsproxy_dnsproxy_proto protoreflect.FileDescriptor

const file_dnsproxy_dnsproxy_proto_rawDesc = "" +
	"\n" +
	"\x17dnsproxy/dnsproxy.proto\x12\bdnsproxy\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa2\x01\n" +
	"\x10RestoredRulesMap\x12;\n" +
	"\x05rules\x18\x01 \x03(\v2%.dnsproxy.RestoredRulesMap.RulesEntryR\x05rules\x1aQ\n" +
	"\n" +
	"RulesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x04R\x03key\x12-\n" +
	"\x05value\x18\x02 \x01(\v2\x17.dnsproxy.RestoredRulesR\x05value:\x028\x01\"\x96\x01\n" +
	"\rRestoredRules\x128\n" +
	"\x05rules\x18\x01 \x03(\v2\".dnsproxy.RestoredRules.RulesEntryR\x05rules\x1aK\n" +
	"\n" +
	"RulesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\rR\x03key\x12'\n" +
	"\x05value\x18\x02 \x01(\v2\x11.dnsproxy.IPRulesR\x05value:\x028\x01\"/\n" +
	"\aIPRules\x12$\n" +
	"\x04list\x18\x01 \x03(\v2\x10.dnsproxy.IPRuleR\x04list\"0\n" +
	"\x06IPRule\x12\x14\n" +
	"\x05regex\x18\x01 \x01(\tR\x05regex\x12\x10\n" +
	"\x03ips\x18\x02 \x03(\tR\x03ips\",\n" +
	"\n" +
	"EndpointID\x12\x1e\n" +
	"\n" +
	"endpointID\x18\x01 \x01(\rR\n" +
	"endpointID\"\a\n" +
	"\x05Empty\"\x8e\x01\n" +
	"\tFQDNRules\x12\x1e\n" +
	"\n" +
	"endpointID\x18\x01 \x01(\x04R\n" +
	"endpointID\x12\x1a\n" +
	"\bdestPort\x18\x02 \x01(\rR\bdestPort\x12'\n" +
	"\x05rules\x18\x03 \x01(\v2\x11.dnsproxy.L7RulesR\x05rules\x12\x1c\n" +
	"\tdestProto\x18\x04 \x01(\rR\tdestProto\"\x89\x03\n" +
	"\aL7Rules\x12_\n" +
	"\x14SelectorRegexMapping\x18\x01 \x03(\v2+.dnsproxy.L7Rules.SelectorRegexMappingEntryR\x14SelectorRegexMapping\x12n\n" +
	"\x19SelectorIdentitiesMapping\x18\x02 \x03(\v20.dnsproxy.L7Rules.SelectorIdentitiesMappingEntryR\x19SelectorIdentitiesMapping\x1aG\n" +
	"\x19SelectorRegexMappingEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1ad\n" +
	"\x1eSelectorIdentitiesMappingEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.dnsproxy.IdentityListR\x05value:\x028\x01\"\"\n" +
	"\fIdentityList\x12\x12\n" +
	"\x04list\x18\x01 \x03(\rR\x04list\"\x91\x02\n" +
	"\x0fDNSNotification\x12.\n" +
	"\x04time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\x12.\n" +
	"\bendpoint\x18\x02 \x01(\v2\x12.dnsproxy.EndpointR\bendpoint\x12\x1a\n" +
	"\bepIPPort\x18\x03 \x01(\tR\bepIPPort\x12\x1e\n" +
	"\n" +
	"serverAddr\x18\x04 \x01(\tR\n" +
	"serverAddr\x12\x10\n" +
	"\x03msg\x18\x05 \x01(\fR\x03msg\x12\x1a\n" +
	"\bprotocol\x18\x06 \x01(\tR\bprotocol\x12\x18\n" +
	"\aallowed\x18\a \x01(\bR\aallowed\x12\x1a\n" +
	"\bserverID\x18\b \x01(\rR\bserverID\"\x17\n" +
	"\x03IPs\x12\x10\n" +
	"\x03IPs\x18\x01 \x03(\fR\x03IPs\"\x19\n" +
	"\aFQDN_IP\x12\x0e\n" +
	"\x02IP\x18\x01 \x01(\fR\x02IP\"J\n" +
	"\bIdentity\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\rR\x02ID\x12\x16\n" +
	"\x06Source\x18\x02 \x01(\tR\x06Source\x12\x16\n" +
	"\x06Exists\x18\x03 \x01(\bR\x06Exists\"1\n" +
	"\vFQDNMapping\x12\x0e\n" +
	"\x02IP\x18\x01 \x01(\fR\x02IP\x12\x12\n" +
	"\x04FQDN\x18\x02 \x01(\tR\x04FQDN\"\x94\x01\n" +
	"\x0eSelectorUpdate\x12@\n" +
	"\ffqdnSelector\x18\x01 \x01(\v2\x1c.dnsproxy.FQDNSelectorUpdateR\ffqdnSelector\x12@\n" +
	"\ffqdnIdentity\x18\x02 \x01(\v2\x1c.dnsproxy.FQDNIdentityUpdateR\ffqdnIdentity\"r\n" +
	"\x12FQDNSelectorUpdate\x12(\n" +
	"\x04type\x18\x01 \x01(\x0e2\x14.dnsproxy.UpdateTypeR\x04type\x122\n" +
	"\bselector\x18\x02 \x01(\v2\x16.dnsproxy.FQDNSelectorR\bselector\"P\n" +
	"\fFQDNSelector\x12\x1c\n" +
	"\tMatchName\x18\x01 \x01(\tR\tMatchName\x12\"\n" +
	"\fMatchPattern\x18\x02 \x01(\tR\fMatchPattern\"\x83\x01\n" +
	"\x12FQDNIdentityUpdate\x12(\n" +
	"\x04type\x18\x01 \x01(\x0e2\x14.dnsproxy.UpdateTypeR\x04type\x12'\n" +
	"\x06labels\x18\x02 \x03(\v2\x0f.dnsproxy.LabelR\x06labels\x12\x1a\n" +
	"\bidentity\x18\x03 \x01(\x04R\bidentity\"G\n" +
	"\x05Label\x12\x10\n" +
	"\x03Key\x18\x01 \x01(\tR\x03Key\x12\x14\n" +
	"\x05Value\x18\x02 \x01(\tR\x05Value\x12\x16\n" +
	"\x06Source\x18\x03 \x01(\tR\x06Source\"!\n" +
	"\aSuccess\x12\x16\n" +
	"\x06result\x18\x01 \x01(\bR\x06result\"\xb9\x01\n" +
	"\bEndpoint\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\rR\x02ID\x12\x1a\n" +
	"\bidentity\x18\x02 \x01(\rR\bidentity\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\x12\x16\n" +
	"\x06labels\x18\x04 \x03(\tR\x06labels\x12\x19\n" +
	"\bpod_name\x18\x05 \x01(\tR\apodName\x120\n" +
	"\tworkloads\x18\x06 \x03(\v2\x12.dnsproxy.WorkloadR\tworkloads\"2\n" +
	"\bWorkload\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind**\n" +
	"\x0eIPCacheVersion\x12\x0f\n" +
	"\vUnspecified\x10\x00\x12\a\n" +
	"\x03One\x10\x01*o\n" +
	"\n" +
	"UpdateType\x12\x1a\n" +
	"\x16UPDATETYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11UPDATETYPE_UPSERT\x10\x01\x12\x15\n" +
	"\x11UPDATETYPE_REMOVE\x10\x02\x12\x17\n" +
	"\x13UPDATETYPE_BOOKMARK\x10\x032\xa4\x04\n" +
	"\x0eFQDNProxyAgent\x12?\n" +
	"\x0fProvideMappings\x12\x15.dnsproxy.FQDNMapping\x1a\x11.dnsproxy.Success\"\x00(\x01\x12=\n" +
	"\x12LookupEndpointByIP\x12\x11.dnsproxy.FQDN_IP\x1a\x12.dnsproxy.Endpoint\"\x00\x12E\n" +
	"\x1aLookupSecurityIdentityByIP\x12\x11.dnsproxy.FQDN_IP\x1a\x12.dnsproxy.Identity\"\x00\x12B\n" +
	"\x1bLookupIPsBySecurityIdentity\x12\x12.dnsproxy.Identity\x1a\r.dnsproxy.IPs\"\x00\x12B\n" +
	"\x12NotifyOnDNSMessage\x12\x19.dnsproxy.DNSNotification\x1a\x0f.dnsproxy.Empty\"\x00\x12<\n" +
	"\vGetAllRules\x12\x0f.dnsproxy.Empty\x1a\x1a.dnsproxy.RestoredRulesMap\"\x00\x12C\n" +
	"\x12SubscribeSelectors\x12\x0f.dnsproxy.Empty\x1a\x18.dnsproxy.SelectorUpdate\"\x000\x01\x12@\n" +
	"\x12SubscribeFQDNRules\x12\x0f.dnsproxy.Empty\x1a\x13.dnsproxy.FQDNRules\"\x00(\x010\x012\xc1\x01\n" +
	"\tFQDNProxy\x127\n" +
	"\rUpdateAllowed\x12\x13.dnsproxy.FQDNRules\x1a\x0f.dnsproxy.Empty\"\x00\x12>\n" +
	"\x13RemoveRestoredRules\x12\x14.dnsproxy.EndpointID\x1a\x0f.dnsproxy.Empty\"\x00\x12;\n" +
	"\bGetRules\x12\x14.dnsproxy.EndpointID\x1a\x17.dnsproxy.RestoredRules\"\x00B@Z>github.com/cilium/cilium/enterprise/fqdn-proxy/api/v1/dnsproxyb\x06proto3"

var (
	file_dnsproxy_dnsproxy_proto_rawDescOnce sync.Once
	file_dnsproxy_dnsproxy_proto_rawDescData []byte
)

func file_dnsproxy_dnsproxy_proto_rawDescGZIP() []byte {
	file_dnsproxy_dnsproxy_proto_rawDescOnce.Do(func() {
		file_dnsproxy_dnsproxy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dnsproxy_dnsproxy_proto_rawDesc), len(file_dnsproxy_dnsproxy_proto_rawDesc)))
	})
	return file_dnsproxy_dnsproxy_proto_rawDescData
}

var file_dnsproxy_dnsproxy_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_dnsproxy_dnsproxy_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_dnsproxy_dnsproxy_proto_goTypes = []any{
	(IPCacheVersion)(0),           // 0: dnsproxy.IPCacheVersion
	(UpdateType)(0),               // 1: dnsproxy.UpdateType
	(*RestoredRulesMap)(nil),      // 2: dnsproxy.RestoredRulesMap
	(*RestoredRules)(nil),         // 3: dnsproxy.RestoredRules
	(*IPRules)(nil),               // 4: dnsproxy.IPRules
	(*IPRule)(nil),                // 5: dnsproxy.IPRule
	(*EndpointID)(nil),            // 6: dnsproxy.EndpointID
	(*Empty)(nil),                 // 7: dnsproxy.Empty
	(*FQDNRules)(nil),             // 8: dnsproxy.FQDNRules
	(*L7Rules)(nil),               // 9: dnsproxy.L7Rules
	(*IdentityList)(nil),          // 10: dnsproxy.IdentityList
	(*DNSNotification)(nil),       // 11: dnsproxy.DNSNotification
	(*IPs)(nil),                   // 12: dnsproxy.IPs
	(*FQDN_IP)(nil),               // 13: dnsproxy.FQDN_IP
	(*Identity)(nil),              // 14: dnsproxy.Identity
	(*FQDNMapping)(nil),           // 15: dnsproxy.FQDNMapping
	(*SelectorUpdate)(nil),        // 16: dnsproxy.SelectorUpdate
	(*FQDNSelectorUpdate)(nil),    // 17: dnsproxy.FQDNSelectorUpdate
	(*FQDNSelector)(nil),          // 18: dnsproxy.FQDNSelector
	(*FQDNIdentityUpdate)(nil),    // 19: dnsproxy.FQDNIdentityUpdate
	(*Label)(nil),                 // 20: dnsproxy.Label
	(*Success)(nil),               // 21: dnsproxy.Success
	(*Endpoint)(nil),              // 22: dnsproxy.Endpoint
	(*Workload)(nil),              // 23: dnsproxy.Workload
	nil,                           // 24: dnsproxy.RestoredRulesMap.RulesEntry
	nil,                           // 25: dnsproxy.RestoredRules.RulesEntry
	nil,                           // 26: dnsproxy.L7Rules.SelectorRegexMappingEntry
	nil,                           // 27: dnsproxy.L7Rules.SelectorIdentitiesMappingEntry
	(*timestamppb.Timestamp)(nil), // 28: google.protobuf.Timestamp
}
var file_dnsproxy_dnsproxy_proto_depIdxs = []int32{
	24, // 0: dnsproxy.RestoredRulesMap.rules:type_name -> dnsproxy.RestoredRulesMap.RulesEntry
	25, // 1: dnsproxy.RestoredRules.rules:type_name -> dnsproxy.RestoredRules.RulesEntry
	5,  // 2: dnsproxy.IPRules.list:type_name -> dnsproxy.IPRule
	9,  // 3: dnsproxy.FQDNRules.rules:type_name -> dnsproxy.L7Rules
	26, // 4: dnsproxy.L7Rules.SelectorRegexMapping:type_name -> dnsproxy.L7Rules.SelectorRegexMappingEntry
	27, // 5: dnsproxy.L7Rules.SelectorIdentitiesMapping:type_name -> dnsproxy.L7Rules.SelectorIdentitiesMappingEntry
	28, // 6: dnsproxy.DNSNotification.time:type_name -> google.protobuf.Timestamp
	22, // 7: dnsproxy.DNSNotification.endpoint:type_name -> dnsproxy.Endpoint
	17, // 8: dnsproxy.SelectorUpdate.fqdnSelector:type_name -> dnsproxy.FQDNSelectorUpdate
	19, // 9: dnsproxy.SelectorUpdate.fqdnIdentity:type_name -> dnsproxy.FQDNIdentityUpdate
	1,  // 10: dnsproxy.FQDNSelectorUpdate.type:type_name -> dnsproxy.UpdateType
	18, // 11: dnsproxy.FQDNSelectorUpdate.selector:type_name -> dnsproxy.FQDNSelector
	1,  // 12: dnsproxy.FQDNIdentityUpdate.type:type_name -> dnsproxy.UpdateType
	20, // 13: dnsproxy.FQDNIdentityUpdate.labels:type_name -> dnsproxy.Label
	23, // 14: dnsproxy.Endpoint.workloads:type_name -> dnsproxy.Workload
	3,  // 15: dnsproxy.RestoredRulesMap.RulesEntry.value:type_name -> dnsproxy.RestoredRules
	4,  // 16: dnsproxy.RestoredRules.RulesEntry.value:type_name -> dnsproxy.IPRules
	10, // 17: dnsproxy.L7Rules.SelectorIdentitiesMappingEntry.value:type_name -> dnsproxy.IdentityList
	15, // 18: dnsproxy.FQDNProxyAgent.ProvideMappings:input_type -> dnsproxy.FQDNMapping
	13, // 19: dnsproxy.FQDNProxyAgent.LookupEndpointByIP:input_type -> dnsproxy.FQDN_IP
	13, // 20: dnsproxy.FQDNProxyAgent.LookupSecurityIdentityByIP:input_type -> dnsproxy.FQDN_IP
	14, // 21: dnsproxy.FQDNProxyAgent.LookupIPsBySecurityIdentity:input_type -> dnsproxy.Identity
	11, // 22: dnsproxy.FQDNProxyAgent.NotifyOnDNSMessage:input_type -> dnsproxy.DNSNotification
	7,  // 23: dnsproxy.FQDNProxyAgent.GetAllRules:input_type -> dnsproxy.Empty
	7,  // 24: dnsproxy.FQDNProxyAgent.SubscribeSelectors:input_type -> dnsproxy.Empty
	7,  // 25: dnsproxy.FQDNProxyAgent.SubscribeFQDNRules:input_type -> dnsproxy.Empty
	8,  // 26: dnsproxy.FQDNProxy.UpdateAllowed:input_type -> dnsproxy.FQDNRules
	6,  // 27: dnsproxy.FQDNProxy.RemoveRestoredRules:input_type -> dnsproxy.EndpointID
	6,  // 28: dnsproxy.FQDNProxy.GetRules:input_type -> dnsproxy.EndpointID
	21, // 29: dnsproxy.FQDNProxyAgent.ProvideMappings:output_type -> dnsproxy.Success
	22, // 30: dnsproxy.FQDNProxyAgent.LookupEndpointByIP:output_type -> dnsproxy.Endpoint
	14, // 31: dnsproxy.FQDNProxyAgent.LookupSecurityIdentityByIP:output_type -> dnsproxy.Identity
	12, // 32: dnsproxy.FQDNProxyAgent.LookupIPsBySecurityIdentity:output_type -> dnsproxy.IPs
	7,  // 33: dnsproxy.FQDNProxyAgent.NotifyOnDNSMessage:output_type -> dnsproxy.Empty
	2,  // 34: dnsproxy.FQDNProxyAgent.GetAllRules:output_type -> dnsproxy.RestoredRulesMap
	16, // 35: dnsproxy.FQDNProxyAgent.SubscribeSelectors:output_type -> dnsproxy.SelectorUpdate
	8,  // 36: dnsproxy.FQDNProxyAgent.SubscribeFQDNRules:output_type -> dnsproxy.FQDNRules
	7,  // 37: dnsproxy.FQDNProxy.UpdateAllowed:output_type -> dnsproxy.Empty
	7,  // 38: dnsproxy.FQDNProxy.RemoveRestoredRules:output_type -> dnsproxy.Empty
	3,  // 39: dnsproxy.FQDNProxy.GetRules:output_type -> dnsproxy.RestoredRules
	29, // [29:40] is the sub-list for method output_type
	18, // [18:29] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_dnsproxy_dnsproxy_proto_init() }
func file_dnsproxy_dnsproxy_proto_init() {
	if File_dnsproxy_dnsproxy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dnsproxy_dnsproxy_proto_rawDesc), len(file_dnsproxy_dnsproxy_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_dnsproxy_dnsproxy_proto_goTypes,
		DependencyIndexes: file_dnsproxy_dnsproxy_proto_depIdxs,
		EnumInfos:         file_dnsproxy_dnsproxy_proto_enumTypes,
		MessageInfos:      file_dnsproxy_dnsproxy_proto_msgTypes,
	}.Build()
	File_dnsproxy_dnsproxy_proto = out.File
	file_dnsproxy_dnsproxy_proto_goTypes = nil
	file_dnsproxy_dnsproxy_proto_depIdxs = nil
}
