//  Copyright (C) Isovalent, Inc. - All Rights Reserved.
//
//  NOTICE: All information contained herein is, and remains the property of
//  Isovalent Inc and its suppliers, if any. The intellectual and technical
//  concepts contained herein are proprietary to Isovalent Inc and its suppliers
//  and may be covered by U.S. and Foreign Patents, patents in process, and are
//  protected by trade secret or copyright law.  Dissemination of this information
//  or reproduction of this material is strictly forbidden unless prior written
//  permission is obtained from Isovalent Inc.
//

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: dnsproxy/dnsproxy.proto

package dnsproxy

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FQDNProxyAgent_ProvideMappings_FullMethodName             = "/dnsproxy.FQDNProxyAgent/ProvideMappings"
	FQDNProxyAgent_LookupEndpointByIP_FullMethodName          = "/dnsproxy.FQDNProxyAgent/LookupEndpointByIP"
	FQDNProxyAgent_LookupSecurityIdentityByIP_FullMethodName  = "/dnsproxy.FQDNProxyAgent/LookupSecurityIdentityByIP"
	FQDNProxyAgent_LookupIPsBySecurityIdentity_FullMethodName = "/dnsproxy.FQDNProxyAgent/LookupIPsBySecurityIdentity"
	FQDNProxyAgent_NotifyOnDNSMessage_FullMethodName          = "/dnsproxy.FQDNProxyAgent/NotifyOnDNSMessage"
	FQDNProxyAgent_GetAllRules_FullMethodName                 = "/dnsproxy.FQDNProxyAgent/GetAllRules"
	FQDNProxyAgent_SubscribeSelectors_FullMethodName          = "/dnsproxy.FQDNProxyAgent/SubscribeSelectors"
	FQDNProxyAgent_SubscribeFQDNRules_FullMethodName          = "/dnsproxy.FQDNProxyAgent/SubscribeFQDNRules"
	FQDNProxyAgent_SubscribeState_FullMethodName              = "/dnsproxy.FQDNProxyAgent/SubscribeState"
)

// FQDNProxyAgentClient is the client API for FQDNProxyAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FQDNProxyAgentClient interface {
	// A client-to-server streaming RPC.
	//
	// Accepts a stream of FQDNMapping
	ProvideMappings(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[FQDNMapping, Success], error)
	// LookupEndpointByIP returns endpoint data based on IP
	LookupEndpointByIP(ctx context.Context, in *FQDN_IP, opts ...grpc.CallOption) (*Endpoint, error)
	// LookupEndpointByIP returns endpoint data based on IP
	LookupSecurityIdentityByIP(ctx context.Context, in *FQDN_IP, opts ...grpc.CallOption) (*Identity, error)
	// LookupIPsBySecurityIdentity retrieves ips for endpoints with given security identity
	LookupIPsBySecurityIdentity(ctx context.Context, in *Identity, opts ...grpc.CallOption) (*IPs, error)
	// NotifyOnDNSMessage notifies Agent of a DNS message
	NotifyOnDNSMessage(ctx context.Context, in *DNSNotification, opts ...grpc.CallOption) (*Empty, error)
	// GetAllRules retrieves all FQDN rules from agent proxy
	GetAllRules(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*RestoredRulesMap, error)
	// Returns a stream of FQDN selector and identity updates.
	SubscribeSelectors(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SelectorUpdate], error)
	// Returns a stream of FQDNRules from the agent to the proxy
	// Proxy should write an Empty response to ack receipt of the rule.
	// Added: v1.18-ce.
	SubscribeFQDNRules(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Empty, FQDNRules], error)
	// SubscribeState creates a bidirectional stream for the agent and remote proxy
	// to exchange state information.
	SubscribeState(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[RemoteProxyState, AgentState], error)
}

type fQDNProxyAgentClient struct {
	cc grpc.ClientConnInterface
}

func NewFQDNProxyAgentClient(cc grpc.ClientConnInterface) FQDNProxyAgentClient {
	return &fQDNProxyAgentClient{cc}
}

func (c *fQDNProxyAgentClient) ProvideMappings(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[FQDNMapping, Success], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FQDNProxyAgent_ServiceDesc.Streams[0], FQDNProxyAgent_ProvideMappings_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FQDNMapping, Success]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FQDNProxyAgent_ProvideMappingsClient = grpc.ClientStreamingClient[FQDNMapping, Success]

func (c *fQDNProxyAgentClient) LookupEndpointByIP(ctx context.Context, in *FQDN_IP, opts ...grpc.CallOption) (*Endpoint, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Endpoint)
	err := c.cc.Invoke(ctx, FQDNProxyAgent_LookupEndpointByIP_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fQDNProxyAgentClient) LookupSecurityIdentityByIP(ctx context.Context, in *FQDN_IP, opts ...grpc.CallOption) (*Identity, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Identity)
	err := c.cc.Invoke(ctx, FQDNProxyAgent_LookupSecurityIdentityByIP_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fQDNProxyAgentClient) LookupIPsBySecurityIdentity(ctx context.Context, in *Identity, opts ...grpc.CallOption) (*IPs, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IPs)
	err := c.cc.Invoke(ctx, FQDNProxyAgent_LookupIPsBySecurityIdentity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fQDNProxyAgentClient) NotifyOnDNSMessage(ctx context.Context, in *DNSNotification, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, FQDNProxyAgent_NotifyOnDNSMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fQDNProxyAgentClient) GetAllRules(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*RestoredRulesMap, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RestoredRulesMap)
	err := c.cc.Invoke(ctx, FQDNProxyAgent_GetAllRules_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fQDNProxyAgentClient) SubscribeSelectors(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SelectorUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FQDNProxyAgent_ServiceDesc.Streams[1], FQDNProxyAgent_SubscribeSelectors_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Empty, SelectorUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FQDNProxyAgent_SubscribeSelectorsClient = grpc.ServerStreamingClient[SelectorUpdate]

func (c *fQDNProxyAgentClient) SubscribeFQDNRules(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Empty, FQDNRules], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FQDNProxyAgent_ServiceDesc.Streams[2], FQDNProxyAgent_SubscribeFQDNRules_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Empty, FQDNRules]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FQDNProxyAgent_SubscribeFQDNRulesClient = grpc.BidiStreamingClient[Empty, FQDNRules]

func (c *fQDNProxyAgentClient) SubscribeState(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[RemoteProxyState, AgentState], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FQDNProxyAgent_ServiceDesc.Streams[3], FQDNProxyAgent_SubscribeState_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RemoteProxyState, AgentState]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FQDNProxyAgent_SubscribeStateClient = grpc.BidiStreamingClient[RemoteProxyState, AgentState]

// FQDNProxyAgentServer is the server API for FQDNProxyAgent service.
// All implementations must embed UnimplementedFQDNProxyAgentServer
// for forward compatibility.
type FQDNProxyAgentServer interface {
	// A client-to-server streaming RPC.
	//
	// Accepts a stream of FQDNMapping
	ProvideMappings(grpc.ClientStreamingServer[FQDNMapping, Success]) error
	// LookupEndpointByIP returns endpoint data based on IP
	LookupEndpointByIP(context.Context, *FQDN_IP) (*Endpoint, error)
	// LookupEndpointByIP returns endpoint data based on IP
	LookupSecurityIdentityByIP(context.Context, *FQDN_IP) (*Identity, error)
	// LookupIPsBySecurityIdentity retrieves ips for endpoints with given security identity
	LookupIPsBySecurityIdentity(context.Context, *Identity) (*IPs, error)
	// NotifyOnDNSMessage notifies Agent of a DNS message
	NotifyOnDNSMessage(context.Context, *DNSNotification) (*Empty, error)
	// GetAllRules retrieves all FQDN rules from agent proxy
	GetAllRules(context.Context, *Empty) (*RestoredRulesMap, error)
	// Returns a stream of FQDN selector and identity updates.
	SubscribeSelectors(*Empty, grpc.ServerStreamingServer[SelectorUpdate]) error
	// Returns a stream of FQDNRules from the agent to the proxy
	// Proxy should write an Empty response to ack receipt of the rule.
	// Added: v1.18-ce.
	SubscribeFQDNRules(grpc.BidiStreamingServer[Empty, FQDNRules]) error
	// SubscribeState creates a bidirectional stream for the agent and remote proxy
	// to exchange state information.
	SubscribeState(grpc.BidiStreamingServer[RemoteProxyState, AgentState]) error
	mustEmbedUnimplementedFQDNProxyAgentServer()
}

// UnimplementedFQDNProxyAgentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFQDNProxyAgentServer struct{}

func (UnimplementedFQDNProxyAgentServer) ProvideMappings(grpc.ClientStreamingServer[FQDNMapping, Success]) error {
	return status.Errorf(codes.Unimplemented, "method ProvideMappings not implemented")
}
func (UnimplementedFQDNProxyAgentServer) LookupEndpointByIP(context.Context, *FQDN_IP) (*Endpoint, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LookupEndpointByIP not implemented")
}
func (UnimplementedFQDNProxyAgentServer) LookupSecurityIdentityByIP(context.Context, *FQDN_IP) (*Identity, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LookupSecurityIdentityByIP not implemented")
}
func (UnimplementedFQDNProxyAgentServer) LookupIPsBySecurityIdentity(context.Context, *Identity) (*IPs, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LookupIPsBySecurityIdentity not implemented")
}
func (UnimplementedFQDNProxyAgentServer) NotifyOnDNSMessage(context.Context, *DNSNotification) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NotifyOnDNSMessage not implemented")
}
func (UnimplementedFQDNProxyAgentServer) GetAllRules(context.Context, *Empty) (*RestoredRulesMap, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllRules not implemented")
}
func (UnimplementedFQDNProxyAgentServer) SubscribeSelectors(*Empty, grpc.ServerStreamingServer[SelectorUpdate]) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeSelectors not implemented")
}
func (UnimplementedFQDNProxyAgentServer) SubscribeFQDNRules(grpc.BidiStreamingServer[Empty, FQDNRules]) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeFQDNRules not implemented")
}
func (UnimplementedFQDNProxyAgentServer) SubscribeState(grpc.BidiStreamingServer[RemoteProxyState, AgentState]) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeState not implemented")
}
func (UnimplementedFQDNProxyAgentServer) mustEmbedUnimplementedFQDNProxyAgentServer() {}
func (UnimplementedFQDNProxyAgentServer) testEmbeddedByValue()                        {}

// UnsafeFQDNProxyAgentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FQDNProxyAgentServer will
// result in compilation errors.
type UnsafeFQDNProxyAgentServer interface {
	mustEmbedUnimplementedFQDNProxyAgentServer()
}

func RegisterFQDNProxyAgentServer(s grpc.ServiceRegistrar, srv FQDNProxyAgentServer) {
	// If the following call pancis, it indicates UnimplementedFQDNProxyAgentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FQDNProxyAgent_ServiceDesc, srv)
}

func _FQDNProxyAgent_ProvideMappings_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FQDNProxyAgentServer).ProvideMappings(&grpc.GenericServerStream[FQDNMapping, Success]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FQDNProxyAgent_ProvideMappingsServer = grpc.ClientStreamingServer[FQDNMapping, Success]

func _FQDNProxyAgent_LookupEndpointByIP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FQDN_IP)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FQDNProxyAgentServer).LookupEndpointByIP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FQDNProxyAgent_LookupEndpointByIP_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FQDNProxyAgentServer).LookupEndpointByIP(ctx, req.(*FQDN_IP))
	}
	return interceptor(ctx, in, info, handler)
}

func _FQDNProxyAgent_LookupSecurityIdentityByIP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FQDN_IP)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FQDNProxyAgentServer).LookupSecurityIdentityByIP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FQDNProxyAgent_LookupSecurityIdentityByIP_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FQDNProxyAgentServer).LookupSecurityIdentityByIP(ctx, req.(*FQDN_IP))
	}
	return interceptor(ctx, in, info, handler)
}

func _FQDNProxyAgent_LookupIPsBySecurityIdentity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Identity)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FQDNProxyAgentServer).LookupIPsBySecurityIdentity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FQDNProxyAgent_LookupIPsBySecurityIdentity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FQDNProxyAgentServer).LookupIPsBySecurityIdentity(ctx, req.(*Identity))
	}
	return interceptor(ctx, in, info, handler)
}

func _FQDNProxyAgent_NotifyOnDNSMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DNSNotification)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FQDNProxyAgentServer).NotifyOnDNSMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FQDNProxyAgent_NotifyOnDNSMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FQDNProxyAgentServer).NotifyOnDNSMessage(ctx, req.(*DNSNotification))
	}
	return interceptor(ctx, in, info, handler)
}

func _FQDNProxyAgent_GetAllRules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FQDNProxyAgentServer).GetAllRules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FQDNProxyAgent_GetAllRules_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FQDNProxyAgentServer).GetAllRules(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _FQDNProxyAgent_SubscribeSelectors_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FQDNProxyAgentServer).SubscribeSelectors(m, &grpc.GenericServerStream[Empty, SelectorUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FQDNProxyAgent_SubscribeSelectorsServer = grpc.ServerStreamingServer[SelectorUpdate]

func _FQDNProxyAgent_SubscribeFQDNRules_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FQDNProxyAgentServer).SubscribeFQDNRules(&grpc.GenericServerStream[Empty, FQDNRules]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FQDNProxyAgent_SubscribeFQDNRulesServer = grpc.BidiStreamingServer[Empty, FQDNRules]

func _FQDNProxyAgent_SubscribeState_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FQDNProxyAgentServer).SubscribeState(&grpc.GenericServerStream[RemoteProxyState, AgentState]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FQDNProxyAgent_SubscribeStateServer = grpc.BidiStreamingServer[RemoteProxyState, AgentState]

// FQDNProxyAgent_ServiceDesc is the grpc.ServiceDesc for FQDNProxyAgent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FQDNProxyAgent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dnsproxy.FQDNProxyAgent",
	HandlerType: (*FQDNProxyAgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LookupEndpointByIP",
			Handler:    _FQDNProxyAgent_LookupEndpointByIP_Handler,
		},
		{
			MethodName: "LookupSecurityIdentityByIP",
			Handler:    _FQDNProxyAgent_LookupSecurityIdentityByIP_Handler,
		},
		{
			MethodName: "LookupIPsBySecurityIdentity",
			Handler:    _FQDNProxyAgent_LookupIPsBySecurityIdentity_Handler,
		},
		{
			MethodName: "NotifyOnDNSMessage",
			Handler:    _FQDNProxyAgent_NotifyOnDNSMessage_Handler,
		},
		{
			MethodName: "GetAllRules",
			Handler:    _FQDNProxyAgent_GetAllRules_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ProvideMappings",
			Handler:       _FQDNProxyAgent_ProvideMappings_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "SubscribeSelectors",
			Handler:       _FQDNProxyAgent_SubscribeSelectors_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SubscribeFQDNRules",
			Handler:       _FQDNProxyAgent_SubscribeFQDNRules_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "SubscribeState",
			Handler:       _FQDNProxyAgent_SubscribeState_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "dnsproxy/dnsproxy.proto",
}

const (
	FQDNProxy_UpdateAllowed_FullMethodName       = "/dnsproxy.FQDNProxy/UpdateAllowed"
	FQDNProxy_RemoveRestoredRules_FullMethodName = "/dnsproxy.FQDNProxy/RemoveRestoredRules"
	FQDNProxy_GetRules_FullMethodName            = "/dnsproxy.FQDNProxy/GetRules"
)

// FQDNProxyClient is the client API for FQDNProxy service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FQDNProxyClient interface {
	UpdateAllowed(ctx context.Context, in *FQDNRules, opts ...grpc.CallOption) (*Empty, error)
	RemoveRestoredRules(ctx context.Context, in *EndpointID, opts ...grpc.CallOption) (*Empty, error)
	GetRules(ctx context.Context, in *EndpointID, opts ...grpc.CallOption) (*RestoredRules, error)
}

type fQDNProxyClient struct {
	cc grpc.ClientConnInterface
}

func NewFQDNProxyClient(cc grpc.ClientConnInterface) FQDNProxyClient {
	return &fQDNProxyClient{cc}
}

func (c *fQDNProxyClient) UpdateAllowed(ctx context.Context, in *FQDNRules, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, FQDNProxy_UpdateAllowed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fQDNProxyClient) RemoveRestoredRules(ctx context.Context, in *EndpointID, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, FQDNProxy_RemoveRestoredRules_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fQDNProxyClient) GetRules(ctx context.Context, in *EndpointID, opts ...grpc.CallOption) (*RestoredRules, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RestoredRules)
	err := c.cc.Invoke(ctx, FQDNProxy_GetRules_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FQDNProxyServer is the server API for FQDNProxy service.
// All implementations must embed UnimplementedFQDNProxyServer
// for forward compatibility.
type FQDNProxyServer interface {
	UpdateAllowed(context.Context, *FQDNRules) (*Empty, error)
	RemoveRestoredRules(context.Context, *EndpointID) (*Empty, error)
	GetRules(context.Context, *EndpointID) (*RestoredRules, error)
	mustEmbedUnimplementedFQDNProxyServer()
}

// UnimplementedFQDNProxyServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFQDNProxyServer struct{}

func (UnimplementedFQDNProxyServer) UpdateAllowed(context.Context, *FQDNRules) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAllowed not implemented")
}
func (UnimplementedFQDNProxyServer) RemoveRestoredRules(context.Context, *EndpointID) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveRestoredRules not implemented")
}
func (UnimplementedFQDNProxyServer) GetRules(context.Context, *EndpointID) (*RestoredRules, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRules not implemented")
}
func (UnimplementedFQDNProxyServer) mustEmbedUnimplementedFQDNProxyServer() {}
func (UnimplementedFQDNProxyServer) testEmbeddedByValue()                   {}

// UnsafeFQDNProxyServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FQDNProxyServer will
// result in compilation errors.
type UnsafeFQDNProxyServer interface {
	mustEmbedUnimplementedFQDNProxyServer()
}

func RegisterFQDNProxyServer(s grpc.ServiceRegistrar, srv FQDNProxyServer) {
	// If the following call pancis, it indicates UnimplementedFQDNProxyServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FQDNProxy_ServiceDesc, srv)
}

func _FQDNProxy_UpdateAllowed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FQDNRules)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FQDNProxyServer).UpdateAllowed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FQDNProxy_UpdateAllowed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FQDNProxyServer).UpdateAllowed(ctx, req.(*FQDNRules))
	}
	return interceptor(ctx, in, info, handler)
}

func _FQDNProxy_RemoveRestoredRules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EndpointID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FQDNProxyServer).RemoveRestoredRules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FQDNProxy_RemoveRestoredRules_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FQDNProxyServer).RemoveRestoredRules(ctx, req.(*EndpointID))
	}
	return interceptor(ctx, in, info, handler)
}

func _FQDNProxy_GetRules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EndpointID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FQDNProxyServer).GetRules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FQDNProxy_GetRules_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FQDNProxyServer).GetRules(ctx, req.(*EndpointID))
	}
	return interceptor(ctx, in, info, handler)
}

// FQDNProxy_ServiceDesc is the grpc.ServiceDesc for FQDNProxy service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FQDNProxy_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dnsproxy.FQDNProxy",
	HandlerType: (*FQDNProxyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateAllowed",
			Handler:    _FQDNProxy_UpdateAllowed_Handler,
		},
		{
			MethodName: "RemoveRestoredRules",
			Handler:    _FQDNProxy_RemoveRestoredRules_Handler,
		},
		{
			MethodName: "GetRules",
			Handler:    _FQDNProxy_GetRules_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dnsproxy/dnsproxy.proto",
}
