// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v2 "github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2"
	ciliumiov2 "github.com/cilium/cilium/pkg/k8s/client/clientset/versioned/typed/cilium.io/v2"
	gentype "k8s.io/client-go/gentype"
)

// fakeCiliumVRFs implements CiliumVRFInterface
type fakeCiliumVRFs struct {
	*gentype.FakeClientWithList[*v2.CiliumVRF, *v2.CiliumVRFList]
	Fake *FakeCiliumV2
}

func newFakeCiliumVRFs(fake *FakeCiliumV2) ciliumiov2.CiliumVRFInterface {
	return &fakeCiliumVRFs{
		gentype.NewFakeClientWithList[*v2.CiliumVRF, *v2.CiliumVRFList](
			fake.Fake,
			"",
			v2.SchemeGroupVersion.WithResource("ciliumvrfs"),
			v2.SchemeGroupVersion.WithKind("CiliumVRF"),
			func() *v2.CiliumVRF { return &v2.CiliumVRF{} },
			func() *v2.CiliumVRFList { return &v2.CiliumVRFList{} },
			func(dst, src *v2.CiliumVRFList) { dst.ListMeta = src.ListMeta },
			func(list *v2.CiliumVRFList) []*v2.CiliumVRF { return gentype.ToPointerSlice(list.Items) },
			func(list *v2.CiliumVRFList, items []*v2.CiliumVRF) { list.Items = gentype.FromPointerSlice(items) },
		),
		fake,
	}
}
