// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	isovalentcomv1alpha1 "github.com/cilium/cilium/pkg/k8s/apis/isovalent.com/v1alpha1"
)

// BFDEchoFunctionConfigApplyConfiguration represents a declarative configuration of the BFDEchoFunctionConfig type for use
// with apply.
type BFDEchoFunctionConfigApplyConfiguration struct {
	Directions                   []isovalentcomv1alpha1.BFDEchoFunctionDirection `json:"directions,omitempty"`
	ReceiveIntervalMilliseconds  *int32                                          `json:"receiveIntervalMilliseconds,omitempty"`
	TransmitIntervalMilliseconds *int32                                          `json:"transmitIntervalMilliseconds,omitempty"`
}

// BFDEchoFunctionConfigApplyConfiguration constructs a declarative configuration of the BFDEchoFunctionConfig type for use with
// apply.
func BFDEchoFunctionConfig() *BFDEchoFunctionConfigApplyConfiguration {
	return &BFDEchoFunctionConfigApplyConfiguration{}
}

// WithDirections adds the given value to the Directions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Directions field.
func (b *BFDEchoFunctionConfigApplyConfiguration) WithDirections(values ...isovalentcomv1alpha1.BFDEchoFunctionDirection) *BFDEchoFunctionConfigApplyConfiguration {
	for i := range values {
		b.Directions = append(b.Directions, values[i])
	}
	return b
}

// WithReceiveIntervalMilliseconds sets the ReceiveIntervalMilliseconds field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ReceiveIntervalMilliseconds field is set to the value of the last call.
func (b *BFDEchoFunctionConfigApplyConfiguration) WithReceiveIntervalMilliseconds(value int32) *BFDEchoFunctionConfigApplyConfiguration {
	b.ReceiveIntervalMilliseconds = &value
	return b
}

// WithTransmitIntervalMilliseconds sets the TransmitIntervalMilliseconds field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TransmitIntervalMilliseconds field is set to the value of the last call.
func (b *BFDEchoFunctionConfigApplyConfiguration) WithTransmitIntervalMilliseconds(value int32) *BFDEchoFunctionConfigApplyConfiguration {
	b.TransmitIntervalMilliseconds = &value
	return b
}
