// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	isovalentcomv1alpha1 "github.com/cilium/cilium/pkg/k8s/apis/isovalent.com/v1alpha1"
)

// HealthCheckHTTPApplyConfiguration represents a declarative configuration of the HealthCheckHTTP type for use
// with apply.
type HealthCheckHTTPApplyConfiguration struct {
	Host               *string                                            `json:"host,omitempty"`
	Path               *string                                            `json:"path,omitempty"`
	Method             *isovalentcomv1alpha1.HealthCheckHTTPMethod        `json:"method,omitempty"`
	HealthyStatusCodes []*isovalentcomv1alpha1.HealthCheckHTTPStatusRange `json:"healthyStatusCodes,omitempty"`
	Send               *HealthCheckPayloadApplyConfiguration              `json:"send,omitempty"`
	Receive            []*isovalentcomv1alpha1.HealthCheckPayload         `json:"receive,omitempty"`
}

// HealthCheckHTTPApplyConfiguration constructs a declarative configuration of the HealthCheckHTTP type for use with
// apply.
func HealthCheckHTTP() *HealthCheckHTTPApplyConfiguration {
	return &HealthCheckHTTPApplyConfiguration{}
}

// WithHost sets the Host field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Host field is set to the value of the last call.
func (b *HealthCheckHTTPApplyConfiguration) WithHost(value string) *HealthCheckHTTPApplyConfiguration {
	b.Host = &value
	return b
}

// WithPath sets the Path field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Path field is set to the value of the last call.
func (b *HealthCheckHTTPApplyConfiguration) WithPath(value string) *HealthCheckHTTPApplyConfiguration {
	b.Path = &value
	return b
}

// WithMethod sets the Method field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Method field is set to the value of the last call.
func (b *HealthCheckHTTPApplyConfiguration) WithMethod(value isovalentcomv1alpha1.HealthCheckHTTPMethod) *HealthCheckHTTPApplyConfiguration {
	b.Method = &value
	return b
}

// WithHealthyStatusCodes adds the given value to the HealthyStatusCodes field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the HealthyStatusCodes field.
func (b *HealthCheckHTTPApplyConfiguration) WithHealthyStatusCodes(values ...**isovalentcomv1alpha1.HealthCheckHTTPStatusRange) *HealthCheckHTTPApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithHealthyStatusCodes")
		}
		b.HealthyStatusCodes = append(b.HealthyStatusCodes, *values[i])
	}
	return b
}

// WithSend sets the Send field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Send field is set to the value of the last call.
func (b *HealthCheckHTTPApplyConfiguration) WithSend(value *HealthCheckPayloadApplyConfiguration) *HealthCheckHTTPApplyConfiguration {
	b.Send = value
	return b
}

// WithReceive adds the given value to the Receive field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Receive field.
func (b *HealthCheckHTTPApplyConfiguration) WithReceive(values ...**isovalentcomv1alpha1.HealthCheckPayload) *HealthCheckHTTPApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithReceive")
		}
		b.Receive = append(b.Receive, *values[i])
	}
	return b
}
