// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// IsovalentMulticastNodeSpecApplyConfiguration represents a declarative configuration of the IsovalentMulticastNodeSpec type for use
// with apply.
type IsovalentMulticastNodeSpecApplyConfiguration struct {
	NodeIP *string `json:"nodeIP,omitempty"`
}

// IsovalentMulticastNodeSpecApplyConfiguration constructs a declarative configuration of the IsovalentMulticastNodeSpec type for use with
// apply.
func IsovalentMulticastNodeSpec() *IsovalentMulticastNodeSpecApplyConfiguration {
	return &IsovalentMulticastNodeSpecApplyConfiguration{}
}

// WithNodeIP sets the NodeIP field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NodeIP field is set to the value of the last call.
func (b *IsovalentMulticastNodeSpecApplyConfiguration) WithNodeIP(value string) *IsovalentMulticastNodeSpecApplyConfiguration {
	b.NodeIP = &value
	return b
}
