// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// IsovalentBGPNodePeerApplyConfiguration represents a declarative configuration of the IsovalentBGPNodePeer type for use
// with apply.
type IsovalentBGPNodePeerApplyConfiguration struct {
	Name          *string                                `json:"name,omitempty"`
	PeerAddress   *string                                `json:"peerAddress,omitempty"`
	PeerASN       *int64                                 `json:"peerASN,omitempty"`
	AutoDiscovery *BGPAutoDiscoveryApplyConfiguration    `json:"autoDiscovery,omitempty"`
	LocalAddress  *string                                `json:"localAddress,omitempty"`
	PeerConfigRef *PeerConfigReferenceApplyConfiguration `json:"peerConfigRef,omitempty"`
}

// IsovalentBGPNodePeerApplyConfiguration constructs a declarative configuration of the IsovalentBGPNodePeer type for use with
// apply.
func IsovalentBGPNodePeer() *IsovalentBGPNodePeerApplyConfiguration {
	return &IsovalentBGPNodePeerApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *IsovalentBGPNodePeerApplyConfiguration) WithName(value string) *IsovalentBGPNodePeerApplyConfiguration {
	b.Name = &value
	return b
}

// WithPeerAddress sets the PeerAddress field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PeerAddress field is set to the value of the last call.
func (b *IsovalentBGPNodePeerApplyConfiguration) WithPeerAddress(value string) *IsovalentBGPNodePeerApplyConfiguration {
	b.PeerAddress = &value
	return b
}

// WithPeerASN sets the PeerASN field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PeerASN field is set to the value of the last call.
func (b *IsovalentBGPNodePeerApplyConfiguration) WithPeerASN(value int64) *IsovalentBGPNodePeerApplyConfiguration {
	b.PeerASN = &value
	return b
}

// WithAutoDiscovery sets the AutoDiscovery field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AutoDiscovery field is set to the value of the last call.
func (b *IsovalentBGPNodePeerApplyConfiguration) WithAutoDiscovery(value *BGPAutoDiscoveryApplyConfiguration) *IsovalentBGPNodePeerApplyConfiguration {
	b.AutoDiscovery = value
	return b
}

// WithLocalAddress sets the LocalAddress field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LocalAddress field is set to the value of the last call.
func (b *IsovalentBGPNodePeerApplyConfiguration) WithLocalAddress(value string) *IsovalentBGPNodePeerApplyConfiguration {
	b.LocalAddress = &value
	return b
}

// WithPeerConfigRef sets the PeerConfigRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PeerConfigRef field is set to the value of the last call.
func (b *IsovalentBGPNodePeerApplyConfiguration) WithPeerConfigRef(value *PeerConfigReferenceApplyConfiguration) *IsovalentBGPNodePeerApplyConfiguration {
	b.PeerConfigRef = value
	return b
}
