// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	isovalentcomv1alpha1 "github.com/cilium/cilium/pkg/k8s/apis/isovalent.com/v1alpha1"
)

// IsovalentMulticastGroupSpecApplyConfiguration represents a declarative configuration of the IsovalentMulticastGroupSpec type for use
// with apply.
type IsovalentMulticastGroupSpecApplyConfiguration struct {
	GroupAddrs []isovalentcomv1alpha1.MulticastGroupAddr `json:"groupAddrs,omitempty"`
}

// IsovalentMulticastGroupSpecApplyConfiguration constructs a declarative configuration of the IsovalentMulticastGroupSpec type for use with
// apply.
func IsovalentMulticastGroupSpec() *IsovalentMulticastGroupSpecApplyConfiguration {
	return &IsovalentMulticastGroupSpecApplyConfiguration{}
}

// WithGroupAddrs adds the given value to the GroupAddrs field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the GroupAddrs field.
func (b *IsovalentMulticastGroupSpecApplyConfiguration) WithGroupAddrs(values ...isovalentcomv1alpha1.MulticastGroupAddr) *IsovalentMulticastGroupSpecApplyConfiguration {
	for i := range values {
		b.GroupAddrs = append(b.GroupAddrs, values[i])
	}
	return b
}
