// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// IsovalentSRv6LocatorApplyConfiguration represents a declarative configuration of the IsovalentSRv6Locator type for use
// with apply.
type IsovalentSRv6LocatorApplyConfiguration struct {
	Prefix       *string                                      `json:"prefix,omitempty"`
	Structure    *IsovalentSRv6SIDStructureApplyConfiguration `json:"structure,omitempty"`
	BehaviorType *string                                      `json:"behaviorType,omitempty"`
}

// IsovalentSRv6LocatorApplyConfiguration constructs a declarative configuration of the IsovalentSRv6Locator type for use with
// apply.
func IsovalentSRv6Locator() *IsovalentSRv6LocatorApplyConfiguration {
	return &IsovalentSRv6LocatorApplyConfiguration{}
}

// WithPrefix sets the Prefix field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Prefix field is set to the value of the last call.
func (b *IsovalentSRv6LocatorApplyConfiguration) WithPrefix(value string) *IsovalentSRv6LocatorApplyConfiguration {
	b.Prefix = &value
	return b
}

// WithStructure sets the Structure field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Structure field is set to the value of the last call.
func (b *IsovalentSRv6LocatorApplyConfiguration) WithStructure(value *IsovalentSRv6SIDStructureApplyConfiguration) *IsovalentSRv6LocatorApplyConfiguration {
	b.Structure = value
	return b
}

// WithBehaviorType sets the BehaviorType field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BehaviorType field is set to the value of the last call.
func (b *IsovalentSRv6LocatorApplyConfiguration) WithBehaviorType(value string) *IsovalentSRv6LocatorApplyConfiguration {
	b.BehaviorType = &value
	return b
}
