// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// IsovalentSRv6SIDStructureApplyConfiguration represents a declarative configuration of the IsovalentSRv6SIDStructure type for use
// with apply.
type IsovalentSRv6SIDStructureApplyConfiguration struct {
	LocatorBlockLenBits *byte `json:"locatorBlockLenBits,omitempty"`
	LocatorNodeLenBits  *byte `json:"locatorNodeLenBits,omitempty"`
	FunctionLenBits     *byte `json:"functionLenBits,omitempty"`
	ArgumentLenBits     *byte `json:"argumentLenBits,omitempty"`
}

// IsovalentSRv6SIDStructureApplyConfiguration constructs a declarative configuration of the IsovalentSRv6SIDStructure type for use with
// apply.
func IsovalentSRv6SIDStructure() *IsovalentSRv6SIDStructureApplyConfiguration {
	return &IsovalentSRv6SIDStructureApplyConfiguration{}
}

// WithLocatorBlockLenBits sets the LocatorBlockLenBits field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LocatorBlockLenBits field is set to the value of the last call.
func (b *IsovalentSRv6SIDStructureApplyConfiguration) WithLocatorBlockLenBits(value byte) *IsovalentSRv6SIDStructureApplyConfiguration {
	b.LocatorBlockLenBits = &value
	return b
}

// WithLocatorNodeLenBits sets the LocatorNodeLenBits field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LocatorNodeLenBits field is set to the value of the last call.
func (b *IsovalentSRv6SIDStructureApplyConfiguration) WithLocatorNodeLenBits(value byte) *IsovalentSRv6SIDStructureApplyConfiguration {
	b.LocatorNodeLenBits = &value
	return b
}

// WithFunctionLenBits sets the FunctionLenBits field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FunctionLenBits field is set to the value of the last call.
func (b *IsovalentSRv6SIDStructureApplyConfiguration) WithFunctionLenBits(value byte) *IsovalentSRv6SIDStructureApplyConfiguration {
	b.FunctionLenBits = &value
	return b
}

// WithArgumentLenBits sets the ArgumentLenBits field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ArgumentLenBits field is set to the value of the last call.
func (b *IsovalentSRv6SIDStructureApplyConfiguration) WithArgumentLenBits(value byte) *IsovalentSRv6SIDStructureApplyConfiguration {
	b.ArgumentLenBits = &value
	return b
}
