// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	isovalentcomv1alpha1 "github.com/cilium/cilium/pkg/k8s/apis/isovalent.com/v1alpha1"
)

// IsovalentVRFRuleApplyConfiguration represents a declarative configuration of the IsovalentVRFRule type for use
// with apply.
type IsovalentVRFRuleApplyConfiguration struct {
	Selectors        []IsovalentVRFEgressRuleApplyConfiguration `json:"selectors,omitempty"`
	DestinationCIDRs []isovalentcomv1alpha1.CIDR                `json:"destinationCIDRs,omitempty"`
}

// IsovalentVRFRuleApplyConfiguration constructs a declarative configuration of the IsovalentVRFRule type for use with
// apply.
func IsovalentVRFRule() *IsovalentVRFRuleApplyConfiguration {
	return &IsovalentVRFRuleApplyConfiguration{}
}

// WithSelectors adds the given value to the Selectors field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Selectors field.
func (b *IsovalentVRFRuleApplyConfiguration) WithSelectors(values ...*IsovalentVRFEgressRuleApplyConfiguration) *IsovalentVRFRuleApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithSelectors")
		}
		b.Selectors = append(b.Selectors, *values[i])
	}
	return b
}

// WithDestinationCIDRs adds the given value to the DestinationCIDRs field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the DestinationCIDRs field.
func (b *IsovalentVRFRuleApplyConfiguration) WithDestinationCIDRs(values ...isovalentcomv1alpha1.CIDR) *IsovalentVRFRuleApplyConfiguration {
	for i := range values {
		b.DestinationCIDRs = append(b.DestinationCIDRs, values[i])
	}
	return b
}
