// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// LBServiceSecretRefApplyConfiguration represents a declarative configuration of the LBServiceSecretRef type for use
// with apply.
type LBServiceSecretRefApplyConfiguration struct {
	Name *string `json:"name,omitempty"`
}

// LBServiceSecretRefApplyConfiguration constructs a declarative configuration of the LBServiceSecretRef type for use with
// apply.
func LBServiceSecretRef() *LBServiceSecretRefApplyConfiguration {
	return &LBServiceSecretRefApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *LBServiceSecretRefApplyConfiguration) WithName(value string) *LBServiceSecretRefApplyConfiguration {
	b.Name = &value
	return b
}
