// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// LBServiceRequestFilteringRuleTLSServernameApplyConfiguration represents a declarative configuration of the LBServiceRequestFilteringRuleTLSServername type for use
// with apply.
type LBServiceRequestFilteringRuleTLSServernameApplyConfiguration struct {
	Exact  *string `json:"exact,omitempty"`
	Suffix *string `json:"suffix,omitempty"`
}

// LBServiceRequestFilteringRuleTLSServernameApplyConfiguration constructs a declarative configuration of the LBServiceRequestFilteringRuleTLSServername type for use with
// apply.
func LBServiceRequestFilteringRuleTLSServername() *LBServiceRequestFilteringRuleTLSServernameApplyConfiguration {
	return &LBServiceRequestFilteringRuleTLSServernameApplyConfiguration{}
}

// WithExact sets the Exact field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Exact field is set to the value of the last call.
func (b *LBServiceRequestFilteringRuleTLSServernameApplyConfiguration) WithExact(value string) *LBServiceRequestFilteringRuleTLSServernameApplyConfiguration {
	b.Exact = &value
	return b
}

// WithSuffix sets the Suffix field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Suffix field is set to the value of the last call.
func (b *LBServiceRequestFilteringRuleTLSServernameApplyConfiguration) WithSuffix(value string) *LBServiceRequestFilteringRuleTLSServernameApplyConfiguration {
	b.Suffix = &value
	return b
}
