// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// LBServiceHTTPJWTProviderApplyConfiguration represents a declarative configuration of the LBServiceHTTPJWTProvider type for use
// with apply.
type LBServiceHTTPJWTProviderApplyConfiguration struct {
	Name      *string                                     `json:"name,omitempty"`
	Issuer    *string                                     `json:"issuer,omitempty"`
	Audiences []string                                    `json:"audiences,omitempty"`
	JWKS      *LBServiceHTTPJWTAuthJWKSApplyConfiguration `json:"jwks,omitempty"`
}

// LBServiceHTTPJWTProviderApplyConfiguration constructs a declarative configuration of the LBServiceHTTPJWTProvider type for use with
// apply.
func LBServiceHTTPJWTProvider() *LBServiceHTTPJWTProviderApplyConfiguration {
	return &LBServiceHTTPJWTProviderApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *LBServiceHTTPJWTProviderApplyConfiguration) WithName(value string) *LBServiceHTTPJWTProviderApplyConfiguration {
	b.Name = &value
	return b
}

// WithIssuer sets the Issuer field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Issuer field is set to the value of the last call.
func (b *LBServiceHTTPJWTProviderApplyConfiguration) WithIssuer(value string) *LBServiceHTTPJWTProviderApplyConfiguration {
	b.Issuer = &value
	return b
}

// WithAudiences adds the given value to the Audiences field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Audiences field.
func (b *LBServiceHTTPJWTProviderApplyConfiguration) WithAudiences(values ...string) *LBServiceHTTPJWTProviderApplyConfiguration {
	for i := range values {
		b.Audiences = append(b.Audiences, values[i])
	}
	return b
}

// WithJWKS sets the JWKS field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the JWKS field is set to the value of the last call.
func (b *LBServiceHTTPJWTProviderApplyConfiguration) WithJWKS(value *LBServiceHTTPJWTAuthJWKSApplyConfiguration) *LBServiceHTTPJWTProviderApplyConfiguration {
	b.JWKS = value
	return b
}
