// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// LBServiceTLSPassthroughRouteApplyConfiguration represents a declarative configuration of the LBServiceTLSPassthroughRoute type for use
// with apply.
type LBServiceTLSPassthroughRouteApplyConfiguration struct {
	Match               *LBServiceTLSPassthroughRouteMatchApplyConfiguration    `json:"match,omitempty"`
	BackendRef          *LBServiceBackendRefApplyConfiguration                  `json:"backendRef,omitempty"`
	PersistentBackend   *LBServiceTLSRoutePersistentBackendApplyConfiguration   `json:"persistentBackend,omitempty"`
	ConnectionFiltering *LBServiceTLSRouteConnectionFilteringApplyConfiguration `json:"connectionFiltering,omitempty"`
	RateLimits          *LBServiceTLSRouteRateLimitsApplyConfiguration          `json:"rateLimits,omitempty"`
}

// LBServiceTLSPassthroughRouteApplyConfiguration constructs a declarative configuration of the LBServiceTLSPassthroughRoute type for use with
// apply.
func LBServiceTLSPassthroughRoute() *LBServiceTLSPassthroughRouteApplyConfiguration {
	return &LBServiceTLSPassthroughRouteApplyConfiguration{}
}

// WithMatch sets the Match field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Match field is set to the value of the last call.
func (b *LBServiceTLSPassthroughRouteApplyConfiguration) WithMatch(value *LBServiceTLSPassthroughRouteMatchApplyConfiguration) *LBServiceTLSPassthroughRouteApplyConfiguration {
	b.Match = value
	return b
}

// WithBackendRef sets the BackendRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BackendRef field is set to the value of the last call.
func (b *LBServiceTLSPassthroughRouteApplyConfiguration) WithBackendRef(value *LBServiceBackendRefApplyConfiguration) *LBServiceTLSPassthroughRouteApplyConfiguration {
	b.BackendRef = value
	return b
}

// WithPersistentBackend sets the PersistentBackend field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PersistentBackend field is set to the value of the last call.
func (b *LBServiceTLSPassthroughRouteApplyConfiguration) WithPersistentBackend(value *LBServiceTLSRoutePersistentBackendApplyConfiguration) *LBServiceTLSPassthroughRouteApplyConfiguration {
	b.PersistentBackend = value
	return b
}

// WithConnectionFiltering sets the ConnectionFiltering field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ConnectionFiltering field is set to the value of the last call.
func (b *LBServiceTLSPassthroughRouteApplyConfiguration) WithConnectionFiltering(value *LBServiceTLSRouteConnectionFilteringApplyConfiguration) *LBServiceTLSPassthroughRouteApplyConfiguration {
	b.ConnectionFiltering = value
	return b
}

// WithRateLimits sets the RateLimits field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RateLimits field is set to the value of the last call.
func (b *LBServiceTLSPassthroughRouteApplyConfiguration) WithRateLimits(value *LBServiceTLSRouteRateLimitsApplyConfiguration) *LBServiceTLSPassthroughRouteApplyConfiguration {
	b.RateLimits = value
	return b
}
