// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	isovalentcomv1alpha1 "github.com/cilium/cilium/pkg/k8s/apis/isovalent.com/v1alpha1"
)

// LBServiceProxyProtocolConfigApplyConfiguration represents a declarative configuration of the LBServiceProxyProtocolConfig type for use
// with apply.
type LBServiceProxyProtocolConfigApplyConfiguration struct {
	DisallowedVersions []isovalentcomv1alpha1.LBProxyProtocolVersion `json:"disallowedVersions,omitempty"`
	PassthroughTLVs    []isovalentcomv1alpha1.LBProxyProtocolTLV     `json:"passthroughTLVs,omitempty"`
}

// LBServiceProxyProtocolConfigApplyConfiguration constructs a declarative configuration of the LBServiceProxyProtocolConfig type for use with
// apply.
func LBServiceProxyProtocolConfig() *LBServiceProxyProtocolConfigApplyConfiguration {
	return &LBServiceProxyProtocolConfigApplyConfiguration{}
}

// WithDisallowedVersions adds the given value to the DisallowedVersions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the DisallowedVersions field.
func (b *LBServiceProxyProtocolConfigApplyConfiguration) WithDisallowedVersions(values ...isovalentcomv1alpha1.LBProxyProtocolVersion) *LBServiceProxyProtocolConfigApplyConfiguration {
	for i := range values {
		b.DisallowedVersions = append(b.DisallowedVersions, values[i])
	}
	return b
}

// WithPassthroughTLVs adds the given value to the PassthroughTLVs field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the PassthroughTLVs field.
func (b *LBServiceProxyProtocolConfigApplyConfiguration) WithPassthroughTLVs(values ...isovalentcomv1alpha1.LBProxyProtocolTLV) *LBServiceProxyProtocolConfigApplyConfiguration {
	for i := range values {
		b.PassthroughTLVs = append(b.PassthroughTLVs, values[i])
	}
	return b
}
