// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// LBServiceHTTPRouteJWTAuthApplyConfiguration represents a declarative configuration of the LBServiceHTTPRouteJWTAuth type for use
// with apply.
type LBServiceHTTPRouteJWTAuthApplyConfiguration struct {
	Disabled *bool `json:"disabled,omitempty"`
}

// LBServiceHTTPRouteJWTAuthApplyConfiguration constructs a declarative configuration of the LBServiceHTTPRouteJWTAuth type for use with
// apply.
func LBServiceHTTPRouteJWTAuth() *LBServiceHTTPRouteJWTAuthApplyConfiguration {
	return &LBServiceHTTPRouteJWTAuthApplyConfiguration{}
}

// WithDisabled sets the Disabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Disabled field is set to the value of the last call.
func (b *LBServiceHTTPRouteJWTAuthApplyConfiguration) WithDisabled(value bool) *LBServiceHTTPRouteJWTAuthApplyConfiguration {
	b.Disabled = &value
	return b
}
