// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// LBServiceTLSRouteApplyConfiguration represents a declarative configuration of the LBServiceTLSRoute type for use
// with apply.
type LBServiceTLSRouteApplyConfiguration struct {
	Match               *LBServiceTLSRouteMatchApplyConfiguration               `json:"match,omitempty"`
	BackendRef          *LBServiceBackendRefApplyConfiguration                  `json:"backendRef,omitempty"`
	PersistentBackend   *LBServiceTLSRoutePersistentBackendApplyConfiguration   `json:"persistentBackend,omitempty"`
	ConnectionFiltering *LBServiceTLSRouteConnectionFilteringApplyConfiguration `json:"connectionFiltering,omitempty"`
	RateLimits          *LBServiceTLSRouteRateLimitsApplyConfiguration          `json:"rateLimits,omitempty"`
}

// LBServiceTLSRouteApplyConfiguration constructs a declarative configuration of the LBServiceTLSRoute type for use with
// apply.
func LBServiceTLSRoute() *LBServiceTLSRouteApplyConfiguration {
	return &LBServiceTLSRouteApplyConfiguration{}
}

// WithMatch sets the Match field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Match field is set to the value of the last call.
func (b *LBServiceTLSRouteApplyConfiguration) WithMatch(value *LBServiceTLSRouteMatchApplyConfiguration) *LBServiceTLSRouteApplyConfiguration {
	b.Match = value
	return b
}

// WithBackendRef sets the BackendRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BackendRef field is set to the value of the last call.
func (b *LBServiceTLSRouteApplyConfiguration) WithBackendRef(value *LBServiceBackendRefApplyConfiguration) *LBServiceTLSRouteApplyConfiguration {
	b.BackendRef = value
	return b
}

// WithPersistentBackend sets the PersistentBackend field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PersistentBackend field is set to the value of the last call.
func (b *LBServiceTLSRouteApplyConfiguration) WithPersistentBackend(value *LBServiceTLSRoutePersistentBackendApplyConfiguration) *LBServiceTLSRouteApplyConfiguration {
	b.PersistentBackend = value
	return b
}

// WithConnectionFiltering sets the ConnectionFiltering field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ConnectionFiltering field is set to the value of the last call.
func (b *LBServiceTLSRouteApplyConfiguration) WithConnectionFiltering(value *LBServiceTLSRouteConnectionFilteringApplyConfiguration) *LBServiceTLSRouteApplyConfiguration {
	b.ConnectionFiltering = value
	return b
}

// WithRateLimits sets the RateLimits field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RateLimits field is set to the value of the last call.
func (b *LBServiceTLSRouteApplyConfiguration) WithRateLimits(value *LBServiceTLSRouteRateLimitsApplyConfiguration) *LBServiceTLSRouteApplyConfiguration {
	b.RateLimits = value
	return b
}
