// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	isovalentcomv1alpha1 "github.com/cilium/cilium/pkg/k8s/apis/isovalent.com/v1alpha1"
)

// LBServiceTCPRouteConnectionFilteringApplyConfiguration represents a declarative configuration of the LBServiceTCPRouteConnectionFiltering type for use
// with apply.
type LBServiceTCPRouteConnectionFilteringApplyConfiguration struct {
	RuleType *isovalentcomv1alpha1.RequestFilteringRuleType            `json:"ruleType,omitempty"`
	Rules    []LBServiceTCPRouteRequestFilteringRuleApplyConfiguration `json:"rules,omitempty"`
}

// LBServiceTCPRouteConnectionFilteringApplyConfiguration constructs a declarative configuration of the LBServiceTCPRouteConnectionFiltering type for use with
// apply.
func LBServiceTCPRouteConnectionFiltering() *LBServiceTCPRouteConnectionFilteringApplyConfiguration {
	return &LBServiceTCPRouteConnectionFilteringApplyConfiguration{}
}

// WithRuleType sets the RuleType field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RuleType field is set to the value of the last call.
func (b *LBServiceTCPRouteConnectionFilteringApplyConfiguration) WithRuleType(value isovalentcomv1alpha1.RequestFilteringRuleType) *LBServiceTCPRouteConnectionFilteringApplyConfiguration {
	b.RuleType = &value
	return b
}

// WithRules adds the given value to the Rules field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Rules field.
func (b *LBServiceTCPRouteConnectionFilteringApplyConfiguration) WithRules(values ...*LBServiceTCPRouteRequestFilteringRuleApplyConfiguration) *LBServiceTCPRouteConnectionFilteringApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithRules")
		}
		b.Rules = append(b.Rules, *values[i])
	}
	return b
}
