// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// LBServiceBackendRefApplyConfiguration represents a declarative configuration of the LBServiceBackendRef type for use
// with apply.
type LBServiceBackendRefApplyConfiguration struct {
	Name *string `json:"name,omitempty"`
}

// LBServiceBackendRefApplyConfiguration constructs a declarative configuration of the LBServiceBackendRef type for use with
// apply.
func LBServiceBackendRef() *LBServiceBackendRefApplyConfiguration {
	return &LBServiceBackendRefApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *LBServiceBackendRefApplyConfiguration) WithName(value string) *LBServiceBackendRefApplyConfiguration {
	b.Name = &value
	return b
}
