// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// LBServiceTCPRouteRequestFilteringRuleApplyConfiguration represents a declarative configuration of the LBServiceTCPRouteRequestFilteringRule type for use
// with apply.
type LBServiceTCPRouteRequestFilteringRuleApplyConfiguration struct {
	SourceCIDR *LBServiceRequestFilteringRuleSourceCIDRApplyConfiguration `json:"sourceCIDR,omitempty"`
}

// LBServiceTCPRouteRequestFilteringRuleApplyConfiguration constructs a declarative configuration of the LBServiceTCPRouteRequestFilteringRule type for use with
// apply.
func LBServiceTCPRouteRequestFilteringRule() *LBServiceTCPRouteRequestFilteringRuleApplyConfiguration {
	return &LBServiceTCPRouteRequestFilteringRuleApplyConfiguration{}
}

// WithSourceCIDR sets the SourceCIDR field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SourceCIDR field is set to the value of the last call.
func (b *LBServiceTCPRouteRequestFilteringRuleApplyConfiguration) WithSourceCIDR(value *LBServiceRequestFilteringRuleSourceCIDRApplyConfiguration) *LBServiceTCPRouteRequestFilteringRuleApplyConfiguration {
	b.SourceCIDR = value
	return b
}
