// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// LBServiceHTTPPathApplyConfiguration represents a declarative configuration of the LBServiceHTTPPath type for use
// with apply.
type LBServiceHTTPPathApplyConfiguration struct {
	Exact  *string `json:"exact,omitempty"`
	Prefix *string `json:"prefix,omitempty"`
}

// LBServiceHTTPPathApplyConfiguration constructs a declarative configuration of the LBServiceHTTPPath type for use with
// apply.
func LBServiceHTTPPath() *LBServiceHTTPPathApplyConfiguration {
	return &LBServiceHTTPPathApplyConfiguration{}
}

// WithExact sets the Exact field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Exact field is set to the value of the last call.
func (b *LBServiceHTTPPathApplyConfiguration) WithExact(value string) *LBServiceHTTPPathApplyConfiguration {
	b.Exact = &value
	return b
}

// WithPrefix sets the Prefix field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Prefix field is set to the value of the last call.
func (b *LBServiceHTTPPathApplyConfiguration) WithPrefix(value string) *LBServiceHTTPPathApplyConfiguration {
	b.Prefix = &value
	return b
}
