// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// LBServiceRequestFilteringRuleHTTPHostnameApplyConfiguration represents a declarative configuration of the LBServiceRequestFilteringRuleHTTPHostname type for use
// with apply.
type LBServiceRequestFilteringRuleHTTPHostnameApplyConfiguration struct {
	Exact  *string `json:"exact,omitempty"`
	Suffix *string `json:"suffix,omitempty"`
}

// LBServiceRequestFilteringRuleHTTPHostnameApplyConfiguration constructs a declarative configuration of the LBServiceRequestFilteringRuleHTTPHostname type for use with
// apply.
func LBServiceRequestFilteringRuleHTTPHostname() *LBServiceRequestFilteringRuleHTTPHostnameApplyConfiguration {
	return &LBServiceRequestFilteringRuleHTTPHostnameApplyConfiguration{}
}

// WithExact sets the Exact field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Exact field is set to the value of the last call.
func (b *LBServiceRequestFilteringRuleHTTPHostnameApplyConfiguration) WithExact(value string) *LBServiceRequestFilteringRuleHTTPHostnameApplyConfiguration {
	b.Exact = &value
	return b
}

// WithSuffix sets the Suffix field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Suffix field is set to the value of the last call.
func (b *LBServiceRequestFilteringRuleHTTPHostnameApplyConfiguration) WithSuffix(value string) *LBServiceRequestFilteringRuleHTTPHostnameApplyConfiguration {
	b.Suffix = &value
	return b
}
