// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	isovalentcomv1alpha1 "github.com/cilium/cilium/pkg/k8s/apis/isovalent.com/v1alpha1"
)

// LBServiceHTTPRouteRequestFilteringRuleApplyConfiguration represents a declarative configuration of the LBServiceHTTPRouteRequestFilteringRule type for use
// with apply.
type LBServiceHTTPRouteRequestFilteringRuleApplyConfiguration struct {
	SourceCIDR *LBServiceRequestFilteringRuleSourceCIDRApplyConfiguration      `json:"sourceCIDR,omitempty"`
	HostName   *LBServiceRequestFilteringRuleHTTPHostnameApplyConfiguration    `json:"hostName,omitempty"`
	Path       *LBServiceRequestFilteringRuleHTTPPathApplyConfiguration        `json:"path,omitempty"`
	Headers    []*isovalentcomv1alpha1.LBServiceRequestFilteringRuleHTTPHeader `json:"headers,omitempty"`
	JWTClaims  []*isovalentcomv1alpha1.LBServiceRequestFilteringRuleJWTClaim   `json:"jwtClaims,omitempty"`
}

// LBServiceHTTPRouteRequestFilteringRuleApplyConfiguration constructs a declarative configuration of the LBServiceHTTPRouteRequestFilteringRule type for use with
// apply.
func LBServiceHTTPRouteRequestFilteringRule() *LBServiceHTTPRouteRequestFilteringRuleApplyConfiguration {
	return &LBServiceHTTPRouteRequestFilteringRuleApplyConfiguration{}
}

// WithSourceCIDR sets the SourceCIDR field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SourceCIDR field is set to the value of the last call.
func (b *LBServiceHTTPRouteRequestFilteringRuleApplyConfiguration) WithSourceCIDR(value *LBServiceRequestFilteringRuleSourceCIDRApplyConfiguration) *LBServiceHTTPRouteRequestFilteringRuleApplyConfiguration {
	b.SourceCIDR = value
	return b
}

// WithHostName sets the HostName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HostName field is set to the value of the last call.
func (b *LBServiceHTTPRouteRequestFilteringRuleApplyConfiguration) WithHostName(value *LBServiceRequestFilteringRuleHTTPHostnameApplyConfiguration) *LBServiceHTTPRouteRequestFilteringRuleApplyConfiguration {
	b.HostName = value
	return b
}

// WithPath sets the Path field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Path field is set to the value of the last call.
func (b *LBServiceHTTPRouteRequestFilteringRuleApplyConfiguration) WithPath(value *LBServiceRequestFilteringRuleHTTPPathApplyConfiguration) *LBServiceHTTPRouteRequestFilteringRuleApplyConfiguration {
	b.Path = value
	return b
}

// WithHeaders adds the given value to the Headers field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Headers field.
func (b *LBServiceHTTPRouteRequestFilteringRuleApplyConfiguration) WithHeaders(values ...**isovalentcomv1alpha1.LBServiceRequestFilteringRuleHTTPHeader) *LBServiceHTTPRouteRequestFilteringRuleApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithHeaders")
		}
		b.Headers = append(b.Headers, *values[i])
	}
	return b
}

// WithJWTClaims adds the given value to the JWTClaims field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the JWTClaims field.
func (b *LBServiceHTTPRouteRequestFilteringRuleApplyConfiguration) WithJWTClaims(values ...**isovalentcomv1alpha1.LBServiceRequestFilteringRuleJWTClaim) *LBServiceHTTPRouteRequestFilteringRuleApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithJWTClaims")
		}
		b.JWTClaims = append(b.JWTClaims, *values[i])
	}
	return b
}
