// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// LBServiceUDPRouteRequestFilteringRuleApplyConfiguration represents a declarative configuration of the LBServiceUDPRouteRequestFilteringRule type for use
// with apply.
type LBServiceUDPRouteRequestFilteringRuleApplyConfiguration struct {
	SourceCIDR *LBServiceRequestFilteringRuleSourceCIDRApplyConfiguration `json:"sourceCIDR,omitempty"`
}

// LBServiceUDPRouteRequestFilteringRuleApplyConfiguration constructs a declarative configuration of the LBServiceUDPRouteRequestFilteringRule type for use with
// apply.
func LBServiceUDPRouteRequestFilteringRule() *LBServiceUDPRouteRequestFilteringRuleApplyConfiguration {
	return &LBServiceUDPRouteRequestFilteringRuleApplyConfiguration{}
}

// WithSourceCIDR sets the SourceCIDR field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SourceCIDR field is set to the value of the last call.
func (b *LBServiceUDPRouteRequestFilteringRuleApplyConfiguration) WithSourceCIDR(value *LBServiceRequestFilteringRuleSourceCIDRApplyConfiguration) *LBServiceUDPRouteRequestFilteringRuleApplyConfiguration {
	b.SourceCIDR = value
	return b
}
