// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// LBServiceHTTPSRouteApplyConfiguration represents a declarative configuration of the LBServiceHTTPSRoute type for use
// with apply.
type LBServiceHTTPSRouteApplyConfiguration struct {
	Match             *LBServiceHTTPRouteMatchApplyConfiguration             `json:"match,omitempty"`
	BackendRef        *LBServiceBackendRefApplyConfiguration                 `json:"backendRef,omitempty"`
	PersistentBackend *LBServiceHTTPRoutePersistentBackendApplyConfiguration `json:"persistentBackend,omitempty"`
	RequestFiltering  *LBServiceHTTPSRouteRequestFilteringApplyConfiguration `json:"requestFiltering,omitempty"`
	RateLimits        *LBServiceHTTPRouteRateLimitsApplyConfiguration        `json:"rateLimits,omitempty"`
	Auth              *LBServiceHTTPRouteAuthApplyConfiguration              `json:"auth,omitempty"`
}

// LBServiceHTTPSRouteApplyConfiguration constructs a declarative configuration of the LBServiceHTTPSRoute type for use with
// apply.
func LBServiceHTTPSRoute() *LBServiceHTTPSRouteApplyConfiguration {
	return &LBServiceHTTPSRouteApplyConfiguration{}
}

// WithMatch sets the Match field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Match field is set to the value of the last call.
func (b *LBServiceHTTPSRouteApplyConfiguration) WithMatch(value *LBServiceHTTPRouteMatchApplyConfiguration) *LBServiceHTTPSRouteApplyConfiguration {
	b.Match = value
	return b
}

// WithBackendRef sets the BackendRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BackendRef field is set to the value of the last call.
func (b *LBServiceHTTPSRouteApplyConfiguration) WithBackendRef(value *LBServiceBackendRefApplyConfiguration) *LBServiceHTTPSRouteApplyConfiguration {
	b.BackendRef = value
	return b
}

// WithPersistentBackend sets the PersistentBackend field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PersistentBackend field is set to the value of the last call.
func (b *LBServiceHTTPSRouteApplyConfiguration) WithPersistentBackend(value *LBServiceHTTPRoutePersistentBackendApplyConfiguration) *LBServiceHTTPSRouteApplyConfiguration {
	b.PersistentBackend = value
	return b
}

// WithRequestFiltering sets the RequestFiltering field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RequestFiltering field is set to the value of the last call.
func (b *LBServiceHTTPSRouteApplyConfiguration) WithRequestFiltering(value *LBServiceHTTPSRouteRequestFilteringApplyConfiguration) *LBServiceHTTPSRouteApplyConfiguration {
	b.RequestFiltering = value
	return b
}

// WithRateLimits sets the RateLimits field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RateLimits field is set to the value of the last call.
func (b *LBServiceHTTPSRouteApplyConfiguration) WithRateLimits(value *LBServiceHTTPRouteRateLimitsApplyConfiguration) *LBServiceHTTPSRouteApplyConfiguration {
	b.RateLimits = value
	return b
}

// WithAuth sets the Auth field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Auth field is set to the value of the last call.
func (b *LBServiceHTTPSRouteApplyConfiguration) WithAuth(value *LBServiceHTTPRouteAuthApplyConfiguration) *LBServiceHTTPSRouteApplyConfiguration {
	b.Auth = value
	return b
}
