// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// LBServiceUDPRoutePersistentBackendApplyConfiguration represents a declarative configuration of the LBServiceUDPRoutePersistentBackend type for use
// with apply.
type LBServiceUDPRoutePersistentBackendApplyConfiguration struct {
	SourceIP *bool `json:"sourceIP,omitempty"`
}

// LBServiceUDPRoutePersistentBackendApplyConfiguration constructs a declarative configuration of the LBServiceUDPRoutePersistentBackend type for use with
// apply.
func LBServiceUDPRoutePersistentBackend() *LBServiceUDPRoutePersistentBackendApplyConfiguration {
	return &LBServiceUDPRoutePersistentBackendApplyConfiguration{}
}

// WithSourceIP sets the SourceIP field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SourceIP field is set to the value of the last call.
func (b *LBServiceUDPRoutePersistentBackendApplyConfiguration) WithSourceIP(value bool) *LBServiceUDPRoutePersistentBackendApplyConfiguration {
	b.SourceIP = &value
	return b
}
