// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// LBServiceRequestFilteringRuleSourceCIDRApplyConfiguration represents a declarative configuration of the LBServiceRequestFilteringRuleSourceCIDR type for use
// with apply.
type LBServiceRequestFilteringRuleSourceCIDRApplyConfiguration struct {
	CIDR *string `json:"cidr,omitempty"`
}

// LBServiceRequestFilteringRuleSourceCIDRApplyConfiguration constructs a declarative configuration of the LBServiceRequestFilteringRuleSourceCIDR type for use with
// apply.
func LBServiceRequestFilteringRuleSourceCIDR() *LBServiceRequestFilteringRuleSourceCIDRApplyConfiguration {
	return &LBServiceRequestFilteringRuleSourceCIDRApplyConfiguration{}
}

// WithCIDR sets the CIDR field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CIDR field is set to the value of the last call.
func (b *LBServiceRequestFilteringRuleSourceCIDRApplyConfiguration) WithCIDR(value string) *LBServiceRequestFilteringRuleSourceCIDRApplyConfiguration {
	b.CIDR = &value
	return b
}
