// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// LBServiceApplicationsApplyConfiguration represents a declarative configuration of the LBServiceApplications type for use
// with apply.
type LBServiceApplicationsApplyConfiguration struct {
	HTTPProxy      *LBServiceApplicationHTTPProxyApplyConfiguration      `json:"httpProxy,omitempty"`
	HTTPSProxy     *LBServiceApplicationHTTPSProxyApplyConfiguration     `json:"httpsProxy,omitempty"`
	TLSPassthrough *LBServiceApplicationTLSPassthroughApplyConfiguration `json:"tlsPassthrough,omitempty"`
	TLSProxy       *LBServiceApplicationTLSProxyApplyConfiguration       `json:"tlsProxy,omitempty"`
	TCPProxy       *LBServiceApplicationTCPProxyApplyConfiguration       `json:"tcpProxy,omitempty"`
	UDPProxy       *LBServiceApplicationUDPProxyApplyConfiguration       `json:"udpProxy,omitempty"`
}

// LBServiceApplicationsApplyConfiguration constructs a declarative configuration of the LBServiceApplications type for use with
// apply.
func LBServiceApplications() *LBServiceApplicationsApplyConfiguration {
	return &LBServiceApplicationsApplyConfiguration{}
}

// WithHTTPProxy sets the HTTPProxy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HTTPProxy field is set to the value of the last call.
func (b *LBServiceApplicationsApplyConfiguration) WithHTTPProxy(value *LBServiceApplicationHTTPProxyApplyConfiguration) *LBServiceApplicationsApplyConfiguration {
	b.HTTPProxy = value
	return b
}

// WithHTTPSProxy sets the HTTPSProxy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HTTPSProxy field is set to the value of the last call.
func (b *LBServiceApplicationsApplyConfiguration) WithHTTPSProxy(value *LBServiceApplicationHTTPSProxyApplyConfiguration) *LBServiceApplicationsApplyConfiguration {
	b.HTTPSProxy = value
	return b
}

// WithTLSPassthrough sets the TLSPassthrough field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TLSPassthrough field is set to the value of the last call.
func (b *LBServiceApplicationsApplyConfiguration) WithTLSPassthrough(value *LBServiceApplicationTLSPassthroughApplyConfiguration) *LBServiceApplicationsApplyConfiguration {
	b.TLSPassthrough = value
	return b
}

// WithTLSProxy sets the TLSProxy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TLSProxy field is set to the value of the last call.
func (b *LBServiceApplicationsApplyConfiguration) WithTLSProxy(value *LBServiceApplicationTLSProxyApplyConfiguration) *LBServiceApplicationsApplyConfiguration {
	b.TLSProxy = value
	return b
}

// WithTCPProxy sets the TCPProxy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TCPProxy field is set to the value of the last call.
func (b *LBServiceApplicationsApplyConfiguration) WithTCPProxy(value *LBServiceApplicationTCPProxyApplyConfiguration) *LBServiceApplicationsApplyConfiguration {
	b.TCPProxy = value
	return b
}

// WithUDPProxy sets the UDPProxy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UDPProxy field is set to the value of the last call.
func (b *LBServiceApplicationsApplyConfiguration) WithUDPProxy(value *LBServiceApplicationUDPProxyApplyConfiguration) *LBServiceApplicationsApplyConfiguration {
	b.UDPProxy = value
	return b
}
