// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	isovalentcomv1alpha1 "github.com/cilium/cilium/pkg/k8s/apis/isovalent.com/v1alpha1"
)

// LBServiceApplicationUDPProxyStatusApplyConfiguration represents a declarative configuration of the LBServiceApplicationUDPProxyStatus type for use
// with apply.
type LBServiceApplicationUDPProxyStatusApplyConfiguration struct {
	DeploymentMode *isovalentcomv1alpha1.LBUDPProxyDeploymentModeType `json:"deploymentMode,omitempty"`
}

// LBServiceApplicationUDPProxyStatusApplyConfiguration constructs a declarative configuration of the LBServiceApplicationUDPProxyStatus type for use with
// apply.
func LBServiceApplicationUDPProxyStatus() *LBServiceApplicationUDPProxyStatusApplyConfiguration {
	return &LBServiceApplicationUDPProxyStatusApplyConfiguration{}
}

// WithDeploymentMode sets the DeploymentMode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DeploymentMode field is set to the value of the last call.
func (b *LBServiceApplicationUDPProxyStatusApplyConfiguration) WithDeploymentMode(value isovalentcomv1alpha1.LBUDPProxyDeploymentModeType) *LBServiceApplicationUDPProxyStatusApplyConfiguration {
	b.DeploymentMode = &value
	return b
}
