// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// LBServiceRateLimitApplyConfiguration represents a declarative configuration of the LBServiceRateLimit type for use
// with apply.
type LBServiceRateLimitApplyConfiguration struct {
	Limit             *uint `json:"limit,omitempty"`
	TimePeriodSeconds *uint `json:"timePeriodSeconds,omitempty"`
}

// LBServiceRateLimitApplyConfiguration constructs a declarative configuration of the LBServiceRateLimit type for use with
// apply.
func LBServiceRateLimit() *LBServiceRateLimitApplyConfiguration {
	return &LBServiceRateLimitApplyConfiguration{}
}

// WithLimit sets the Limit field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Limit field is set to the value of the last call.
func (b *LBServiceRateLimitApplyConfiguration) WithLimit(value uint) *LBServiceRateLimitApplyConfiguration {
	b.Limit = &value
	return b
}

// WithTimePeriodSeconds sets the TimePeriodSeconds field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TimePeriodSeconds field is set to the value of the last call.
func (b *LBServiceRateLimitApplyConfiguration) WithTimePeriodSeconds(value uint) *LBServiceRateLimitApplyConfiguration {
	b.TimePeriodSeconds = &value
	return b
}
