// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// LBServiceHTTPRoutePersistentBackendHeaderApplyConfiguration represents a declarative configuration of the LBServiceHTTPRoutePersistentBackendHeader type for use
// with apply.
type LBServiceHTTPRoutePersistentBackendHeaderApplyConfiguration struct {
	Name *string `json:"name,omitempty"`
}

// LBServiceHTTPRoutePersistentBackendHeaderApplyConfiguration constructs a declarative configuration of the LBServiceHTTPRoutePersistentBackendHeader type for use with
// apply.
func LBServiceHTTPRoutePersistentBackendHeader() *LBServiceHTTPRoutePersistentBackendHeaderApplyConfiguration {
	return &LBServiceHTTPRoutePersistentBackendHeaderApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *LBServiceHTTPRoutePersistentBackendHeaderApplyConfiguration) WithName(value string) *LBServiceHTTPRoutePersistentBackendHeaderApplyConfiguration {
	b.Name = &value
	return b
}
