// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	isovalentcomv1alpha1 "github.com/cilium/cilium/pkg/k8s/apis/isovalent.com/v1alpha1"
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// LBVIPStatusApplyConfiguration represents a declarative configuration of the LBVIPStatus type for use
// with apply.
type LBVIPStatusApplyConfiguration struct {
	Conditions []v1.ConditionApplyConfiguration       `json:"conditions,omitempty"`
	Status     *isovalentcomv1alpha1.LBResourceStatus `json:"status,omitempty"`
	Addresses  *LBVIPAddressesApplyConfiguration      `json:"addresses,omitempty"`
}

// LBVIPStatusApplyConfiguration constructs a declarative configuration of the LBVIPStatus type for use with
// apply.
func LBVIPStatus() *LBVIPStatusApplyConfiguration {
	return &LBVIPStatusApplyConfiguration{}
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *LBVIPStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *LBVIPStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}

// WithStatus sets the Status field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Status field is set to the value of the last call.
func (b *LBVIPStatusApplyConfiguration) WithStatus(value isovalentcomv1alpha1.LBResourceStatus) *LBVIPStatusApplyConfiguration {
	b.Status = &value
	return b
}

// WithAddresses sets the Addresses field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Addresses field is set to the value of the last call.
func (b *LBVIPStatusApplyConfiguration) WithAddresses(value *LBVIPAddressesApplyConfiguration) *LBVIPStatusApplyConfiguration {
	b.Addresses = value
	return b
}
