// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// LoadbalancingConsistentHashingAlgorithmApplyConfiguration represents a declarative configuration of the LoadbalancingConsistentHashingAlgorithm type for use
// with apply.
type LoadbalancingConsistentHashingAlgorithmApplyConfiguration struct {
	Maglev *LoadbalancingConsistentHashingAlgorithmMaglevApplyConfiguration `json:"maglev,omitempty"`
}

// LoadbalancingConsistentHashingAlgorithmApplyConfiguration constructs a declarative configuration of the LoadbalancingConsistentHashingAlgorithm type for use with
// apply.
func LoadbalancingConsistentHashingAlgorithm() *LoadbalancingConsistentHashingAlgorithmApplyConfiguration {
	return &LoadbalancingConsistentHashingAlgorithmApplyConfiguration{}
}

// WithMaglev sets the Maglev field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Maglev field is set to the value of the last call.
func (b *LoadbalancingConsistentHashingAlgorithmApplyConfiguration) WithMaglev(value *LoadbalancingConsistentHashingAlgorithmMaglevApplyConfiguration) *LoadbalancingConsistentHashingAlgorithmApplyConfiguration {
	b.Maglev = value
	return b
}
