// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// PrivateNetworkEndpointSliceEntryApplyConfiguration represents a declarative configuration of the PrivateNetworkEndpointSliceEntry type for use
// with apply.
type PrivateNetworkEndpointSliceEntryApplyConfiguration struct {
	ActivatedAt *v1.MicroTime                                           `json:"activatedAt,omitempty"`
	Endpoint    *PrivateNetworkEndpointSliceEndpointApplyConfiguration  `json:"endpoint,omitempty"`
	Interface   *PrivateNetworkEndpointSliceInterfaceApplyConfiguration `json:"interface,omitempty"`
	Flags       *PrivateNetworkEndpointSliceFlagsApplyConfiguration     `json:"flags,omitempty"`
}

// PrivateNetworkEndpointSliceEntryApplyConfiguration constructs a declarative configuration of the PrivateNetworkEndpointSliceEntry type for use with
// apply.
func PrivateNetworkEndpointSliceEntry() *PrivateNetworkEndpointSliceEntryApplyConfiguration {
	return &PrivateNetworkEndpointSliceEntryApplyConfiguration{}
}

// WithActivatedAt sets the ActivatedAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ActivatedAt field is set to the value of the last call.
func (b *PrivateNetworkEndpointSliceEntryApplyConfiguration) WithActivatedAt(value v1.MicroTime) *PrivateNetworkEndpointSliceEntryApplyConfiguration {
	b.ActivatedAt = &value
	return b
}

// WithEndpoint sets the Endpoint field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Endpoint field is set to the value of the last call.
func (b *PrivateNetworkEndpointSliceEntryApplyConfiguration) WithEndpoint(value *PrivateNetworkEndpointSliceEndpointApplyConfiguration) *PrivateNetworkEndpointSliceEntryApplyConfiguration {
	b.Endpoint = value
	return b
}

// WithInterface sets the Interface field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Interface field is set to the value of the last call.
func (b *PrivateNetworkEndpointSliceEntryApplyConfiguration) WithInterface(value *PrivateNetworkEndpointSliceInterfaceApplyConfiguration) *PrivateNetworkEndpointSliceEntryApplyConfiguration {
	b.Interface = value
	return b
}

// WithFlags sets the Flags field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Flags field is set to the value of the last call.
func (b *PrivateNetworkEndpointSliceEntryApplyConfiguration) WithFlags(value *PrivateNetworkEndpointSliceFlagsApplyConfiguration) *PrivateNetworkEndpointSliceEntryApplyConfiguration {
	b.Flags = value
	return b
}
