// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	isovalentcomv1alpha1 "github.com/cilium/cilium/pkg/k8s/apis/isovalent.com/v1alpha1"
)

// RouteSpecApplyConfiguration represents a declarative configuration of the RouteSpec type for use
// with apply.
type RouteSpecApplyConfiguration struct {
	Destination *isovalentcomv1alpha1.NetworkCIDR `json:"destination,omitempty"`
	Gateway     *isovalentcomv1alpha1.IP          `json:"gateway,omitempty"`
}

// RouteSpecApplyConfiguration constructs a declarative configuration of the RouteSpec type for use with
// apply.
func RouteSpec() *RouteSpecApplyConfiguration {
	return &RouteSpecApplyConfiguration{}
}

// WithDestination sets the Destination field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Destination field is set to the value of the last call.
func (b *RouteSpecApplyConfiguration) WithDestination(value isovalentcomv1alpha1.NetworkCIDR) *RouteSpecApplyConfiguration {
	b.Destination = &value
	return b
}

// WithGateway sets the Gateway field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Gateway field is set to the value of the last call.
func (b *RouteSpecApplyConfiguration) WithGateway(value isovalentcomv1alpha1.IP) *RouteSpecApplyConfiguration {
	b.Gateway = &value
	return b
}
