// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by client-gen. DO NOT EDIT.

package v2

import (
	context "context"

	ciliumiov2 "github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2"
	scheme "github.com/cilium/cilium/pkg/k8s/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// CiliumVRFsGetter has a method to return a CiliumVRFInterface.
// A group's client should implement this interface.
type CiliumVRFsGetter interface {
	CiliumVRFs() CiliumVRFInterface
}

// CiliumVRFInterface has methods to work with CiliumVRF resources.
type CiliumVRFInterface interface {
	Create(ctx context.Context, ciliumVRF *ciliumiov2.CiliumVRF, opts v1.CreateOptions) (*ciliumiov2.CiliumVRF, error)
	Update(ctx context.Context, ciliumVRF *ciliumiov2.CiliumVRF, opts v1.UpdateOptions) (*ciliumiov2.CiliumVRF, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*ciliumiov2.CiliumVRF, error)
	List(ctx context.Context, opts v1.ListOptions) (*ciliumiov2.CiliumVRFList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *ciliumiov2.CiliumVRF, err error)
	CiliumVRFExpansion
}

// ciliumVRFs implements CiliumVRFInterface
type ciliumVRFs struct {
	*gentype.ClientWithList[*ciliumiov2.CiliumVRF, *ciliumiov2.CiliumVRFList]
}

// newCiliumVRFs returns a CiliumVRFs
func newCiliumVRFs(c *CiliumV2Client) *ciliumVRFs {
	return &ciliumVRFs{
		gentype.NewClientWithList[*ciliumiov2.CiliumVRF, *ciliumiov2.CiliumVRFList](
			"ciliumvrfs",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *ciliumiov2.CiliumVRF { return &ciliumiov2.CiliumVRF{} },
			func() *ciliumiov2.CiliumVRFList { return &ciliumiov2.CiliumVRFList{} },
		),
	}
}
