// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	isovalentcomv1alpha1 "github.com/cilium/cilium/pkg/k8s/apis/isovalent.com/v1alpha1"
	scheme "github.com/cilium/cilium/pkg/k8s/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// IsovalentBGPPeerConfigsGetter has a method to return a IsovalentBGPPeerConfigInterface.
// A group's client should implement this interface.
type IsovalentBGPPeerConfigsGetter interface {
	IsovalentBGPPeerConfigs() IsovalentBGPPeerConfigInterface
}

// IsovalentBGPPeerConfigInterface has methods to work with IsovalentBGPPeerConfig resources.
type IsovalentBGPPeerConfigInterface interface {
	Create(ctx context.Context, isovalentBGPPeerConfig *isovalentcomv1alpha1.IsovalentBGPPeerConfig, opts v1.CreateOptions) (*isovalentcomv1alpha1.IsovalentBGPPeerConfig, error)
	Update(ctx context.Context, isovalentBGPPeerConfig *isovalentcomv1alpha1.IsovalentBGPPeerConfig, opts v1.UpdateOptions) (*isovalentcomv1alpha1.IsovalentBGPPeerConfig, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, isovalentBGPPeerConfig *isovalentcomv1alpha1.IsovalentBGPPeerConfig, opts v1.UpdateOptions) (*isovalentcomv1alpha1.IsovalentBGPPeerConfig, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*isovalentcomv1alpha1.IsovalentBGPPeerConfig, error)
	List(ctx context.Context, opts v1.ListOptions) (*isovalentcomv1alpha1.IsovalentBGPPeerConfigList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *isovalentcomv1alpha1.IsovalentBGPPeerConfig, err error)
	IsovalentBGPPeerConfigExpansion
}

// isovalentBGPPeerConfigs implements IsovalentBGPPeerConfigInterface
type isovalentBGPPeerConfigs struct {
	*gentype.ClientWithList[*isovalentcomv1alpha1.IsovalentBGPPeerConfig, *isovalentcomv1alpha1.IsovalentBGPPeerConfigList]
}

// newIsovalentBGPPeerConfigs returns a IsovalentBGPPeerConfigs
func newIsovalentBGPPeerConfigs(c *IsovalentV1alpha1Client) *isovalentBGPPeerConfigs {
	return &isovalentBGPPeerConfigs{
		gentype.NewClientWithList[*isovalentcomv1alpha1.IsovalentBGPPeerConfig, *isovalentcomv1alpha1.IsovalentBGPPeerConfigList](
			"isovalentbgppeerconfigs",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *isovalentcomv1alpha1.IsovalentBGPPeerConfig {
				return &isovalentcomv1alpha1.IsovalentBGPPeerConfig{}
			},
			func() *isovalentcomv1alpha1.IsovalentBGPPeerConfigList {
				return &isovalentcomv1alpha1.IsovalentBGPPeerConfigList{}
			},
		),
	}
}
