// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	isovalentcomv1alpha1 "github.com/cilium/cilium/pkg/k8s/apis/isovalent.com/v1alpha1"
	applyconfigurationisovalentcomv1alpha1 "github.com/cilium/cilium/pkg/k8s/client/applyconfiguration/isovalent.com/v1alpha1"
	scheme "github.com/cilium/cilium/pkg/k8s/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// IsovalentBFDNodeConfigOverridesGetter has a method to return a IsovalentBFDNodeConfigOverrideInterface.
// A group's client should implement this interface.
type IsovalentBFDNodeConfigOverridesGetter interface {
	IsovalentBFDNodeConfigOverrides() IsovalentBFDNodeConfigOverrideInterface
}

// IsovalentBFDNodeConfigOverrideInterface has methods to work with IsovalentBFDNodeConfigOverride resources.
type IsovalentBFDNodeConfigOverrideInterface interface {
	Create(ctx context.Context, isovalentBFDNodeConfigOverride *isovalentcomv1alpha1.IsovalentBFDNodeConfigOverride, opts v1.CreateOptions) (*isovalentcomv1alpha1.IsovalentBFDNodeConfigOverride, error)
	Update(ctx context.Context, isovalentBFDNodeConfigOverride *isovalentcomv1alpha1.IsovalentBFDNodeConfigOverride, opts v1.UpdateOptions) (*isovalentcomv1alpha1.IsovalentBFDNodeConfigOverride, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*isovalentcomv1alpha1.IsovalentBFDNodeConfigOverride, error)
	List(ctx context.Context, opts v1.ListOptions) (*isovalentcomv1alpha1.IsovalentBFDNodeConfigOverrideList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *isovalentcomv1alpha1.IsovalentBFDNodeConfigOverride, err error)
	Apply(ctx context.Context, isovalentBFDNodeConfigOverride *applyconfigurationisovalentcomv1alpha1.IsovalentBFDNodeConfigOverrideApplyConfiguration, opts v1.ApplyOptions) (result *isovalentcomv1alpha1.IsovalentBFDNodeConfigOverride, err error)
	IsovalentBFDNodeConfigOverrideExpansion
}

// isovalentBFDNodeConfigOverrides implements IsovalentBFDNodeConfigOverrideInterface
type isovalentBFDNodeConfigOverrides struct {
	*gentype.ClientWithListAndApply[*isovalentcomv1alpha1.IsovalentBFDNodeConfigOverride, *isovalentcomv1alpha1.IsovalentBFDNodeConfigOverrideList, *applyconfigurationisovalentcomv1alpha1.IsovalentBFDNodeConfigOverrideApplyConfiguration]
}

// newIsovalentBFDNodeConfigOverrides returns a IsovalentBFDNodeConfigOverrides
func newIsovalentBFDNodeConfigOverrides(c *IsovalentV1alpha1Client) *isovalentBFDNodeConfigOverrides {
	return &isovalentBFDNodeConfigOverrides{
		gentype.NewClientWithListAndApply[*isovalentcomv1alpha1.IsovalentBFDNodeConfigOverride, *isovalentcomv1alpha1.IsovalentBFDNodeConfigOverrideList, *applyconfigurationisovalentcomv1alpha1.IsovalentBFDNodeConfigOverrideApplyConfiguration](
			"isovalentbfdnodeconfigoverrides",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *isovalentcomv1alpha1.IsovalentBFDNodeConfigOverride {
				return &isovalentcomv1alpha1.IsovalentBFDNodeConfigOverride{}
			},
			func() *isovalentcomv1alpha1.IsovalentBFDNodeConfigOverrideList {
				return &isovalentcomv1alpha1.IsovalentBFDNodeConfigOverrideList{}
			},
		),
	}
}
