// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	isovalentcomv1alpha1 "github.com/cilium/cilium/pkg/k8s/apis/isovalent.com/v1alpha1"
	applyconfigurationisovalentcomv1alpha1 "github.com/cilium/cilium/pkg/k8s/client/applyconfiguration/isovalent.com/v1alpha1"
	scheme "github.com/cilium/cilium/pkg/k8s/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// IsovalentClusterwideEncryptionPoliciesGetter has a method to return a IsovalentClusterwideEncryptionPolicyInterface.
// A group's client should implement this interface.
type IsovalentClusterwideEncryptionPoliciesGetter interface {
	IsovalentClusterwideEncryptionPolicies() IsovalentClusterwideEncryptionPolicyInterface
}

// IsovalentClusterwideEncryptionPolicyInterface has methods to work with IsovalentClusterwideEncryptionPolicy resources.
type IsovalentClusterwideEncryptionPolicyInterface interface {
	Create(ctx context.Context, isovalentClusterwideEncryptionPolicy *isovalentcomv1alpha1.IsovalentClusterwideEncryptionPolicy, opts v1.CreateOptions) (*isovalentcomv1alpha1.IsovalentClusterwideEncryptionPolicy, error)
	Update(ctx context.Context, isovalentClusterwideEncryptionPolicy *isovalentcomv1alpha1.IsovalentClusterwideEncryptionPolicy, opts v1.UpdateOptions) (*isovalentcomv1alpha1.IsovalentClusterwideEncryptionPolicy, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*isovalentcomv1alpha1.IsovalentClusterwideEncryptionPolicy, error)
	List(ctx context.Context, opts v1.ListOptions) (*isovalentcomv1alpha1.IsovalentClusterwideEncryptionPolicyList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *isovalentcomv1alpha1.IsovalentClusterwideEncryptionPolicy, err error)
	Apply(ctx context.Context, isovalentClusterwideEncryptionPolicy *applyconfigurationisovalentcomv1alpha1.IsovalentClusterwideEncryptionPolicyApplyConfiguration, opts v1.ApplyOptions) (result *isovalentcomv1alpha1.IsovalentClusterwideEncryptionPolicy, err error)
	IsovalentClusterwideEncryptionPolicyExpansion
}

// isovalentClusterwideEncryptionPolicies implements IsovalentClusterwideEncryptionPolicyInterface
type isovalentClusterwideEncryptionPolicies struct {
	*gentype.ClientWithListAndApply[*isovalentcomv1alpha1.IsovalentClusterwideEncryptionPolicy, *isovalentcomv1alpha1.IsovalentClusterwideEncryptionPolicyList, *applyconfigurationisovalentcomv1alpha1.IsovalentClusterwideEncryptionPolicyApplyConfiguration]
}

// newIsovalentClusterwideEncryptionPolicies returns a IsovalentClusterwideEncryptionPolicies
func newIsovalentClusterwideEncryptionPolicies(c *IsovalentV1alpha1Client) *isovalentClusterwideEncryptionPolicies {
	return &isovalentClusterwideEncryptionPolicies{
		gentype.NewClientWithListAndApply[*isovalentcomv1alpha1.IsovalentClusterwideEncryptionPolicy, *isovalentcomv1alpha1.IsovalentClusterwideEncryptionPolicyList, *applyconfigurationisovalentcomv1alpha1.IsovalentClusterwideEncryptionPolicyApplyConfiguration](
			"isovalentclusterwideencryptionpolicies",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *isovalentcomv1alpha1.IsovalentClusterwideEncryptionPolicy {
				return &isovalentcomv1alpha1.IsovalentClusterwideEncryptionPolicy{}
			},
			func() *isovalentcomv1alpha1.IsovalentClusterwideEncryptionPolicyList {
				return &isovalentcomv1alpha1.IsovalentClusterwideEncryptionPolicyList{}
			},
		),
	}
}
