// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	isovalentcomv1alpha1 "github.com/cilium/cilium/pkg/k8s/apis/isovalent.com/v1alpha1"
	scheme "github.com/cilium/cilium/pkg/k8s/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// IsovalentWAFPoliciesGetter has a method to return a IsovalentWAFPolicyInterface.
// A group's client should implement this interface.
type IsovalentWAFPoliciesGetter interface {
	IsovalentWAFPolicies(namespace string) IsovalentWAFPolicyInterface
}

// IsovalentWAFPolicyInterface has methods to work with IsovalentWAFPolicy resources.
type IsovalentWAFPolicyInterface interface {
	Create(ctx context.Context, isovalentWAFPolicy *isovalentcomv1alpha1.IsovalentWAFPolicy, opts v1.CreateOptions) (*isovalentcomv1alpha1.IsovalentWAFPolicy, error)
	Update(ctx context.Context, isovalentWAFPolicy *isovalentcomv1alpha1.IsovalentWAFPolicy, opts v1.UpdateOptions) (*isovalentcomv1alpha1.IsovalentWAFPolicy, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, isovalentWAFPolicy *isovalentcomv1alpha1.IsovalentWAFPolicy, opts v1.UpdateOptions) (*isovalentcomv1alpha1.IsovalentWAFPolicy, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*isovalentcomv1alpha1.IsovalentWAFPolicy, error)
	List(ctx context.Context, opts v1.ListOptions) (*isovalentcomv1alpha1.IsovalentWAFPolicyList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *isovalentcomv1alpha1.IsovalentWAFPolicy, err error)
	IsovalentWAFPolicyExpansion
}

// isovalentWAFPolicies implements IsovalentWAFPolicyInterface
type isovalentWAFPolicies struct {
	*gentype.ClientWithList[*isovalentcomv1alpha1.IsovalentWAFPolicy, *isovalentcomv1alpha1.IsovalentWAFPolicyList]
}

// newIsovalentWAFPolicies returns a IsovalentWAFPolicies
func newIsovalentWAFPolicies(c *IsovalentV1alpha1Client, namespace string) *isovalentWAFPolicies {
	return &isovalentWAFPolicies{
		gentype.NewClientWithList[*isovalentcomv1alpha1.IsovalentWAFPolicy, *isovalentcomv1alpha1.IsovalentWAFPolicyList](
			"isovalentwafpolicies",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *isovalentcomv1alpha1.IsovalentWAFPolicy { return &isovalentcomv1alpha1.IsovalentWAFPolicy{} },
			func() *isovalentcomv1alpha1.IsovalentWAFPolicyList {
				return &isovalentcomv1alpha1.IsovalentWAFPolicyList{}
			},
		),
	}
}
