// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"

	v1alpha1 "github.com/cilium/cilium/pkg/k8s/apis/isovalent.com/v1alpha1"
	scheme "github.com/cilium/cilium/pkg/k8s/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// LBBackendPoolsGetter has a method to return a LBBackendPoolInterface.
// A group's client should implement this interface.
type LBBackendPoolsGetter interface {
	LBBackendPools(namespace string) LBBackendPoolInterface
}

// LBBackendPoolInterface has methods to work with LBBackendPool resources.
type LBBackendPoolInterface interface {
	Create(ctx context.Context, lBBackendPool *v1alpha1.LBBackendPool, opts v1.CreateOptions) (*v1alpha1.LBBackendPool, error)
	Update(ctx context.Context, lBBackendPool *v1alpha1.LBBackendPool, opts v1.UpdateOptions) (*v1alpha1.LBBackendPool, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, lBBackendPool *v1alpha1.LBBackendPool, opts v1.UpdateOptions) (*v1alpha1.LBBackendPool, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.LBBackendPool, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.LBBackendPoolList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.LBBackendPool, err error)
	LBBackendPoolExpansion
}

// lBBackendPools implements LBBackendPoolInterface
type lBBackendPools struct {
	*gentype.ClientWithList[*v1alpha1.LBBackendPool, *v1alpha1.LBBackendPoolList]
}

// newLBBackendPools returns a LBBackendPools
func newLBBackendPools(c *IsovalentV1alpha1Client, namespace string) *lBBackendPools {
	return &lBBackendPools{
		gentype.NewClientWithList[*v1alpha1.LBBackendPool, *v1alpha1.LBBackendPoolList](
			"lbbackendpools",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *v1alpha1.LBBackendPool { return &v1alpha1.LBBackendPool{} },
			func() *v1alpha1.LBBackendPoolList { return &v1alpha1.LBBackendPoolList{} }),
	}
}
