// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/cilium/cilium/pkg/k8s/apis/isovalent.com/v1alpha1"
	scheme "github.com/cilium/cilium/pkg/k8s/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// LBVIPsGetter has a method to return a LBVIPInterface.
// A group's client should implement this interface.
type LBVIPsGetter interface {
	LBVIPs(namespace string) LBVIPInterface
}

// LBVIPInterface has methods to work with LBVIP resources.
type LBVIPInterface interface {
	Create(ctx context.Context, lBVIP *v1alpha1.LBVIP, opts v1.CreateOptions) (*v1alpha1.LBVIP, error)
	Update(ctx context.Context, lBVIP *v1alpha1.LBVIP, opts v1.UpdateOptions) (*v1alpha1.LBVIP, error)
	UpdateStatus(ctx context.Context, lBVIP *v1alpha1.LBVIP, opts v1.UpdateOptions) (*v1alpha1.LBVIP, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.LBVIP, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.LBVIPList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.LBVIP, err error)
	LBVIPExpansion
}

// lBVIPs implements LBVIPInterface
type lBVIPs struct {
	client rest.Interface
	ns     string
}

// newLBVIPs returns a LBVIPs
func newLBVIPs(c *IsovalentV1alpha1Client, namespace string) *lBVIPs {
	return &lBVIPs{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the lBVIP, and returns the corresponding lBVIP object, and an error if there is any.
func (c *lBVIPs) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.LBVIP, err error) {
	result = &v1alpha1.LBVIP{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("lbvips").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of LBVIPs that match those selectors.
func (c *lBVIPs) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.LBVIPList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.LBVIPList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("lbvips").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested lBVIPs.
func (c *lBVIPs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("lbvips").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a lBVIP and creates it.  Returns the server's representation of the lBVIP, and an error, if there is any.
func (c *lBVIPs) Create(ctx context.Context, lBVIP *v1alpha1.LBVIP, opts v1.CreateOptions) (result *v1alpha1.LBVIP, err error) {
	result = &v1alpha1.LBVIP{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("lbvips").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(lBVIP).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a lBVIP and updates it. Returns the server's representation of the lBVIP, and an error, if there is any.
func (c *lBVIPs) Update(ctx context.Context, lBVIP *v1alpha1.LBVIP, opts v1.UpdateOptions) (result *v1alpha1.LBVIP, err error) {
	result = &v1alpha1.LBVIP{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("lbvips").
		Name(lBVIP.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(lBVIP).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *lBVIPs) UpdateStatus(ctx context.Context, lBVIP *v1alpha1.LBVIP, opts v1.UpdateOptions) (result *v1alpha1.LBVIP, err error) {
	result = &v1alpha1.LBVIP{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("lbvips").
		Name(lBVIP.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(lBVIP).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the lBVIP and deletes it. Returns an error if one occurs.
func (c *lBVIPs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("lbvips").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *lBVIPs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("lbvips").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched lBVIP.
func (c *lBVIPs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.LBVIP, err error) {
	result = &v1alpha1.LBVIP{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("lbvips").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
