// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"

	v1alpha1 "github.com/cilium/cilium/pkg/k8s/apis/isovalent.com/v1alpha1"
	scheme "github.com/cilium/cilium/pkg/k8s/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// LBVIPsGetter has a method to return a LBVIPInterface.
// A group's client should implement this interface.
type LBVIPsGetter interface {
	LBVIPs(namespace string) LBVIPInterface
}

// LBVIPInterface has methods to work with LBVIP resources.
type LBVIPInterface interface {
	Create(ctx context.Context, lBVIP *v1alpha1.LBVIP, opts v1.CreateOptions) (*v1alpha1.LBVIP, error)
	Update(ctx context.Context, lBVIP *v1alpha1.LBVIP, opts v1.UpdateOptions) (*v1alpha1.LBVIP, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, lBVIP *v1alpha1.LBVIP, opts v1.UpdateOptions) (*v1alpha1.LBVIP, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.LBVIP, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.LBVIPList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.LBVIP, err error)
	LBVIPExpansion
}

// lBVIPs implements LBVIPInterface
type lBVIPs struct {
	*gentype.ClientWithList[*v1alpha1.LBVIP, *v1alpha1.LBVIPList]
}

// newLBVIPs returns a LBVIPs
func newLBVIPs(c *IsovalentV1alpha1Client, namespace string) *lBVIPs {
	return &lBVIPs{
		gentype.NewClientWithList[*v1alpha1.LBVIP, *v1alpha1.LBVIPList](
			"lbvips",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *v1alpha1.LBVIP { return &v1alpha1.LBVIP{} },
			func() *v1alpha1.LBVIPList { return &v1alpha1.LBVIPList{} }),
	}
}
