// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	isovalentcomv1alpha1 "github.com/cilium/cilium/pkg/k8s/apis/isovalent.com/v1alpha1"
	applyconfigurationisovalentcomv1alpha1 "github.com/cilium/cilium/pkg/k8s/client/applyconfiguration/isovalent.com/v1alpha1"
	scheme "github.com/cilium/cilium/pkg/k8s/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// PrivateNetworkEndpointSlicesGetter has a method to return a PrivateNetworkEndpointSliceInterface.
// A group's client should implement this interface.
type PrivateNetworkEndpointSlicesGetter interface {
	PrivateNetworkEndpointSlices(namespace string) PrivateNetworkEndpointSliceInterface
}

// PrivateNetworkEndpointSliceInterface has methods to work with PrivateNetworkEndpointSlice resources.
type PrivateNetworkEndpointSliceInterface interface {
	Create(ctx context.Context, privateNetworkEndpointSlice *isovalentcomv1alpha1.PrivateNetworkEndpointSlice, opts v1.CreateOptions) (*isovalentcomv1alpha1.PrivateNetworkEndpointSlice, error)
	Update(ctx context.Context, privateNetworkEndpointSlice *isovalentcomv1alpha1.PrivateNetworkEndpointSlice, opts v1.UpdateOptions) (*isovalentcomv1alpha1.PrivateNetworkEndpointSlice, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*isovalentcomv1alpha1.PrivateNetworkEndpointSlice, error)
	List(ctx context.Context, opts v1.ListOptions) (*isovalentcomv1alpha1.PrivateNetworkEndpointSliceList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *isovalentcomv1alpha1.PrivateNetworkEndpointSlice, err error)
	Apply(ctx context.Context, privateNetworkEndpointSlice *applyconfigurationisovalentcomv1alpha1.PrivateNetworkEndpointSliceApplyConfiguration, opts v1.ApplyOptions) (result *isovalentcomv1alpha1.PrivateNetworkEndpointSlice, err error)
	PrivateNetworkEndpointSliceExpansion
}

// privateNetworkEndpointSlices implements PrivateNetworkEndpointSliceInterface
type privateNetworkEndpointSlices struct {
	*gentype.ClientWithListAndApply[*isovalentcomv1alpha1.PrivateNetworkEndpointSlice, *isovalentcomv1alpha1.PrivateNetworkEndpointSliceList, *applyconfigurationisovalentcomv1alpha1.PrivateNetworkEndpointSliceApplyConfiguration]
}

// newPrivateNetworkEndpointSlices returns a PrivateNetworkEndpointSlices
func newPrivateNetworkEndpointSlices(c *IsovalentV1alpha1Client, namespace string) *privateNetworkEndpointSlices {
	return &privateNetworkEndpointSlices{
		gentype.NewClientWithListAndApply[*isovalentcomv1alpha1.PrivateNetworkEndpointSlice, *isovalentcomv1alpha1.PrivateNetworkEndpointSliceList, *applyconfigurationisovalentcomv1alpha1.PrivateNetworkEndpointSliceApplyConfiguration](
			"privatenetworkendpointslices",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *isovalentcomv1alpha1.PrivateNetworkEndpointSlice {
				return &isovalentcomv1alpha1.PrivateNetworkEndpointSlice{}
			},
			func() *isovalentcomv1alpha1.PrivateNetworkEndpointSliceList {
				return &isovalentcomv1alpha1.PrivateNetworkEndpointSliceList{}
			},
		),
	}
}
