// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	isovalentcomv1alpha1 "github.com/cilium/cilium/pkg/k8s/apis/isovalent.com/v1alpha1"
	scheme "github.com/cilium/cilium/pkg/k8s/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// PrivateNetworkNodeAttachmentsGetter has a method to return a PrivateNetworkNodeAttachmentInterface.
// A group's client should implement this interface.
type PrivateNetworkNodeAttachmentsGetter interface {
	PrivateNetworkNodeAttachments() PrivateNetworkNodeAttachmentInterface
}

// PrivateNetworkNodeAttachmentInterface has methods to work with PrivateNetworkNodeAttachment resources.
type PrivateNetworkNodeAttachmentInterface interface {
	Create(ctx context.Context, privateNetworkNodeAttachment *isovalentcomv1alpha1.PrivateNetworkNodeAttachment, opts v1.CreateOptions) (*isovalentcomv1alpha1.PrivateNetworkNodeAttachment, error)
	Update(ctx context.Context, privateNetworkNodeAttachment *isovalentcomv1alpha1.PrivateNetworkNodeAttachment, opts v1.UpdateOptions) (*isovalentcomv1alpha1.PrivateNetworkNodeAttachment, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*isovalentcomv1alpha1.PrivateNetworkNodeAttachment, error)
	List(ctx context.Context, opts v1.ListOptions) (*isovalentcomv1alpha1.PrivateNetworkNodeAttachmentList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *isovalentcomv1alpha1.PrivateNetworkNodeAttachment, err error)
	PrivateNetworkNodeAttachmentExpansion
}

// privateNetworkNodeAttachments implements PrivateNetworkNodeAttachmentInterface
type privateNetworkNodeAttachments struct {
	*gentype.ClientWithList[*isovalentcomv1alpha1.PrivateNetworkNodeAttachment, *isovalentcomv1alpha1.PrivateNetworkNodeAttachmentList]
}

// newPrivateNetworkNodeAttachments returns a PrivateNetworkNodeAttachments
func newPrivateNetworkNodeAttachments(c *IsovalentV1alpha1Client) *privateNetworkNodeAttachments {
	return &privateNetworkNodeAttachments{
		gentype.NewClientWithList[*isovalentcomv1alpha1.PrivateNetworkNodeAttachment, *isovalentcomv1alpha1.PrivateNetworkNodeAttachmentList](
			"privatenetworknodeattachments",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *isovalentcomv1alpha1.PrivateNetworkNodeAttachment {
				return &isovalentcomv1alpha1.PrivateNetworkNodeAttachment{}
			},
			func() *isovalentcomv1alpha1.PrivateNetworkNodeAttachmentList {
				return &isovalentcomv1alpha1.PrivateNetworkNodeAttachmentList{}
			},
		),
	}
}
