// Code generated by dpgen. DO NOT EDIT.

// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

package config

import "github.com/cilium/cilium/pkg/datapath/types"

// BPFHostEnterprise is a configuration struct for a Cilium datapath object.
//
// Warning: do not instantiate directly! Always use [NewBPFHostEnterprise] to
// ensure the default values configured in the ELF are honored.
type BPFHostEnterprise struct {
	// The interface index of the evpn vxlan device.
	EVPNDeviceIfIndex uint32 `config:"evpn_device_ifindex"`
	// The mac address of the evpn vxlan device.
	EVPNDeviceMAC types.MACAddr `config:"evpn_device_mac"`
	// True if evpn feature is enabled.
	EVPNEnable bool `config:"evpn_enable"`
	// True if running on network bridge.
	PrivnetBridgeEnable bool `config:"privnet_bridge_enable"`
	// True if the endpoint is in a non-default network.
	PrivnetEnable bool `config:"privnet_enable"`
	// True if host / remote node traffic is allowed into privnet.
	PrivnetHostReachability bool `config:"privnet_host_reachability"`
	// Link-local IPv4 address used to SNAT host traffic to PrivNet.
	PrivnetHostSNATIPv4 types.V4Addr `config:"privnet_host_snat_ipv4"`
	// Link-local IPv6 address used to SNAT host traffic to PrivNet.
	PrivnetHostSNATIPv6 types.V6Addr `config:"privnet_host_snat_ipv6"`
	// True if running in local access mode.
	PrivnetLocalAccessEnable bool `config:"privnet_local_access_enable"`
	// The security identifier for unknown network traffic.
	PrivnetUnknownSecID uint32 `config:"privnet_unknown_sec_id"`
}

func NewBPFHostEnterprise() *BPFHostEnterprise {
	return &BPFHostEnterprise{0x0,
		cast[types.MACAddr]([]byte{0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}),
		false, false, false, false, cast[types.V4Addr]([]byte{0x0, 0x0, 0x0, 0x0}),
		cast[types.V6Addr]([]byte{0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}),
		false, 0x0}
}
