// Code generated by dpgen. DO NOT EDIT.

// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

package config

// BPFLXCEnterprise is a configuration struct for a Cilium datapath object.
// Warning: do not instantiate directly! Always use [NewBPFLXCEnterprise] to
// ensure the default values configured in the ELF are honored.
type BPFLXCEnterprise struct {
	// True if running on network bridge.
	PrivnetBridgeEnable bool `config:"privnet_bridge_enable"`
	// True if the endpoint is in a non-default network.
	PrivnetEnable bool `config:"privnet_enable"`
	// The endpoint's IPv6 address within the network.
	PrivnetIPv6 [16]byte `config:"privnet_ipv6"`
	// The identifier of the private network.
	PrivnetNetworkID uint16 `config:"privnet_network_id"`
	// The security identifier for unknown network traffic.
	PrivnetUnknownSecID uint32 `config:"privnet_unknown_sec_id"`
}

func NewBPFLXCEnterprise() *BPFLXCEnterprise {
	return &BPFLXCEnterprise{false, false,
		[16]byte{0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0},
		0x0, 0x0}
}
