apiVersion: isovalent.com/v1alpha1
kind: IsovalentNetworkPolicy
metadata:
  name: allow-egress-l7-{{ .SubjectName }}-on-http-{{ .Port }}
  namespace: {{ .TestNamespace }}
  labels:
    app.kubernetes.io/part-of: cilium-cli-privnet
spec:
  endpointSelector:
    matchLabels:
      name: {{ .SubjectName }}
      "cni:com.isovalent.private-network.name": {{ .Network }}
  egress:
    - toPorts:
        - ports:
            - port: "{{ .Port }}"
              protocol: TCP
          rules:
            http:
              - {}
