apiVersion: cilium.io/v1alpha1
kind: CiliumConfig
metadata:
  labels:
    app.kubernetes.io/name: clife
    app.kubernetes.io/managed-by: kustomize
  name: config
spec:
  cluster:
    name: default
  debug:
    enabled: true
    verbose: "envoy"
  bpf:
    monitorAggregation: "none"
  securityContext:
    privileged: true
  ipam:
    mode: "cluster-pool"
    operator:
      clusterPoolIPv4MaskSize: 
      clusterPoolIPv4PodCIDRList:
  cni:
    binPath: "/var/lib/cni/bin"
    confPath: "/var/run/multus/cni/net.d"
    # portmap is needed for supporting HostPort without KPR
    chainingMode: portmap
    exclusive: false
  prometheus:
    serviceMonitor:
      enabled: false
  hubble:
    enabled: true
    relay: 
      enabled: true
      retryTimeout: "5s"
  sessionAffinity: true
  kubeProxyReplacement: false
  # TODO: not sure this is needed, was historically used in the CuTE configuration
  endpointRoutes: {enabled: true}
  # avoid conflicts
  clusterHealthPort: 9940
  # default firewall configuration
  tunnelPort: 4789
  enterprise:
    featureGate:
      minimumMaturity: "Alpha"
      approved:
      - CNIChainingMode
    clustermesh:
      phantomServices:
        enabled: true
  extraEnv:
  # Disabling due to the cache being altered -> panic
  # https://github.com/cilium/cilium/pull/41005/commits/645be2636bd6c67a0d1fcbb8a5524da71919e124
  # - name: "KUBE_CACHE_MUTATION_DETECTOR"
  #   value: "true"
  - name: "CILIUM_FEATURE_METRICS_WITH_DEFAULTS"
    value: "true"
  # Disabling Envoy version check as it gets reported in the logs
  # although the default defined in values.yaml is used.
  disableEnvoyVersionCheck: true
