apiVersion: cilium.io/v1alpha1
kind: CiliumConfig
metadata:
  labels:
    app.kubernetes.io/name: clife
    app.kubernetes.io/managed-by: kustomize
  name: config
spec:
  cluster:
    name: default
  debug:
    enabled: true
    verbose: "envoy"
  bpf:
    monitorAggregation: "none"
  securityContext:
    privileged: true
  ipam:
    mode: "cluster-pool"
    operator:
      # it gets automatically populated based on CI settings 
      clusterPoolIPv4MaskSize:
      clusterPoolIPv4PodCIDRList:
  cni:
    binPath: "/var/lib/cni/bin"
    confPath: "/var/run/multus/cni/net.d"
    chainingMode: none
    exclusive: false
  prometheus:
    serviceMonitor:
      enabled: false
  hubble:
    enabled: true
    relay:
      enabled: true
      retryTimeout: "5s"
  sessionAffinity: true
  kubeProxyReplacement: true
  # host namespace only is required for running OpenShift Service Mesh
  socketLB:
    hostNamespaceOnly: true
  k8sServiceHost:
  k8sServicePort:
  # TODO: not sure this is needed, was historically used in the CuTE configuration
  endpointRoutes: {enabled: true}
  # avoid conflicts
  clusterHealthPort: 9940
  # default firewall configuration
  tunnelPort: 4789
  enterprise:
    featureGate:
      minimumMaturity: "Alpha"
    clustermesh:
      phantomServices:
        enabled: true
  # Pin Envoy image to resolve binary compatibility issues. This override is necessary because the default in values.yaml gets overwritten during CLife image rebuilds.
  # The issue is that Envoy binaries are copied from Ubuntu 24.04 to UBI, and they are incompatible with RHEL 9.6 libraries
  # This is a temporary workaround.
  envoy:
    image:
      repository: quay.io/cilium/cilium-envoy
      tag: v1.35.3-1760614940-cb5737105ff9a4ca5d080c0c8f3ea1bfdc08de83
      digest: sha256:808c986a99e2a1ea9785b49604a1ccd1e1cdc21d4b7a2ff1236cc31788ea9b45
      useDigest: true
  extraEnv:
  # Disabling due to the cache being altered -> panic
  # https://github.com/cilium/cilium/pull/41005/commits/645be2636bd6c67a0d1fcbb8a5524da71919e124
  # - name: "KUBE_CACHE_MUTATION_DETECTOR"
  #   value: "true"
  - name: "CILIUM_FEATURE_METRICS_WITH_DEFAULTS"
    value: "true"
  # Disabling Envoy version check as it gets reported in the logs
  # although the default defined in values.yaml is used.
  disableEnvoyVersionCheck: true
