apiVersion: cilium.io/v1alpha1
kind: CiliumConfig
metadata:
  labels:
    app.kubernetes.io/name: clife
    app.kubernetes.io/managed-by: kustomize
  name: config
spec:
  cluster:
    name: default
  debug:
    enabled: true
    verbose: "envoy"
  bpf:
    monitorAggregation: "none"
    masquerade: true
    ctAccounting: true
    hostLegacyRouting: true
    lbAlgorithmAnnotation: true
    lbModeAnnotation: true
  enableIPv4Masquerade: true
  securityContext:
    privileged: true
  ipam:
    mode: "cluster-pool"
    operator:
      # it gets automatically populated by the CuTE
      clusterPoolIPv4MaskSize: ${POD_CIDR_HOST_PREFIX}
      clusterPoolIPv4PodCIDRList:
      - ${POD_CIDR}
  cni:
    binPath: "/var/lib/cni/bin"
    confPath: "/var/run/multus/cni/net.d"
    chainingMode: none
    exclusive: false
  autoDirectNodeRoutes: true
  directRoutingSkipUnreachable: true
  ipv4NativeRoutingCIDR: ${POD_CIDR}
  prometheus:
    serviceMonitor:
      enabled: false
  hubble:
    enabled: false
  sessionAffinity: true
  kubeProxyReplacement: true
  routingMode: native
  ipv6:
    enabled: false
  # host namespace only is required for running OpenShift Service Mesh
  socketLB:
    hostNamespaceOnly: true
  k8sServiceHost: ${KUBERNETES_SERVICE_HOST}
  k8sServicePort: ${KUBERNETES_SERVICE_PORT}
  # TODO: not sure this is needed, was historically used in the CuTE configuration
  endpointRoutes: {enabled: true}
  # avoid conflicts
  clusterHealthPort: 9940
  # default firewall configuration
  enterprise:
    bfd:
      enabled: true
    bgpControlPlane:
      enabled: true
      enableServiceHealthChecking: true
      nodeMaintenance:
        # immediate withdraw -> as any other T1 node can take over (at least in T1&T2 deployment mode)
        withdrawTime: 1ms
        gracefulShutdownCommunity:
          enabled: false # recommended if BGP router supports it
    egressGatewayHA:
      enabled: false
    featureGate:
      minimumMaturity: Alpha
      approved:
        - BFD
        - EnterpriseBGPControlPlane
        - IPAMMultiPool
    loadbalancer:
      enabled: true
  loadBalancer:
    acceleration: disabled
    dsrDispatch: ipip
    mode: dsr
  envoy:
    nodeSelector:
      service.cilium.io/node: "t2"
    dnsPolicy: ClusterFirstWithHostNet
    extraHostPathMounts:
      - name: envoy-accesslog
        mountPath: /var/log/envoy
        hostPath: /var/log/envoy
        hostPathType: DirectoryOrCreate
        readOnly: false
        mountPropagation: HostToContainer
    prometheus:
      enabled: true
      serviceMonitor:
        enabled: true
  envoyConfig:
    enabled: true
  extraConfig:
    loadbalancer-cp-requestid-generate: "true"
    loadbalancer-cp-requestid-response: "true"
    loadbalancer-cp-accesslog-file-path: "/var/log/envoy/accesslog.log"
    loadbalancer-cp-accesslog-enable-hc: "true"
    loadbalancer-cp-t2-use-remote-address: "true"
    loadbalancer-cp-t2-xff-num-trusted-hops: "0"
    # Disable hubble-flow-exporter
    export-file-path: "" # performance optimization
  extraEnv:
  - name: "KUBE_CACHE_MUTATION_DETECTOR"
    value: "true"
  - name: "CILIUM_FEATURE_METRICS_WITH_DEFAULTS"
    value: "true"
  # Disabling Envoy version check as it gets reported in the logs
  # although the default defined in values.yaml is used.
  disableEnvoyVersionCheck: true
  nodeinit:
    enabled: true
    startup:
      preScript: |
        # Enable netfilter
        sudo modprobe br_netfilter
        # Enable IP forwarding and allow Envoy to bind to all ports
        sudo tee /etc/sysctl.d/kubernetes.conf <<EOF
        net.ipv4.ip_forward = 1
        net.ipv4.ip_unprivileged_port_start = 0
        EOF
        sudo sysctl --system
