// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	isovalentcomv1 "github.com/cilium/cilium/pkg/k8s/apis/isovalent.com/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// IsovalentBGPPolicyLister helps list IsovalentBGPPolicies.
// All objects returned here must be treated as read-only.
type IsovalentBGPPolicyLister interface {
	// List lists all IsovalentBGPPolicies in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*isovalentcomv1.IsovalentBGPPolicy, err error)
	// Get retrieves the IsovalentBGPPolicy from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*isovalentcomv1.IsovalentBGPPolicy, error)
	IsovalentBGPPolicyListerExpansion
}

// isovalentBGPPolicyLister implements the IsovalentBGPPolicyLister interface.
type isovalentBGPPolicyLister struct {
	listers.ResourceIndexer[*isovalentcomv1.IsovalentBGPPolicy]
}

// NewIsovalentBGPPolicyLister returns a new IsovalentBGPPolicyLister.
func NewIsovalentBGPPolicyLister(indexer cache.Indexer) IsovalentBGPPolicyLister {
	return &isovalentBGPPolicyLister{listers.New[*isovalentcomv1.IsovalentBGPPolicy](indexer, isovalentcomv1.Resource("isovalentbgppolicy"))}
}
