// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	isovalentcomv1 "github.com/cilium/cilium/pkg/k8s/apis/isovalent.com/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// IsovalentBGPClusterConfigLister helps list IsovalentBGPClusterConfigs.
// All objects returned here must be treated as read-only.
type IsovalentBGPClusterConfigLister interface {
	// List lists all IsovalentBGPClusterConfigs in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*isovalentcomv1.IsovalentBGPClusterConfig, err error)
	// Get retrieves the IsovalentBGPClusterConfig from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*isovalentcomv1.IsovalentBGPClusterConfig, error)
	IsovalentBGPClusterConfigListerExpansion
}

// isovalentBGPClusterConfigLister implements the IsovalentBGPClusterConfigLister interface.
type isovalentBGPClusterConfigLister struct {
	listers.ResourceIndexer[*isovalentcomv1.IsovalentBGPClusterConfig]
}

// NewIsovalentBGPClusterConfigLister returns a new IsovalentBGPClusterConfigLister.
func NewIsovalentBGPClusterConfigLister(indexer cache.Indexer) IsovalentBGPClusterConfigLister {
	return &isovalentBGPClusterConfigLister{listers.New[*isovalentcomv1.IsovalentBGPClusterConfig](indexer, isovalentcomv1.Resource("isovalentbgpclusterconfig"))}
}
