apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cloudprober-oneoff
spec:
  selector:
    matchLabels:
      other: oneoff
      app: cloudprober
  template:
    metadata:
      labels:
        app: cloudprober
        other: oneoff
    spec:
      volumes:
        - name: cloudprober-config
          configMap:
            name: cloudprober-oneoff-config
        - name: ca-bundle
          configMap:
            name: tls-interception
      containers:
        - name: cloudprober
          image: cloudprober/cloudprober:v0.13.8-1
          command: ["/cloudprober"]
          args:
          - --config_file=/cfg/cloudprober.cfg
          - --cloud_metadata=none
          - --disable_cloud_logging=true
          - --logtostderr
          volumeMounts:
            - name: cloudprober-config
              mountPath: /cfg
            - name: ca-bundle
              mountPath: "/etc/ssl/cert.pem"
              subPath: "ca.crt"
          ports:
            - name: http
              containerPort: 9313
