prometheus:
  prometheusSpec:
    serviceMonitorSelector: {}
    serviceMonitorSelectorNilUsesHelmValues: false
kube-state-metrics:
  metricLabelsAllowlist:
  - "nodes=[service.cilium.io/node]"
prometheus-node-exporter:
  extraArgs:
  - --collector.ethtool
