//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by deepequal-gen. DO NOT EDIT.

package v1

// DeepEqual is an autogenerated deepequal function, deeply comparing the
// receiver with other. in must be non-nil.
func (in *BGPAdvertisement) DeepEqual(other *BGPAdvertisement) bool {
	if other == nil {
		return false
	}

	if in.AdvertisementType != other.AdvertisementType {
		return false
	}
	if (in.Service == nil) != (other.Service == nil) {
		return false
	} else if in.Service != nil {
		if !in.Service.DeepEqual(other.Service) {
			return false
		}
	}

	if (in.Selector == nil) != (other.Selector == nil) {
		return false
	} else if in.Selector != nil {
		if !in.Selector.DeepEqual(other.Selector) {
			return false
		}
	}

	if (in.Attributes == nil) != (other.Attributes == nil) {
		return false
	} else if in.Attributes != nil {
		if !in.Attributes.DeepEqual(other.Attributes) {
			return false
		}
	}

	return true
}

// DeepEqual is an autogenerated deepequal function, deeply comparing the
// receiver with other. in must be non-nil.
func (in *BGPAutoDiscovery) DeepEqual(other *BGPAutoDiscovery) bool {
	if other == nil {
		return false
	}

	if in.Mode != other.Mode {
		return false
	}
	if (in.Unnumbered == nil) != (other.Unnumbered == nil) {
		return false
	} else if in.Unnumbered != nil {
		if !in.Unnumbered.DeepEqual(other.Unnumbered) {
			return false
		}
	}

	return true
}

// DeepEqual is an autogenerated deepequal function, deeply comparing the
// receiver with other. in must be non-nil.
func (in *BGPImportPolicy) DeepEqual(other *BGPImportPolicy) bool {
	if other == nil {
		return false
	}

	if ((in.Statements != nil) && (other.Statements != nil)) || ((in.Statements == nil) != (other.Statements == nil)) {
		in, other := &in.Statements, &other.Statements
		if other == nil {
			return false
		}

		if len(*in) != len(*other) {
			return false
		} else {
			for i, inElement := range *in {
				if !inElement.DeepEqual(&(*other)[i]) {
					return false
				}
			}
		}
	}

	return true
}

// DeepEqual is an autogenerated deepequal function, deeply comparing the
// receiver with other. in must be non-nil.
func (in *BGPPolicyActions) DeepEqual(other *BGPPolicyActions) bool {
	if other == nil {
		return false
	}

	if in.RouteAction != other.RouteAction {
		return false
	}

	return true
}

// DeepEqual is an autogenerated deepequal function, deeply comparing the
// receiver with other. in must be non-nil.
func (in *BGPPolicyConditions) DeepEqual(other *BGPPolicyConditions) bool {
	if other == nil {
		return false
	}

	if (in.PrefixesV4 == nil) != (other.PrefixesV4 == nil) {
		return false
	} else if in.PrefixesV4 != nil {
		if !in.PrefixesV4.DeepEqual(other.PrefixesV4) {
			return false
		}
	}

	if (in.PrefixesV6 == nil) != (other.PrefixesV6 == nil) {
		return false
	} else if in.PrefixesV6 != nil {
		if !in.PrefixesV6.DeepEqual(other.PrefixesV6) {
			return false
		}
	}

	return true
}

// DeepEqual is an autogenerated deepequal function, deeply comparing the
// receiver with other. in must be non-nil.
func (in *BGPPolicyStatement) DeepEqual(other *BGPPolicyStatement) bool {
	if other == nil {
		return false
	}

	if !in.Conditions.DeepEqual(&other.Conditions) {
		return false
	}

	if in.Actions != other.Actions {
		return false
	}

	return true
}

// DeepEqual is an autogenerated deepequal function, deeply comparing the
// receiver with other. in must be non-nil.
func (in *BGPServiceOptions) DeepEqual(other *BGPServiceOptions) bool {
	if other == nil {
		return false
	}

	if ((in.Addresses != nil) && (other.Addresses != nil)) || ((in.Addresses == nil) != (other.Addresses == nil)) {
		in, other := &in.Addresses, &other.Addresses
		if other == nil {
			return false
		}

		if len(*in) != len(*other) {
			return false
		} else {
			for i, inElement := range *in {
				if inElement != (*other)[i] {
					return false
				}
			}
		}
	}

	if (in.AggregationLengthIPv4 == nil) != (other.AggregationLengthIPv4 == nil) {
		return false
	} else if in.AggregationLengthIPv4 != nil {
		if *in.AggregationLengthIPv4 != *other.AggregationLengthIPv4 {
			return false
		}
	}

	if (in.AggregationLengthIPv6 == nil) != (other.AggregationLengthIPv6 == nil) {
		return false
	} else if in.AggregationLengthIPv6 != nil {
		if *in.AggregationLengthIPv6 != *other.AggregationLengthIPv6 {
			return false
		}
	}

	return true
}

// DeepEqual is an autogenerated deepequal function, deeply comparing the
// receiver with other. in must be non-nil.
func (in *BGPUnnumbered) DeepEqual(other *BGPUnnumbered) bool {
	if other == nil {
		return false
	}

	if in.Interface != other.Interface {
		return false
	}

	return true
}

// DeepEqual is an autogenerated deepequal function, deeply comparing the
// receiver with other. in must be non-nil.
func (in *BGPVRF) DeepEqual(other *BGPVRF) bool {
	if other == nil {
		return false
	}

	if in.VRFRef != other.VRFRef {
		return false
	}
	if (in.ConfigRef == nil) != (other.ConfigRef == nil) {
		return false
	} else if in.ConfigRef != nil {
		if *in.ConfigRef != *other.ConfigRef {
			return false
		}
	}

	if (in.RD == nil) != (other.RD == nil) {
		return false
	} else if in.RD != nil {
		if *in.RD != *other.RD {
			return false
		}
	}

	if ((in.ImportRTs != nil) && (other.ImportRTs != nil)) || ((in.ImportRTs == nil) != (other.ImportRTs == nil)) {
		in, other := &in.ImportRTs, &other.ImportRTs
		if other == nil {
			return false
		}

		if len(*in) != len(*other) {
			return false
		} else {
			for i, inElement := range *in {
				if inElement != (*other)[i] {
					return false
				}
			}
		}
	}

	if ((in.ExportRTs != nil) && (other.ExportRTs != nil)) || ((in.ExportRTs == nil) != (other.ExportRTs == nil)) {
		in, other := &in.ExportRTs, &other.ExportRTs
		if other == nil {
			return false
		}

		if len(*in) != len(*other) {
			return false
		} else {
			for i, inElement := range *in {
				if inElement != (*other)[i] {
					return false
				}
			}
		}
	}

	return true
}

// DeepEqual is an autogenerated deepequal function, deeply comparing the
// receiver with other. in must be non-nil.
func (in *EgressGroup) DeepEqual(other *EgressGroup) bool {
	if other == nil {
		return false
	}

	if (in.NodeSelector == nil) != (other.NodeSelector == nil) {
		return false
	} else if in.NodeSelector != nil {
		if !in.NodeSelector.DeepEqual(other.NodeSelector) {
			return false
		}
	}

	if in.Interface != other.Interface {
		return false
	}
	if in.EgressIP != other.EgressIP {
		return false
	}
	if in.MaxGatewayNodes != other.MaxGatewayNodes {
		return false
	}

	return true
}

// DeepEqual is an autogenerated deepequal function, deeply comparing the
// receiver with other. in must be non-nil.
func (in *EgressRule) DeepEqual(other *EgressRule) bool {
	if other == nil {
		return false
	}

	if (in.NamespaceSelector == nil) != (other.NamespaceSelector == nil) {
		return false
	} else if in.NamespaceSelector != nil {
		if !in.NamespaceSelector.DeepEqual(other.NamespaceSelector) {
			return false
		}
	}

	if (in.PodSelector == nil) != (other.PodSelector == nil) {
		return false
	} else if in.PodSelector != nil {
		if !in.PodSelector.DeepEqual(other.PodSelector) {
			return false
		}
	}

	return true
}

// DeepEqual is an autogenerated deepequal function, deeply comparing the
// receiver with other. in must be non-nil.
func (in *IsovalentBGPAdvertisement) DeepEqual(other *IsovalentBGPAdvertisement) bool {
	if other == nil {
		return false
	}

	if !in.Spec.DeepEqual(&other.Spec) {
		return false
	}

	return true
}

// DeepEqual is an autogenerated deepequal function, deeply comparing the
// receiver with other. in must be non-nil.
func (in *IsovalentBGPAdvertisementSpec) DeepEqual(other *IsovalentBGPAdvertisementSpec) bool {
	if other == nil {
		return false
	}

	if ((in.Advertisements != nil) && (other.Advertisements != nil)) || ((in.Advertisements == nil) != (other.Advertisements == nil)) {
		in, other := &in.Advertisements, &other.Advertisements
		if other == nil {
			return false
		}

		if len(*in) != len(*other) {
			return false
		} else {
			for i, inElement := range *in {
				if !inElement.DeepEqual(&(*other)[i]) {
					return false
				}
			}
		}
	}

	return true
}

// DeepEqual is an autogenerated deepequal function, deeply comparing the
// receiver with other. in must be non-nil.
func (in *IsovalentBGPClusterConfig) DeepEqual(other *IsovalentBGPClusterConfig) bool {
	if other == nil {
		return false
	}

	if !in.Spec.DeepEqual(&other.Spec) {
		return false
	}

	if !in.Status.DeepEqual(&other.Status) {
		return false
	}

	return true
}

// DeepEqual is an autogenerated deepequal function, deeply comparing the
// receiver with other. in must be non-nil.
func (in *IsovalentBGPClusterConfigSpec) DeepEqual(other *IsovalentBGPClusterConfigSpec) bool {
	if other == nil {
		return false
	}

	if (in.NodeSelector == nil) != (other.NodeSelector == nil) {
		return false
	} else if in.NodeSelector != nil {
		if !in.NodeSelector.DeepEqual(other.NodeSelector) {
			return false
		}
	}

	if ((in.BGPInstances != nil) && (other.BGPInstances != nil)) || ((in.BGPInstances == nil) != (other.BGPInstances == nil)) {
		in, other := &in.BGPInstances, &other.BGPInstances
		if other == nil {
			return false
		}

		if len(*in) != len(*other) {
			return false
		} else {
			for i, inElement := range *in {
				if !inElement.DeepEqual(&(*other)[i]) {
					return false
				}
			}
		}
	}

	return true
}

// DeepEqual is an autogenerated deepequal function, deeply comparing the
// receiver with other. in must be non-nil.
func (in *IsovalentBGPClusterConfigStatus) DeepEqual(other *IsovalentBGPClusterConfigStatus) bool {
	if other == nil {
		return false
	}

	return true
}

// DeepEqual is an autogenerated deepequal function, deeply comparing the
// receiver with other. in must be non-nil.
func (in *IsovalentBGPFamilyWithAdverts) DeepEqual(other *IsovalentBGPFamilyWithAdverts) bool {
	if other == nil {
		return false
	}

	if in.CiliumBGPFamily != other.CiliumBGPFamily {
		return false
	}

	if (in.Advertisements == nil) != (other.Advertisements == nil) {
		return false
	} else if in.Advertisements != nil {
		if !in.Advertisements.DeepEqual(other.Advertisements) {
			return false
		}
	}

	if (in.ImportPolicyRef == nil) != (other.ImportPolicyRef == nil) {
		return false
	} else if in.ImportPolicyRef != nil {
		if !in.ImportPolicyRef.DeepEqual(other.ImportPolicyRef) {
			return false
		}
	}

	return true
}

// DeepEqual is an autogenerated deepequal function, deeply comparing the
// receiver with other. in must be non-nil.
func (in *IsovalentBGPInstance) DeepEqual(other *IsovalentBGPInstance) bool {
	if other == nil {
		return false
	}

	if in.Name != other.Name {
		return false
	}
	if (in.LocalASN == nil) != (other.LocalASN == nil) {
		return false
	} else if in.LocalASN != nil {
		if *in.LocalASN != *other.LocalASN {
			return false
		}
	}

	if (in.LocalPort == nil) != (other.LocalPort == nil) {
		return false
	} else if in.LocalPort != nil {
		if *in.LocalPort != *other.LocalPort {
			return false
		}
	}

	if ((in.Peers != nil) && (other.Peers != nil)) || ((in.Peers == nil) != (other.Peers == nil)) {
		in, other := &in.Peers, &other.Peers
		if other == nil {
			return false
		}

		if len(*in) != len(*other) {
			return false
		} else {
			for i, inElement := range *in {
				if !inElement.DeepEqual(&(*other)[i]) {
					return false
				}
			}
		}
	}

	if ((in.VRFs != nil) && (other.VRFs != nil)) || ((in.VRFs == nil) != (other.VRFs == nil)) {
		in, other := &in.VRFs, &other.VRFs
		if other == nil {
			return false
		}

		if len(*in) != len(*other) {
			return false
		} else {
			for i, inElement := range *in {
				if !inElement.DeepEqual(&(*other)[i]) {
					return false
				}
			}
		}
	}

	if (in.RouteReflector == nil) != (other.RouteReflector == nil) {
		return false
	} else if in.RouteReflector != nil {
		if !in.RouteReflector.DeepEqual(other.RouteReflector) {
			return false
		}
	}

	return true
}

// DeepEqual is an autogenerated deepequal function, deeply comparing the
// receiver with other. in must be non-nil.
func (in *IsovalentBGPMaintenance) DeepEqual(other *IsovalentBGPMaintenance) bool {
	if other == nil {
		return false
	}

	if in.Mode != other.Mode {
		return false
	}

	return true
}

// DeepEqual is an autogenerated deepequal function, deeply comparing the
// receiver with other. in must be non-nil.
func (in *IsovalentBGPNodeConfig) DeepEqual(other *IsovalentBGPNodeConfig) bool {
	if other == nil {
		return false
	}

	if !in.Spec.DeepEqual(&other.Spec) {
		return false
	}

	if !in.Status.DeepEqual(&other.Status) {
		return false
	}

	return true
}

// DeepEqual is an autogenerated deepequal function, deeply comparing the
// receiver with other. in must be non-nil.
func (in *IsovalentBGPNodeConfigInstanceOverride) DeepEqual(other *IsovalentBGPNodeConfigInstanceOverride) bool {
	if other == nil {
		return false
	}

	if in.Name != other.Name {
		return false
	}
	if (in.RouterID == nil) != (other.RouterID == nil) {
		return false
	} else if in.RouterID != nil {
		if *in.RouterID != *other.RouterID {
			return false
		}
	}

	if (in.LocalPort == nil) != (other.LocalPort == nil) {
		return false
	} else if in.LocalPort != nil {
		if *in.LocalPort != *other.LocalPort {
			return false
		}
	}

	if (in.SRv6Responder == nil) != (other.SRv6Responder == nil) {
		return false
	} else if in.SRv6Responder != nil {
		if *in.SRv6Responder != *other.SRv6Responder {
			return false
		}
	}

	if (in.LocalASN == nil) != (other.LocalASN == nil) {
		return false
	} else if in.LocalASN != nil {
		if *in.LocalASN != *other.LocalASN {
			return false
		}
	}

	if ((in.Peers != nil) && (other.Peers != nil)) || ((in.Peers == nil) != (other.Peers == nil)) {
		in, other := &in.Peers, &other.Peers
		if other == nil {
			return false
		}

		if len(*in) != len(*other) {
			return false
		} else {
			for i, inElement := range *in {
				if !inElement.DeepEqual(&(*other)[i]) {
					return false
				}
			}
		}
	}

	if (in.Maintenance == nil) != (other.Maintenance == nil) {
		return false
	} else if in.Maintenance != nil {
		if !in.Maintenance.DeepEqual(other.Maintenance) {
			return false
		}
	}

	return true
}

// DeepEqual is an autogenerated deepequal function, deeply comparing the
// receiver with other. in must be non-nil.
func (in *IsovalentBGPNodeConfigOverride) DeepEqual(other *IsovalentBGPNodeConfigOverride) bool {
	if other == nil {
		return false
	}

	if !in.Spec.DeepEqual(&other.Spec) {
		return false
	}

	return true
}

// DeepEqual is an autogenerated deepequal function, deeply comparing the
// receiver with other. in must be non-nil.
func (in *IsovalentBGPNodeConfigOverrideSpec) DeepEqual(other *IsovalentBGPNodeConfigOverrideSpec) bool {
	if other == nil {
		return false
	}

	if ((in.BGPInstances != nil) && (other.BGPInstances != nil)) || ((in.BGPInstances == nil) != (other.BGPInstances == nil)) {
		in, other := &in.BGPInstances, &other.BGPInstances
		if other == nil {
			return false
		}

		if len(*in) != len(*other) {
			return false
		} else {
			for i, inElement := range *in {
				if !inElement.DeepEqual(&(*other)[i]) {
					return false
				}
			}
		}
	}

	return true
}

// DeepEqual is an autogenerated deepequal function, deeply comparing the
// receiver with other. in must be non-nil.
func (in *IsovalentBGPNodeConfigPeerOverride) DeepEqual(other *IsovalentBGPNodeConfigPeerOverride) bool {
	if other == nil {
		return false
	}

	if in.Name != other.Name {
		return false
	}
	if (in.LocalAddress == nil) != (other.LocalAddress == nil) {
		return false
	} else if in.LocalAddress != nil {
		if *in.LocalAddress != *other.LocalAddress {
			return false
		}
	}

	if (in.AutoDiscovery == nil) != (other.AutoDiscovery == nil) {
		return false
	} else if in.AutoDiscovery != nil {
		if !in.AutoDiscovery.DeepEqual(other.AutoDiscovery) {
			return false
		}
	}

	if (in.LocalPort == nil) != (other.LocalPort == nil) {
		return false
	} else if in.LocalPort != nil {
		if *in.LocalPort != *other.LocalPort {
			return false
		}
	}

	return true
}

// DeepEqual is an autogenerated deepequal function, deeply comparing the
// receiver with other. in must be non-nil.
func (in *IsovalentBGPNodeInstance) DeepEqual(other *IsovalentBGPNodeInstance) bool {
	if other == nil {
		return false
	}

	if in.Name != other.Name {
		return false
	}
	if (in.LocalASN == nil) != (other.LocalASN == nil) {
		return false
	} else if in.LocalASN != nil {
		if *in.LocalASN != *other.LocalASN {
			return false
		}
	}

	if (in.RouterID == nil) != (other.RouterID == nil) {
		return false
	} else if in.RouterID != nil {
		if *in.RouterID != *other.RouterID {
			return false
		}
	}

	if (in.LocalPort == nil) != (other.LocalPort == nil) {
		return false
	} else if in.LocalPort != nil {
		if *in.LocalPort != *other.LocalPort {
			return false
		}
	}

	if (in.SRv6Responder == nil) != (other.SRv6Responder == nil) {
		return false
	} else if in.SRv6Responder != nil {
		if *in.SRv6Responder != *other.SRv6Responder {
			return false
		}
	}

	if ((in.Peers != nil) && (other.Peers != nil)) || ((in.Peers == nil) != (other.Peers == nil)) {
		in, other := &in.Peers, &other.Peers
		if other == nil {
			return false
		}

		if len(*in) != len(*other) {
			return false
		} else {
			for i, inElement := range *in {
				if !inElement.DeepEqual(&(*other)[i]) {
					return false
				}
			}
		}
	}

	if ((in.VRFs != nil) && (other.VRFs != nil)) || ((in.VRFs == nil) != (other.VRFs == nil)) {
		in, other := &in.VRFs, &other.VRFs
		if other == nil {
			return false
		}

		if len(*in) != len(*other) {
			return false
		} else {
			for i, inElement := range *in {
				if !inElement.DeepEqual(&(*other)[i]) {
					return false
				}
			}
		}
	}

	if (in.RouteReflector == nil) != (other.RouteReflector == nil) {
		return false
	} else if in.RouteReflector != nil {
		if !in.RouteReflector.DeepEqual(other.RouteReflector) {
			return false
		}
	}

	if (in.Maintenance == nil) != (other.Maintenance == nil) {
		return false
	} else if in.Maintenance != nil {
		if !in.Maintenance.DeepEqual(other.Maintenance) {
			return false
		}
	}

	return true
}

// DeepEqual is an autogenerated deepequal function, deeply comparing the
// receiver with other. in must be non-nil.
func (in *IsovalentBGPNodeInstanceStatus) DeepEqual(other *IsovalentBGPNodeInstanceStatus) bool {
	if other == nil {
		return false
	}

	if !in.CiliumBGPNodeInstanceStatus.DeepEqual(&other.CiliumBGPNodeInstanceStatus) {
		return false
	}

	return true
}

// DeepEqual is an autogenerated deepequal function, deeply comparing the
// receiver with other. in must be non-nil.
func (in *IsovalentBGPNodePeer) DeepEqual(other *IsovalentBGPNodePeer) bool {
	if other == nil {
		return false
	}

	if in.Name != other.Name {
		return false
	}
	if (in.PeerAddress == nil) != (other.PeerAddress == nil) {
		return false
	} else if in.PeerAddress != nil {
		if *in.PeerAddress != *other.PeerAddress {
			return false
		}
	}

	if (in.PeerASN == nil) != (other.PeerASN == nil) {
		return false
	} else if in.PeerASN != nil {
		if *in.PeerASN != *other.PeerASN {
			return false
		}
	}

	if (in.AutoDiscovery == nil) != (other.AutoDiscovery == nil) {
		return false
	} else if in.AutoDiscovery != nil {
		if !in.AutoDiscovery.DeepEqual(other.AutoDiscovery) {
			return false
		}
	}

	if (in.LocalAddress == nil) != (other.LocalAddress == nil) {
		return false
	} else if in.LocalAddress != nil {
		if *in.LocalAddress != *other.LocalAddress {
			return false
		}
	}

	if (in.PeerConfigRef == nil) != (other.PeerConfigRef == nil) {
		return false
	} else if in.PeerConfigRef != nil {
		if !in.PeerConfigRef.DeepEqual(other.PeerConfigRef) {
			return false
		}
	}

	if (in.RouteReflector == nil) != (other.RouteReflector == nil) {
		return false
	} else if in.RouteReflector != nil {
		if !in.RouteReflector.DeepEqual(other.RouteReflector) {
			return false
		}
	}

	return true
}

// DeepEqual is an autogenerated deepequal function, deeply comparing the
// receiver with other. in must be non-nil.
func (in *IsovalentBGPNodeSpec) DeepEqual(other *IsovalentBGPNodeSpec) bool {
	if other == nil {
		return false
	}

	if ((in.BGPInstances != nil) && (other.BGPInstances != nil)) || ((in.BGPInstances == nil) != (other.BGPInstances == nil)) {
		in, other := &in.BGPInstances, &other.BGPInstances
		if other == nil {
			return false
		}

		if len(*in) != len(*other) {
			return false
		} else {
			for i, inElement := range *in {
				if !inElement.DeepEqual(&(*other)[i]) {
					return false
				}
			}
		}
	}

	return true
}

// DeepEqual is an autogenerated deepequal function, deeply comparing the
// receiver with other. in must be non-nil.
func (in *IsovalentBGPNodeStatus) DeepEqual(other *IsovalentBGPNodeStatus) bool {
	if other == nil {
		return false
	}

	if ((in.BGPInstances != nil) && (other.BGPInstances != nil)) || ((in.BGPInstances == nil) != (other.BGPInstances == nil)) {
		in, other := &in.BGPInstances, &other.BGPInstances
		if other == nil {
			return false
		}

		if len(*in) != len(*other) {
			return false
		} else {
			for i, inElement := range *in {
				if !inElement.DeepEqual(&(*other)[i]) {
					return false
				}
			}
		}
	}

	return true
}

// DeepEqual is an autogenerated deepequal function, deeply comparing the
// receiver with other. in must be non-nil.
func (in *IsovalentBGPNodeVRF) DeepEqual(other *IsovalentBGPNodeVRF) bool {
	if other == nil {
		return false
	}

	if in.VRFRef != other.VRFRef {
		return false
	}
	if (in.ConfigRef == nil) != (other.ConfigRef == nil) {
		return false
	} else if in.ConfigRef != nil {
		if *in.ConfigRef != *other.ConfigRef {
			return false
		}
	}

	if (in.RD == nil) != (other.RD == nil) {
		return false
	} else if in.RD != nil {
		if *in.RD != *other.RD {
			return false
		}
	}

	if ((in.ImportRTs != nil) && (other.ImportRTs != nil)) || ((in.ImportRTs == nil) != (other.ImportRTs == nil)) {
		in, other := &in.ImportRTs, &other.ImportRTs
		if other == nil {
			return false
		}

		if len(*in) != len(*other) {
			return false
		} else {
			for i, inElement := range *in {
				if inElement != (*other)[i] {
					return false
				}
			}
		}
	}

	if ((in.ExportRTs != nil) && (other.ExportRTs != nil)) || ((in.ExportRTs == nil) != (other.ExportRTs == nil)) {
		in, other := &in.ExportRTs, &other.ExportRTs
		if other == nil {
			return false
		}

		if len(*in) != len(*other) {
			return false
		} else {
			for i, inElement := range *in {
				if inElement != (*other)[i] {
					return false
				}
			}
		}
	}

	return true
}

// DeepEqual is an autogenerated deepequal function, deeply comparing the
// receiver with other. in must be non-nil.
func (in *IsovalentBGPPeer) DeepEqual(other *IsovalentBGPPeer) bool {
	if other == nil {
		return false
	}

	if in.Name != other.Name {
		return false
	}
	if (in.PeerAddress == nil) != (other.PeerAddress == nil) {
		return false
	} else if in.PeerAddress != nil {
		if *in.PeerAddress != *other.PeerAddress {
			return false
		}
	}

	if (in.PeerASN == nil) != (other.PeerASN == nil) {
		return false
	} else if in.PeerASN != nil {
		if *in.PeerASN != *other.PeerASN {
			return false
		}
	}

	if (in.AutoDiscovery == nil) != (other.AutoDiscovery == nil) {
		return false
	} else if in.AutoDiscovery != nil {
		if !in.AutoDiscovery.DeepEqual(other.AutoDiscovery) {
			return false
		}
	}

	if (in.PeerConfigRef == nil) != (other.PeerConfigRef == nil) {
		return false
	} else if in.PeerConfigRef != nil {
		if !in.PeerConfigRef.DeepEqual(other.PeerConfigRef) {
			return false
		}
	}

	return true
}

// DeepEqual is an autogenerated deepequal function, deeply comparing the
// receiver with other. in must be non-nil.
func (in *IsovalentBGPPeerConfig) DeepEqual(other *IsovalentBGPPeerConfig) bool {
	if other == nil {
		return false
	}

	if !in.Spec.DeepEqual(&other.Spec) {
		return false
	}

	if !in.Status.DeepEqual(&other.Status) {
		return false
	}

	return true
}

// DeepEqual is an autogenerated deepequal function, deeply comparing the
// receiver with other. in must be non-nil.
func (in *IsovalentBGPPeerConfigSpec) DeepEqual(other *IsovalentBGPPeerConfigSpec) bool {
	if other == nil {
		return false
	}

	if (in.Transport == nil) != (other.Transport == nil) {
		return false
	} else if in.Transport != nil {
		if !in.Transport.DeepEqual(other.Transport) {
			return false
		}
	}

	if (in.Timers == nil) != (other.Timers == nil) {
		return false
	} else if in.Timers != nil {
		if !in.Timers.DeepEqual(other.Timers) {
			return false
		}
	}

	if (in.AuthSecretRef == nil) != (other.AuthSecretRef == nil) {
		return false
	} else if in.AuthSecretRef != nil {
		if *in.AuthSecretRef != *other.AuthSecretRef {
			return false
		}
	}

	if (in.GracefulRestart == nil) != (other.GracefulRestart == nil) {
		return false
	} else if in.GracefulRestart != nil {
		if !in.GracefulRestart.DeepEqual(other.GracefulRestart) {
			return false
		}
	}

	if (in.EBGPMultihop == nil) != (other.EBGPMultihop == nil) {
		return false
	} else if in.EBGPMultihop != nil {
		if *in.EBGPMultihop != *other.EBGPMultihop {
			return false
		}
	}

	if ((in.Families != nil) && (other.Families != nil)) || ((in.Families == nil) != (other.Families == nil)) {
		in, other := &in.Families, &other.Families
		if other == nil {
			return false
		}

		if len(*in) != len(*other) {
			return false
		} else {
			for i, inElement := range *in {
				if !inElement.DeepEqual(&(*other)[i]) {
					return false
				}
			}
		}
	}

	if (in.BFDProfileRef == nil) != (other.BFDProfileRef == nil) {
		return false
	} else if in.BFDProfileRef != nil {
		if *in.BFDProfileRef != *other.BFDProfileRef {
			return false
		}
	}

	return true
}

// DeepEqual is an autogenerated deepequal function, deeply comparing the
// receiver with other. in must be non-nil.
func (in *IsovalentBGPPeerConfigStatus) DeepEqual(other *IsovalentBGPPeerConfigStatus) bool {
	if other == nil {
		return false
	}

	return true
}

// DeepEqual is an autogenerated deepequal function, deeply comparing the
// receiver with other. in must be non-nil.
func (in *IsovalentBGPPolicy) DeepEqual(other *IsovalentBGPPolicy) bool {
	if other == nil {
		return false
	}

	if !in.Spec.DeepEqual(&other.Spec) {
		return false
	}

	return true
}

// DeepEqual is an autogenerated deepequal function, deeply comparing the
// receiver with other. in must be non-nil.
func (in *IsovalentBGPPolicyRef) DeepEqual(other *IsovalentBGPPolicyRef) bool {
	if other == nil {
		return false
	}

	if in.Name != other.Name {
		return false
	}

	return true
}

// DeepEqual is an autogenerated deepequal function, deeply comparing the
// receiver with other. in must be non-nil.
func (in *IsovalentBGPPolicySpec) DeepEqual(other *IsovalentBGPPolicySpec) bool {
	if other == nil {
		return false
	}

	if !in.Import.DeepEqual(&other.Import) {
		return false
	}

	return true
}

// deepEqual is an autogenerated deepequal function, deeply comparing the
// receiver with other. in must be non-nil.
func (in *IsovalentClusterwideNetworkPolicy) deepEqual(other *IsovalentClusterwideNetworkPolicy) bool {
	if other == nil {
		return false
	}

	if (in.Spec == nil) != (other.Spec == nil) {
		return false
	} else if in.Spec != nil {
		if !in.Spec.DeepEqual(other.Spec) {
			return false
		}
	}

	if ((in.Specs != nil) && (other.Specs != nil)) || ((in.Specs == nil) != (other.Specs == nil)) {
		in, other := &in.Specs, &other.Specs
		if other == nil {
			return false
		}

		if len(*in) != len(*other) {
			return false
		} else {
			for i, inElement := range *in {
				if !inElement.DeepEqual((*other)[i]) {
					return false
				}
			}
		}
	}

	if !in.Status.DeepEqual(&other.Status) {
		return false
	}

	return true
}

// DeepEqual is an autogenerated deepequal function, deeply comparing the
// receiver with other. in must be non-nil.
func (in *IsovalentEgressGatewayPolicy) DeepEqual(other *IsovalentEgressGatewayPolicy) bool {
	if other == nil {
		return false
	}

	if !in.Spec.DeepEqual(&other.Spec) {
		return false
	}

	if !in.Status.DeepEqual(&other.Status) {
		return false
	}

	return true
}

// DeepEqual is an autogenerated deepequal function, deeply comparing the
// receiver with other. in must be non-nil.
func (in *IsovalentEgressGatewayPolicyGroupStatus) DeepEqual(other *IsovalentEgressGatewayPolicyGroupStatus) bool {
	if other == nil {
		return false
	}

	if ((in.ActiveGatewayIPs != nil) && (other.ActiveGatewayIPs != nil)) || ((in.ActiveGatewayIPs == nil) != (other.ActiveGatewayIPs == nil)) {
		in, other := &in.ActiveGatewayIPs, &other.ActiveGatewayIPs
		if other == nil {
			return false
		}

		if len(*in) != len(*other) {
			return false
		} else {
			for i, inElement := range *in {
				if inElement != (*other)[i] {
					return false
				}
			}
		}
	}

	if ((in.HealthyGatewayIPs != nil) && (other.HealthyGatewayIPs != nil)) || ((in.HealthyGatewayIPs == nil) != (other.HealthyGatewayIPs == nil)) {
		in, other := &in.HealthyGatewayIPs, &other.HealthyGatewayIPs
		if other == nil {
			return false
		}

		if len(*in) != len(*other) {
			return false
		} else {
			for i, inElement := range *in {
				if inElement != (*other)[i] {
					return false
				}
			}
		}
	}

	if ((in.EgressIPByGatewayIP != nil) && (other.EgressIPByGatewayIP != nil)) || ((in.EgressIPByGatewayIP == nil) != (other.EgressIPByGatewayIP == nil)) {
		in, other := &in.EgressIPByGatewayIP, &other.EgressIPByGatewayIP
		if other == nil {
			return false
		}

		if len(*in) != len(*other) {
			return false
		} else {
			for key, inValue := range *in {
				if otherValue, present := (*other)[key]; !present {
					return false
				} else {
					if inValue != otherValue {
						return false
					}
				}
			}
		}
	}

	return true
}

// DeepEqual is an autogenerated deepequal function, deeply comparing the
// receiver with other. in must be non-nil.
func (in *IsovalentEgressGatewayPolicySpec) DeepEqual(other *IsovalentEgressGatewayPolicySpec) bool {
	if other == nil {
		return false
	}

	if ((in.Selectors != nil) && (other.Selectors != nil)) || ((in.Selectors == nil) != (other.Selectors == nil)) {
		in, other := &in.Selectors, &other.Selectors
		if other == nil {
			return false
		}

		if len(*in) != len(*other) {
			return false
		} else {
			for i, inElement := range *in {
				if !inElement.DeepEqual(&(*other)[i]) {
					return false
				}
			}
		}
	}

	if ((in.DestinationCIDRs != nil) && (other.DestinationCIDRs != nil)) || ((in.DestinationCIDRs == nil) != (other.DestinationCIDRs == nil)) {
		in, other := &in.DestinationCIDRs, &other.DestinationCIDRs
		if other == nil {
			return false
		}

		if len(*in) != len(*other) {
			return false
		} else {
			for i, inElement := range *in {
				if inElement != (*other)[i] {
					return false
				}
			}
		}
	}

	if ((in.ExcludedCIDRs != nil) && (other.ExcludedCIDRs != nil)) || ((in.ExcludedCIDRs == nil) != (other.ExcludedCIDRs == nil)) {
		in, other := &in.ExcludedCIDRs, &other.ExcludedCIDRs
		if other == nil {
			return false
		}

		if len(*in) != len(*other) {
			return false
		} else {
			for i, inElement := range *in {
				if inElement != (*other)[i] {
					return false
				}
			}
		}
	}

	if ((in.EgressCIDRs != nil) && (other.EgressCIDRs != nil)) || ((in.EgressCIDRs == nil) != (other.EgressCIDRs == nil)) {
		in, other := &in.EgressCIDRs, &other.EgressCIDRs
		if other == nil {
			return false
		}

		if len(*in) != len(*other) {
			return false
		} else {
			for i, inElement := range *in {
				if inElement != (*other)[i] {
					return false
				}
			}
		}
	}

	if ((in.EgressGroups != nil) && (other.EgressGroups != nil)) || ((in.EgressGroups == nil) != (other.EgressGroups == nil)) {
		in, other := &in.EgressGroups, &other.EgressGroups
		if other == nil {
			return false
		}

		if len(*in) != len(*other) {
			return false
		} else {
			for i, inElement := range *in {
				if !inElement.DeepEqual(&(*other)[i]) {
					return false
				}
			}
		}
	}

	if in.AZAffinity != other.AZAffinity {
		return false
	}

	return true
}

// DeepEqual is an autogenerated deepequal function, deeply comparing the
// receiver with other. in must be non-nil.
func (in *IsovalentEgressGatewayPolicyStatus) DeepEqual(other *IsovalentEgressGatewayPolicyStatus) bool {
	if other == nil {
		return false
	}

	if in.ObservedGeneration != other.ObservedGeneration {
		return false
	}
	if ((in.GroupStatuses != nil) && (other.GroupStatuses != nil)) || ((in.GroupStatuses == nil) != (other.GroupStatuses == nil)) {
		in, other := &in.GroupStatuses, &other.GroupStatuses
		if other == nil {
			return false
		}

		if len(*in) != len(*other) {
			return false
		} else {
			for i, inElement := range *in {
				if !inElement.DeepEqual(&(*other)[i]) {
					return false
				}
			}
		}
	}

	return true
}

// deepEqual is an autogenerated deepequal function, deeply comparing the
// receiver with other. in must be non-nil.
func (in *IsovalentNetworkPolicy) deepEqual(other *IsovalentNetworkPolicy) bool {
	if other == nil {
		return false
	}

	if (in.Spec == nil) != (other.Spec == nil) {
		return false
	} else if in.Spec != nil {
		if !in.Spec.DeepEqual(other.Spec) {
			return false
		}
	}

	if ((in.Specs != nil) && (other.Specs != nil)) || ((in.Specs == nil) != (other.Specs == nil)) {
		in, other := &in.Specs, &other.Specs
		if other == nil {
			return false
		}

		if len(*in) != len(*other) {
			return false
		} else {
			for i, inElement := range *in {
				if !inElement.DeepEqual((*other)[i]) {
					return false
				}
			}
		}
	}

	return true
}

// DeepEqual is an autogenerated deepequal function, deeply comparing the
// receiver with other. in must be non-nil.
func (in *IsovalentNetworkPolicyNodeStatus) DeepEqual(other *IsovalentNetworkPolicyNodeStatus) bool {
	if other == nil {
		return false
	}

	if in.OK != other.OK {
		return false
	}
	if in.Error != other.Error {
		return false
	}
	if !in.LastUpdated.DeepEqual(&other.LastUpdated) {
		return false
	}

	if in.Revision != other.Revision {
		return false
	}
	if in.Enforcing != other.Enforcing {
		return false
	}
	if ((in.Annotations != nil) && (other.Annotations != nil)) || ((in.Annotations == nil) != (other.Annotations == nil)) {
		in, other := &in.Annotations, &other.Annotations
		if other == nil {
			return false
		}

		if len(*in) != len(*other) {
			return false
		} else {
			for key, inValue := range *in {
				if otherValue, present := (*other)[key]; !present {
					return false
				} else {
					if inValue != otherValue {
						return false
					}
				}
			}
		}
	}

	return true
}

// deepEqual is an autogenerated deepequal function, deeply comparing the
// receiver with other. in must be non-nil.
func (in *IsovalentNetworkPolicyRule) deepEqual(other *IsovalentNetworkPolicyRule) bool {
	if other == nil {
		return false
	}

	if !in.Rule.DeepEqual(&other.Rule) {
		return false
	}

	if (in.Order == nil) != (other.Order == nil) {
		return false
	} else if in.Order != nil {
		if *in.Order != *other.Order {
			return false
		}
	}

	return true
}

// DeepEqual is an autogenerated deepequal function, deeply comparing the
// receiver with other. in must be non-nil.
func (in *IsovalentNetworkPolicyStatus) DeepEqual(other *IsovalentNetworkPolicyStatus) bool {
	if other == nil {
		return false
	}

	if ((in.DerivativePolicies != nil) && (other.DerivativePolicies != nil)) || ((in.DerivativePolicies == nil) != (other.DerivativePolicies == nil)) {
		in, other := &in.DerivativePolicies, &other.DerivativePolicies
		if other == nil {
			return false
		}

		if len(*in) != len(*other) {
			return false
		} else {
			for key, inValue := range *in {
				if otherValue, present := (*other)[key]; !present {
					return false
				} else {
					if !inValue.DeepEqual(&otherValue) {
						return false
					}
				}
			}
		}
	}

	if ((in.Conditions != nil) && (other.Conditions != nil)) || ((in.Conditions == nil) != (other.Conditions == nil)) {
		in, other := &in.Conditions, &other.Conditions
		if other == nil {
			return false
		}

		if len(*in) != len(*other) {
			return false
		} else {
			for i, inElement := range *in {
				if !inElement.DeepEqual(&(*other)[i]) {
					return false
				}
			}
		}
	}

	return true
}

// DeepEqual is an autogenerated deepequal function, deeply comparing the
// receiver with other. in must be non-nil.
func (in *NetworkPolicyCondition) DeepEqual(other *NetworkPolicyCondition) bool {
	if other == nil {
		return false
	}

	if in.Type != other.Type {
		return false
	}
	if in.Status != other.Status {
		return false
	}
	if !in.LastTransitionTime.DeepEqual(&other.LastTransitionTime) {
		return false
	}

	if in.Reason != other.Reason {
		return false
	}
	if in.Message != other.Message {
		return false
	}

	return true
}

// DeepEqual is an autogenerated deepequal function, deeply comparing the
// receiver with other. in must be non-nil.
func (in *NodeRouteReflector) DeepEqual(other *NodeRouteReflector) bool {
	if other == nil {
		return false
	}

	if in.Role != other.Role {
		return false
	}
	if in.ClusterID != other.ClusterID {
		return false
	}

	return true
}

// DeepEqual is an autogenerated deepequal function, deeply comparing the
// receiver with other. in must be non-nil.
func (in *PeerConfigReference) DeepEqual(other *PeerConfigReference) bool {
	if other == nil {
		return false
	}

	if in.Name != other.Name {
		return false
	}

	return true
}

// DeepEqual is an autogenerated deepequal function, deeply comparing the
// receiver with other. in must be non-nil.
func (in *PrefixV4Match) DeepEqual(other *PrefixV4Match) bool {
	if other == nil {
		return false
	}

	if in.Prefix != other.Prefix {
		return false
	}
	if (in.MaxLen == nil) != (other.MaxLen == nil) {
		return false
	} else if in.MaxLen != nil {
		if *in.MaxLen != *other.MaxLen {
			return false
		}
	}

	if (in.MinLen == nil) != (other.MinLen == nil) {
		return false
	} else if in.MinLen != nil {
		if *in.MinLen != *other.MinLen {
			return false
		}
	}

	return true
}

// DeepEqual is an autogenerated deepequal function, deeply comparing the
// receiver with other. in must be non-nil.
func (in *PrefixV6Match) DeepEqual(other *PrefixV6Match) bool {
	if other == nil {
		return false
	}

	if in.Prefix != other.Prefix {
		return false
	}
	if (in.MaxLen == nil) != (other.MaxLen == nil) {
		return false
	} else if in.MaxLen != nil {
		if *in.MaxLen != *other.MaxLen {
			return false
		}
	}

	if (in.MinLen == nil) != (other.MinLen == nil) {
		return false
	} else if in.MinLen != nil {
		if *in.MinLen != *other.MinLen {
			return false
		}
	}

	return true
}

// DeepEqual is an autogenerated deepequal function, deeply comparing the
// receiver with other. in must be non-nil.
func (in *PrefixesV4Condition) DeepEqual(other *PrefixesV4Condition) bool {
	if other == nil {
		return false
	}

	if in.MatchType != other.MatchType {
		return false
	}
	if ((in.Matches != nil) && (other.Matches != nil)) || ((in.Matches == nil) != (other.Matches == nil)) {
		in, other := &in.Matches, &other.Matches
		if other == nil {
			return false
		}

		if len(*in) != len(*other) {
			return false
		} else {
			for i, inElement := range *in {
				if !inElement.DeepEqual(&(*other)[i]) {
					return false
				}
			}
		}
	}

	return true
}

// DeepEqual is an autogenerated deepequal function, deeply comparing the
// receiver with other. in must be non-nil.
func (in *PrefixesV6Condition) DeepEqual(other *PrefixesV6Condition) bool {
	if other == nil {
		return false
	}

	if in.MatchType != other.MatchType {
		return false
	}
	if ((in.Matches != nil) && (other.Matches != nil)) || ((in.Matches == nil) != (other.Matches == nil)) {
		in, other := &in.Matches, &other.Matches
		if other == nil {
			return false
		}

		if len(*in) != len(*other) {
			return false
		} else {
			for i, inElement := range *in {
				if !inElement.DeepEqual(&(*other)[i]) {
					return false
				}
			}
		}
	}

	return true
}

// DeepEqual is an autogenerated deepequal function, deeply comparing the
// receiver with other. in must be non-nil.
func (in *RouteReflector) DeepEqual(other *RouteReflector) bool {
	if other == nil {
		return false
	}

	if in.Role != other.Role {
		return false
	}
	if in.ClusterID != other.ClusterID {
		return false
	}
	if (in.PeeringAddressFamily == nil) != (other.PeeringAddressFamily == nil) {
		return false
	} else if in.PeeringAddressFamily != nil {
		if *in.PeeringAddressFamily != *other.PeeringAddressFamily {
			return false
		}
	}

	if (in.PeerConfigRefV4 == nil) != (other.PeerConfigRefV4 == nil) {
		return false
	} else if in.PeerConfigRefV4 != nil {
		if !in.PeerConfigRefV4.DeepEqual(other.PeerConfigRefV4) {
			return false
		}
	}

	if (in.PeerConfigRefV6 == nil) != (other.PeerConfigRefV6 == nil) {
		return false
	} else if in.PeerConfigRefV6 != nil {
		if !in.PeerConfigRefV6.DeepEqual(other.PeerConfigRefV6) {
			return false
		}
	}

	return true
}
