prometheus:
  prometheusSpec:
    serviceMonitorSelector: {}
    serviceMonitorSelectorNilUsesHelmValues: false
kube-state-metrics:
  metricLabelsAllowlist:
  - "nodes=[service.cilium.io/node]"
prometheus-node-exporter:
  extraArgs:
  - --collector.ethtool
grafana:
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/default

  grafana.ini:
    dashboards:
      default_home_dashboard_path: /var/lib/grafana/dashboards/default/lb.json

  dashboardsConfigMaps:
    default: "grafana-dashboards"
