apiVersion: isovalent.com/v1alpha1
kind: LBBackend
metadata:
  namespace: default
  name: lb-1
spec:
  healthcheck:
    interval: "10s"
  addresses:
    - ip: 9.9.9.9
      port: 8080
    - ip: 8.9.9.9
      port: 8080
---
apiVersion: isovalent.com/v1alpha1
kind: LBBackend
metadata:
  namespace: default
  name: lb-2
spec:
  healthcheck:
    interval: "10s"
  addresses:
    - ip: 9.9.9.9
      port: 8080
    - ip: 8.9.9.9
      port: 8080
---
apiVersion: isovalent.com/v1alpha1
kind: LBBackend
metadata:
  namespace: default
  name: lb-3
spec:
  healthcheck:
    interval: "10s"
  addresses:
    - ip: 9.9.9.9
      port: 8080
    - ip: 8.9.9.9
      port: 8080
---
apiVersion: isovalent.com/v1alpha1
kind: LBBackend
metadata:
  namespace: default
  name: lb-4
spec:
  healthcheck:
    interval: "10s"
  addresses:
    - ip: 9.9.9.9
      port: 8080
    - ip: 8.9.9.9
      port: 8080
---
apiVersion: isovalent.com/v1alpha1
kind: LBBackend
metadata:
  namespace: default
  name: lb-5
spec:
  healthcheck:
    interval: "10s"
  addresses:
    - ip: 9.9.9.9
      port: 8080
    - ip: 8.9.9.9
      port: 8080
---
apiVersion: isovalent.com/v1alpha1
kind: LBBackend
metadata:
  namespace: default
  name: lb-6
spec:
  healthcheck:
    interval: "10s"
  addresses:
    - ip: 9.9.9.9
      port: 8080
---
apiVersion: isovalent.com/v1alpha1
kind: LBBackend
metadata:
  namespace: default
  name: lb-7
spec:
  healthcheck:
    interval: "10s"
  addresses:
    - ip: 9.9.9.9
      port: 8080
