apiVersion: isovalent.com/v1alpha1
kind: LBBackendPool
metadata:
  namespace: default
  name: lb-1
spec:
  healthCheck:
    intervalSeconds: 2
    timeoutSeconds: 2
    http:
      path: "/health"
  backends:
    - ip: 9.9.9.9
      port: 8080
    - ip: 8.9.9.9
      port: 8080
  loadbalancing:
    algorithm:
      consistentHashing: {}
---
apiVersion: isovalent.com/v1alpha1
kind: LBBackendPool
metadata:
  namespace: default
  name: lb-2
spec:
  healthCheck:
    intervalSeconds: 2
    timeoutSeconds: 2
    http:
      path: "/health"
  backends:
    - ip: 9.9.9.9
      port: 8080
    - ip: 8.9.9.9
      port: 8080
---
apiVersion: isovalent.com/v1alpha1
kind: LBBackendPool
metadata:
  namespace: default
  name: lb-3
spec:
  healthCheck:
    intervalSeconds: 2
    timeoutSeconds: 2
    http:
      path: "/health"
  backends:
    - ip: 9.9.9.9
      port: 8080
    - ip: 8.9.9.9
      port: 8080
      weight: 5
---
apiVersion: isovalent.com/v1alpha1
kind: LBBackendPool
metadata:
  namespace: default
  name: lb-4
spec:
  healthCheck:
    intervalSeconds: 2
    timeoutSeconds: 2
    http:
      path: "/health"
  backends:
    - ip: 9.9.9.9
      port: 8080
    - ip: 8.9.9.9
      port: 8080
---
apiVersion: isovalent.com/v1alpha1
kind: LBBackendPool
metadata:
  namespace: default
  name: lb-5
spec:
  healthCheck:
    intervalSeconds: 2
    timeoutSeconds: 2
    http:
      path: "/health"
  backends:
    - ip: 9.9.9.9
      port: 8080
    - ip: 8.9.9.9
      port: 8080
  httpConfig:
    enableHTTP11: false
    enableHTTP2: true
---
apiVersion: isovalent.com/v1alpha1
kind: LBBackendPool
metadata:
  namespace: default
  name: lb-6
spec:
  healthCheck:
    intervalSeconds: 2
    timeoutSeconds: 2
    http:
      path: "/health"
  backends:
    - ip: 9.9.9.9
      port: 8080
---
apiVersion: isovalent.com/v1alpha1
kind: LBBackendPool
metadata:
  namespace: default
  name: lb-7
spec:
  healthCheck:
    intervalSeconds: 2
    timeoutSeconds: 2
    http:
      path: "/health"
  backends:
    - ip: 9.9.9.9
      port: 8080
---
apiVersion: isovalent.com/v1alpha1
kind: LBBackendPool
metadata:
  namespace: default
  name: lb-8
spec:
  healthCheck:
    intervalSeconds: 2
    timeoutSeconds: 2
    http:
      path: "/health"
  backends:
    - ip: 9.9.9.9
      port: 8080
  tlsConfig: {}
---
apiVersion: isovalent.com/v1alpha1
kind: LBBackendPool
metadata:
  namespace: default
  name: lb-9
spec:
  healthCheck:
    intervalSeconds: 2
    timeoutSeconds: 2
    http:
      path: "/health"
  backends:
    - ip: 9.9.9.9
      port: 8080
