---
apiVersion: isovalent.com/v1alpha1
kind: IsovalentBGPClusterConfig
metadata:
  name: frr
spec:
  nodeSelector:
    matchLabels:
      service.cilium.io/node: t1
  bgpInstances:
    - name: "t1"
      localASN: 64512
      peers: [] # will be set by the script

---
apiVersion: isovalent.com/v1alpha1
kind: IsovalentBGPPeerConfig
metadata:
  name: frr-peer
spec:
  families:
    - afi: ipv4
      safi: unicast
      advertisements:
        matchLabels:
          advertise: "bgp"
  timers:
    connectRetryTimeSeconds: 1
  bfdProfileRef: frr # enable BFD for this peering

---
apiVersion: isovalent.com/v1alpha1
kind: IsovalentBGPAdvertisement
metadata:
  name: lb-services
  labels:
    advertise: bgp
spec:
  advertisements:
    - advertisementType: "Service"
      service:
        addresses:
          - LoadBalancerIP
      selector:
        matchExpressions:
          # match any LB service
          - { key: somekey, operator: NotIn, values: ["never-used-value"] }
