apiVersion: "cilium.io/v2alpha1"
kind: CiliumBGPPeeringPolicy
metadata:
  name: frr
spec:
  nodeSelector:
    matchLabels:
      service.cilium.io/node: t1
  virtualRouters:
    - localASN: 64512
      serviceSelector:
        matchExpressions:
          # match any LB service
          - { key: somekey, operator: NotIn, values: ["never-used-value"] }
      neighbors: [] # will be replaced by the script
