apiVersion: isovalent.com/v1alpha1
kind: LBFrontend
metadata:
  namespace: default
  name: lb-1
spec:
  port: 443
  tls:
    certificates:
      - secretName: "test-secure"
  routes:
    - https:
        hostNames:
          - "secure.acme.io"
        backend: lb-1
---
apiVersion: isovalent.com/v1alpha1
kind: LBFrontend
metadata:
  namespace: default
  name: lb-2
spec:
  vip: "100.64.0.101"
  port: 80
  routes:
    - http:
        hostNames:
          - "insecure.acme.io"
        backend: lb-2
---
apiVersion: isovalent.com/v1alpha1
kind: LBFrontend
metadata:
  namespace: default
  name: lb-3
spec:
  vip: "100.64.0.101"
  port: 81
  routes:
    - http:
        hostNames:
          - "*"
        backend: lb-3
---
apiVersion: isovalent.com/v1alpha1
kind: LBFrontend
metadata:
  namespace: default
  name: lb-4
spec:
  vip: "100.64.0.102"
  port: 80
  routes:
    - http:
        hostNames:
          - "mixed.acme.io"
        backend: lb-4
---
apiVersion: isovalent.com/v1alpha1
kind: LBFrontend
metadata:
  namespace: default
  name: lb-5
spec:
  port: 80
  tls:
    certificates:
      - secretName: "test-secure80"
  routes:
    - https:
        hostNames:
          - "secure-80.acme.io"
        backend: lb-5
---
apiVersion: isovalent.com/v1alpha1
kind: LBFrontend
metadata:
  namespace: default
  name: lb-6
spec:
  port: 80
  routes:
    - tlsPassthrough:
        hostNames:
          - "passthrough.acme.io"
        backend: lb-6
    - tlsPassthrough:
        hostNames:
          - "passthrough-2.acme.io"
        backend: lb-7
---

