apiVersion: isovalent.com/v1alpha1
kind: LBFrontend
metadata:
  namespace: default
  name: lb-1
spec:
  port: 443
  applications:
    httpsProxy:
      tlsConfig:
        certificates:
          - secretName: "test-secure"
      routes:
        - hostNames:
            - "secure.acme.io"
          backendRef:
            name: lb-1
---
apiVersion: isovalent.com/v1alpha1
kind: LBFrontend
metadata:
  namespace: default
  name: lb-2
spec:
  vip: "100.64.0.101"
  port: 80
  applications:
    httpProxy:
      routes:
        - hostNames:
            - "insecure.acme.io"
          path:
            exact: "/api/foo-insecure"
          backendRef:
            name: lb-2
---
apiVersion: isovalent.com/v1alpha1
kind: LBFrontend
metadata:
  namespace: default
  name: lb-3
spec:
  vip: "100.64.0.101"
  port: 81
  applications:
    httpProxy:
      routes:
        - backendRef:
            name: lb-3
---
apiVersion: isovalent.com/v1alpha1
kind: LBFrontend
metadata:
  namespace: default
  name: lb-4
spec:
  vip: "100.64.0.102"
  port: 80
  applications:
    httpProxy:
      routes:
        - hostNames:
            - "mixed.acme.io"
          backendRef:
            name: lb-4
---
apiVersion: isovalent.com/v1alpha1
kind: LBFrontend
metadata:
  namespace: default
  name: lb-5
spec:
  port: 80
  applications:
    httpsProxy:
      tlsConfig:
        certificates:
          - secretName: "test-secure80"
      routes:
        - hostNames:
            - "secure-80.acme.io"
          backendRef:
            name: lb-5
---
apiVersion: isovalent.com/v1alpha1
kind: LBFrontend
metadata:
  namespace: default
  name: lb-6
spec:
  port: 80
  applications:
    tlsPassthrough:
      routes:
        - hostNames:
            - "passthrough.acme.io"
          backendRef:
            name: lb-6
        - backendRef:
            name: lb-7
---

