// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	isovalentcomv1alpha1 "github.com/cilium/cilium/pkg/k8s/apis/isovalent.com/v1alpha1"
	versioned "github.com/cilium/cilium/pkg/k8s/client/clientset/versioned"
	internalinterfaces "github.com/cilium/cilium/pkg/k8s/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/cilium/cilium/pkg/k8s/client/listers/isovalent.com/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// IsovalentLBInformer provides access to a shared informer and lister for
// IsovalentLBs.
type IsovalentLBInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.IsovalentLBLister
}

type isovalentLBInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewIsovalentLBInformer constructs a new informer for IsovalentLB type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewIsovalentLBInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredIsovalentLBInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredIsovalentLBInformer constructs a new informer for IsovalentLB type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredIsovalentLBInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.IsovalentV1alpha1().IsovalentLBs(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.IsovalentV1alpha1().IsovalentLBs(namespace).Watch(context.TODO(), options)
			},
		},
		&isovalentcomv1alpha1.IsovalentLB{},
		resyncPeriod,
		indexers,
	)
}

func (f *isovalentLBInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredIsovalentLBInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *isovalentLBInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&isovalentcomv1alpha1.IsovalentLB{}, f.defaultInformer)
}

func (f *isovalentLBInformer) Lister() v1alpha1.IsovalentLBLister {
	return v1alpha1.NewIsovalentLBLister(f.Informer().GetIndexer())
}
