{
 "title": "ILB",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(kube_node_labels,node)"
    }
   },
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(cilium_lb_bytes_total,service)"
    }
   },
   {
    "name": "backend",
    "label": "Backend",
    "query": {
     "query": "label_values(cilium_lb_bytes_total,backend)"
    }
   }
  ]
 },
 "panels": [
  { "title": "[T1] Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "[CT maps] Service BPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (service) (\n    rate(\n        cilium_lb_bytes_total{node=~\"^${node}$\", service=~\"^${service}$\", backend=~\"^${backend}$\"}[$__rate_interval]\n    ) \n    * on (node) group_left() (\n        kube_node_labels{label_service_cilium_io_node=~\"t1\"}\n    )\n) != 0",
     "legendFormat": "{{vip}}"
    }
   ]
  },
  {
   "title": "[CT maps] Service PPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum by (service) (\n    rate(\n        cilium_lb_packets_total{node=~\"^${node}$\", service=~\"^${service}$\", backend=~\"^${backend}$\"}[$__rate_interval]\n    ) \n    * on (node) group_left() (\n        kube_node_labels{label_service_cilium_io_node=~\"t1\"}\n    )\n) != 0",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "[CT maps] Service BPS by backend",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (backend) (\n    rate(\n        cilium_lb_bytes_total{node=~\"^${node}$\", service=~\"^${service}$\", backend=~\"^${backend}$\"}[$__rate_interval]\n    ) \n    * on (node) group_left() (\n        kube_node_labels{label_service_cilium_io_node=~\"t1\"}\n    )\n) != 0",
     "legendFormat": "{{backend}}"
    }
   ]
  },
  {
   "title": "[CT maps] Service PPS by backend",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum by (backend) (\n    rate(\n        cilium_lb_packets_total{node=~\"^${node}$\", service=~\"^${service}$\", backend=~\"^${backend}$\"}[$__rate_interval]\n    ) \n    * on (node) group_left() (\n        kube_node_labels{label_service_cilium_io_node=~\"t1\"}\n    )\n) != 0",
     "legendFormat": "{{backend}}"
    }
   ]
  },
  {
   "title": "[ethtool] BPS (xdp)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (instance) (\n    rate(\n        {__name__=~\"node_ethtool_received_queue_.*_xdp_bytes\"}[$__rate_interval])\n    ) * on (instance) group_left(node) (\n        label_replace(kube_node_status_addresses{node=~\"${node}\"}, \"instance\", \"$1:9100\", \"address\", \"(.*)\"\n    )\n) * on (node) (\n    kube_node_labels{label_service_cilium_io_node=\"t1\"}\n) != 0",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "[ethtool] PPS (xdp)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum by (instance) (\n    rate(\n        {__name__=~\"node_ethtool_received_queue_.*_xdp_packets\"}[$__rate_interval])\n    ) * on (instance) group_left(node) (\n        label_replace(kube_node_status_addresses{node=~\"${node}\"}, \"instance\", \"$1:9100\", \"address\", \"(.*)\"\n    )\n) * on (node) (\n    kube_node_labels{label_service_cilium_io_node=\"t1\"}\n) != 0",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "[CT map] Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by (node) (\n    rate(\n        cilium_lb_open_connections_metric{node=~\"^${node}$\"}[$__rate_interval]\n    ) \n    * on (node) group_left() (\n        kube_node_labels{label_service_cilium_io_node=~\"t1\"}\n    )\n) != 0",
     "legendFormat": "{{node}}"
    }
   ]
  },
  { "title": "[T1] Healthcheck", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Healthcheck status",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "cilium_lb_healthcheck_status{node=~\"^${node}$\", service=~\"^${service}$\", backend=~\"^${backend}$\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "[T1] BGP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "BGP sessions DOWN",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "count by(node) (cilium_bgp_control_plane_session_state == 0.0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "BGP sessions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "targets": [
    {
     "expr": "count by(node) (cilium_bgp_control_plane_session_state)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "BGP advertised routes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "count by (node) (cilium_bgp_control_plane_advertised_routes)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "[T2] Listeners", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "Total connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by (envoy_listener_address) (\n    rate(\n        envoy_listener_downstream_cx_total{node=~\"^${node}$\", envoy_listener_address=~\"^${service}$\"}[$__rate_interval]\n    ) \n    * on (node) group_left() (\n        kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n    )\n) != 0",
     "legendFormat": "{{envoy_listener_address}}"
    }
   ]
  },
  {
   "title": "Active connections",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 60 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(envoy_listener_downstream_cx_active)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Listener errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by (envoy_listener_address) (rate(\n    envoy_listener_downstream_cx_transport_socket_connect_timeout{node=~\"^${node}$\", envoy_listener_address=~\"^${service}$\"}[$__rate_interval]\n) \n* on (node) group_left() (\n    kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n)) != 0",
     "legendFormat": "cx timeout {{envoy_listener_address}}"
    },
    {
     "expr": "sum by (envoy_listener_address) (rate(\n    envoy_listener_downstream_cx_overflow{node=~\"^${node}$\", envoy_listener_address=~\"^${service}$\"}[$__rate_interval]\n) \n* on (node) group_left() (\n    kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n)) != 0",
     "legendFormat": "cx overflow {{envoy_listener_address}}"
    },
    {
     "expr": "sum by (envoy_listener_address) (rate(\n    envoy_listener_downstream_cx_overload_reject{node=~\"^${node}$\", envoy_listener_address=~\"^${service}$\"}[$__rate_interval]\n) \n* on (node) group_left() (\n    kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n)) != 0",
     "legendFormat": "cx overload reject {{envoy_listener_address}}"
    },
    {
     "expr": "sum by (envoy_listener_address) (rate(\n    envoy_listener_downstream_global_cx_overflow{node=~\"^${node}$\", envoy_listener_address=~\"^${service}$\"}[$__rate_interval]\n) \n* on (node) group_left() (\n    kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n)) != 0",
     "legendFormat": "global cx overflow {{envoy_listener_address}}"
    },
    {
     "expr": "sum by (envoy_listener_address) (rate(\n    envoy_listener_downstream_pre_cx_timeout{node=~\"^${node}$\", envoy_listener_address=~\"^${service}$\"}[$__rate_interval]\n) \n* on (node) group_left() (\n    kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n)) != 0",
     "legendFormat": "pre cx timeout {{envoy_listener_address}}"
    },
    {
     "expr": "sum by (envoy_listener_address) (rate(\n    envoy_listener_extension_config_missing{node=~\"^${node}$\", envoy_listener_address=~\"^${service}$\"}[$__rate_interval]\n) \n* on (node) group_left() (\n    kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n)) != 0",
     "legendFormat": "extension config missing {{envoy_listener_address}}"
    },
    {
     "expr": "sum by (envoy_listener_address) (rate(\n    envoy_listener_network_extension_config_missing{node=~\"^${node}$\", envoy_listener_address=~\"^${service}$\"}[$__rate_interval]\n) \n* on (node) group_left() (\n    kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n)) != 0",
     "legendFormat": "network extension config missing {{envoy_listener_address}}"
    },
    {
     "expr": "sum by (envoy_listener_address) (rate(\n    envoy_listener_no_filter_chain_match{node=~\"^${node}$\", envoy_listener_address=~\"^${service}$\"}[$__rate_interval]\n) \n* on (node) group_left() (\n    kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n)) != 0",
     "legendFormat": "no filter chain match {{envoy_listener_address}}"
    },
    {
     "expr": "sum by (envoy_listener_address) (rate(\n    envoy_listener_downstream_listener_filter_remote_close{node=~\"^${node}$\", envoy_listener_address=~\"^${service}$\"}[$__rate_interval]\n) \n* on (node) group_left() (\n    kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n)) != 0",
     "legendFormat": "filter remote close {{envoy_listener_address}}"
    },
    {
     "expr": "sum by (envoy_listener_address) (rate(\n    envoy_listener_downstream_listener_filter_error{node=~\"^${node}$\", envoy_listener_address=~\"^${service}$\"}[$__rate_interval]\n) \n* on (node) group_left() (\n    kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n)) != 0",
     "legendFormat": "listener filter error {{envoy_listener_address}}"
    }
   ]
  },
  { "title": "[T2] TCP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 } },
  {
   "title": "Downstream RX bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (envoy_tcp_prefix) (\n    rate(\n        envoy_tcp_downstream_cx_rx_bytes_total{node=~\"^${node}$\"}[$__rate_interval]\n    ) \n    * on (node) group_left() (\n        kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n    )\n) != 0",
     "legendFormat": "{{envoy_tcp_prefix}}"
    }
   ]
  },
  {
   "title": "Downstream TX bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (envoy_tcp_prefix) (\n    rate(\n        envoy_tcp_downstream_cx_tx_bytes_total{node=~\"^${node}$\"}[$__rate_interval]\n    ) \n    * on (node) group_left() (\n        kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n    )\n) != 0",
     "legendFormat": "{{envoy_tcp_prefix}}"
    }
   ]
  },
  {
   "title": "Downstream connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by (envoy_tcp_prefix) (\n    rate(\n        envoy_tcp_downstream_cx_total{node=~\"^${node}$\"}[$__rate_interval]\n    ) \n    * on (node) group_left() (\n        kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n    )\n) != 0",
     "legendFormat": "{{envoy_tcp_prefix}}"
    }
   ]
  },
  { "title": "[T2] TLS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 93 } },
  {
   "title": "Handshake",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 94 },
   "targets": [
    {
     "expr": "sum by (envoy_listener_address) (\n    rate(\n        envoy_listener_ssl_handshake{node=~\"^${node}$\", envoy_listener_address=~\"^${service}$\"}[$__rate_interval]\n    ) \n    * on (node) group_left() (\n        kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n    )\n) != 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ciphers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 94 },
   "targets": [
    {
     "expr": "sum by (cipher_suite, envoy_cluster_name) (envoy_cluster_ssl_ciphers{envoy_cluster_name =~ \"^${service}$\"})",
     "legendFormat": "{{cipher_suite}} {{envoy_cluster_name}}"
    }
   ]
  },
  {
   "title": "TLS errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 102 },
   "targets": [
    {
     "expr": "sum by (envoy_listener_address) (rate(\n    envoy_listener_ssl_connection_error{node=~\"^${node}$\", envoy_listener_address=~\"^${service}$\"}[$__rate_interval]\n) \n* on (node) group_left() (\n    kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n)) != 0",
     "legendFormat": "cx error {{envoy_listener_address}}"
    },
    {
     "expr": "sum by (envoy_listener_address) (rate(\n    envoy_listener_ssl_fail_verify_no_cert{node=~\"^${node}$\", envoy_listener_address=~\"^${service}$\"}[$__rate_interval]\n) \n* on (node) group_left() (\n    kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n)) != 0",
     "legendFormat": "fail verify no cert {{envoy_listener_address}}"
    },
    {
     "expr": "sum by (envoy_listener_address) (rate(\n    envoy_listener_ssl_fail_verify_error{node=~\"^${node}$\", envoy_listener_address=~\"^${service}$\"}[$__rate_interval]\n) \n* on (node) group_left() (\n    kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n)) != 0",
     "legendFormat": "fail verify error {{envoy_listener_address}}"
    },
    {
     "expr": "sum by (envoy_listener_address) (rate(\n    envoy_listener_ssl_fail_verify_san{node=~\"^${node}$\", envoy_listener_address=~\"^${service}$\"}[$__rate_interval]\n) \n* on (node) group_left() (\n    kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n)) != 0",
     "legendFormat": "fail verify san {{envoy_listener_address}}"
    },
    {
     "expr": "sum by (envoy_listener_address) (rate(\n    envoy_listener_ssl_fail_verify_cert_hash{node=~\"^${node}$\", envoy_listener_address=~\"^${service}$\"}[$__rate_interval]\n) \n* on (node) group_left() (\n    kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n)) != 0",
     "legendFormat": "fail verify cert hash {{envoy_listener_address}}"
    },
    {
     "expr": "sum by (envoy_listener_address) (rate(\n    envoy_listener_ssl_ocsp_staple_failed{node=~\"^${node}$\", envoy_listener_address=~\"^${service}$\"}[$__rate_interval]\n) \n* on (node) group_left() (\n    kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n)) != 0",
     "legendFormat": "ocsp staple failed {{envoy_listener_address}}"
    }
   ]
  },
  { "title": "[T2] HTTP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 110 } },
  {
   "title": "Downstream connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by (envoy_http_conn_manager_prefix) (\n    rate(\n        envoy_http_downstream_cx_total{node=~\"^${node}$\"}[$__rate_interval]\n    ) \n    * on (node) group_left() (\n        kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n    )\n) != 0",
     "legendFormat": "{{backend}}"
    }
   ]
  },
  {
   "title": "Downstream requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (envoy_http_conn_manager_prefix) (\n    rate(\n        envoy_http_downstream_rq_total{node=~\"^${node}$\"}[$__rate_interval]\n    ) \n    * on (node) group_left() (\n        kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n    )\n) != 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Downstream RX bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 119 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum by (envoy_http_conn_manager_prefix) (\n    rate(\n        envoy_http_downstream_cx_rx_bytes_total{node=~\"^${node}$\"}[$__rate_interval]\n    ) \n    * on (node) group_left() (\n        kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n    )\n) != 0",
     "legendFormat": "{{backend}}"
    }
   ]
  },
  {
   "title": "Downstream TX bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 119 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum by (envoy_http_conn_manager_prefix) (\n    rate(\n        envoy_http_downstream_cx_tx_bytes_total{node=~\"^${node}$\"}[$__rate_interval]\n    ) \n    * on (node) group_left() (\n        kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n    )\n) != 0",
     "legendFormat": "{{backend}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 127 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (envoy_http_conn_manager_prefix) (rate(\n    envoy_http_downstream_cx_protocol_error{node=~\"^${node}$\", envoy_http_conn_manager_prefix =~ \"${service}\"}[$__rate_interval]\n) \n* on (node) group_left() (\n    kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n)) != 0",
     "legendFormat": "protocol error {{envoy_http_conn_manager_prefix}}"
    },
    {
     "expr": "sum by (envoy_http_conn_manager_prefix) (rate(\n    envoy_http_downstream_rq_rejected_via_ip_detection{node=~\"^${node}$\", envoy_http_conn_manager_prefix =~ \"${service}\"}[$__rate_interval]\n) \n* on (node) group_left() (\n    kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n)) != 0",
     "legendFormat": "rq rejected via ip detection {{envoy_http_conn_manager_prefix}}"
    },
    {
     "expr": "sum by (envoy_http_conn_manager_prefix) (rate(\n    envoy_http_downstream_rq_response_before_rq_complete{node=~\"^${node}$\", envoy_http_conn_manager_prefix =~ \"${service}\"}[$__rate_interval]\n) \n* on (node) group_left() (\n    kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n)) != 0",
     "legendFormat": "re response before rq complete {{envoy_http_conn_manager_prefix}}"
    },
    {
     "expr": "sum by (envoy_http_conn_manager_prefix) (rate(\n    envoy_http_downstream_rq_rx_reset{node=~\"^${node}$\", envoy_http_conn_manager_prefix =~ \"${service}\"}[$__rate_interval]\n) \n* on (node) group_left() (\n    kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n)) != 0",
     "legendFormat": "rq rx reset {{envoy_http_conn_manager_prefix}}"
    },
    {
     "expr": "sum by (envoy_http_conn_manager_prefix) (rate(\n    envoy_http_downstream_rq_tx_reset{node=~\"^${node}$\", envoy_http_conn_manager_prefix =~ \"${service}\"}[$__rate_interval]\n) \n* on (node) group_left() (\n    kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n)) != 0",
     "legendFormat": "rq tx reset {{envoy_http_conn_manager_prefix}}"
    },
    {
     "expr": "sum by (envoy_http_conn_manager_prefix) (rate(\n    envoy_http_downstream_rq_too_large{node=~\"^${node}$\", envoy_http_conn_manager_prefix =~ \"${service}\"}[$__rate_interval]\n) \n* on (node) group_left() (\n    kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n)) != 0",
     "legendFormat": "rq too large {{envoy_http_conn_manager_prefix}}"
    },
    {
     "expr": "sum by (envoy_http_conn_manager_prefix) (rate(\n    envoy_http_downstream_rq_idle_timeout{node=~\"^${node}$\", envoy_http_conn_manager_prefix =~ \"${service}\"}[$__rate_interval]\n) \n* on (node) group_left() (\n    kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n)) != 0",
     "legendFormat": "rq idle timeout {{envoy_http_conn_manager_prefix}}"
    },
    {
     "expr": "sum by (envoy_http_conn_manager_prefix) (rate(\n    envoy_http_downstream_rq_max_duration_reached{node=~\"^${node}$\", envoy_http_conn_manager_prefix =~ \"${service}\"}[$__rate_interval]\n) \n* on (node) group_left() (\n    kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n)) != 0",
     "legendFormat": "rq max duration reached {{envoy_http_conn_manager_prefix}}"
    },
    {
     "expr": "sum by (envoy_http_conn_manager_prefix) (rate(\n    envoy_http_downstream_rq_timeout{node=~\"^${node}$\", envoy_http_conn_manager_prefix =~ \"${service}\"}[$__rate_interval]\n) \n* on (node) group_left() (\n    kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n)) != 0",
     "legendFormat": "rq timeout {{envoy_http_conn_manager_prefix}}"
    },
    {
     "expr": "sum by (envoy_http_conn_manager_prefix) (rate(\n    envoy_http_downstream_rq_overload_close{node=~\"^${node}$\", envoy_http_conn_manager_prefix =~ \"${service}\"}[$__rate_interval]\n) \n* on (node) group_left() (\n    kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n)) != 0",
     "legendFormat": "rq overload close {{envoy_http_conn_manager_prefix}}"
    },
    {
     "expr": "sum by (envoy_http_conn_manager_prefix) (rate(\n    envoy_http_downstream_rq_too_many_premature_resets{node=~\"^${node}$\", envoy_http_conn_manager_prefix =~ \"${service}\"}[$__rate_interval]\n) \n* on (node) group_left() (\n    kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n)) != 0",
     "legendFormat": "rq too many premature resets {{envoy_http_conn_manager_prefix}}"
    },
    {
     "expr": "sum by (envoy_http_conn_manager_prefix) (rate(\n    envoy_http_rs_too_large{node=~\"^${node}$\", envoy_http_conn_manager_prefix =~ \"${service}\"}[$__rate_interval]\n) \n* on (node) group_left() (\n    kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n)) != 0",
     "legendFormat": "http rs too large {{envoy_http_conn_manager_prefix}}"
    }
   ]
  },
  { "title": "[T2] Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 136 } },
  {
   "title": "Upstream connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 137 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by (envoy_cluster_name) (\n    rate(\n        envoy_cluster_upstream_cx_total{node=~\"^${node}$\"}[$__rate_interval]\n    ) \n    * on (node) group_left() (\n        kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n    )\n) != 0",
     "legendFormat": "{{envoy_cluster_name}}"
    }
   ]
  },
  {
   "title": "Total upstream connections",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 137 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(envoy_cluster_upstream_cx_total)\n\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connection errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 145 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by (envoy_cluster_name) (rate(\n    envoy_cluster_upstream_cx_connect_fail{node=~\"^${node}$\"}[$__rate_interval]\n) \n* on (node) group_left() (\n    kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n)) != 0",
     "legendFormat": "upstream_cx_connect_fail {{envoy_cluster_name}}"
    },
    {
     "expr": "sum by (envoy_cluster_name) (rate(\n    envoy_cluster_upstream_cx_connect_timeout{node=~\"^${node}$\"}[$__rate_interval]\n) \n* on (node) group_left() (\n    kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n)) != 0",
     "legendFormat": "upstream_cx_connect_timeout {{envoy_cluster_name}}"
    },
    {
     "expr": "sum by (envoy_cluster_name) (rate(\n    envoy_cluster_upstream_cx_pool_overflow{node=~\"^${node}$\"}[$__rate_interval]\n) \n* on (node) group_left() (\n    kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n)) != 0",
     "legendFormat": "upstream_cx_pool_overflow {{envoy_cluster_name}}"
    },
    {
     "expr": "sum by (envoy_cluster_name) (rate(\n    envoy_cluster_upstream_cx_protocol_error{node=~\"^${node}$\"}[$__rate_interval]\n) \n* on (node) group_left() (\n    kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n)) != 0",
     "legendFormat": "upstream_cx_protocol_error {{envoy_cluster_name}}"
    },
    {
     "expr": "sum by (envoy_cluster_name) (rate(\n    envoy_cluster_upstream_cx_max_requests{node=~\"^${node}$\"}[$__rate_interval]\n) \n* on (node) group_left() (\n    kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n)) != 0",
     "legendFormat": "upstream_cx_max_requests {{envoy_cluster_name}}"
    },
    {
     "expr": "sum by (envoy_cluster_name) (rate(\n    envoy_cluster_upstream_cx_none_healthy{node=~\"^${node}$\"}[$__rate_interval]\n) \n* on (node) group_left() (\n    kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n)) != 0",
     "legendFormat": "upstream_cx_none_healthy {{envoy_cluster_name}}"
    }
   ]
  },
  {
   "title": "Request errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 153 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by (envoy_cluster_name) (rate(\n    envoy_cluster_upstream_rq_pending_overflow{node=~\"^${node}$\", envoy_cluster_name=~\"^${service}$\"}[$__rate_interval]\n) \n* on (node) group_left() (\n    kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n)) != 0",
     "legendFormat": "rq pending overflow {{envoy_cluster_name}}"
    },
    {
     "expr": "sum by (envoy_cluster_name) (rate(\n    envoy_cluster_upstream_rq_pending_failure_eject{node=~\"^${node}$\", envoy_cluster_name=~\"^${service}$\"}[$__rate_interval]\n) \n* on (node) group_left() (\n    kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n)) != 0",
     "legendFormat": "rq pending failure eject {{envoy_cluster_name}}"
    },
    {
     "expr": "sum by (envoy_cluster_name) (rate(\n    envoy_cluster_upstream_rq_maintenance_mode{node=~\"^${node}$\", envoy_cluster_name=~\"^${service}$\"}[$__rate_interval]\n) \n* on (node) group_left() (\n    kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n)) != 0",
     "legendFormat": "rq maintenance mode {{envoy_cluster_name}}"
    },
    {
     "expr": "sum by (envoy_cluster_name) (rate(\n    envoy_cluster_upstream_rq_timeout{node=~\"^${node}$\", envoy_cluster_name=~\"^${service}$\"}[$__rate_interval]\n) \n* on (node) group_left() (\n    kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n)) != 0",
     "legendFormat": "rq timeout {{envoy_cluster_name}}"
    },
    {
     "expr": "sum by (envoy_cluster_name) (rate(\n    envoy_cluster_upstream_rq_per_try_timeout{node=~\"^${node}$\", envoy_cluster_name=~\"^${service}$\"}[$__rate_interval]\n) \n* on (node) group_left() (\n    kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n)) != 0",
     "legendFormat": "rq per try timeout {{envoy_cluster_name}}"
    }
   ]
  },
  {
   "title": "envoy_cluster_health_check_success",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 161 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (envoy_cluster_name) (\n    rate(\n        envoy_cluster_health_check_success{node=~\"^${node}$\"}[$__rate_interval]\n    ) \n    * on (node) group_left() (\n        kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n    )\n) != 0",
     "legendFormat": "{{envoy_cluster_name}}"
    }
   ]
  },
  {
   "title": "Healthcheck failures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 161 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by (envoy_cluster_name) (rate(\n    envoy_cluster_health_check_failure{node=~\"^${node}$\", envoy_cluster_name=~\"^${app}$\"}[$__rate_interval]\n) \n* on (node) group_left() (\n    kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n))",
     "legendFormat": "envoy_cluster_health_check_failure {{envoy_cluster_name}}"
    },
    {
     "expr": "sum by (envoy_cluster_name) (rate(\n    envoy_cluster_health_check_passive_failure{node=~\"^${t2}$\", envoy_cluster_name=~\"^${app}$\"}[$__rate_interval]\n) \n* on (node) group_left() (\n    kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n))",
     "legendFormat": "envoy_cluster_health_check_passive_failure {{envoy_cluster_name}}"
    },
    {
     "expr": "sum by (envoy_cluster_name) (rate(\n    envoy_cluster_health_check_network_failure{node=~\"^${t2}$\", envoy_cluster_name=~\"^${app}$\"}[$__rate_interval]\n) \n* on (node) group_left() (\n    kube_node_labels{label_service_cilium_io_node=~\"t2\"}\n))",
     "legendFormat": "envoy_cluster_health_check_network_failure {{envoy_cluster_name}}"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 169 } },
  {
   "title": "CPU %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 170 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * avg(\n  1 - rate(\n    node_cpu_seconds_total{mode=~\"idle\"}[$__rate_interval]\n    )\n  ) by (instance)\n* on (instance) group_left(node) (\n  label_replace(kube_node_status_addresses{node=~\"^${node}$\"}, \"instance\", \"$1:9100\", \"address\", \"(.*)\")\n)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 170 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_load1{job=\"node-exporter\"} \n* on (instance) group_left(node) (\n    label_replace(kube_node_status_addresses{node=~\"^${node}$\"}, \"instance\", \"$1:9100\", \"address\", \"(.*)\")\n)",
     "legendFormat": "{{node}}, 1m"
    },
    {
     "expr": "node_load5{job=\"node-exporter\"} \n* on (instance) group_left(node) (\n    label_replace(kube_node_status_addresses{node=~\"^${node}$\"}, \"instance\", \"$1:9100\", \"address\", \"(.*)\")\n)",
     "legendFormat": "{{node}}, 5m"
    },
    {
     "expr": "node_load15{job=\"node-exporter\"} \n* on (instance) group_left(node) (\n    label_replace(kube_node_status_addresses{node=~\"^${node}$\"}, \"instance\", \"$1:9100\", \"address\", \"(.*)\")\n)",
     "legendFormat": "{{node}}, 15m"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 178 } },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 179 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(\n  node_memory_MemTotal_bytes{job=\"node-exporter\"}\n-\n  node_memory_MemFree_bytes{job=\"node-exporter\"}\n-\n  node_memory_Buffers_bytes{job=\"node-exporter\"}\n-\n  node_memory_Cached_bytes{job=\"node-exporter\"}\n)\n* on (instance) group_left(node) (\n  label_replace(kube_node_status_addresses{node=~\"^${node}$\"}, \"instance\", \"$1:9100\", \"address\", \"(.*)\")\n)\n",
     "legendFormat": "{{node}} used"
    },
    {
     "expr": "node_memory_Buffers_bytes{job=\"node-exporter\"} * on (instance) group_left(node) (\n  label_replace(kube_node_status_addresses{node=~\"^${node}$\"}, \"instance\", \"$1:9100\", \"address\", \"(.*)\")\n)",
     "legendFormat": "{{node}} buffers"
    },
    {
     "expr": "node_memory_Cached_bytes{job=\"node-exporter\"} * on (instance) group_left(node) (\n  label_replace(kube_node_status_addresses{node=~\"^${node}$\"}, \"instance\", \"$1:9100\", \"address\", \"(.*)\")\n)\n",
     "legendFormat": "{{node}} cached"
    },
    {
     "expr": "node_memory_MemFree_bytes{job=\"node-exporter\"} * on (instance) group_left(node) (\n  label_replace(kube_node_status_addresses{node=~\"^${node}$\"}, \"instance\", \"$1:9100\", \"address\", \"(.*)\")\n)",
     "legendFormat": "{{node}} free"
    }
   ]
  }
 ]
}