{
 "title": "ILB Operator",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(cilium_lb_bytes_total,service)"
    }
   }
  ]
 },
 "panels": [
  { "title": "LB status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Services with unhealthy BGP peers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by (service) (cilium_operator_loadbalancer_controlplane_unhealthy_bgp_peers{service=~\"^${service}\"}) != 0",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Services with unhealthy BGP nodes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum by (service) (cilium_operator_loadbalancer_controlplane_unhealthy_bgp_nodes{service=~\"^${service}\"}) != 0",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Services with unhealthy T1 nodes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by (service) (cilium_operator_loadbalancer_controlplane_unhealthy_t1_nodes{service=~\"^${service}\"}) != 0",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Services with unhealthy T2 Healthchecks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum by (service) (cilium_operator_loadbalancer_controlplane_unhealthy_t2_healthchecks{service=~\"^${service}\"}) != 0",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Services with unhealthy T2 nodes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum by (service) (cilium_operator_loadbalancer_controlplane_unhealthy_t2_nodes{service=~\"^${service}\"}) != 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Services with unhealthy T2 backend Healthchecks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "sum by (service) (cilium_operator_loadbalancer_controlplane_unhealthy_t2_backend_healthchecks{service=~\"^${service}\"}) != 0",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Services with unhealthy T2 backend pools",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum by (service) (cilium_operator_loadbalancer_controlplane_unhealthy_backend_pools{service=~\"^${service}\"}) != 0",
     "legendFormat": "{{service}}"
    }
   ]
  },
  { "title": "Controller runtime", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Successfull reconciliations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(controller_runtime_reconcile_total{result=\"success\", controller=~\"lb.*\"}[$__rate_interval])",
     "legendFormat": "{{controller}} {{result}}"
    }
   ]
  },
  {
   "title": "Reconcile requeue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "targets": [
    {
     "expr": "rate(controller_runtime_reconcile_total{result=\"requeue\", controller=~\"lb.*\"}[$__rate_interval])",
     "legendFormat": "{{controller}} {{result}}"
    }
   ]
  },
  {
   "title": "Reconcile errors (controller_runtime_reconcile_total{result=\"error\"})",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "targets": [
    {
     "expr": "rate(controller_runtime_reconcile_total{result=\"error\", controller=~\"lb.*\"}[$__rate_interval])",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "Reconcile requeue after",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(controller_runtime_reconcile_total{result=\"requeue_after\", controller=~\"lb.*\"}[$__rate_interval])",
     "legendFormat": "{{controller}} {{result}}"
    }
   ]
  },
  {
   "title": "Reconcile errors (controller_runtime_reconcile_errors_total)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "targets": [
    {
     "expr": "rate(controller_runtime_reconcile_errors_total{controller=~\"lb.*\"}[$__rate_interval])",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "Terminal reconcile errors (controller_runtime_reconcile_errors_total)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "targets": [
    {
     "expr": "rate(controller_runtime_terminal_reconcile_errors_total{controller=~\"lb.*\"}[$__rate_interval])",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "Reconcile panics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "targets": [
    {
     "expr": "rate(controller_runtime_reconcile_panics_total{controller=~\"lb.*\"}[$__rate_interval])",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "Reconciliation length",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(controller_runtime_reconcile_time_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max concurrent reconciles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "controller_runtime_max_concurrent_reconciles{controller=~\"lb.*\"}",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "Active workers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "controller_runtime_active_workers{controller=~\"lb.*\"}",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  { "title": "Workqueue", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 } },
  {
   "title": "Workqueue depth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "workqueue_depth{controller=~\"lb.*\"}",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "Workqueue adds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "targets": [
    {
     "expr": "rate(workqueue_adds_total{controller=~\"lb.*\"}[$__rate_interval])",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "Workqueue duration",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(workqueue_queue_duration_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "Workqueue work duration",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(workqueue_work_duration_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Workqueue unfinished work",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "workqueue_unfinished_work_seconds{controller=~\"lb.*\"}",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "Workqueue longest running processor",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "workqueue_longest_running_processor_seconds{controller=~\"lb.*\"}",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "Workqueue retries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(workqueue_retries_total{controller=~\"lb.*\"}[$__rate_interval])",
     "legendFormat": "{{controller}}"
    }
   ]
  }
 ]
}