{{- if .Values.preflight.enabled }}
{{- /*
Keep file in sync with cilium-agent/enterprise-clusterrole.yaml
*/ -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: enterprise-cilium-pre-flight
  labels:
    app.kubernetes.io/part-of: cilium
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
rules:
- apiGroups:
  - isovalent.com
  resources:
  - isovalentegressgatewaypolicies
  - isovalentsrv6sidmanagers
  - isovalentsrv6locatorpools
  - isovalentsrv6egresspolicies
  - isovalentvrfs
  - isovalentmulticastgroups
  - isovalentbfdprofiles
  - isovalentnetworkpolicies
  - isovalentclusterwidenetworkpolicies
  verbs:
  - list
  - watch
- apiGroups:
  - isovalent.com
  resources:
  - isovalentsrv6sidmanagers/status
  verbs:
  - patch
- apiGroups:
  - isovalent.com
  resources:
  - isovalentsrv6egresspolicies
  verbs:
  - create
  - delete
  - get
{{- if .Values.enterprise.multiNetwork.enabled }}
- apiGroups:
    - isovalent.com
  resources:
    - isovalentpodnetworks
  verbs:
    - list
    - watch
    - get
{{- end }}
{{- if .Values.enterprise.bgpControlPlane.enabled }}
- apiGroups:
  - isovalent.com
  resources:
  - isovalentbgppeerconfigs
  - isovalentbgpadvertisements
  - isovalentbgpvrfconfigs
  verbs:
  - list
  - watch
  - get
{{- end }}
- apiGroups:
  - isovalent.com
  resources:
  - isovalentmulticastnodes
  - isovalentmulticastnodes/status
  - isovalentbfdnodeconfigs
  - isovalentbfdnodeconfigs/status
  - isovalentbgpnodeconfigs
  - isovalentbgpnodeconfigs/status
  verbs:
  - create
  - update
  - delete
  - get
  - watch
  - list
  - patch
{{- if .Values.enterprise.encryption.policy.enabled }}
- apiGroups:
    - isovalent.com
  resources:
    - isovalentclusterwideencryptionpolicies
  verbs:
    - list
    - watch
    - get
{{- end }}
{{- if .Values.enterprise.privateNetworks.enabled }}
- apiGroups:
    - isovalent.com
  resources:
    - clusterwideprivatenetworks
    - privatenetworknodeattachments
  verbs:
    - list
    - watch
    - get
- apiGroups:
    - isovalent.com
  resources:
    - privatenetworkendpointslices
  verbs:
    - list
    - watch
    - get
    - create
    - update
    - delete
{{- end }}
{{- end }}
