// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by client-gen. DO NOT EDIT.

package v1

type IsovalentBGPAdvertisementExpansion interface{}

type IsovalentBGPClusterConfigExpansion interface{}

type IsovalentBGPNodeConfigExpansion interface{}

type IsovalentBGPNodeConfigOverrideExpansion interface{}

type IsovalentBGPPeerConfigExpansion interface{}

type IsovalentClusterwideNetworkPolicyExpansion interface{}

type IsovalentEgressGatewayPolicyExpansion interface{}

type IsovalentNetworkPolicyExpansion interface{}
