// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	context "context"

	isovalentcomv1 "github.com/cilium/cilium/pkg/k8s/apis/isovalent.com/v1"
	scheme "github.com/cilium/cilium/pkg/k8s/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// IsovalentBGPNodeConfigsGetter has a method to return a IsovalentBGPNodeConfigInterface.
// A group's client should implement this interface.
type IsovalentBGPNodeConfigsGetter interface {
	IsovalentBGPNodeConfigs() IsovalentBGPNodeConfigInterface
}

// IsovalentBGPNodeConfigInterface has methods to work with IsovalentBGPNodeConfig resources.
type IsovalentBGPNodeConfigInterface interface {
	Create(ctx context.Context, isovalentBGPNodeConfig *isovalentcomv1.IsovalentBGPNodeConfig, opts metav1.CreateOptions) (*isovalentcomv1.IsovalentBGPNodeConfig, error)
	Update(ctx context.Context, isovalentBGPNodeConfig *isovalentcomv1.IsovalentBGPNodeConfig, opts metav1.UpdateOptions) (*isovalentcomv1.IsovalentBGPNodeConfig, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, isovalentBGPNodeConfig *isovalentcomv1.IsovalentBGPNodeConfig, opts metav1.UpdateOptions) (*isovalentcomv1.IsovalentBGPNodeConfig, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*isovalentcomv1.IsovalentBGPNodeConfig, error)
	List(ctx context.Context, opts metav1.ListOptions) (*isovalentcomv1.IsovalentBGPNodeConfigList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *isovalentcomv1.IsovalentBGPNodeConfig, err error)
	IsovalentBGPNodeConfigExpansion
}

// isovalentBGPNodeConfigs implements IsovalentBGPNodeConfigInterface
type isovalentBGPNodeConfigs struct {
	*gentype.ClientWithList[*isovalentcomv1.IsovalentBGPNodeConfig, *isovalentcomv1.IsovalentBGPNodeConfigList]
}

// newIsovalentBGPNodeConfigs returns a IsovalentBGPNodeConfigs
func newIsovalentBGPNodeConfigs(c *IsovalentV1Client) *isovalentBGPNodeConfigs {
	return &isovalentBGPNodeConfigs{
		gentype.NewClientWithList[*isovalentcomv1.IsovalentBGPNodeConfig, *isovalentcomv1.IsovalentBGPNodeConfigList](
			"isovalentbgpnodeconfigs",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *isovalentcomv1.IsovalentBGPNodeConfig { return &isovalentcomv1.IsovalentBGPNodeConfig{} },
			func() *isovalentcomv1.IsovalentBGPNodeConfigList { return &isovalentcomv1.IsovalentBGPNodeConfigList{} },
		),
	}
}
