// Code generated by go-swagger; DO NOT EDIT.

// Copyright (C) Isovalent, Inc. - All Rights Reserved.
//
// NOTICE: All information contained herein is, and remains the property of
// Isovalent Inc and its suppliers, if any. The intellectual and technical
// concepts contained herein are proprietary to Isovalent Inc and its suppliers
// and may be covered by U.S. and Foreign Patents, patents in process, and are
// protected by trade secret or copyright law.  Dissemination of this information
// or reproduction of this material is strictly forbidden unless prior written
// permission is obtained from Isovalent Inc.

package network

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// NewGetNetworkPrivateAddressingParams creates a new GetNetworkPrivateAddressingParams object
//
// There are no default values defined in the spec.
func NewGetNetworkPrivateAddressingParams() GetNetworkPrivateAddressingParams {

	return GetNetworkPrivateAddressingParams{}
}

// GetNetworkPrivateAddressingParams contains all the bound params for the get network private addressing operation
// typically these are obtained from a http.Request
//
// swagger:parameters GetNetworkPrivateAddressing
type GetNetworkPrivateAddressingParams struct {
	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Interface name, used to identify the network attachment in case of multi-NIC pods
	  Required: true
	  In: query
	*/
	Ifname string

	/*Name of the target private network, if provided via CNI configuration
	  In: query
	*/
	Network *string

	/*Kubernetes pod name for which to query the network attachment
	  Required: true
	  In: query
	*/
	PodName string

	/*Kubernetes pod namespace for which to query the network attachment
	  Required: true
	  In: query
	*/
	PodNamespace string

	/*Kubernetes pod uid for which to query the network attachment
	  Required: true
	  In: query
	*/
	PodUID string

	/*Name of the target subnet in the private network, if provided via CNI configuration
	  In: query
	*/
	Subnet *string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetNetworkPrivateAddressingParams() beforehand.
func (o *GetNetworkPrivateAddressingParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r
	qs := runtime.Values(r.URL.Query())

	qIfname, qhkIfname, _ := qs.GetOK("ifname")
	if err := o.bindIfname(qIfname, qhkIfname, route.Formats); err != nil {
		res = append(res, err)
	}

	qNetwork, qhkNetwork, _ := qs.GetOK("network")
	if err := o.bindNetwork(qNetwork, qhkNetwork, route.Formats); err != nil {
		res = append(res, err)
	}

	qPodName, qhkPodName, _ := qs.GetOK("pod-name")
	if err := o.bindPodName(qPodName, qhkPodName, route.Formats); err != nil {
		res = append(res, err)
	}

	qPodNamespace, qhkPodNamespace, _ := qs.GetOK("pod-namespace")
	if err := o.bindPodNamespace(qPodNamespace, qhkPodNamespace, route.Formats); err != nil {
		res = append(res, err)
	}

	qPodUID, qhkPodUID, _ := qs.GetOK("pod-uid")
	if err := o.bindPodUID(qPodUID, qhkPodUID, route.Formats); err != nil {
		res = append(res, err)
	}

	qSubnet, qhkSubnet, _ := qs.GetOK("subnet")
	if err := o.bindSubnet(qSubnet, qhkSubnet, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindIfname binds and validates parameter Ifname from query.
func (o *GetNetworkPrivateAddressingParams) bindIfname(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("ifname", "query", rawData)
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// AllowEmptyValue: false

	if err := validate.RequiredString("ifname", "query", raw); err != nil {
		return err
	}
	o.Ifname = raw

	return nil
}

// bindNetwork binds and validates parameter Network from query.
func (o *GetNetworkPrivateAddressingParams) bindNetwork(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		return nil
	}
	o.Network = &raw

	return nil
}

// bindPodName binds and validates parameter PodName from query.
func (o *GetNetworkPrivateAddressingParams) bindPodName(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("pod-name", "query", rawData)
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// AllowEmptyValue: false

	if err := validate.RequiredString("pod-name", "query", raw); err != nil {
		return err
	}
	o.PodName = raw

	return nil
}

// bindPodNamespace binds and validates parameter PodNamespace from query.
func (o *GetNetworkPrivateAddressingParams) bindPodNamespace(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("pod-namespace", "query", rawData)
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// AllowEmptyValue: false

	if err := validate.RequiredString("pod-namespace", "query", raw); err != nil {
		return err
	}
	o.PodNamespace = raw

	return nil
}

// bindPodUID binds and validates parameter PodUID from query.
func (o *GetNetworkPrivateAddressingParams) bindPodUID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("pod-uid", "query", rawData)
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// AllowEmptyValue: false

	if err := validate.RequiredString("pod-uid", "query", raw); err != nil {
		return err
	}
	o.PodUID = raw

	return nil
}

// bindSubnet binds and validates parameter Subnet from query.
func (o *GetNetworkPrivateAddressingParams) bindSubnet(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		return nil
	}
	o.Subnet = &raw

	return nil
}
