{
 "title": "Encryption Policy Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Encryption Policy Subsystem", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Encryption Policy Computation",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "seconds" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(cilium_encryption_policy_computation_runs_duration_seconds_bucket[$__interval])) by (le, reason))",
     "legendFormat": "P50 {{reason}}"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(cilium_encryption_policy_computation_runs_duration_seconds_bucket[$__interval])) by (le, reason))",
     "legendFormat": "P90 {{reason}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(cilium_encryption_policy_computation_runs_duration_seconds_bucket[$__interval])) by (le, reason))",
     "legendFormat": "P99 {{reason}}"
    }
   ]
  },
  {
   "title": "Encryption Policy BPF Reconciliation",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "seconds" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(cilium_encryption_policy_bpf_reconciliation_duration_seconds_bucket[$__interval])) by (le, reason))",
     "legendFormat": "P50 {{reason}}"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(cilium_encryption_policy_bpf_reconciliation_duration_seconds_bucket[$__interval])) by (le, reason))",
     "legendFormat": "P90 {{reason}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(cilium_encryption_policy_bpf_reconciliation_duration_seconds_bucket[$__interval])) by (le, reason))",
     "legendFormat": "P99 {{reason}}"
    }
   ]
  },
  {
   "title": "Encryption Policy Counters",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "count" }
   ],
   "targets": [
    {
     "expr": "avg(increase(cilium_encryption_policy_computation_runs_total[$__interval])) by (reason)",
     "legendFormat": "Average {{reason}} events"
    },
    {
     "expr": "sum(cilium_encryption_bpf_reconciliation_errors_total)",
     "legendFormat": "Total BPF Reconiliation Errors"
    }
   ]
  },
  {
   "title": "Policies",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(cilium_encryption_policy_rules)",
     "legendFormat": "Number of encryption policy rules"
    }
   ]
  },
  {
   "title": "Encryption Policy BPF Map Pressure",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(cilium_bpf_map_pressure{map_name=\"encryption_policy_map\"})",
     "legendFormat": "Encryption Policy Map Pressure"
    }
   ]
  },
  { "title": "CPU and Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Cilium Agent CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "percentunit", "label": "Percentage" }
   ],
   "targets": [
    {
     "expr": "avg(irate(cilium_process_cpu_seconds_total[$__interval]))",
     "legendFormat": "Average"
    },
    {
     "expr": "min(irate(cilium_process_cpu_seconds_total[$__interval]))",
     "legendFormat": "Min"
    },
    {
     "expr": "max(irate(cilium_process_cpu_seconds_total[$__interval]))",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Cilium Agent RSS Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg(cilium_process_resident_memory_bytes)",
     "legendFormat": "Average"
    },
    {
     "expr": "min(cilium_process_resident_memory_bytes)",
     "legendFormat": "Min"
    },
    {
     "expr": "max(cilium_process_resident_memory_bytes)",
     "legendFormat": "Max"
    }
   ]
  }
 ]
}