{{- if and .Values.agent (eq (include "hubble.timescape.tls.enabled" .) "true") (eq .Values.hubble.tls.auto.method "helm") }}
{{- $_ := include "cilium.ca.setup" . -}}
{{- $cn := "hubble-timescape" | join "." }}
{{- $dns := list $cn }}
{{- $cert := genSignedCert $cn nil $dns (.Values.hubble.tls.auto.certValidityDuration | int) .commonCA -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: hubble-timescape-client-certs
  namespace: {{ include "cilium.namespace" . }}
  labels:
    cilium.io/helm-template-non-idempotent: "true"
  annotations:
  {{- with .Values.hubble.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.nonIdempotentAnnotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: kubernetes.io/tls
data:
  ca.crt:  {{ .commonCA.Cert | b64enc }}
  tls.crt: {{ $cert.Cert | b64enc }}
  tls.key: {{ $cert.Key  | b64enc }}
{{- end }}
