// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	isovalentcomv1alpha1 "github.com/cilium/cilium/pkg/k8s/apis/isovalent.com/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// ClusterwidePrivateNetworkLister helps list ClusterwidePrivateNetworks.
// All objects returned here must be treated as read-only.
type ClusterwidePrivateNetworkLister interface {
	// List lists all ClusterwidePrivateNetworks in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*isovalentcomv1alpha1.ClusterwidePrivateNetwork, err error)
	// Get retrieves the ClusterwidePrivateNetwork from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*isovalentcomv1alpha1.ClusterwidePrivateNetwork, error)
	ClusterwidePrivateNetworkListerExpansion
}

// clusterwidePrivateNetworkLister implements the ClusterwidePrivateNetworkLister interface.
type clusterwidePrivateNetworkLister struct {
	listers.ResourceIndexer[*isovalentcomv1alpha1.ClusterwidePrivateNetwork]
}

// NewClusterwidePrivateNetworkLister returns a new ClusterwidePrivateNetworkLister.
func NewClusterwidePrivateNetworkLister(indexer cache.Indexer) ClusterwidePrivateNetworkLister {
	return &clusterwidePrivateNetworkLister{listers.New[*isovalentcomv1alpha1.ClusterwidePrivateNetwork](indexer, isovalentcomv1alpha1.Resource("clusterwideprivatenetwork"))}
}
