// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	isovalentcomv1alpha1 "github.com/cilium/cilium/pkg/k8s/apis/isovalent.com/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// IsovalentWAFPolicyLister helps list IsovalentWAFPolicies.
// All objects returned here must be treated as read-only.
type IsovalentWAFPolicyLister interface {
	// List lists all IsovalentWAFPolicies in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*isovalentcomv1alpha1.IsovalentWAFPolicy, err error)
	// IsovalentWAFPolicies returns an object that can list and get IsovalentWAFPolicies.
	IsovalentWAFPolicies(namespace string) IsovalentWAFPolicyNamespaceLister
	IsovalentWAFPolicyListerExpansion
}

// isovalentWAFPolicyLister implements the IsovalentWAFPolicyLister interface.
type isovalentWAFPolicyLister struct {
	listers.ResourceIndexer[*isovalentcomv1alpha1.IsovalentWAFPolicy]
}

// NewIsovalentWAFPolicyLister returns a new IsovalentWAFPolicyLister.
func NewIsovalentWAFPolicyLister(indexer cache.Indexer) IsovalentWAFPolicyLister {
	return &isovalentWAFPolicyLister{listers.New[*isovalentcomv1alpha1.IsovalentWAFPolicy](indexer, isovalentcomv1alpha1.Resource("isovalentwafpolicy"))}
}

// IsovalentWAFPolicies returns an object that can list and get IsovalentWAFPolicies.
func (s *isovalentWAFPolicyLister) IsovalentWAFPolicies(namespace string) IsovalentWAFPolicyNamespaceLister {
	return isovalentWAFPolicyNamespaceLister{listers.NewNamespaced[*isovalentcomv1alpha1.IsovalentWAFPolicy](s.ResourceIndexer, namespace)}
}

// IsovalentWAFPolicyNamespaceLister helps list and get IsovalentWAFPolicies.
// All objects returned here must be treated as read-only.
type IsovalentWAFPolicyNamespaceLister interface {
	// List lists all IsovalentWAFPolicies in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*isovalentcomv1alpha1.IsovalentWAFPolicy, err error)
	// Get retrieves the IsovalentWAFPolicy from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*isovalentcomv1alpha1.IsovalentWAFPolicy, error)
	IsovalentWAFPolicyNamespaceListerExpansion
}

// isovalentWAFPolicyNamespaceLister implements the IsovalentWAFPolicyNamespaceLister
// interface.
type isovalentWAFPolicyNamespaceLister struct {
	listers.ResourceIndexer[*isovalentcomv1alpha1.IsovalentWAFPolicy]
}
