// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	isovalentcomv1alpha1 "github.com/cilium/cilium/pkg/k8s/apis/isovalent.com/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// IsovalentBGPVRFConfigLister helps list IsovalentBGPVRFConfigs.
// All objects returned here must be treated as read-only.
type IsovalentBGPVRFConfigLister interface {
	// List lists all IsovalentBGPVRFConfigs in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*isovalentcomv1alpha1.IsovalentBGPVRFConfig, err error)
	// Get retrieves the IsovalentBGPVRFConfig from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*isovalentcomv1alpha1.IsovalentBGPVRFConfig, error)
	IsovalentBGPVRFConfigListerExpansion
}

// isovalentBGPVRFConfigLister implements the IsovalentBGPVRFConfigLister interface.
type isovalentBGPVRFConfigLister struct {
	listers.ResourceIndexer[*isovalentcomv1alpha1.IsovalentBGPVRFConfig]
}

// NewIsovalentBGPVRFConfigLister returns a new IsovalentBGPVRFConfigLister.
func NewIsovalentBGPVRFConfigLister(indexer cache.Indexer) IsovalentBGPVRFConfigLister {
	return &isovalentBGPVRFConfigLister{listers.New[*isovalentcomv1alpha1.IsovalentBGPVRFConfig](indexer, isovalentcomv1alpha1.Resource("isovalentbgpvrfconfig"))}
}
