// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	isovalentcomv1alpha1 "github.com/cilium/cilium/pkg/k8s/apis/isovalent.com/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// IsovalentMulticastNodeLister helps list IsovalentMulticastNodes.
// All objects returned here must be treated as read-only.
type IsovalentMulticastNodeLister interface {
	// List lists all IsovalentMulticastNodes in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*isovalentcomv1alpha1.IsovalentMulticastNode, err error)
	// Get retrieves the IsovalentMulticastNode from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*isovalentcomv1alpha1.IsovalentMulticastNode, error)
	IsovalentMulticastNodeListerExpansion
}

// isovalentMulticastNodeLister implements the IsovalentMulticastNodeLister interface.
type isovalentMulticastNodeLister struct {
	listers.ResourceIndexer[*isovalentcomv1alpha1.IsovalentMulticastNode]
}

// NewIsovalentMulticastNodeLister returns a new IsovalentMulticastNodeLister.
func NewIsovalentMulticastNodeLister(indexer cache.Indexer) IsovalentMulticastNodeLister {
	return &isovalentMulticastNodeLister{listers.New[*isovalentcomv1alpha1.IsovalentMulticastNode](indexer, isovalentcomv1alpha1.Resource("isovalentmulticastnode"))}
}
