// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/cilium/cilium/pkg/k8s/apis/isovalent.com/v1alpha1"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/listers"
	"k8s.io/client-go/tools/cache"
)

// IsovalentLBLister helps list IsovalentLBs.
// All objects returned here must be treated as read-only.
type IsovalentLBLister interface {
	// List lists all IsovalentLBs in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.IsovalentLB, err error)
	// IsovalentLBs returns an object that can list and get IsovalentLBs.
	IsovalentLBs(namespace string) IsovalentLBNamespaceLister
	IsovalentLBListerExpansion
}

// isovalentLBLister implements the IsovalentLBLister interface.
type isovalentLBLister struct {
	listers.ResourceIndexer[*v1alpha1.IsovalentLB]
}

// NewIsovalentLBLister returns a new IsovalentLBLister.
func NewIsovalentLBLister(indexer cache.Indexer) IsovalentLBLister {
	return &isovalentLBLister{listers.New[*v1alpha1.IsovalentLB](indexer, v1alpha1.Resource("isovalentlb"))}
}

// IsovalentLBs returns an object that can list and get IsovalentLBs.
func (s *isovalentLBLister) IsovalentLBs(namespace string) IsovalentLBNamespaceLister {
	return isovalentLBNamespaceLister{listers.NewNamespaced[*v1alpha1.IsovalentLB](s.ResourceIndexer, namespace)}
}

// IsovalentLBNamespaceLister helps list and get IsovalentLBs.
// All objects returned here must be treated as read-only.
type IsovalentLBNamespaceLister interface {
	// List lists all IsovalentLBs in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.IsovalentLB, err error)
	// Get retrieves the IsovalentLB from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.IsovalentLB, error)
	IsovalentLBNamespaceListerExpansion
}

// isovalentLBNamespaceLister implements the IsovalentLBNamespaceLister
// interface.
type isovalentLBNamespaceLister struct {
	listers.ResourceIndexer[*v1alpha1.IsovalentLB]
}
