// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/cilium/cilium/pkg/k8s/apis/isovalent.com/v1alpha1"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/listers"
	"k8s.io/client-go/tools/cache"
)

// LBBackendLister helps list LBBackends.
// All objects returned here must be treated as read-only.
type LBBackendLister interface {
	// List lists all LBBackends in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.LBBackend, err error)
	// LBBackends returns an object that can list and get LBBackends.
	LBBackends(namespace string) LBBackendNamespaceLister
	LBBackendListerExpansion
}

// lBBackendLister implements the LBBackendLister interface.
type lBBackendLister struct {
	listers.ResourceIndexer[*v1alpha1.LBBackend]
}

// NewLBBackendLister returns a new LBBackendLister.
func NewLBBackendLister(indexer cache.Indexer) LBBackendLister {
	return &lBBackendLister{listers.New[*v1alpha1.LBBackend](indexer, v1alpha1.Resource("lbbackend"))}
}

// LBBackends returns an object that can list and get LBBackends.
func (s *lBBackendLister) LBBackends(namespace string) LBBackendNamespaceLister {
	return lBBackendNamespaceLister{listers.NewNamespaced[*v1alpha1.LBBackend](s.ResourceIndexer, namespace)}
}

// LBBackendNamespaceLister helps list and get LBBackends.
// All objects returned here must be treated as read-only.
type LBBackendNamespaceLister interface {
	// List lists all LBBackends in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.LBBackend, err error)
	// Get retrieves the LBBackend from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.LBBackend, error)
	LBBackendNamespaceListerExpansion
}

// lBBackendNamespaceLister implements the LBBackendNamespaceLister
// interface.
type lBBackendNamespaceLister struct {
	listers.ResourceIndexer[*v1alpha1.LBBackend]
}
