// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by informer-gen. DO NOT EDIT.

package externalversions

import (
	fmt "fmt"

	v2 "github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2"
	v2alpha1 "github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2alpha1"
	v1 "github.com/cilium/cilium/pkg/k8s/apis/isovalent.com/v1"
	v1alpha1 "github.com/cilium/cilium/pkg/k8s/apis/isovalent.com/v1alpha1"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	cache "k8s.io/client-go/tools/cache"
)

// GenericInformer is type of SharedIndexInformer which will locate and delegate to other
// sharedInformers based on type
type GenericInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() cache.GenericLister
}

type genericInformer struct {
	informer cache.SharedIndexInformer
	resource schema.GroupResource
}

// Informer returns the SharedIndexInformer.
func (f *genericInformer) Informer() cache.SharedIndexInformer {
	return f.informer
}

// Lister returns the GenericLister.
func (f *genericInformer) Lister() cache.GenericLister {
	return cache.NewGenericLister(f.Informer().GetIndexer(), f.resource)
}

// ForResource gives generic access to a shared informer of the matching type
// TODO extend this to unknown resources with a client pool
func (f *sharedInformerFactory) ForResource(resource schema.GroupVersionResource) (GenericInformer, error) {
	switch resource {
	// Group=cilium.io, Version=v2
	case v2.SchemeGroupVersion.WithResource("ciliumbgpadvertisements"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Cilium().V2().CiliumBGPAdvertisements().Informer()}, nil
	case v2.SchemeGroupVersion.WithResource("ciliumbgpclusterconfigs"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Cilium().V2().CiliumBGPClusterConfigs().Informer()}, nil
	case v2.SchemeGroupVersion.WithResource("ciliumbgpnodeconfigs"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Cilium().V2().CiliumBGPNodeConfigs().Informer()}, nil
	case v2.SchemeGroupVersion.WithResource("ciliumbgpnodeconfigoverrides"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Cilium().V2().CiliumBGPNodeConfigOverrides().Informer()}, nil
	case v2.SchemeGroupVersion.WithResource("ciliumbgppeerconfigs"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Cilium().V2().CiliumBGPPeerConfigs().Informer()}, nil
	case v2.SchemeGroupVersion.WithResource("ciliumcidrgroups"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Cilium().V2().CiliumCIDRGroups().Informer()}, nil
	case v2.SchemeGroupVersion.WithResource("ciliumclusterwideenvoyconfigs"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Cilium().V2().CiliumClusterwideEnvoyConfigs().Informer()}, nil
	case v2.SchemeGroupVersion.WithResource("ciliumclusterwidenetworkpolicies"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Cilium().V2().CiliumClusterwideNetworkPolicies().Informer()}, nil
	case v2.SchemeGroupVersion.WithResource("ciliumegressgatewaypolicies"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Cilium().V2().CiliumEgressGatewayPolicies().Informer()}, nil
	case v2.SchemeGroupVersion.WithResource("ciliumendpoints"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Cilium().V2().CiliumEndpoints().Informer()}, nil
	case v2.SchemeGroupVersion.WithResource("ciliumenvoyconfigs"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Cilium().V2().CiliumEnvoyConfigs().Informer()}, nil
	case v2.SchemeGroupVersion.WithResource("ciliumidentities"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Cilium().V2().CiliumIdentities().Informer()}, nil
	case v2.SchemeGroupVersion.WithResource("ciliumloadbalancerippools"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Cilium().V2().CiliumLoadBalancerIPPools().Informer()}, nil
	case v2.SchemeGroupVersion.WithResource("ciliumlocalredirectpolicies"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Cilium().V2().CiliumLocalRedirectPolicies().Informer()}, nil
	case v2.SchemeGroupVersion.WithResource("ciliumnetworkpolicies"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Cilium().V2().CiliumNetworkPolicies().Informer()}, nil
	case v2.SchemeGroupVersion.WithResource("ciliumnodes"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Cilium().V2().CiliumNodes().Informer()}, nil
	case v2.SchemeGroupVersion.WithResource("ciliumnodeconfigs"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Cilium().V2().CiliumNodeConfigs().Informer()}, nil

		// Group=cilium.io, Version=v2alpha1
	case v2alpha1.SchemeGroupVersion.WithResource("ciliumbgpadvertisements"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Cilium().V2alpha1().CiliumBGPAdvertisements().Informer()}, nil
	case v2alpha1.SchemeGroupVersion.WithResource("ciliumbgpclusterconfigs"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Cilium().V2alpha1().CiliumBGPClusterConfigs().Informer()}, nil
	case v2alpha1.SchemeGroupVersion.WithResource("ciliumbgpnodeconfigs"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Cilium().V2alpha1().CiliumBGPNodeConfigs().Informer()}, nil
	case v2alpha1.SchemeGroupVersion.WithResource("ciliumbgpnodeconfigoverrides"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Cilium().V2alpha1().CiliumBGPNodeConfigOverrides().Informer()}, nil
	case v2alpha1.SchemeGroupVersion.WithResource("ciliumbgppeerconfigs"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Cilium().V2alpha1().CiliumBGPPeerConfigs().Informer()}, nil
	case v2alpha1.SchemeGroupVersion.WithResource("ciliumbgppeeringpolicies"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Cilium().V2alpha1().CiliumBGPPeeringPolicies().Informer()}, nil
	case v2alpha1.SchemeGroupVersion.WithResource("ciliumcidrgroups"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Cilium().V2alpha1().CiliumCIDRGroups().Informer()}, nil
	case v2alpha1.SchemeGroupVersion.WithResource("ciliumendpointslices"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Cilium().V2alpha1().CiliumEndpointSlices().Informer()}, nil
	case v2alpha1.SchemeGroupVersion.WithResource("ciliumgatewayclassconfigs"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Cilium().V2alpha1().CiliumGatewayClassConfigs().Informer()}, nil
	case v2alpha1.SchemeGroupVersion.WithResource("ciliuml2announcementpolicies"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Cilium().V2alpha1().CiliumL2AnnouncementPolicies().Informer()}, nil
	case v2alpha1.SchemeGroupVersion.WithResource("ciliumloadbalancerippools"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Cilium().V2alpha1().CiliumLoadBalancerIPPools().Informer()}, nil
	case v2alpha1.SchemeGroupVersion.WithResource("ciliumnodeconfigs"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Cilium().V2alpha1().CiliumNodeConfigs().Informer()}, nil
	case v2alpha1.SchemeGroupVersion.WithResource("ciliumpodippools"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Cilium().V2alpha1().CiliumPodIPPools().Informer()}, nil

		// Group=isovalent.com, Version=v1
	case v1.SchemeGroupVersion.WithResource("isovalentbgpadvertisements"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Isovalent().V1().IsovalentBGPAdvertisements().Informer()}, nil
	case v1.SchemeGroupVersion.WithResource("isovalentbgpclusterconfigs"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Isovalent().V1().IsovalentBGPClusterConfigs().Informer()}, nil
	case v1.SchemeGroupVersion.WithResource("isovalentbgpnodeconfigs"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Isovalent().V1().IsovalentBGPNodeConfigs().Informer()}, nil
	case v1.SchemeGroupVersion.WithResource("isovalentbgpnodeconfigoverrides"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Isovalent().V1().IsovalentBGPNodeConfigOverrides().Informer()}, nil
	case v1.SchemeGroupVersion.WithResource("isovalentbgppeerconfigs"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Isovalent().V1().IsovalentBGPPeerConfigs().Informer()}, nil
	case v1.SchemeGroupVersion.WithResource("isovalentclusterwidenetworkpolicies"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Isovalent().V1().IsovalentClusterwideNetworkPolicies().Informer()}, nil
	case v1.SchemeGroupVersion.WithResource("isovalentegressgatewaypolicies"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Isovalent().V1().IsovalentEgressGatewayPolicies().Informer()}, nil
	case v1.SchemeGroupVersion.WithResource("isovalentnetworkpolicies"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Isovalent().V1().IsovalentNetworkPolicies().Informer()}, nil

		// Group=isovalent.com, Version=v1alpha1
	case v1alpha1.SchemeGroupVersion.WithResource("clusterwideprivatenetworks"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Isovalent().V1alpha1().ClusterwidePrivateNetworks().Informer()}, nil
	case v1alpha1.SchemeGroupVersion.WithResource("isovalentbfdnodeconfigs"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Isovalent().V1alpha1().IsovalentBFDNodeConfigs().Informer()}, nil
	case v1alpha1.SchemeGroupVersion.WithResource("isovalentbfdnodeconfigoverrides"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Isovalent().V1alpha1().IsovalentBFDNodeConfigOverrides().Informer()}, nil
	case v1alpha1.SchemeGroupVersion.WithResource("isovalentbfdprofiles"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Isovalent().V1alpha1().IsovalentBFDProfiles().Informer()}, nil
	case v1alpha1.SchemeGroupVersion.WithResource("isovalentbgpadvertisements"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Isovalent().V1alpha1().IsovalentBGPAdvertisements().Informer()}, nil
	case v1alpha1.SchemeGroupVersion.WithResource("isovalentbgpclusterconfigs"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Isovalent().V1alpha1().IsovalentBGPClusterConfigs().Informer()}, nil
	case v1alpha1.SchemeGroupVersion.WithResource("isovalentbgpnodeconfigs"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Isovalent().V1alpha1().IsovalentBGPNodeConfigs().Informer()}, nil
	case v1alpha1.SchemeGroupVersion.WithResource("isovalentbgpnodeconfigoverrides"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Isovalent().V1alpha1().IsovalentBGPNodeConfigOverrides().Informer()}, nil
	case v1alpha1.SchemeGroupVersion.WithResource("isovalentbgppeerconfigs"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Isovalent().V1alpha1().IsovalentBGPPeerConfigs().Informer()}, nil
	case v1alpha1.SchemeGroupVersion.WithResource("isovalentbgpvrfconfigs"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Isovalent().V1alpha1().IsovalentBGPVRFConfigs().Informer()}, nil
	case v1alpha1.SchemeGroupVersion.WithResource("isovalentclusterwideencryptionpolicies"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Isovalent().V1alpha1().IsovalentClusterwideEncryptionPolicies().Informer()}, nil
	case v1alpha1.SchemeGroupVersion.WithResource("isovalentclusterwidenetworkpolicies"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Isovalent().V1alpha1().IsovalentClusterwideNetworkPolicies().Informer()}, nil
	case v1alpha1.SchemeGroupVersion.WithResource("isovalentfqdngroups"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Isovalent().V1alpha1().IsovalentFQDNGroups().Informer()}, nil
	case v1alpha1.SchemeGroupVersion.WithResource("isovalentmeshendpoints"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Isovalent().V1alpha1().IsovalentMeshEndpoints().Informer()}, nil
	case v1alpha1.SchemeGroupVersion.WithResource("isovalentmulticastgroups"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Isovalent().V1alpha1().IsovalentMulticastGroups().Informer()}, nil
	case v1alpha1.SchemeGroupVersion.WithResource("isovalentmulticastnodes"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Isovalent().V1alpha1().IsovalentMulticastNodes().Informer()}, nil
	case v1alpha1.SchemeGroupVersion.WithResource("isovalentnetworkpolicies"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Isovalent().V1alpha1().IsovalentNetworkPolicies().Informer()}, nil
	case v1alpha1.SchemeGroupVersion.WithResource("isovalentpodnetworks"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Isovalent().V1alpha1().IsovalentPodNetworks().Informer()}, nil
	case v1alpha1.SchemeGroupVersion.WithResource("isovalentsrv6egresspolicies"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Isovalent().V1alpha1().IsovalentSRv6EgressPolicies().Informer()}, nil
	case v1alpha1.SchemeGroupVersion.WithResource("isovalentsrv6locatorpools"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Isovalent().V1alpha1().IsovalentSRv6LocatorPools().Informer()}, nil
	case v1alpha1.SchemeGroupVersion.WithResource("isovalentsrv6sidmanagers"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Isovalent().V1alpha1().IsovalentSRv6SIDManagers().Informer()}, nil
	case v1alpha1.SchemeGroupVersion.WithResource("isovalentvrfs"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Isovalent().V1alpha1().IsovalentVRFs().Informer()}, nil
	case v1alpha1.SchemeGroupVersion.WithResource("lbbackendpools"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Isovalent().V1alpha1().LBBackendPools().Informer()}, nil
	case v1alpha1.SchemeGroupVersion.WithResource("lbdeployments"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Isovalent().V1alpha1().LBDeployments().Informer()}, nil
	case v1alpha1.SchemeGroupVersion.WithResource("lbservices"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Isovalent().V1alpha1().LBServices().Informer()}, nil
	case v1alpha1.SchemeGroupVersion.WithResource("lbvips"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Isovalent().V1alpha1().LBVIPs().Informer()}, nil
	case v1alpha1.SchemeGroupVersion.WithResource("privatenetworkendpointslices"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Isovalent().V1alpha1().PrivateNetworkEndpointSlices().Informer()}, nil
	case v1alpha1.SchemeGroupVersion.WithResource("privatenetworkexternalendpoints"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Isovalent().V1alpha1().PrivateNetworkExternalEndpoints().Informer()}, nil

	}

	return nil, fmt.Errorf("no informer found for %v", resource)
}
