{{- if and
  .Values.agent
  (eq (include "hubble.timescape.tls.enabled" .) "true")
  (eq .Values.hubble.tls.auto.method "certmanager")
  (or
    (not .Values.hubble.timescape.clustermesh.primary.id)
    (eq (int64 .Values.hubble.timescape.clustermesh.primary.id) (int64 .Values.cluster.id))
  )
}}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hubble-timescape-server-certs
  namespace: {{ include "cilium.namespace" . }}
  {{- with .Values.hubble.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  issuerRef:
    {{- toYaml .Values.hubble.tls.auto.certManagerIssuerRef | nindent 4 }}
  secretName: hubble-timescape-server-certs
  commonName: "hubble-timescape"
  dnsNames:
  - "hubble-timescape"
  - "hubble-timescape.{{ .Release.Namespace }}.svc.cluster.local"
  - "hubble-timescape.{{ .Release.Namespace }}.svc"
  - "localhost"
  {{- range $dns := .Values.hubble.timescape.tls.server.extraDnsNames }}
  - {{ $dns | quote }}
  {{- end }}
  {{- if .Values.hubble.timescape.tls.server.extraIpAddresses }}
  ipAddresses:
  {{- range $ip := .Values.hubble.timescape.tls.server.extraIpAddresses }}
  - {{ $ip | quote }}
  {{- end }}
  {{- end }}
  duration: {{ printf "%dh0m0s" (mul .Values.hubble.tls.auto.certValidityDuration 24) }}
  privateKey:
    rotationPolicy: Always
  isCA: false
  usages:
    - signing
    - key encipherment
    - server auth
    - client auth
{{- end }}
