apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    app: cilium-etcd
  name: cilium-etcd
  namespace: monitoring
spec:
  podMetricsEndpoints:
    - interval: 60s
      port: etcd-metrics
  jobLabel: app
  selector:
    matchLabels:
      app: etcd
  namespaceSelector:
    matchNames:
    - kube-system
