{{- if and
  .Values.hubble.timescape.enabled
  .Values.hubble.timescape.metrics.serviceMonitor.enabled
  (or
    .Values.hubble.timescape.metrics.enabled
    .Values.hubble.timescape.metrics.clickhouse.enabled
  )
  (or
    (not .Values.hubble.timescape.clustermesh.primary.id)
    (eq (int64 .Values.hubble.timescape.clustermesh.primary.id) (int64 .Values.cluster.id))
  )
}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: hubble-timescape
  namespace: {{ .Values.hubble.timescape.metrics.serviceMonitor.namespace | default (include "cilium.namespace" .) }}
  labels:
    {{- include "hubble.timescape.labels" . | nindent 4 -}}
    {{/* The timescape labels already contain the .Values.commonLabels */}}
    {{- with .Values.hubble.timescape.metrics.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.hubble.timescape.metrics.serviceMonitor.annotations }}
  annotations:
      {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: hubble-timescape
      app.kubernetes.io/component: hubble-timescape
      app.kubernetes.io/part-of: cilium
  namespaceSelector:
    matchNames:
    - {{ include "cilium.namespace" . }}
  endpoints:
  {{- if .Values.hubble.timescape.metrics.enabled }}
    {{- include "hubble.timescape.servicemonitor.endpoint" (dict
        "values" .Values.hubble.timescape.metrics.serviceMonitor
        "port" "metrics"
      ) | nindent 2 }}
  {{- end }}
  {{- if .Values.hubble.timescape.metrics.clickhouse.enabled }}
    {{- include "hubble.timescape.servicemonitor.endpoint" (dict
        "values" .Values.hubble.timescape.metrics.serviceMonitor.clickhouse
        "port" "ch-metrics"
      ) | nindent 2 }}
  {{- end }}
{{- end }}
