{{- $envoyDS := eq (include "envoyDaemonSetEnabled" .) "true" -}}
{{- if (and $envoyDS (not .Values.preflight.enabled) .Values.envoy.gracefulRestart .Values.envoy.gracefulRestart.enabled) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: enterprise-cilium-envoy
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    app.kubernetes.io/part-of: cilium
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - create
  - patch
{{- end }}
