name: OLM Build CI

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - enterprise/olm/**
  push:
    branches:
      - main-ce
      - ft/main-ce/**
    paths:
      - enterprise/olm/**

permissions:
  # To be able to access the repository with `actions/checkout`
  contents: read
  # Required to generate OIDC tokens for `sigstore/cosign-installer` authentication
  id-token: write

jobs:
  test:
    timeout-minutes: 10
    name: Run Controller Tests
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout the repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          sparse-checkout: |
            enterprise/olm
            install/kubernetes/cilium

      - name: Setup go
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          cache: false
          # renovate: datasource=golang-version depName=go
          go-version: 1.26.1

      - name: Run tests
        working-directory: ./enterprise/olm
        run: |
          make test

  build-and-push-prs:
    needs: test
    timeout-minutes: 30
    name: Build and Push Images
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout the repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          sparse-checkout: |
            .github/actions
            enterprise/olm
            install/kubernetes
            images/scripts

      - name: Set Environment Variables
        uses: ./.github/actions/set-env-variables

      - name: Setup go
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          cache: false
          # renovate: datasource=golang-version depName=go
          go-version: 1.26.1

      - name: Login to quay.io
        uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2 # v4.0.0
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME_CI }}
          password: ${{ secrets.QUAY_PASSWORD_CI }}

      - name: Login to registry.redhat.io for pulling images
        uses: docker/login-action@9fe7774c8f8ebfade96f0a62aa10f3882309d517
        with:
          registry: registry.redhat.io
          username: ${{ secrets.REDHAT_USERNAME_CI }}
          password: ${{ secrets.REDHAT_PASSWORD_CI }}

      - name: Getting image tag
        id: tag
        run: |
          if [ "${{ github.event.pull_request.head.sha }}" != "" ]; then
            tag=${{ github.event.pull_request.head.sha }}
          else
            tag=${{ github.sha }}
          fi
          echo tag=${tag} >> $GITHUB_OUTPUT

      # Need to wait for the images of the components to be built as the digests of the component images
      # are populated into the value.yaml file copied into the CLife image.
      - name: Wait for images to be available
        id: wait_images
        timeout-minutes: 20
        shell: bash
        run: |
          for image in cilium-ubi-ci operator-generic-ubi-ci hubble-relay-ubi-ci clustermesh-apiserver-ubi-ci; do
            until docker manifest inspect quay.io/isovalent-dev/$image:${{ steps.tag.outputs.tag }} &> /dev/null; do sleep 45s; done
          done
          echo "images available"

      - name: Build and Push OLM container image
        env:
          IMG: "quay.io/${{ env.QUAY_ORGANIZATION_DEV }}/clife-ci:${{ steps.tag.outputs.tag }}"
          CL_TAG: "${{ steps.tag.outputs.tag }}"
        working-directory: ./enterprise/olm
        run: |
          make docker-buildx VERSION=${{ steps.tag.outputs.tag }}

      - name: CI Build digest
        id: docker_digest
        shell: bash
        run: |
          digest=$(images/scripts/get-image-digest.sh "quay.io/${{ env.QUAY_ORGANIZATION_DEV }}/clife-ci:${{ steps.tag.outputs.tag }}")
          echo digest=${digest} >> $GITHUB_OUTPUT

      - name: Install Cosign
        uses: sigstore/cosign-installer@ba7bc0a3fef59531c69a25acd34668d6d3fe6f22 # v4.1.0

      - name: Sign Container Images
        run: |
          cosign sign -y quay.io/${{ env.QUAY_ORGANIZATION_DEV }}/clife-ci@${{ steps.docker_digest.outputs.digest }}

      - name: Generate SBOM
        uses: anchore/sbom-action@57aae528053a48a3f6235f2d9461b05fbcb7366d # v0.23.1
        with:
          artifact-name: sbom_ci_clife_${{ steps.tag.outputs.tag }}.spdx.json
          output-file: ./sbom_ci_clife_${{ steps.tag.outputs.tag }}.spdx.json
          image: ${{ steps.tag.outputs.primary_tag }}

      - name: Attach SBOM attestation to container image
        run: |
          cosign attest -y --predicate sbom_ci_clife_${{ steps.tag.outputs.tag }}.spdx.json --type spdxjson "quay.io/${{ env.QUAY_ORGANIZATION_DEV }}/clife-ci:${{ steps.tag.outputs.tag }}"
