name: Panda Scale Test (ci-panda-scale)

on:
#  schedule:
#    - cron: '39 0 * * 1-5'

  workflow_dispatch:
    inputs:
      PR-number:
        description: "Pull request number."
        required: true
      context-ref:
        description: "Context in which the workflow runs. If PR is from a fork, will be the PR target branch (general case). If PR is NOT from a fork, will be the PR branch itself (this allows committers to test changes to workflows directly from PRs)."
        required: true
      SHA:
        description: "SHA under test (head of the PR branch)."
        required: true
      extra-args:
        description: "[JSON object] Arbitrary arguments passed from the trigger comment via regex capture group. Parse with 'fromJson(inputs.extra-args).argName' in workflow."
        required: false
        default: '{}'

permissions:
  # To be able to access the repository with actions/checkout
  contents: read
  # To be able to request the JWT from GitHub's OIDC provider
  id-token: write
  # To allow retrieving information from the PR API
  pull-requests: read
  # To be able to set commit status
  statuses: write

concurrency:
  # Structure:
  # - Workflow name
  # - Event type
  # - A unique identifier depending on event type:
  #   - schedule: SHA
  #   - workflow_dispatch: PR number
  #
  # This structure ensures a unique concurrency group name is generated for each
  # type of testing, such that re-runs will cancel the previous run.
  group: |
    ${{ github.workflow }}
    ${{ github.event_name }}
    ${{
      (github.event_name == 'schedule' && github.sha) ||
      (github.event_name == 'workflow_dispatch' && github.event.inputs.PR-number)
    }}
  cancel-in-progress: false

env:
  # renovate: datasource=golang-version depName=go
  go_version: 1.25.0
  cilium_cli_ci_version:
  # Adding k8s.local to the end makes kops happy-
  # has stricter DNS naming requirements.
  test_name: panda-scale
  cluster_name: ${{ github.run_id }}-${{ github.run_attempt }}
  # Domain name for GCP nodes. Used for TLS auth in the kvstore.
  # Project is set up with zonal DNS, but reverse lookups on IPs
  # return global DNS names without the zone. Since etcd will perform
  # a reverse lookup on connecting peers to check if their DNS name
  # matches a SAN wildcard, the zone is left off of the domain.
  # For more information, see
  # https://cloud.google.com/compute/docs/internal-dns and
  # https://etcd.io/docs/v3.4/op-guide/security/ (search
  # 'server supports reverse-lookup on wildcard DNS SAN').
  domain: c.${{ secrets.GCP_PERF_PROJECT_ID }}.internal
  # renovate: datasource=docker depName=google/cloud-sdk
  gcloud_version: 535.0.0

  # renovate: datasource=github-releases depName=cert-manager/cert-manager
  cert_manager_version: v1.18.2
  # renovate: datasource=github-releases depName=cert-manager/trust-manager
  trust_manager_version: v0.19.0

jobs:
  echo-inputs:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    name: Echo Workflow Dispatch Inputs
    runs-on: ubuntu-24.04
    steps:
      - name: Echo Workflow Dispatch Inputs
        run: |
          echo '${{ tojson(inputs) }}'

  commit-status-start:
    name: Commit Status Start
    runs-on: ubuntu-24.04
    steps:
      - name: Set initial commit status
        uses: myrotvorets/set-commit-status-action@3730c0a348a2ace3c110851bed53331bc6406e9f # v2.0.1
        with:
          sha: ${{ inputs.SHA || github.sha }}

  install-and-scaletest:
    runs-on: ${{ vars.GH_RUNNER_EXTRA_POWER }}
    name: Install and Scale Test
    timeout-minutes: 150
    steps:
      - name: Checkout context ref (trusted)
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          ref: ${{ inputs.context-ref || github.sha }}
          persist-credentials: false

      - name: Set Environment Variables
        uses: ./.github/actions/set-env-variables

      - name: Set up job variables
        id: vars
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ] ; then
            SHA="${{ inputs.SHA }}"
          else
            SHA="${{ github.sha }}"
          fi

          # Retrieve the target sha to run against on top of version
          if [[ ${{ inputs.extra-args }} =~ sha=([a-f0-9]+) ]]; then
            SHA=${BASH_REMATCH[1]}
          fi

          # Retrieve the desired version from the arguments.
          if [[ ${{ inputs.extra-args }} =~ version=([-+.0-9a-z]+) ]]; then
            VERSION=${BASH_REMATCH[1]}
          else
            VERSION=""
          fi

          # Retrieve the desired number of nodes from the arguments.
          if [[ ${{ inputs.extra-args }} =~ nodes=([0-9+]+) ]]; then
            WORKLOAD_NODES=${BASH_REMATCH[1]}
          else
            WORKLOAD_NODES=100
          fi

          ETCD_NODES=3
          SCRAPE_INTERVAL=60s
          if [[ $WORKLOAD_NODES -ge 2500 ]]; then
            ETCD_NODES=5
            SCRAPE_INTERVAL=120s
          fi

          # Adding k8s.local to the end makes kops happy
          # has stricter DNS naming requirements.
          CLUSTER_NAME="${{ env.test_name }}-${{ env.cluster_name }}.k8s.local"

          cat<<'EOF' > values-export-aggregation.yaml
          extraConfig:
            export-aggregation: connection
            export-aggregation-ignore-source-port: "true"
            export-aggregation-state-filter: new closed established error
            export-flow-allowlist: |-
              {"verdict":["DROPPED", "ERROR"]}
              {"event_type":[{"type":5}]}
              {"destination_identity":[2]}
            export-flow-denylist: |-
              {"reply":[true], "event_type":[{"type":4}]}
              {"source_label":["reserved:health"]}
              {"destination_label":["reserved:health"]}
              {"dns_query":[".*\\.local\\.$", ".*\\.internal\\.$"]}
              {"verdict":["DROPPED"],"event_type":[{"type":1,"match_sub_type":true,"sub_type":139}]}
              {"destination_ip":["10.0.0.0/8"]}
              {"source_label":["k8s:app.kubernetes.io/name=cloudprober"]}
              {"source_label":["reserved:host"]}
              {"source_label":["k8s:app.kubernetes.io/name=network-monitor"]}
              {"source_label":["k8s:app=victoriametrics"]}
          EOF

          cat<<'EOF' > values-hubble-metrics.yaml
          hubble:
            metrics:
              enabled:
              - policy:labelsContext=source_namespace,source_workload,source_app,destination_namespace,destination_workload,destination_app,traffic_direction;sourceContext=dns|reserved-identity;destinationContext=dns|reserved-identity
              - drop:labelsContext=source_namespace,source_workload,source_app,destination_namespace,destination_workload,destination_app,traffic_direction;sourceContext=dns|reserved-identity;destinationContext=dns|reserved-identity
              - httpV2:exemplars=true;labelsContext=source_namespace,source_workload,source_app,destination_namespace,destination_workload,destination_app,traffic_direction;sourceContext=dns|reserved-identity;destinationContext=dns|reserved-identity
          EOF

          CILIUM_INSTALL_DEFAULTS=" \
            --set=pprof.enabled=true \
            --set=prometheus.enabled=true \
            --set=operator.prometheus.enabled=true \
            --set=envoy.prometheus.enabled=true \
            --set=cluster.name=${{ env.cluster_name }} \
            --set=k8sServiceHost=api.internal.${CLUSTER_NAME} \
            --set=k8sServicePort=443 \
            --set=kubeProxyReplacement=true \
            --set=healthChecking=false \
            --set=monitor.enabled=false \
            --set=routingMode=tunnel \
            --set=operator.replicas=1 \
            --set=envoyConfig.enabled=true \
            --set=envoy.enabled=true \
            --set=ipam.mode=\"cluster-pool\" \
            --set=ipam.operator.clusterPoolIPv4PodCIDRList[0]=\"10.0.0.0/9\" \
            --set=envoy.updateStrategy.rollingUpdate.maxUnavailable=10% \
            --set-string=extraConfig.external-dns-proxy=true \
            --set-string=extraConfig.monitor-aggregation-interval=10m \
            --set-string=extraConfig.use-full-tls-context=false \
            --set=localRedirectPolicy=true \
            --set=dnsProxy.proxyResponseMaxDelay=250ms \
            --set=bpf.policyMapMax=65536 \
            --set=bpf.masquerade=true \
            --set=bpf.hostLegacyRouting=false \
            --set=dnsProxy.minTtl=300 \
            --set=hubble.enabled=true \
            --set=hubble.eventBufferCapacity=65535 \
            --set=enterprise.featureGate.approved={LocalRedirectPolicy} \
            --values=values-export-aggregation.yaml \
            --values=values-hubble-metrics.yaml \
            --wait=false"

          # To be applied by Panda values:
          CILIUM_INSTALL_DEFAULTS+=" --set=updateStrategy.rollingUpdate.maxUnavailable=5% \
                        --set-string=extraConfig.kvstore-pod-network-support=false"
          # Additionally, qps for operator below

          if [[ -z "$VERSION" ]]; then
            CILIUM_INSTALL_DEFAULTS+=" --set=image.repository=quay.io/${{ env.QUAY_ORGANIZATION_DEV }}/cilium-ci \
            --set=image.useDigest=false \
            --set=image.tag=${SHA} \
            --set=operator.image.repository=quay.io/${{ env.QUAY_ORGANIZATION_DEV }}/operator \
            --set=operator.image.suffix=-ci \
            --set=operator.image.tag=${SHA} \
            --set=operator.image.useDigest=false \
            --set=clustermesh.apiserver.image.repository=quay.io/${{ env.QUAY_ORGANIZATION_DEV }}/clustermesh-apiserver-ci \
            --set=clustermesh.apiserver.image.tag=${SHA} \
            --set=clustermesh.apiserver.image.useDigest=false \
            --set=hubble.relay.image.repository=quay.io/${{ env.QUAY_ORGANIZATION_DEV }}/hubble-relay-ci \
            --set=hubble.relay.image.tag=${SHA} \
            --set=hubble.relay.image.useDigest=false"
          fi

          echo SHA=${SHA} >> $GITHUB_OUTPUT
          echo cilium_install_defaults=${CILIUM_INSTALL_DEFAULTS} >> $GITHUB_OUTPUT
          echo CLUSTER_NAME=${CLUSTER_NAME} >> $GITHUB_OUTPUT

          echo WORKLOAD_NODES=${WORKLOAD_NODES} >> $GITHUB_OUTPUT
          echo ETCD_NODES=${ETCD_NODES} >> $GITHUB_OUTPUT
          echo SCRAPE_INTERVAL=${SCRAPE_INTERVAL} >> $GITHUB_OUTPUT
          echo INSTANCES_PER_GROUP=$(( WORKLOAD_NODES / 5 )) >> $GITHUB_OUTPUT
          echo VERSION=${VERSION} >> $GITHUB_OUTPUT

      - name: Checkout pull request branch (NOT TRUSTED)
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          ref: ${{ steps.vars.outputs.SHA }}
          persist-credentials: false
          path: untrusted
          sparse-checkout: |
            VERSION
            install/kubernetes/cilium
            enterprise/fqdn-proxy/installation

      - name: Wait for images
        if: ${{ steps.vars.outputs.version == '' }}
        uses: ./.github/actions/wait-for-images
        with:
          SHA: ${{ steps.vars.outputs.SHA }}
          images: cilium-ci operator-generic-ci hubble-relay-ci cilium-dnsproxy-ci

      - name: Install Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version: ${{ env.go_version }}

      - name: Install Kops
        uses: cilium/scale-tests-action/install-kops@87a9ed3bcb8f6fb2c046a7a6bf5f409628d33a67 # main

      - name: Setup gcloud credentials
        uses: google-github-actions/auth@b7593ed2efd1c1617e1b0254da33b86225adb2a5 # v2.1.12
        with:
          workload_identity_provider: ${{ secrets.GCP_PERF_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_PERF_SA }}
          create_credentials_file: true
          export_environment_variables: true

      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@cb1e50a9932213ecece00a606661ae9ca44f3397 # v2.2.0
        with:
          project_id: ${{ secrets.GCP_PERF_PROJECT_ID }}
          version: ${{ env.gcloud_version }}

      - name: Clone ClusterLoader2
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          repository: kubernetes/perf-tests
          # Avoid using renovate to update this dependency because: (1)
          # perf-tests does not tag or release, so renovate will pull
          # all updates to the default branch and (2) continually
          # updating CL2 may impact the stability of the scale test
          # results.
          ref: ce821d6232cee6719dd86e7e68eee361e337e92a
          persist-credentials: false
          sparse-checkout: clusterloader2
          path: perf-tests

      - name: Setup CL2
        run: |
          # CL2 needs ssh access to control plane nodes
          gcloud compute config-ssh

          # Copy the custom configs to the folder where CL2 expects them.
          cp -r .github/actions/cl2-modules ./perf-tests/clusterloader2/testing/custom

          cd ./perf-tests/clusterloader2

          go build ./cmd/clusterloader.go

      - name: Install Cilium CLI
        uses: cilium/cilium-cli@746083db48591ffbebd37743873a91a13a6b04b8 # v0.18.6
        with:
          repository: ${{ env.CILIUM_CLI_RELEASE_REPO }}
          release-version: ${{ env.CILIUM_CLI_VERSION }}
          ci-version: ${{ env.cilium_cli_ci_version }}

      - name: Display version info of installed tools
        run: |
          echo "--- go ---"
          go version
          echo "--- cilium-cli ---"
          cilium version --client
          echo "--- kops ---"
          ./kops version
          echo "--- gcloud ---"
          gcloud version

      - name: Deploy cluster
        id: deploy-cluster
        uses: cilium/scale-tests-action/create-cluster@87a9ed3bcb8f6fb2c046a7a6bf5f409628d33a67 # main
        timeout-minutes: 10
        with:
          cluster_name: ${{ steps.vars.outputs.cluster_name }}
          control_plane_size: ${{ steps.vars.outputs.WORKLOAD_NODES <= 1000 && 'n2-standard-16' || 'n2-standard-32' }}
          control_plane_count: 3
          node_size: ${{ steps.vars.outputs.WORKLOAD_NODES <= 1000 && 'n2-standard-16' || 'n2-standard-32' }}
          node_count: 1
          kops_state: ${{ secrets.GCP_PERF_KOPS_STATE_STORE }}
          project_id: ${{ secrets.GCP_PERF_PROJECT_ID }}
          node_cidr: 10.255.0.0/16
          kube_proxy_enabled: false
          sync_cloud_routes: false
          etcd_volume_size: ${{ steps.vars.outputs.WORKLOAD_NODES <= 1000 && 250 || 500 }}
          max_in_flight: 200

      - name: Create instance group for etcd
        uses: cilium/scale-tests-action/create-instance-group@87a9ed3bcb8f6fb2c046a7a6bf5f409628d33a67 # main
        timeout-minutes: 5
        with:
          cluster_name: ${{ steps.vars.outputs.cluster_name }}
          kops_state: ${{ secrets.GCP_PERF_KOPS_STATE_STORE }}
          node_size: ${{ steps.vars.outputs.WORKLOAD_NODES <= 1000 && 'n2-standard-16' || 'n2-standard-32' }}
          node_count: ${{ steps.vars.outputs.ETCD_NODES }}
          ig_name: etcd
          node_volume_type: pd-ssd
          node_volume_size: ${{ steps.vars.outputs.WORKLOAD_NODES <= 1000 && 250 || 500 }}

      - name: Setup firewall rules
        uses: cilium/scale-tests-action/setup-firewall@87a9ed3bcb8f6fb2c046a7a6bf5f409628d33a67 # main
        with:
          cluster_name: ${{ steps.vars.outputs.cluster_name }}
          create_native_routing_firewall: 'false'

      - name: Wait for etcd nodes to join the cluster
        timeout-minutes: 5
        shell: bash
        run: |
          cnt=0
          while [[ "$cnt" != ${{ steps.vars.outputs.ETCD_NODES }} ]]; do
            cnt=$(kubectl get nodes -l kops.k8s.io/instancegroup=etcd --no-headers --ignore-not-found | wc -l)
            echo "etcd nodes count: $cnt"
            sleep 10
          done

      # This step is based off of .github/actions/kvstore/action.yaml but with
      # some changes, since we're not deploying to kind and we're not using clustermesh.
      - name: Create etcd Certificates
        shell: bash
        run: |
          set -x
          DIR=$(mktemp -d)

          # Generate the TLS certificates
          openssl genrsa 4096 >$DIR/kvstore-ca-key.pem
          openssl genrsa 4096 >$DIR/kvstore-server-key.pem
          openssl genrsa 4096 >$DIR/kvstore-client-key.pem

          openssl req -new -x509 -nodes -days 1 -subj "/CN=KVStore CA/" \
            -key $DIR/kvstore-ca-key.pem -out $DIR/kvstore-ca-crt.pem

          # The SAN used here is based off of the DNS names assigned to
          # the internal IPs of the GCP nodes which will run etcd.
          # Since we're running on the host network, these names can be
          # reused here.
          openssl req -new -x509 -nodes -days 1 -subj "/CN=etcd/" \
            -addext "subjectAltName=DNS:*.${{ env.domain }}" \
            -key $DIR/kvstore-server-key.pem -out $DIR/kvstore-server-crt.pem \
            -CA $DIR/kvstore-ca-crt.pem -CAkey $DIR/kvstore-ca-key.pem

          # For the client cert, set the CN to "root" to enable easy RBAC.
          # See https://etcd.io/docs/v3.5/op-guide/authentication/rbac/.
          openssl req -new -x509 -nodes -days 1 -subj "/CN=root/" \
            -key $DIR/kvstore-client-key.pem -out $DIR/kvstore-client-crt.pem \
            -CA $DIR/kvstore-ca-crt.pem -CAkey $DIR/kvstore-ca-key.pem

          # The client files are named based off of what cilium expects.
          kubectl create secret generic -n kube-system cilium-etcd-secrets \
            --from-file etcd-client-ca.crt=$DIR/kvstore-ca-crt.pem \
            --from-file etcd-client.crt=$DIR/kvstore-client-crt.pem \
            --from-file etcd-client.key=$DIR/kvstore-client-key.pem
          # This is just for etcd, but follows the same naming pattern.
          kubectl create secret generic -n kube-system etcd-server-secrets \
            --from-file etcd-server-ca.crt=$DIR/kvstore-ca-crt.pem \
            --from-file etcd-server.crt=$DIR/kvstore-server-crt.pem \
            --from-file etcd-server.key=$DIR/kvstore-server-key.pem

      - name: Deploy etcd
        id: etcd
        shell: bash
        run: |
          set -x

          # This is for brevity in the blocks below.
          domain="${{ env.domain }}"

          # Passed to etcd's --initial-cluster argument.
          etcd_initial_cluster=""
          # Extra arguments to pass to the cilium install command.
          helm_args=""

          i=0
          for name in $(kubectl get nodes -o custom-columns=NAME:.metadata.name --no-headers -l kops.k8s.io/instancegroup=etcd); do

            # Build the cluster list for the advertise urls.
            if [ -n "$etcd_initial_cluster" ]; then
              etcd_initial_cluster+=","
            fi
            etcd_initial_cluster+="${name}=https://${name}.${domain}:2380"

            # Build the helm arguments for cilium.
            helm_args+="--set=etcd.endpoints[${i}]=https://${name}.${domain}:2379 "

            # Label and taint the node to reserve it for etcd.
            kubectl label node $name app=etcd
            kubectl taint node $name etcd-ig:NoSchedule

            i=$((i+1))
          done

          echo "helm_args=${helm_args}" >> $GITHUB_OUTPUT

          # Deploy etcd.
          cat ./.github/actions/cl2-modules/enterprise/panda/kvstore/etcd-pod.yaml | \
            sed "s|#REPLACE_ME_REPLICAS|${{ steps.vars.outputs.ETCD_NODES }}|g" | \
            sed "s|#REPLACE_ME_INITIAL_CLUSTER|${etcd_initial_cluster}|g" | \
            sed "s/#REPLACE_ME_DOMAIN/${domain}/g" | \
            kubectl apply -f -

      - name: Wait for the etcd cluster to be ready
        shell: bash
        run: |
          set -x
          if ! kubectl rollout status --timeout=5m -n kube-system statefulset/etcd; then
            kubectl get pods -A -o yaml
            kubectl describe -n kube-system statefulset/etcd
            kubectl logs -n kube-system statefulset/etcd
            exit 1
          fi

      - name: Install Cilium
        id: install-cilium
        run: |
          VERSION_SPECIFIC_OPTIONS=""
          # If version not specified, check git VERSION
          if [[ -z "${{ steps.vars.outputs.version }}" ]]; then
            GIT_VERSION=$(cat ./untrusted/VERSION)
            minor_version=$(echo "$GIT_VERSION" | cut -d'.' -f2)
          else
            minor_version=$(echo "${{ steps.vars.outputs.version }}" | cut -d'.' -f2)
          fi
          if (( minor_version < 17 )); then
            VERSION_SPECIFIC_OPTIONS+=" --set=operator.extraArgs[0]=\"--k8s-client-qps=100\" \
                              --set=operator.extraArgs[1]=\"--k8s-client-burst=100\""
          fi

          cilium_install_args="${{ steps.vars.outputs.cilium_install_defaults }} \
            --set=identityAllocationMode=kvstore \
            --set=etcd.enabled=true \
            --set=etcd.ssl=true \
            $VERSION_SPECIFIC_OPTIONS \
            ${{ steps.etcd.outputs.helm_args }}"

          if [[ -z "${{ steps.vars.outputs.version }}" ]]; then
            helm install -n kube-system cilium ./untrusted/install/kubernetes/cilium \
            $cilium_install_args
          else
            helm repo add isovalent https://helm.isovalent.com
            helm install -n kube-system cilium isovalent/cilium \
            --version ${{ steps.vars.outputs.version }} \
            $cilium_install_args
          fi

      - name: Install Cilium DNS proxy
        run: |
          if [[ -z "${{ steps.vars.outputs.version }}" ]]; then
            helm install -n kube-system cilium-dnsproxy ./untrusted/enterprise/fqdn-proxy/installation \
            --set metrics.enabled=true \
            --set image.repository=quay.io/${{ env.QUAY_ORGANIZATION_DEV }}/cilium-dnsproxy-ci \
            --set image.tag=${{ steps.vars.outputs.sha }}
          else
            helm install -n kube-system cilium-dnsproxy isovalent/cilium-dnsproxy \
            --version ${{ steps.vars.outputs.version }} \
            --set metrics.enabled=true
          fi

          kubectl rollout status -n kube-system ds/cilium-dnsproxy --watch

      - name: Wait for cluster to be ready
        uses: cilium/scale-tests-action/validate-cluster@87a9ed3bcb8f6fb2c046a7a6bf5f409628d33a67 # main
        timeout-minutes: 10
        with:
          cluster_name: ${{ steps.vars.outputs.cluster_name }}
          kops_state: ${{ secrets.GCP_PERF_KOPS_STATE_STORE }}
          interval: 10s

      - name: Wait for Cilium status to be ready
        run: |
          cilium status --wait

      - name: Install cert-manager and trust-manager
        run: |
          helm repo add jetstack https://charts.jetstack.io

          helm install cert-manager \
            jetstack/cert-manager \
            --namespace cert-manager \
            --create-namespace \
            --version ${{ env.cert_manager_version }} \
            --set crds.enabled=true \
            --wait

          helm install trust-manager \
            jetstack/trust-manager \
            --namespace cert-manager \
            --version ${{ env.trust_manager_version }} \
            --set secretTargets.enabled=true \
            --set secretTargets.authorizedSecrets\[0]=tls-origination \
            --wait

      - name: Run CL2 to setup prometheus
        shell: bash
        working-directory: ./perf-tests/clusterloader2
        env:
          CL2_PROMETHEUS_PVC_ENABLED: "true"
          PROMETHEUS_PVC_STORAGE_CLASS: "ssd"
          CL2_PROMETHEUS_SCRAPE_CILIUM_OPERATOR: "true"
          CL2_PROMETHEUS_SCRAPE_CILIUM_AGENT: "true"
          CL2_PROMETHEUS_MEMORY_SCALE_FACTOR: 20.0
          CL2_PROMETHEUS_SCRAPE_CILIUM_AGENT_INTERVAL: "${{ steps.vars.outputs.SCRAPE_INTERVAL }}"
        timeout-minutes: 10
        run: |
          # Don't run any tasks at this point, just setup the monitoring stack
          ./clusterloader \
            -v=2 \
            --prometheus-additional-monitors-path=./testing/custom/enterprise/panda/monitors/ \
            --testconfig=./testing/custom/common/setup.yaml \
            --testoverrides=./testing/prometheus/not-scrape-kube-proxy.yaml \
            --provider=gce \
            --enable-exec-service=false \
            --enable-prometheus-server \
            --tear-down-prometheus-server=false \
            --nodes=${{ steps.vars.outputs.WORKLOAD_NODES }} \
            --kubeconfig=$HOME/.kube/config \
            2>&1 | tee cl2-setup.txt

          # Let the prometheus-operator create the kubelet service, which is only
          # enabled by CL2 only if --prometheus-scrape-kubelets is set.
          kubectl patch deployment prometheus-operator -n monitoring --type=json \
            -p='[{"op": "add", "path": "/spec/template/spec/containers/0/args/-", "value": "--kubelet-service=kube-system/kubelet"}]'
          kubectl rollout status deployment prometheus-operator -n monitoring

      - name: Setup LRP
        run: |
          kubedns=$(kubectl get svc kube-dns -n kube-system -o jsonpath='{.spec.clusterIP}') && sed -i "s/__PILLAR__DNS__SERVER__/$kubedns/g;" ./examples/kubernetes-local-redirect/node-local-dns.yaml
          kubectl apply -f ./examples/kubernetes-local-redirect/node-local-dns.yaml
          kubectl rollout status daemonset node-local-dns -n kube-system
          kubectl apply -f ./examples/kubernetes-local-redirect/node-local-dns-lrp.yaml

      - name: Setup Certificates and Cloudprober
        run: |
          kubectl apply -f ./perf-tests/clusterloader2/testing/custom/enterprise/panda/manifests/certificates.yaml
          kubectl wait --for=condition=Ready -n cilium-secrets certificate/tls-termination
          kubectl wait --for=condition=Synced bundle/tls-origination
          kubectl wait --for=condition=Synced bundle/tls-interception

          kubectl apply -f ./perf-tests/clusterloader2/testing/custom/enterprise/panda/manifests/policy.yaml
          kubectl create configmap cloudprober-config --from-file=cloudprober.cfg=./perf-tests/clusterloader2/testing/custom/enterprise/panda/manifests/cloudprober.cfg
          kubectl create configmap cloudprober-oneoff-config --from-file=cloudprober.cfg=./perf-tests/clusterloader2/testing/custom/enterprise/panda/manifests/cloudprober-oneoff.cfg
          kubectl apply -f ./perf-tests/clusterloader2/testing/custom/enterprise/panda/manifests/cloudprober.yaml
          kubectl rollout status daemonset cloudprober
          kubectl apply -f ./perf-tests/clusterloader2/testing/custom/enterprise/panda/manifests/cloudprober-host.yaml
          kubectl rollout status daemonset cloudprober-host

      - name: Label and taint the monitoring node
        run: |
          # This node is used to host the different utilities, and most notably
          # prometheus. Let's taint it so that it doesn't become a target to
          # schedule test pods, considering that it attracts an unfair number of
          # them (compatibly with max pods per node) due to its size.
          # shellcheck disable=SC2196,SC2267
          kubectl get nodes -o name | egrep '^node/nodes-' | xargs -i kubectl label '{}' app=monitoring
          kubectl taint node -l app=monitoring monitoring:NoSchedule

      - name: Create Instance Group for workload deployments (1)
        uses: cilium/scale-tests-action/create-instance-group@87a9ed3bcb8f6fb2c046a7a6bf5f409628d33a67 # main
        timeout-minutes: 5
        with:
          cluster_name: ${{ steps.vars.outputs.cluster_name }}
          node_size: e2-medium
          node_count: ${{ steps.vars.outputs.INSTANCES_PER_GROUP }}
          ig_name: workloads-1
          kops_state: ${{ secrets.GCP_PERF_KOPS_STATE_STORE }}

      - name: Create Instance Group for workload deployments (2)
        uses: cilium/scale-tests-action/create-instance-group@87a9ed3bcb8f6fb2c046a7a6bf5f409628d33a67 # main
        timeout-minutes: 5
        with:
          cluster_name: ${{ steps.vars.outputs.cluster_name }}
          node_size: e2-medium
          node_count: ${{ steps.vars.outputs.INSTANCES_PER_GROUP }}
          ig_name: workloads-2
          kops_state: ${{ secrets.GCP_PERF_KOPS_STATE_STORE }}

      - name: Create Instance Group for workload deployments (3)
        uses: cilium/scale-tests-action/create-instance-group@87a9ed3bcb8f6fb2c046a7a6bf5f409628d33a67 # main
        timeout-minutes: 5
        with:
          cluster_name: ${{ steps.vars.outputs.cluster_name }}
          node_size: e2-medium
          node_count: ${{ steps.vars.outputs.INSTANCES_PER_GROUP }}
          ig_name: workloads-3
          kops_state: ${{ secrets.GCP_PERF_KOPS_STATE_STORE }}

      - name: Create Instance Group for workload deployments (4)
        uses: cilium/scale-tests-action/create-instance-group@87a9ed3bcb8f6fb2c046a7a6bf5f409628d33a67 # main
        timeout-minutes: 5
        with:
          cluster_name: ${{ steps.vars.outputs.cluster_name }}
          node_size: e2-medium
          node_count: ${{ steps.vars.outputs.INSTANCES_PER_GROUP }}
          ig_name: workloads-4
          kops_state: ${{ secrets.GCP_PERF_KOPS_STATE_STORE }}

      - name: Create Instance Group for workload deployments (5)
        uses: cilium/scale-tests-action/create-instance-group@87a9ed3bcb8f6fb2c046a7a6bf5f409628d33a67 # main
        timeout-minutes: 5
        with:
          cluster_name: ${{ steps.vars.outputs.cluster_name }}
          node_size: e2-medium
          node_count: ${{ steps.vars.outputs.INSTANCES_PER_GROUP }}
          ig_name: workloads-5
          kops_state: ${{ secrets.GCP_PERF_KOPS_STATE_STORE }}

      - name: Wait for workloads nodes to be ready
        timeout-minutes: 20
        run: |
          cnt=0

          # Allow for a 2 per thousand toleration in the expected nodes count, to
          # continue with the test even if a tiny fraction of the workers failed
          # bootstrapping and joining the cluster.
          desired=$(( ${{ steps.vars.outputs.WORKLOAD_NODES}} - ${{ steps.vars.outputs.WORKLOAD_NODES}} * 2 / 1000 ))

          # A more idiomatic way would be using the kops.k8s.io/instancegroup=workloads
          # label selector, but kops appears to be significantly slow at reconciling
          # the labels to the node objects. Hence, let's just grep for the node names.
          while [[ "$cnt" -lt "$desired" ]]; do
            # shellcheck disable=SC2196
            cnt=$(kubectl get nodes --no-headers | egrep -c 'workloads-[-a-z0-9]+\s+Ready\s' || true)
            echo "workloads nodes count: $cnt"
            sleep 10
          done

      # Need to rerun this action, as the firewall rule is reset after
      # an instance group is created.
      - name: Setup firewall rules
        uses: cilium/scale-tests-action/setup-firewall@87a9ed3bcb8f6fb2c046a7a6bf5f409628d33a67 # main
        with:
          cluster_name: ${{ steps.vars.outputs.cluster_name }}
          create_native_routing_firewall: 'false'

      - name: Wait for Cilium status to be ready
        run: |
          kubectl rollout status -n kube-system ds/cilium
          kubectl rollout status -n kube-system ds/cilium-dnsproxy
          kubectl rollout status daemonset cloudprober-host
          kubectl rollout status daemonset cloudprober
          kubectl rollout status daemonset node-local-dns -n kube-system

      - name: Run CL2
        id: run-cl2
        working-directory: ./perf-tests/clusterloader2
        shell: bash
        timeout-minutes: 90
        env:
          CL2_PROMETHEUS_PVC_ENABLED: "true"
          PROMETHEUS_PVC_STORAGE_CLASS: "ssd"
          CL2_PROMETHEUS_SCRAPE_CILIUM_OPERATOR: "true"
          CL2_PROMETHEUS_SCRAPE_CILIUM_AGENT: "true"
          CL2_PROMETHEUS_MEMORY_SCALE_FACTOR: 20.0
          CL2_PROMETHEUS_SCRAPE_CILIUM_AGENT_INTERVAL: "${{ steps.vars.outputs.SCRAPE_INTERVAL }}"
          CL2_DELETE_AUTOMANAGED_NAMESPACES: "false"
        run: |
          # Include in the sysdump (a) all control-plane nodes and (b) 10 workload nodes.
          # We don't use the kops.k8s.io/instancegroup=workloads label because it is not guaranteed to have already been applied.
          NODES_LIST_CP=$(kubectl get nodes -l node-role.kubernetes.io/control-plane -o jsonpath="{.items[*].metadata.name}")
          NODES_LIST_ET=$(kubectl get nodes -l kops.k8s.io/instancegroup=etcd -o jsonpath="{.items[*].metadata.name}")
          NODES_LIST_WO=$(kubectl get nodes -l '!node-role.kubernetes.io/control-plane,kops.k8s.io/instancegroup!=etcd' -o jsonpath="{.items[:10].metadata.name}")
          CL2_SYSDUMP_NODES_LIST=$(echo "${NODES_LIST_CP} ${NODES_LIST_ET} ${NODES_LIST_WO}" | xargs | tr -s ' ' ',')
          echo "Capturing intermediate sysdump with nodes '${CL2_SYSDUMP_NODES_LIST}'"

          export CL2_SYSDUMP_NODES_LIST
          ./clusterloader \
            -v=2 \
            --prometheus-additional-monitors-path=./testing/custom/enterprise/panda/monitors/ \
            --testconfig=./testing/custom/enterprise/panda/config.yaml \
            --testoverrides=./testing/prometheus/not-scrape-kube-proxy.yaml \
            --provider=gce \
            --enable-prometheus-server \
            --tear-down-prometheus-server=false \
            --nodes=${{ steps.vars.outputs.WORKLOAD_NODES }} \
            --report-dir=./report \
            --experimental-prometheus-snapshot-to-report-dir=true \
            --kubeconfig=$HOME/.kube/config \
            2>&1 | tee cl2-output.txt

      - name: Get sysdump
        if: ${{ always() && steps.install-cilium.outcome != 'skipped' && steps.install-cilium.outcome != 'cancelled' }}
        run: |
          # Include in the sysdump (a) all control-plane nodes, (b) 10 workload nodes and (c) up to 10 nodes hosting an agent which crashed.
          # We don't use the jsonpath slice operator here as would trigger an error with less than 10 nodes (e.g., in case of early failures).
          # We don't use the kops.k8s.io/instancegroup=workloads label because it is not guaranteed to have already been applied.
          read -ra NODES_LIST_CP <<< "$(kubectl get nodes -l node-role.kubernetes.io/control-plane -o jsonpath='{.items[*].metadata.name}')"
          read -ra NODES_LIST_ET <<< "$(kubectl get nodes -l kops.k8s.io/instancegroup=etcd -o jsonpath='{.items[*].metadata.name}')"
          read -ra NODES_LIST_WO <<< "$(kubectl get nodes -l '!node-role.kubernetes.io/control-plane,kops.k8s.io/instancegroup!=etcd' -o jsonpath='{.items[*].metadata.name}')"
          read -ra NODES_LIST_CR <<< "$(kubectl get pods -n kube-system -l app.kubernetes.io/name=cilium-agent \
            -o jsonpath='{.items[?(.status.containerStatuses[0].restartCount!=0)].spec.nodeName}')"

          # Leverage xargs to trim duplicated spaces
          NODES_LIST=$(echo "${NODES_LIST_CP[*]} ${NODES_LIST_ET[*]} ${NODES_LIST_WO[*]::10} ${NODES_LIST_CR[*]::10}" | xargs | tr -s ' ' ',')
          echo "Capturing final sysdump with nodes '${NODES_LIST}'"

          cilium sysdump --output-filename cilium-sysdump-final --node-list ${NODES_LIST} \
            --extra-label-selectors=app=etcd
          sudo chmod +r cilium-sysdump-final.zip

      - name: Upload sysdump
        if: ${{ !success() && steps.install-cilium.outcome != 'skipped' && steps.install-cilium.outcome != 'cancelled' }}
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: cilium-sysdump
          path: cilium-sysdump-final.zip
          retention-days: 5

      - name: Cleanup cluster
        if: ${{ always() && steps.deploy-cluster.outcome != 'skipped' }}
        uses: cilium/scale-tests-action/cleanup-cluster@87a9ed3bcb8f6fb2c046a7a6bf5f409628d33a67 # main
        with:
          cluster_name: ${{ steps.vars.outputs.cluster_name }}
          kops_state: ${{ secrets.GCP_PERF_KOPS_STATE_STORE }}

      - name: Export results and sysdump to GS bucket
        if: ${{ always() && steps.run-cl2.outcome != 'skipped' && steps.run-cl2.outcome != 'cancelled' }}
        uses: cilium/scale-tests-action/export-results@87a9ed3bcb8f6fb2c046a7a6bf5f409628d33a67 # main
        with:
          test_name: ${{ env.test_name }}
          tested_version: ${{ steps.vars.outputs.version }}
          tested_sha: ${{ steps.vars.outputs.SHA }}
          results_bucket: ${{ env.GCP_PERF_RESULTS_BUCKET }}
          artifacts: ./perf-tests/clusterloader2/report/
          other_files: cilium-sysdump-final.zip ./perf-tests/clusterloader2/cl2-output.txt ./perf-tests/clusterloader2/cilium-sysdump-middle.zip

  commit-status-final:
    if: ${{ always() }}
    name: Commit Status Final
    needs: install-and-scaletest
    runs-on: ubuntu-24.04
    steps:
      - name: Set final commit status
        uses: myrotvorets/set-commit-status-action@3730c0a348a2ace3c110851bed53331bc6406e9f # v2.0.1
        with:
          sha: ${{ inputs.SHA || github.sha }}
          status: ${{ needs.install-and-scaletest.result }}
