name: Trigger build images external to isovalent/cilium

# Any change in triggers needs to be reflected in the concurrency group.
on:
  schedule:
    # Every day at 00:00
    - cron: "0 0 * * *"
  merge_group:
  push:
    branches:
      - main-ce
      - v1.[0-9]+-ce
    paths:
      - install/kubernetes/Makefile.values
  # Allow to run manually
  workflow_dispatch: {}

permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.event.after || github.event.merge_group && github.run_id }}

jobs:
  check-and-build:
    name: Trigger build images external workflow
    strategy:
      fail-fast: false
      matrix:
        include:
          - component: CERTGEN
            image-name: certgen-ubi
            docker-context: enterprise/images/certgen
            dockerfile: enterprise/images/certgen/Dockerfile
            # renovate: datasource=docker
            base-image: registry.redhat.io/ubi9/ubi-micro:9.5-1742939100@sha256:414cfa255ea10eaef4528a26d5618eb67cf487b635ee20f8f14b9317bfd6a4be
            build-from-source: false

          - component: CILIUM_NODEINIT
            image-name: startup-script-ubi
            docker-context: enterprise/images/startup-script
            dockerfile: enterprise/images/startup-script/Dockerfile
            # renovate: datasource=docker
            base-image: registry.redhat.io/ubi9/ubi-minimal:9.5-1742914212@sha256:ac61c96b93894b9169221e87718733354dd3765dd4a62b275893c7ff0d876869
            build-from-source: false

          - component: CILIUM_ENVOY
            image-name: cilium-envoy-ubi
            docker-context: enterprise/images/cilium-envoy
            dockerfile: enterprise/images/cilium-envoy/Dockerfile
            # renovate: datasource=docker
            base-image: registry.redhat.io/ubi9/ubi-minimal:9.5-1742914212@sha256:ac61c96b93894b9169221e87718733354dd3765dd4a62b275893c7ff0d876869
            build-from-source: false

          - component: HUBBLE_UI_BACKEND
            image-name: hubble-ui-backend-ubi
            docker-context: hubble-ui-backend/backend
            dockerfile: hubble-ui-backend/backend/Dockerfile
            # renovate: datasource=docker
            base-image: registry.redhat.io/ubi9/ubi-micro:9.5-1742939100@sha256:414cfa255ea10eaef4528a26d5618eb67cf487b635ee20f8f14b9317bfd6a4be
            build-from-source: true
            source-repo: isovalent/hubble-ui-enterprise
            source-path: hubble-ui-backend

          - component: HUBBLE_UI_FRONTEND
            image-name: hubble-ui-frontend-ubi
            docker-context: hubble-ui-frontend
            dockerfile: hubble-ui-frontend/Dockerfile
            # renovate: datasource=docker
            base-image: quay.io/isovalent-dev/nginx-unprivileged-ubi:1742895604-0227bb1@sha256:e17eebe7edd734e14bbc20ef60ca13dcc1fa5e4c36d1f2ebb4073b7a4156f319
            build-from-source: true
            source-repo: isovalent/hubble-ui-enterprise
            source-path: hubble-ui-frontend

          - component: CILIUM_ETCD_OPERATOR
            image-name: cilium-etcd-operator-ubi
            docker-context: cilium-etcd-operator
            dockerfile: enterprise/images/cilium-etcd-operator/Dockerfile
            # renovate: datasource=docker
            base-image: registry.redhat.io/ubi9/ubi-micro:9.5-1742939100@sha256:414cfa255ea10eaef4528a26d5618eb67cf487b635ee20f8f14b9317bfd6a4be
            build-from-source: true
            source-repo: cilium/cilium-etcd-operator
            source-path: cilium-etcd-operator

    uses: ./.github/workflows/enterprise-external-images.yaml
    secrets: inherit
    with:
      component: ${{ matrix.component }}
      image-name: ${{ matrix.image-name }}
      docker-context: ${{ matrix.docker-context }}
      dockerfile: ${{ matrix.dockerfile }}
      base-image: ${{ matrix.base-image }}
      build-from-source: ${{ matrix.build-from-source }}
      source-repo: ${{ matrix.source-repo }}
      source-path: ${{ matrix.source-path }}
