name: Build images external to isovalent/cilium

# Any change in triggers needs to be reflected in the concurrency group.
on:
  workflow_call:
    inputs:
      component:
        required: true
        type: string
      image-name:
        required: true
        type: string
      docker-context:
        required: true
        type: string
      dockerfile:
        required: true
        type: string
      base-image:
        required: true
        type: string
      build-from-source:
        required: false
        type: boolean
        default: false
      source-repo:
        required: false
        type: string
      source-path:
        required: false
        type: string

permissions: read-all

jobs:
  check-changes:
    name: Deduce changes
    runs-on: ubuntu-24.04
    outputs:
      rebuild: ${{ steps.check-changes.outputs.rebuild }}
      repo: ${{ steps.check-changes.outputs.repo }}
      version: ${{ steps.check-changes.outputs.version }}
      digest: ${{ steps.check-changes.outputs.digest }}

    steps:
      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          ref: ${{ github.event.after }}
          persist-credentials: false
          fetch-depth: 0

      - name: Check ${{ inputs.component }} code changes
        id: check-changes
        run: |
          echo "repo=$(cat install/kubernetes/Makefile.values| grep ${{ inputs.component }}_REPO | awk -F '=' '{print $2}')" >> $GITHUB_OUTPUT
          version=$(cat install/kubernetes/Makefile.values| grep ${{ inputs.component }}_VERSION | awk -F '=' '{print $2}')
          echo "version=${version}" >> $GITHUB_OUTPUT
          echo "digest=$(cat install/kubernetes/Makefile.values| grep ${{ inputs.component }}_DIGEST | awk -F '=' '{print $2}')" >> $GITHUB_OUTPUT
          # Don't build if the image reference does not exist in Makefile.values
          # This is a workaround as etcd-operator, for instance, should not be part of the matrix in the -trigger workflow for main-ce
          if [[ -z "${version}" ]]; then
             echo "No version available for ${{ inputs.component }} in install/kubernetes/Makefile.values. Build skipped."
             echo "rebuild=false" >> $GITHUB_OUTPUT
          # Don't rebuild if the image already exists
          elif docker manifest inspect quay.io/isovalent-dev/${{ inputs.image-name }}:${version}; then
            echo "Image already exist!"
            echo "rebuild=false" >> $GITHUB_OUTPUT
          else
            echo "rebuild=true" >> $GITHUB_OUTPUT
          fi

  build-push-image:
    needs: [ check-changes ]
    if: ${{ needs.check-changes.outputs.rebuild == 'true' }}
    name: Build and push image
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          ref: ${{ github.event.push.after }}
          persist-credentials: false
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3.12.0

      - name: Login to quay.io
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME_CI }}
          password: ${{ secrets.QUAY_PASSWORD_CI }}

      - name: Login to registry.redhat.io for pulling images
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          registry: registry.redhat.io
          username: ${{ secrets.REDHAT_USERNAME_CI }}
          password: ${{ secrets.REDHAT_PASSWORD_CI }}

      - name: Get GitHub Token [read-only]
        if: ${{ inputs.build-from-source == true }}
        id: gh-ro-token
        uses: getsentry/action-github-app-token@d4b5da6c5e37703f8c3b3e43abb5705b46e159cc # v3.0.0
        with:
          app_id: ${{ secrets.ISOVALENT_READONLY_GH_APP_ID }}
          private_key: ${{ secrets.ISOVALENT_READONLY_GH_APP_PEM }}

      - name: Checkout source repo
        if: ${{ inputs.build-from-source == true }}
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          repository: ${{ inputs.source-repo }}
          token: ${{ steps.gh-ro-token.outputs.token }}
          persist-credentials: false
          path: ${{ inputs.source-path }}
          fetch-tags: true
          fetch-depth: 0

      - name: Checkout source version
        if: ${{ inputs.build-from-source == true }}
        working-directory: ${{ inputs.source-path }}
        run: |
          git checkout ${{ needs.check-changes.outputs.version }}

      - name: Build and push ${{ inputs.component }} image
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        id: docker_build_release
        with:
          context: ${{ inputs.docker-context }}
          file: ${{ inputs.dockerfile }}
          push: true
          platforms: linux/amd64,linux/arm64
          # The purpose of the second tag is to ensure that the image can be pulled by digest
          # even if there is a race condition with another run building and pushing the image with
          # the same primary tag.
          tags: |
            quay.io/isovalent-dev/${{ inputs.image-name }}:${{ needs.check-changes.outputs.version }}
            quay.io/isovalent-dev/${{ inputs.image-name }}:${{ github.run_id }}
          build-args: |
            BASE_IMAGE=${{ inputs.base-image }}
            UPSTREAM_VERSION=${{ needs.check-changes.outputs.version }}
            UPSTREAM_IMAGE=${{ needs.check-changes.outputs.repo }}:${{ needs.check-changes.outputs.version }}@${{ needs.check-changes.outputs.digest }}
            VERSION=${{ needs.check-changes.outputs.version }}

      - name: Image Release Digest Runtime
        shell: bash
        run: |
          mkdir -p image-digest/
          echo "## ${{ inputs.image-name }}" > image-digest/${{ inputs.image-name }}.txt
          echo "" >> image-digest/${{ inputs.image-name }}.txt
          echo "\`quay.io/isovalent-dev/${{ inputs.image-name }}:${{ needs.check-changes.outputs.version }}@${{ needs.check-changes.outputs.digest }}\`" >> image-digest/${{ inputs.image-name }}.txt
          echo "" >> image-digest/${{ inputs.image-name }}.txt

      - name: Upload artifact digests runtime
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: image-digest ${{ inputs.image-name }}
          path: image-digest

  image-digests:
    name: Display Digests
    runs-on: ubuntu-24.04
    needs: build-push-image
    steps:
      - name: Downloading Image Digests
        shell: bash
        run: |
          mkdir -p image-digest/

      - name: Download digests of all images built
        uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
        with:
          path: image-digest/
          pattern: "*image-digest *"

      - name: Image Digests Output
        shell: bash
        run: |
          cd image-digest/
          find -type f | sort | xargs -d '\n' cat