name: OLM Build CI

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - enterprise/olm/**
  push:
    branches:
      - main-ce
      - ft/main-ce/**
    paths:
      - enterprise/olm/**

permissions:
  # To be able to access the repository with `actions/checkout`
  contents: read
  # Required to generate OIDC tokens for `sigstore/cosign-installer` authentication
  id-token: write

jobs:
  build-and-push-prs:
    timeout-minutes: 30
    name: Build and Push Images
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout the repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
          sparse-checkout: |
            .github/actions
            enterprise/olm
            install/kubernetes
            images/scripts

      - name: Set Environment Variables
        uses: ./.github/actions/set-env-variables

      - name: Setup go
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
        with:
          cache: false
          # renovate: datasource=golang-version depName=go
          go-version: 1.25.3

      - name: Login to quay.io
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME_CI }}
          password: ${{ secrets.QUAY_PASSWORD_CI }}

      - name: Login to registry.redhat.io for pulling images
        uses: docker/login-action@28fdb31ff34708d19615a74d67103ddc2ea9725c
        with:
          registry: registry.redhat.io
          username: ${{ secrets.REDHAT_USERNAME_CI }}
          password: ${{ secrets.REDHAT_PASSWORD_CI }}

      - name: Getting image tag
        id: tag
        run: |
          if [ "${{ github.event.pull_request.head.sha }}" != "" ]; then
            tag=${{ github.event.pull_request.head.sha }}
          else
            tag=${{ github.sha }}
          fi
          echo tag=${tag} >> $GITHUB_OUTPUT

      # Need to wait for the images of the components to be built as the digests of the component images
      # are populated into the value.yaml file copied into the CLife image.
      - name: Wait for images to be available
        id: wait_images
        timeout-minutes: 20
        shell: bash
        run: |
          for image in cilium-ubi-ci operator-generic-ubi-ci hubble-relay-ubi-ci clustermesh-apiserver-ubi-ci; do
            until docker manifest inspect quay.io/isovalent-dev/$image:${{ steps.tag.outputs.tag }} &> /dev/null; do sleep 45s; done
          done
          echo "images available"

      - name: Build and Push OLM container image
        env:
          IMG: "quay.io/${{ env.QUAY_ORGANIZATION_DEV }}/clife-ci:${{ steps.tag.outputs.tag }}"
          CL_TAG: "${{ steps.tag.outputs.tag }}"
        working-directory: ./enterprise/olm
        run: |
          make docker-buildx VERSION=${{ steps.tag.outputs.tag }}

      - name: CI Build digest
        id: docker_digest
        shell: bash
        run: |
          digest=$(images/scripts/get-image-digest.sh "quay.io/${{ env.QUAY_ORGANIZATION_DEV }}/clife-ci:${{ steps.tag.outputs.tag }}")
          echo digest=${digest} >> $GITHUB_OUTPUT

      - name: Install Cosign
        uses: sigstore/cosign-installer@faadad0cce49287aee09b3a48701e75088a2c6ad # v4.0.0

      - name: Sign Container Images
        run: |
          cosign sign -y quay.io/${{ env.QUAY_ORGANIZATION_DEV }}/clife-ci@${{ steps.docker_digest.outputs.digest }}

      - name: Generate SBOM
        uses: anchore/sbom-action@8e94d75ddd33f69f691467e42275782e4bfefe84 # v0.20.9
        with:
          artifact-name: sbom_ci_clife_${{ steps.tag.outputs.tag }}.spdx.json
          output-file: ./sbom_ci_clife_${{ steps.tag.outputs.tag }}.spdx.json
          image: ${{ steps.tag.outputs.primary_tag }}

      - name: Attach SBOM attestation to container image
        run: |
          cosign attest -y --predicate sbom_ci_clife_${{ steps.tag.outputs.tag }}.spdx.json --type spdxjson "quay.io/${{ env.QUAY_ORGANIZATION_DEV }}/clife-ci:${{ steps.tag.outputs.tag }}"
