name: Enterprise Lint
on:
  # Check mindfulness on each PR (when applicable per filter below)
  pull_request:
    branches:
      - main-ce
  # Validate mindfulness for each pushed commit
  push:
    branches:
      - main-ce
  # Additionally run once a day at midnight
  schedule:
    - cron:  '0 0 * * *'
  # Allow to run manually via GitHub UI
  workflow_dispatch: {}

permissions: read-all

jobs:
  mindfulness:
    name: Mindfulness
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98
        with:
          persist-credentials: false
          fetch-depth: '0'
      - name: Fetch OSS branch
        id: checkout-oss
        env:
          UPSTREAM: "https://github.com/cilium/cilium"
        run: |
          git remote add upstream "$UPSTREAM"
          git fetch --no-write-fetch-head upstream "refs/heads/main:refs/remotes/upstream/main"
      - name: Create branch based on upstream with backported patches
        if: ${{ always() && steps.checkout.outcome == 'success' && steps.checkout-oss.outcome == 'success' }}
        env:
          BASE_BRANCH: lint-merge-base
        run: |
          git config --global user.email "isovalent-bot@isovalent.com"
          git config --global user.name "isovalent-bot"
          git config set advice.mergeConflict false
          git config set advice.detachedHead false
          contrib/scripts/enterprise-mindful-branch.sh --branch "$BASE_BRANCH" \
            --downstream-branch HEAD --repo cilium/cilium \
            --ignore-failures --debug
          # Ignore failures above as the cherry-picking of upstream commits is best-effort.
      - name: Diff against upstream tree for files that should not diverge from OSS
        if: ${{ always() && steps.checkout.outcome == 'success' && steps.checkout-oss.outcome == 'success' }}
        env:
          BASE_BRANCH: lint-merge-base
        run: |
          contrib/scripts/enterprise-meditation.sh \
            --repo cilium/cilium --debug $BASE_BRANCH || true
          contrib/scripts/enterprise-meditation.sh \
            --repo cilium/cilium --stat --exit-code $BASE_BRANCH
      - name: Compare upstream tree noisily (Never fails, check me for a more unfiltered view of diff)
        if: ${{ always() && steps.checkout.outcome == 'success' && steps.checkout-oss.outcome == 'success' }}
        env:
          BASE_BRANCH: lint-merge-base
        run: |
          # Note: This does not fail when encountering a diff!
          contrib/scripts/enterprise-meditation.sh \
            --repo cilium/cilium --debug \
            --noisy $BASE_BRANCH
          contrib/scripts/enterprise-meditation.sh \
            --repo cilium/cilium --stat \
            --noisy $BASE_BRANCH

  codeowners:
    name: CODEOWNERS
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false

      - name: Check TESTOWNERS.enterprise is up to date
        run: |
          ./contrib/scripts/enterprise-testowners.sh
          if ! git diff --exit-code; then
            echo "Run './contrib/scripts/enterprise-testowners.sh' and submit your changes"
            exit 1
          fi
      - name: Check that all enterprise files are covered in CODEOWNERS
        run: |
          ./contrib/scripts/enterprise-codeowners.sh

  generate-enterprise-api:
    runs-on: ubuntu-24.04
    name: Generate Enterprise API
    steps:
      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false

      - name: Check api generated files
        run: |
          contrib/scripts/enterprise-check-api-code-gen.sh

  gomod-override:
    runs-on: ubuntu-24.04
    name: go.mod
    steps:
      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false

      - name: Set up Go
        uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
        with:
          go-version-file: 'go.mod'

      - name: Check generated go.mod
        run: |
          contrib/scripts/enterprise-gomod-override.sh
