name: Enterprise Image CI Build

# Any change in triggers needs to be reflected in the concurrency group.
on:
  pull_request: {}
  push:
    branches:
      - main-ce
      - ft/main-ce/**

  # If the cache was cleaned we should re-build the cache with the latest commit
  workflow_run:
    workflows:
     - "Image CI Cache Cleaner"
    branches:
     - main-ce
     - ft/main-ce/**
    types:
     - completed

permissions:
  # To be able to access the repository with `actions/checkout`
  contents: read
  # Required to generate OIDC tokens for `sigstore/cosign-installer` authentication
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.event.after }}
  cancel-in-progress: true

jobs:
  build-and-push-prs:
    timeout-minutes: 45
    name: Build and Push Images
    runs-on: ${{ vars.GH_RUNNER_EXTRA_POWER_UBUNTU_LATEST || 'ubuntu-24.04' }}
    outputs:
      sha: ${{ steps.tag.outputs.sha }}
    strategy:
      matrix:
        include:
          - name: cilium
            dockerfile: ./enterprise/images/cilium/Dockerfile
            # renovate: datasource=docker
            base_image: quay.io/isovalent-dev/cilium-runtime-ubi:0b93fa268c14630391e3eafd244040465dbb2be2
            postfix: ubi
            image_name: cilium

          - name: operator
            dockerfile: ./enterprise/images/operator/Dockerfile
            # renovate: datasource=docker
            base_image: registry.redhat.io/ubi9/ubi-micro:9.6@sha256:647c02b5b6d4760b019a468ff620ec53009d8453679bee3b7e5a676499edb1c3
            postfix: ubi
            image_name: operator-generic

          - name: hubble-relay
            dockerfile: ./enterprise/images/hubble-relay/Dockerfile
            # renovate: datasource=docker
            base_image: registry.redhat.io/ubi9/ubi-micro:9.6@sha256:647c02b5b6d4760b019a468ff620ec53009d8453679bee3b7e5a676499edb1c3
            postfix: ubi
            image_name: hubble-relay

          - name: clustermesh-apiserver
            dockerfile: ./enterprise/images/clustermesh-apiserver/Dockerfile
            # renovate: datasource=docker
            base_image: registry.redhat.io/ubi9/ubi-micro:9.6@sha256:647c02b5b6d4760b019a468ff620ec53009d8453679bee3b7e5a676499edb1c3
            postfix: ubi
            image_name: clustermesh-apiserver

    steps:
      - name: Checkout pull request branch
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          persist-credentials: false

      - name: Cleanup Disk space in runner
        if: runner.name == 'ubuntu-24.04'
        uses: ./.github/actions/disk-cleanup

      - name: Set Environment Variables
        uses: ./.github/actions/set-env-variables

      - name: Setup docker volumes into /mnt
        # This allows us to make use of all available disk.
        shell: bash
        run: |
          sudo systemctl stop docker
          sudo mv /var/lib/docker/volumes /mnt/docker-volumes
          sudo ln -s /mnt/docker-volumes /var/lib/docker/volumes
          sudo systemctl start docker

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1
        # Disable GC entirely to avoid buildkit from GC caches.
        with:
          buildkitd-config-inline: |
            [worker.oci]
             gc=false

      - name: Login to quay.io for CI
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME_CI }}
          password: ${{ secrets.QUAY_PASSWORD_CI }}

      - name: Login to registry.redhat.io for CI
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          registry: registry.redhat.io
          username: ${{ secrets.REDHAT_USERNAME_CI }}
          password: ${{ secrets.REDHAT_PASSWORD_CI }}

      - name: Getting image tag
        id: tag
        run: |
          if [ "${{ github.event.pull_request.head.sha }}" != "" ]; then
            sha=${{ github.event.pull_request.head.sha }}
          else
            sha=${{ github.sha }}
          fi
          echo sha=${sha} >> $GITHUB_OUTPUT

          tag=${sha}
          echo tag=${tag} >> $GITHUB_OUTPUT

          if [[ "${{ github.event_name == 'push' }}" == "true" ]]; then
            if [[ "${{ github.ref_name }}" == "${{ github.event.repository.default_branch }}" ]]; then
              floating_tag=latest
            else
              floating_tag="${{ github.ref_name }}"
              # Remove slashes from branch names
              floating_tag=${floating_tag##*/}
            fi
            echo floating_tag=${floating_tag} >> $GITHUB_OUTPUT
          fi

          normal_tag="quay.io/${{ env.QUAY_ORGANIZATION_DEV }}/${{ matrix.image_name }}-${{matrix.postfix}}-ci:${tag}"
          echo primary_tag=${normal_tag} >> $GITHUB_OUTPUT
          extra_tags="--tag ${normal_tag}"

          if [ -n "${floating_tag}" ]; then
            floating_normal_tag="quay.io/${{ env.QUAY_ORGANIZATION_DEV }}/${{ matrix.image_name }}-${{matrix.postfix}}-ci:${floating_tag}"
            extra_tags="${extra_tags} --tag ${floating_normal_tag}"
          fi

          echo extra_tags=${extra_tags} >> $GITHUB_OUTPUT

      - name: Check for disk usage
        shell: bash
        run: |
          df -h

      # Load Golang cache build from GitHub
      - name: Restore Golang cache build from GitHub
        uses: actions/cache/restore@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        id: go-cache
        with:
          path: /tmp/.cache/go
          key: ${{ runner.os }}-go-${{ matrix.name }}-cache-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ matrix.name }}-cache-

      - name: Check for disk usage
        shell: bash
        run: |
          df -h
          docker buildx du

      - name: Create cache directories if they don't exist
        if: ${{ steps.go-cache.outputs.cache-hit != 'true' }}
        shell: bash
        run: |
          mkdir -p /tmp/.cache/go

      # Import GitHub's cache build to docker cache
      - name: Copy ${{ matrix.name }} Golang cache to docker cache
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          provenance: false
          context: /tmp/.cache/go
          file: ./images/cache/Dockerfile
          push: false
          platforms: linux/amd64
          target: import-cache

      - name: Check for disk usage
        shell: bash
        run: |
          df -h
          docker buildx du

      - name: Install Cosign
        uses: sigstore/cosign-installer@faadad0cce49287aee09b3a48701e75088a2c6ad # v4.0.0

      - name: CI Build ${{ matrix.name }} UBI based
        id: docker_build_ci_ubi
        shell: bash
        working-directory: ./enterprise/images
        run: |
          IMAGE_TAG=${{ steps.tag.outputs.tag }} \
          REGISTRIES=quay.io/${{ env.QUAY_ORGANIZATION_DEV }} \
          PUSH=true \
          RUNTIME_IMAGE=${{ matrix.base_image }} \
          UBI_IMAGE=${{ matrix.base_image }} \
          OPERATOR_VARIANT=${{ matrix.image_name }} \
          EXTRA_ARGS="${{ steps.tag.outputs.extra_tags }}" \
          make ${{ matrix.name }}-image

      - name: CI Build ${{ matrix.name }} digest
        id: docker_digest
        shell: bash
        run: |
          digest=$(images/scripts/get-image-digest.sh "${{ steps.tag.outputs.primary_tag }}")
          echo digest=${digest} >> $GITHUB_OUTPUT

      - name: Sign Container Images
        run: |
          cosign sign -y quay.io/${{ env.QUAY_ORGANIZATION_DEV }}/${{ matrix.image_name }}-${{ matrix.postfix }}-ci@${{ steps.docker_digest.outputs.digest }}

      - name: Generate SBOM
        uses: anchore/sbom-action@43a17d6e7add2b5535efe4dcae9952337c479a93 # v0.20.11
        with:
          artifact-name: sbom_ci_${{ matrix.name }}_${{ matrix.postfix }}_${{ steps.tag.outputs.tag }}.spdx.json
          output-file: ./sbom_ci_${{ matrix.name }}_${{ matrix.postfix }}_${{ steps.tag.outputs.tag }}.spdx.json
          image: ${{ steps.tag.outputs.primary_tag }}

      - name: Attach SBOM attestation to container image
        run: |
          cosign attest -y --predicate sbom_ci_${{ matrix.name }}_${{ matrix.postfix }}_${{ steps.tag.outputs.tag }}.spdx.json --type spdxjson ${{ steps.tag.outputs.primary_tag }}

      - name: CI Image Releases digests
        shell: bash
        run: |
          mkdir -p image-digest/
          # shellcheck disable=SC2078
          if [ ${{ github.event_name == 'push' && !startsWith(github.ref_name, 'ft/') }} ]; then
            echo "quay.io/${{ env.QUAY_ORGANIZATION_DEV }}/${{ matrix.image_name }}-${{ matrix.postfix }}-ci:${{ steps.tag.outputs.floating_tag }}@${{ steps.docker_digest.outputs.digest }}" > image-digest/${{ matrix.name }}.txt
          fi
          echo "${{ steps.tag.outputs.primary_tag}}@${{ steps.docker_digest.outputs.digest }}" >> image-digest/${{ matrix.name }}-${{ matrix.postfix }}.txt

      # Upload artifact digests
      - name: Upload artifact digests
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: image-digest ${{ matrix.name }}-${{ matrix.postfix }}
          path: image-digest
          retention-days: 1

      - name: Check for disk usage
        if: ${{ always() }}
        shell: bash
        run: |
          df -h

  image-digests:
    if: ${{ always() }}
    name: Display Digests
    runs-on: ubuntu-24.04
    needs: build-and-push-prs
    steps:
      - name: Downloading Image Digests
        shell: bash
        run: |
          mkdir -p image-digest/

      - name: Download digests of all images built
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
        with:
          path: image-digest/
          pattern: "*image-digest *"

      - name: Image Digests Output
        shell: bash
        run: |
          cd image-digest/
          find -type f | sort | xargs -d '\n' cat
