name: Enterprise LoadBalancer (ci-lb)

# Any change in triggers needs to be reflected in the concurrency group.
on:
  workflow_dispatch:
    inputs:
      PR-number:
        description: "Pull request number."
        required: true
      context-ref:
        description: "Context in which the workflow runs. If PR is from a fork, will be the PR target branch (general case). If PR is NOT from a fork, will be the PR branch itself (this allows committers to test changes to workflows directly from PRs)."
        required: true
      SHA:
        description: "SHA under test (head of the PR branch)."
        required: true
      extra-args:
        description: "[JSON object] Arbitrary arguments passed from the trigger comment via regex capture group. Parse with 'fromJson(inputs.extra-args).argName' in workflow."
        required: false
        default: "{}"
  # Run every 8 hours
  schedule:
    - cron: "0 2/8 * * *"

# By specifying the access of one of the scopes, all of those that are not
# specified are set to 'none'.
permissions:
  # To read actions state with catchpoint/workflow-telemetry-action
  actions: read
  # To be able to access the repository with actions/checkout
  contents: read
  # To allow retrieving information from the PR API
  pull-requests: read
  # To be able to set commit status
  statuses: write

concurrency:
  # Structure:
  # - Workflow name
  # - Event type
  # - A unique identifier depending on event type:
  #   - schedule: SHA
  #   - workflow_dispatch: PR number
  #
  # This structure ensures a unique concurrency group name is generated for each
  # type of testing, such that re-runs will cancel the previous run.
  group: |
    ${{ github.workflow }}
    ${{ github.event_name }}
    ${{
      (github.event_name == 'schedule' && github.sha) ||
      (github.event_name == 'workflow_dispatch' && github.event.inputs.PR-number)
    }}
  cancel-in-progress: true

env:
  cilium_cli_ci_version:

jobs:
  echo-inputs:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    name: Echo Workflow Dispatch Inputs
    runs-on: ubuntu-24.04
    steps:
      - name: Echo Workflow Dispatch Inputs
        run: |
          echo '${{ tojson(inputs) }}'

  commit-status-start:
    name: Commit Status Start
    runs-on: ubuntu-24.04
    steps:
      - name: Set initial commit status
        uses: myrotvorets/set-commit-status-action@3730c0a348a2ace3c110851bed53331bc6406e9f # v2.0.1
        with:
          sha: ${{ inputs.SHA || github.sha }}

  setup-and-test:
    runs-on: ${{ vars.GH_RUNNER_EXTRA_POWER }}
    name: "Setup & Test"
    env:
      job_name: "Setup & Test"
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        include:
          - name: "0"
            mode: "multi-node"
            kernel: "6.1-20240710.064909"
            use-remote-address: "true"
            xff-num-trusted-hops: 0
          - name: "1"
            mode: "single-node"
            kernel: "6.1-20240710.064909"
            use-remote-address: "true"
            xff-num-trusted-hops: 0
          - name: "2"
            mode: "single-node"
            kernel: "6.1-20240710.064909"
            use-remote-address: "false"
            xff-num-trusted-hops: 2

    timeout-minutes: 60

    steps:
      - name: Skip single-node tests on non-scheduled events
        if: ${{ github.event_name != 'schedule' && matrix.mode == 'single-node' }}
        run: |
          echo "skip=true" >> $GITHUB_ENV

      - name: Collect Workflow Telemetry
        if: ${{ env.skip != 'true' }}
        uses: catchpoint/workflow-telemetry-action@94c3c3d9567a0205de6da68a76c428ce4e769af1 # v2.0.0
        with:
          comment_on_pr: false

      - name: Checkout PR
        if: ${{ env.skip != 'true' }}
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ steps.vars.outputs.sha }}
          persist-credentials: false

      - name: Set Environment Variables
        if: ${{ env.skip != 'true' }}
        uses: ./.github/actions/set-env-variables

      - name: Set up job variables
        if: ${{ env.skip != 'true' }}
        id: vars
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            SHA="${{ inputs.SHA }}"
          else
            SHA="${{ github.sha }}"
          fi
          echo sha=${SHA} >> $GITHUB_OUTPUT

          echo kind-params="--xdp \"\" 2 \"\" \"\" \"none\" \"ipv4\"" >> $GITHUB_OUTPUT

      - name: Install Cilium CLI
        if: ${{ env.skip != 'true' }}
        uses: cilium/cilium-cli@f313219850d324b516748ff7b00a6f9fa30d34ae # v0.16.23
        with:
          skip-build: ${{ env.CILIUM_CLI_SKIP_BUILD }}
          image-repo: ${{ env.CILIUM_CLI_IMAGE_REPO }}
          image-tag: ${{ steps.vars.outputs.sha }}

      - name: Provision K8s control-plane on LVH VM
        if: ${{ env.skip != 'true' }}
        uses: ./.github/actions/lvh-kind
        with:
          test-name: enterprise-lb
          kernel: ${{ matrix.kernel }}
          kind-params: "${{ steps.vars.outputs.kind-params }}"
          kind-image: ${{ env.KIND_K8S_IMAGE }}
          port-forward: "6443:6443,22375:2375,22376:22376"

      - name: Preconfigure K8s nodes
        if: ${{ env.skip != 'true' }}
        shell: bash
        run: |
          export DOCKER_HOST="tcp://127.0.0.1:22375"

          kubectl label node kind-control-plane service.cilium.io/node=t1
          kubectl taint node kind-control-plane service.cilium.io/node=t1:NoSchedule
          kubectl label node kind-worker service.cilium.io/node=t2
          kubectl label node kind-worker2 service.cilium.io/node=t2

          kind get nodes --name kind  | xargs -I container_name docker exec container_name sysctl -w net.ipv4.ip_unprivileged_port_start=0

      - name: Create testing host (single-node)
        id: single-node
        if: ${{ env.skip != 'true' && matrix.mode == 'single-node' }}
        shell: bash
        run: |
          export DOCKER_HOST="tcp://127.0.0.1:22375"

          # Create DIND container to simulate the testing host
          docker run -d --name testing-host --env DOCKER_TLS_CERTDIR="" -p 22376:2375 --privileged --network kind-cilium docker:27.3.1-dind
          ip=$(docker inspect '--format={{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' testing-host)
          echo ip=${ip} >> $GITHUB_OUTPUT

      - name: Wait for images to be available
        if: ${{ env.skip != 'true' }}
        timeout-minutes: 30
        shell: bash
        run: |
          for image in cilium-ci operator-generic-ci hubble-relay-ci ; do
            until docker manifest inspect quay.io/${{ env.QUAY_ORGANIZATION_DEV }}/$image:${{ steps.vars.outputs.sha }} &> /dev/null; do sleep 45s; done
          done

      - name: Install Isovalent LB
        if: ${{ env.skip != 'true' }}
        shell: bash
        run: |
          EXTRA=""
          if [ "${{ matrix.use-remote-address }}" != "" ]; then
            EXTRA+=" --helm-set-string=extraConfig.use-remote-address=${{ matrix.use-remote-address }}"
          fi

          if [ "${{ matrix.xff-num-trusted-hops }}" != "" ]; then
            EXTRA+=" --helm-set-string=extraConfig.loadbalancer-cp-t2-xff-num-trusted-hops=${{ matrix.xff-num-trusted-hops }}"
          fi

          cilium install \
             --wait --chart-directory=./install/kubernetes/cilium \
             --helm-set=image.repository=quay.io/isovalent-dev/cilium-ci \
             --helm-set=image.useDigest=false \
             --helm-set=image.tag=${{ steps.vars.outputs.sha }} \
             --helm-set=operator.image.repository=quay.io/isovalent-dev/operator \
             --helm-set=operator.image.suffix=-ci \
             --helm-set=operator.image.tag=${{ steps.vars.outputs.sha }} \
             --helm-set=operator.image.useDigest=false \
             --helm-set=hubble.relay.image.repository=quay.io/isovalent-dev/hubble-relay-ci \
             --helm-set=hubble.relay.image.tag=${{ steps.vars.outputs.sha }} \
             --helm-set=hubble.relay.image.useDigest=false \
             --helm-set=enterprise.loadbalancer.enabled=true \
             --helm-set=enterprise.bgpControlPlane.enabled=true \
             --helm-set=enterprise.bgpControlPlane.enableServiceHealthChecking=true \
             --helm-set=enterprise.bfd.enabled=true \
             --helm-set=debug.enabled=true \
             --helm-set=debug.verbose="envoy datapath" \
             --helm-set-string=envoy.nodeSelector."service\.cilium\.io/node"=t2 \
             --helm-set=envoy.debug.admin.enabled=true \
             --helm-set=envoy.dnsPolicy=ClusterFirstWithHostNet \
             --helm-set=envoyConfig.enabled=true \
             --helm-set=bpf.monitorAggregation=none \
             --helm-set=kubeProxyReplacement=true \
             --helm-set-string=extraConfig.enable-ipip-termination=true \
             --helm-set-string=extraConfig.loadbalancer-cp-accesslog-enable-hc=true \
             --helm-set-string=extraConfig.loadbalancer-cp-t1-hc-probe-timeout-seconds=10 \
             $EXTRA

          cilium status --wait
          kubectl get pods --all-namespaces -o wide
          kubectl -n kube-system exec daemonset/cilium -- cilium-dbg status

          echo "Waiting until CiliumNodeConfig CRD has been created"
          while ! kubectl get crds ciliumnodeconfigs.cilium.io &> /dev/null; do
            echo -n "."
            sleep 2
          done
          echo ""

          kubectl apply -f enterprise/examples/kubernetes/loadbalancer/lb/t1-nodeconfig.yaml
          kubectl -n kube-system delete pod -l k8s-app=cilium --field-selector spec.nodeName=kind-control-plane
          cilium status --wait

      - name: Run tests
        if: ${{ env.skip != 'true' }}
        shell: bash
        run: |
          PARAMS="--sysdump-on-failure=true"
          if [ "${{ matrix.mode }}" == "single-node" ]; then
            export DOCKER_HOST="tcp://127.0.0.1:22376"
            PARAMS="--mode=single-node"
          else
            export DOCKER_HOST="tcp://127.0.0.1:22375"
          fi

          if [ "${{ matrix.use-remote-address }}" != "" ]; then
            PARAMS+=" --use-remote-address=${{ matrix.use-remote-address }}"
          fi

          if [ "${{ matrix.xff-num-trusted-hops }}" != "" ]; then
            PARAMS+=" --xff-num-trusted-hops=${{ matrix.xff-num-trusted-hops }}"
          fi

          # Using gotestsum to generate JUnit XML. It also allows generating
          # test logs with the GHA log grouping format.
          go install gotest.tools/gotestsum@latest

          DOCKER_API_VERSION=1.45 LOADBALANCER_TESTS=true gotestsum --format github-actions --junitfile cilium-junits-${{ matrix.name }}.xml ./enterprise/test/ilb -test.timeout=30m $PARAMS

      - name: Upload sysdumps
        if: ${{ env.skip != 'true' && !success() }}
        uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0
        with:
          name: cilium-sysdumps-${{ matrix.name }}
          path: enterprise/test/ilb/cilium-sysdump-*.zip
          retention-days: 5

      - name: Upload JUnit reports
        if: ${{ env.skip != 'true' }}
        uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0
        with:
          name: cilium-junits-${{ matrix.name }}
          path: cilium-junits-*.xml
          retention-days: 5

  merge-upload:
    if: ${{ always() }}
    name: Merge and Upload Artifacts
    runs-on: ubuntu-24.04
    needs: setup-and-test
    steps:
      - name: Merge JUnits
        uses: actions/upload-artifact/merge@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0
        with:
          name: cilium-junits
          pattern: cilium-junits-*
          retention-days: 5
          delete-merged: true
        continue-on-error: true

  commit-status-final:
    if: ${{ always() }}
    name: Commit Status Final
    needs: setup-and-test
    runs-on: ubuntu-24.04
    steps:
      - name: Set final commit status
        uses: myrotvorets/set-commit-status-action@3730c0a348a2ace3c110851bed53331bc6406e9f # v2.0.1
        with:
          sha: ${{ inputs.SHA || github.sha }}
          status: ${{ needs.setup-and-test.result }}
