name: UBI Base Image Release Build

# Any change in triggers needs to be reflected in the concurrency group.
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - enterprise/images/runtime/**
  workflow_call:
    inputs:
      environment:
        type: string
        default: "release-base-images"

permissions:
  # To be able to access the repository with `actions/checkout`
  contents: read
  # Required to generate OIDC tokens for `sigstore/cosign-installer` authentication
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-and-push:
    name: Build and Push Images
    timeout-minutes: 45
    environment: ${{ inputs.environment || 'release-base-images' }}
    runs-on: ubuntu-24.04
    steps:
      - name: Get git token
        uses: getsentry/action-github-app-token@d4b5da6c5e37703f8c3b3e43abb5705b46e159cc # v3
        id: get_token
        with:
          private_key: ${{ secrets.ISOVALENT_MIRROR_UPSTREAM_BOT_APP_PEM }}
          app_id: ${{ secrets.ISOVALENT_MIRROR_UPSTREAM_BOT_APP_ID }}

      - name: Checkout pull request branch
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Cleanup Disk space in runner
        uses: ./.github/actions/disk-cleanup

      - name: Set Environment Variables
        uses: ./.github/actions/set-env-variables

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3.6.0

      - name: Install Cosign
        uses: sigstore/cosign-installer@faadad0cce49287aee09b3a48701e75088a2c6ad # v4.0.0

      - name: Generating image tag for Cilium-Runtime
        id: runtime-tag
        run: |
          echo tag="$(git ls-tree --full-tree HEAD -- ./enterprise/images/runtime | awk '{ print $3 }')" >> $GITHUB_OUTPUT

      - name: Checking if tag for Cilium-Runtime already exists
        id: cilium-runtime-tag-in-repositories
        shell: bash
        run: |
          if docker buildx imagetools inspect quay.io/${{ env.QUAY_ORGANIZATION_DEV }}/cilium-runtime-ubi:${{  steps.runtime-tag.outputs.tag }} &>/dev/null; then
            echo exists="true" >> $GITHUB_OUTPUT
          else
            echo exists="false" >> $GITHUB_OUTPUT
          fi

      - name: Login to registry.redhat.io for pulling images
        uses: docker/login-action@28fdb31ff34708d19615a74d67103ddc2ea9725c
        with:
          registry: registry.redhat.io
          username: ${{ secrets.REDHAT_USERNAME_CI }}
          password: ${{ secrets.REDHAT_PASSWORD_CI }}

      - name: Login to quay.io
        if: ${{ steps.cilium-runtime-tag-in-repositories.outputs.exists == 'false' }}
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME_CI }}
          password: ${{ secrets.QUAY_PASSWORD_CI }}

      - name: Release build cilium-runtime
        if: ${{ steps.cilium-runtime-tag-in-repositories.outputs.exists == 'false' }}
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        id: docker_build_release_runtime
        with:
          provenance: false
          context: .
          file: ./enterprise/images/runtime/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          target: release
          tags: |
            quay.io/${{ env.QUAY_ORGANIZATION_DEV }}/cilium-runtime-ubi:${{ steps.runtime-tag.outputs.tag }}
          build-args: |
            # renovate: datasource=docker
            CILIUM_LLVM_IMAGE=quay.io/isovalent-dev/cilium-llvm-ubi:1754712783-48bbfc6@sha256:b673ca26acfc574d815c231814707ffa6e39e039450ce95bf296a436f4ff22e9
            # renovate: datasource=docker
            CILIUM_BPFTOOL_IMAGE=quay.io/isovalent-dev/cilium-bpftool-ubi:1754712783-48bbfc6@sha256:e4401c2a3bbbacbf6a061ce8294165d03779ae9a904e7902303d4d0b8c9f9360
            # renovate: datasource=docker
            COMPILERS_IMAGE=quay.io/isovalent-dev/image-compilers-ubi:1754570895-16e2939@sha256:731c9cebd0d6bd5846faa6cf76d0e7841f700df745a9f814273e77c5ae43121a

      - name: Sign Container Image Runtime
        if: ${{ steps.cilium-runtime-tag-in-repositories.outputs.exists == 'false' }}
        run: |
          cosign sign -y quay.io/${{ env.QUAY_ORGANIZATION_DEV }}/cilium-runtime-ubi@${{ steps.docker_build_release_runtime.outputs.digest }}

      - name: Generate SBOM
        if: ${{ steps.cilium-runtime-tag-in-repositories.outputs.exists == 'false' }}
        uses: anchore/sbom-action@aa0e114b2e19480f157109b9922bda359bd98b90 # v0.20.8
        with:
          artifact-name: sbom_cilium-runtime_${{ steps.runtime-tag.outputs.tag }}.spdx.json
          output-file: ./sbom_cilium-runtime_${{ steps.runtime-tag.outputs.tag }}.spdx.json
          image: quay.io/${{ env.QUAY_ORGANIZATION_DEV }}/cilium-runtime-ubi:${{ steps.runtime-tag.outputs.tag }}

      - name: Attach SBOM attestation to container image
        if: ${{ steps.cilium-runtime-tag-in-repositories.outputs.exists == 'false' }}
        run: |
          cosign attest -y --predicate sbom_cilium-runtime_${{ steps.runtime-tag.outputs.tag }}.spdx.json --type spdxjson quay.io/${{ env.QUAY_ORGANIZATION_DEV }}/cilium-runtime-ubi@${{ steps.docker_build_release_runtime.outputs.digest }}

      - name: Image Release Digest Runtime
        if: ${{ steps.cilium-runtime-tag-in-repositories.outputs.exists == 'false' }}
        shell: bash
        run: |
          mkdir -p image-digest/
          echo "## cilium-runtime-ubi" > image-digest/cilium-runtime-ubi.txt
          echo "" >> image-digest/cilium-runtime-ubi.txt
          echo "\`quay.io/${{ env.QUAY_ORGANIZATION_DEV }}/cilium-runtime-ubi:${{ steps.runtime-tag.outputs.tag }}@${{ steps.docker_build_release_runtime.outputs.digest }}\`" >> image-digest/cilium-runtime-ubi.txt
          echo "" >> image-digest/cilium-runtime-ubi.txt

      - name: Upload artifact digests runtime
        if: ${{ steps.cilium-runtime-tag-in-repositories.outputs.exists == 'false' }}
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: image-digest cilium-runtime-ubi
          path: image-digest
          retention-days: 1

      - name: Set-up git
        run: |
          git config user.name "Isovalent Imagebot"
          git config user.email "noreply@isovalent.com"

      - name: Update runtime image and commit
        id: update-runtime-image
        shell: bash
        run: |
          enterprise/images/runtime/update-runtime-image.sh quay.io/${{ env.QUAY_ORGANIZATION_DEV }}/cilium-runtime-ubi:${{ steps.runtime-tag.outputs.tag }}
          if git commit -sam "images: update cilium-runtime-ubi"; then
            echo "committed=true" >> $GITHUB_OUTPUT
          else
            echo "committed=false" >> $GITHUB_OUTPUT
          fi

      - name: Push changes into PR
        if: ${{ steps.update-runtime-image.outputs.committed == 'true' }}
        env:
          ref: ${{ github.event.pull_request.head.ref || github.ref }}
          repository:  ${{ github.event.pull_request.head.repo.full_name || github.repository }}
        run: |
          git diff HEAD^
          git push https://x-access-token:${{ steps.get_token.outputs.token }}@github.com/${{ env.repository }}.git HEAD:$ref

  image-digests:
    name: Display Digests
    runs-on: ubuntu-24.04
    environment: ${{ inputs.environment || 'release-base-images' }}
    needs: build-and-push
    steps:
      - name: Downloading Image Digests
        shell: bash
        run: |
          mkdir -p image-digest/

      - name: Download digests of all images built
        uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5.0.0
        with:
          path: image-digest/
          pattern: "*image-digest *"

      - name: Image Digests Output
        shell: bash
        run: |
          cd image-digest/
          find -type f | sort | xargs -d '\n' cat
