---
name: Auto Backport Merged Pull Requests

on:
  issue_comment:
    types: [created]
  pull_request:
    types: [closed]

  workflow_dispatch:
    inputs:
      PR-number:
        description: "Pull request number."
        required: true
      context-ref:
        description: "Placeholder for ariane. Not used in the workflow."
        required: false
        default: ''
      SHA:
        description: "Placeholder for ariane. Not used in the workflow."
        required: false
        default: ''
      base-SHA:
        description: "Placeholder for ariane. Not used in the workflow."
        required: false
        default: ''
      extra-args:
        description: "[string] Arbitrary arguments (space separated) passed from the trigger comment via regex capture group. Parse with 'fromJson(inputs.extra-args)' in workflow."
        required: false
        default: ''
      target-branches:
        description: "[string] Target branches (space separated) for backporting."
        required: false
        default: ''

permissions:
  id-token: write


# This workflow runs in two scenarios:
# 1. When a pull request is closed (merged)
#    - Checks for the `auto-backport` label on the PR
#    - If present, creates backport PRs to target branches inferred from labels

# 2. When a comment is created on a pull request (when closed and when open - by workflow_dispatch from ariane)
#    - If the comment starts with `/backport` followed by target branches
#    - Checks for the `auto-backport` label on the PR
#    - If present, check if the PR is merged
#      - If not merged, adds `needs-backport/<target-branch>` labels to PR for each target branch specified in the comment
#      - If merged, creates backport PRs to target branches specified in the comment


jobs:
  backport:
    name: Backport Changes
    runs-on: ubuntu-24.04 # Change this to ${{ vars.UBUNTU_2404_2CPU_1GB }} before merging
    timeout-minutes: 10
    env:
        GH_BACKPORTER_APP_ID: ''
        GH_BACKPORTER_APP_PEM: ''
        PR_NUMBER: ${{ github.event.pull_request.number || github.event.issue.number || inputs.PR-number}}
        TARGET_BRANCH_PREFIX: ${{ vars.TARGET_BRANCH_PREFIX }}
        TARGET_BRANCH_SUFFIX: ${{ vars.TARGET_BRANCH_SUFFIX }}
        TARGET_BRANCHES: ''

    # run only when a PR is merged or when a comment with /backport is created on a pull request or on workflow_dispatch
    if: >
      github.event.pull_request.merged ||
      github.event_name == 'workflow_dispatch' ||
      (
        github.event_name == 'issue_comment' &&
        github.event.issue.pull_request &&
        github.event.comment.user.type != 'Bot' &&
        startsWith(github.event.comment.body, '/backport')
      )

    steps:
      - name: Get Mirror GitHub App Credentials from Vault
        id: get-vault-secrets
        uses: hashicorp/vault-action@4c06c5ccf5c0761b6029f56cfb1dcf5565918a3b # v3.4.0
        env:
          SECRETS_PATH: "secret/data/org/${{ github.repository_owner }}"
        with:
          url: ${{ vars.VAULT_URL }}
          method: ${{ vars.VAULT_METHOD }}
          namespace: ${{ vars.VAULT_NAMESPACE }}
          secrets: |
            ${{ env.SECRETS_PATH }} backporter_github_app_pem | GH_BACKPORTER_APP_PEM;
            ${{ env.SECRETS_PATH }} backporter_github_app_id | GH_BACKPORTER_APP_ID;

      - name: Generate Token for Backporter GitHub App
        id: generate-token
        uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2.2.1
        with:
          app-id: ${{ env.GH_BACKPORTER_APP_ID }}
          private-key: ${{ env.GH_BACKPORTER_APP_PEM }}

      - name: Add emoji to issue_comment
        if: github.event_name == 'issue_comment'
        id: add-reactions-to-comment
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        with:
          github-token: ${{ steps.generate-token.outputs.token }}
          script: |
            await github.rest.reactions.createForIssueComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: context.payload.comment.id,
                content: 'rocket'
            });

      - name: Check for `auto-backport` label on the PR
        id: check-backport-labels
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        with:
          github-token: ${{ steps.generate-token.outputs.token }}
          result-encoding: string
          script: |
            const prNumber = process.env.PR_NUMBER;
            const { data: pr } = await github.rest.pulls.get({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: prNumber
            });

            const result = pr.labels.some(label => label.name === '${{ vars.AUTO_BACKPORT_LABEL }}');

            // Check if the `auto-backport` label is present. If not, comment and exit with failure.
            // Do not add comment to workflow runs triggered by pull_request event.
            if (!result && context.eventName != 'pull_request') {
                await github.rest.issues.createComment({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    issue_number: prNumber,
                    body: 'ℹ️ `auto-backport` label not found. Skipping backporting process.\n' +
                      'To enable automatic backporting for this pull request, ' +
                      'please add the `${{ vars.AUTO_BACKPORT_LABEL }}` label.\n' +
                      'You can retrigger the workflow by adding a new comment ' +
                      '`/backport ${{ env.TARGET_BRANCHES }} <space separated branch list>` to this PR.'
                });
            }

            console.log(`Is "auto-backport" label present: ${result}`);
            return result.toString();

      - name: Check if pull_request is merged
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        id: check-pr-merged
        with:
          github-token: ${{ steps.generate-token.outputs.token }}
          result-encoding: string
          script: |
            const { data: pr } = await github.rest.pulls.get({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: process.env.PR_NUMBER
            });

            console.log(`Is pull request merged: ${pr.merged}`);
            return pr.merged === true ? 'true' : 'false';

      - name: Setup Target Branches from workflow_dispatch input
        if: github.event_name == 'workflow_dispatch'
        id: setup-target-branches-dispatch
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        with:
          github-token: ${{ steps.generate-token.outputs.token }}
          script: |
            let targetBranches = '';
            if ( '${{ inputs.target-branches }}'.trim() != '' ) {
                targetBranches = '${{ inputs.target-branches }}';
            }
            if ( '${{ inputs.extra-args }}'.trim() != '' ) {
                targetBranches = JSON.parse('${{ inputs.extra-args }}');
            }
            console.log(`Setting TARGET_BRANCHES to: '${targetBranches}'`);
            core.exportVariable('TARGET_BRANCHES', targetBranches);

      - name: Setup Target Branches from text comment / command
        if: github.event_name == 'issue_comment'
        id: setup-target-branches
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        with:
          github-token: ${{ steps.generate-token.outputs.token }}
          script: |
            let targetBranches = process.env.TARGET_BRANCHES;

            const parsedComment = context.payload.comment.body.trim().split(' ');
            if (parsedComment.length > 1) {
                targetBranches = parsedComment.slice(1)
                    .filter(branch => branch.trim() !== '').join(' ');
            }

            console.log(`Setting TARGET_BRANCHES to: '${targetBranches}'`);
            core.exportVariable('TARGET_BRANCHES', targetBranches);

      - name: Setup Labels if pull_request is not merged
        id: setup-labels
        if: true == false
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        with:
          github-token: ${{ steps.generate-token.outputs.token }}
          script: |
            const target_labels = '${{ env.TARGET_BRANCHES }}'.split(' ')
                .filter(branch => branch.trim() !== '')
                .map(branch => `needs-backport/${branch}${{ env.TARGET_BRANCH_SUFFIX }}`);

            await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: '${{ env.PR_NUMBER }}',
                labels: target_labels
            });

            await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: '${{ env.PR_NUMBER }}',
                body: '⚠️ Backporting process did not create any backport pull requests.\n' +
                        'Backporting will start once this PR is merged.\n' +
                        'Labels `' + target_labels.join(", ") + '` have been added accordingly.'
            });

      - name: Validate Branches
        id: validate-branches
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        if: github.event_name == 'issue_comment' || github.event_name == 'workflow_dispatch'
        with:
          github-token: ${{ steps.generate-token.outputs.token }}
          script: |
            const branchPrefix = process.env.TARGET_BRANCH_PREFIX;
            const branchSuffix = process.env.TARGET_BRANCH_SUFFIX;
            const targetBranches = process.env.TARGET_BRANCHES.split(' ')
                .filter(branch => branch.trim() !== '')
                .map(branch => `${branch}${branchSuffix}`);

            if (targetBranches.length === 0) {
                await github.rest.issues.createComment({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    issue_number: process.env.PR_NUMBER,
                    body: '⚠️ No target branches specified for backporting. ' +
                          'Please provide at least one target branch in the comment like:\n' +
                          '`/backport <target-branch-1> <target-branch-2> ...`'
                });
                core.setFailed('No target branches specified for backporting.');
            }

            for (const branch of targetBranches) {
                const fullBranchName = `${branchPrefix}${branch}`;
                try {
                    await github.rest.repos.getBranch({
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        branch: fullBranchName
                    });
                } catch (error) {
                    await github.rest.issues.createComment({
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        issue_number: process.env.PR_NUMBER,
                        body: `⚠️ Target branch \`${fullBranchName}\` does not exist in the repository. ` +
                            'Please provide valid target branches for backporting.'
                    });
                    core.setFailed(`Target branch ${fullBranchName} does not exist in the repository.`);
                }
            }

            console.log(`Validated target branches: ${targetBranches.join(', ')}`);
            core.exportVariable('TARGET_BRANCHES', targetBranches.join(' '));

      - name: Checkout code
        id: checkout
        if: steps.check-backport-labels.outputs.result == 'true' && steps.check-pr-merged.outputs.result == 'true'
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          token: ${{ steps.generate-token.outputs.token }}

      - name: Create backport pull requests
        id: backport
        uses: isovalent/backport-action@7841e9b4aca996cbaca3e1b0a6972747ca1ec38d
        if: steps.checkout.outcome == 'success'
        with:
          github_token: ${{ steps.generate-token.outputs.token }}
          branch_name: backport/${target_branch}/${pull_number}
          target_branches: ${{ env.TARGET_BRANCHES }}
          add_author_as_assignee: true
          copy_labels_pattern: '^(kind|area|vertical|feature|release\-note)\/.*$'
          copy_milestone: false # Reviewer should set this manually
          copy_requested_reviewers: false # Previous reviewers may not be available for review
          label_pattern: '^needs-backport\/([\w\.\-]+)$'
          pull_title: '[${target_branch} Backport]: ${pull_title}'
          pull_description: |
            Backport of #${pull_number} to `${target_branch}`.
            * [x] #${pull_number}

            ## Upstream pull request description:

            ${pull_description}

            Once this PR is merged, a GitHub action will update the labels of these PRs:
            ```upstream-prs
            ${pull_number}
            ```
          add_labels: 'kind/backports, backport-automation'
          source_pr_number: ${{ env.PR_NUMBER }}
          target_branch_prefix: ${{ env.TARGET_BRANCH_PREFIX }}
          target_branch_suffix: ${{ env.TARGET_BRANCH_SUFFIX }}

      - name: Remove need-backport/* and add backport-pending/* labels to Pull Request
        id: update-labels
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        if: steps.backport.outcome != 'skipped'
        with:
          github-token: ${{ steps.generate-token.outputs.token }}
          script: |
            const prNumber = '${{ env.PR_NUMBER }}';
            console.log('Processing backport results for PR #' + prNumber);
            const { data: pr } = await github.rest.pulls.get({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: prNumber
            });

            /*
                * was_successful_by_target is a string separated by newresults in the format key=value,
                * where the keys are the target branches (include branch names. ex: "v1.18-ce=true\nv1.19-ce=false")
                * that were backported to, and the values are "true" or "false" depending on whether the backport was successful.
                * For each target branch that was backported to, remove target_branch_prefix
                * `backport-pending/<target>` label.
            */

            const results = `${{ steps.backport.outputs.was_successful_by_target }}`
              .split('\n')
              .filter(result => result.trim() !== '');

            console.log('Backporting output:', results);

            const labelsToRemove = [];
            const labelsToAdd = [];

            for (const result of results) {
                const [branch, was_successful] = result.split('=');

                if (was_successful !== 'true') {
                    core.error(`Backport to ${branch} failed.`);
                    continue;
                }

                console.log(`Backport to ${branch} was successful.`);
                // The backport action already uses the full branch name like 'v1.18-ce'
                const label_branch = branch.replace(`${{ env.TARGET_BRANCH_PREFIX }}`, '')
                const needs_backport_label = `needs-backport/${label_branch}`;
                const backport_pending_label = `backport-pending/${label_branch}`;

                labelsToRemove.push(needs_backport_label);
                labelsToAdd.push(backport_pending_label);
            }

            const currentLabels = pr.labels.map(l => l.name);
            const newLabels = currentLabels
                .filter(label => !labelsToRemove.includes(label))
                .concat(labelsToAdd.filter(label => !currentLabels.includes(label)));

            if (labelsToAdd.length > 0) {
                console.log(`Updating labels on PR #${prNumber}.`);
                console.log('Removing labels:', labelsToRemove);
                console.log('Adding labels:', labelsToAdd);

                await github.rest.issues.setLabels({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    issue_number: prNumber,
                    labels: newLabels
                });
            }

            const prs = `${{ steps.backport.outputs.created_pull_numbers }}`
                .split(' ')
                .filter(pr => pr.trim() !== '');

            for (const pr_number of prs) {
                console.log(`Backport PR created: #${pr_number}`);
                const { data: pr } = await github.rest.pulls.get({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    pull_number: pr_number
                });

                const backport_label = `backport/${pr.base.ref.replace(`${{ env.TARGET_BRANCH_PREFIX }}`, '')}`;
                await github.rest.issues.addLabels({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    issue_number: pr_number,
                    labels: [backport_label]
                });
            }

  commit-status-start:
    name: Commit Status Start
    permissions:
      statuses: write
    runs-on: ubuntu-24.04
    if: github.event_name == 'workflow_dispatch' && inputs.SHA != ''
    steps:
      - name: Set initial commit status
        uses: myrotvorets/set-commit-status-action@3730c0a348a2ace3c110851bed53331bc6406e9f # v2.0.1
        with:
          sha: ${{ inputs.SHA }}
  commit-status-final:
    if: ${{ always() && github.event_name == 'workflow_dispatch' && inputs.SHA != '' }}
    name: Commit Status Final
    needs:
      - backport
    runs-on: ubuntu-24.04
    permissions:
      statuses: write
    steps:
      - name: Set final commit status
        uses: myrotvorets/set-commit-status-action@3730c0a348a2ace3c110851bed53331bc6406e9f # v2.0.1
        with:
          sha: ${{ inputs.SHA }}
          status: ${{ needs.backport.result == 'success' && 'success' || 'failure' }}
