name: Build images external to isovalent/cilium

# Any change in triggers needs to be reflected in the concurrency group.
on:
  push:
    branches:
      - main-ce
    paths:
      - install/kubernetes/Makefile.values

permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.event.after || github.event.merge_group && github.run_id }}

jobs:
  check-and-build:
    name: Deduce changes and build image
    environment: release
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - component: CERTGEN
            docker-context: certgen
            base-image: registry.redhat.io/ubi9/ubi-micro@sha256:d115f8aad9c4ae7ee21ae75bbcb3dc2c5dbf9b57bf6dad6dcb5aac5c02003bde
            build-from-upstream: 'true'
            upstream-repo: cilium/certgen
            upstream-path: certgen

          - component: CILIUM_NODEINIT
            docker-context: enterprise/images/startup-script
            base-image: registry.redhat.io/ubi9/ubi-minimal@sha256:14f14e03d68f7fd5f2b18a13478b6b127c341b346c86b6e0b886ed2b7573b8e0
            build-args: STARTUP_VERSION=c54c7edeab7fde4da68e59acd319ab24af242c3f
            build-from-upstream: 'false'

          - component: CILIUM_ENVOY
            docker-context: enterprise/images/cilium-envoy
            base-image: registry.redhat.io/ubi9/ubi-minimal@sha256:14f14e03d68f7fd5f2b18a13478b6b127c341b346c86b6e0b886ed2b7573b8e0
            build-from-upstream: 'false'

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ github.event.push.after }}
          persist-credentials: false
          fetch-depth: 0

      - name: Check ${{ matrix.component }} code changes
        id: check-changes
        run: |
          if git diff --unified=0 ${{ github.event.push.before }} -- install/kubernetes/Makefile.values | grep ${{ matrix.component }} ; then
            echo "changed=true" >> $GITHUB_OUTPUT
            echo "repo=$(cat install/kubernetes/Makefile.values| grep ${{ matrix.component }}_REPO | awk -F '=' '{print $2}')" >> $GITHUB_OUTPUT
            echo "version=$(cat install/kubernetes/Makefile.values| grep ${{ matrix.component }}_VERSION | awk -F '=' '{print $2}')" >> $GITHUB_OUTPUT
            echo "digest=$(cat install/kubernetes/Makefile.values| grep ${{ matrix.component }}_DIGEST | awk -F '=' '{print $2}')" >> $GITHUB_OUTPUT
            echo "cee-image=$(basename ${{ matrix.docker-context }})" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Set up Docker Buildx
        if: ${{ steps.check-changes.outputs.changed == 'true' }}
        uses: docker/setup-buildx-action@f7ce87c1d6bead3e36075b2ce75da1f6cc28aaca

      - name: Login to quay.io
        if: ${{ steps.check-changes.outputs.changed == 'true' }}
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME_RELEASE_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD_RELEASE_PASSWORD }}

      - name: Login to registry.redhat.io for pulling images
        if: ${{ steps.check-changes.outputs.changed == 'true' }}
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567
        with:
          registry: registry.redhat.io
          username: ${{ secrets.REDHAT_USERNAME_CI }}
          password: ${{ secrets.REDHAT_PASSWORD_CI }}

      - name: Checkout upstream repo
        if: ${{ steps.check-changes.outputs.changed == 'true' && matrix.build-from-upstream == 'true' }}
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          repository: ${{ matrix.upstream-repo }}
          persist-credentials: false
          path: ${{ matrix.upstream-path }}
          fetch-tags: true
          fetch-depth: 0

      - name: Checkout upstream version
        if: ${{ steps.check-changes.outputs.changed == 'true' && matrix.build-from-upstream == 'true' }}
        working-directory: ${{ matrix.upstream-path }}
        run: |
          git checkout ${{ steps.check-changes.outputs.version }}

      - name: Build and push ${{ matrix.component }} image
        if: ${{ steps.check-changes.outputs.changed == 'true' }}
        uses: docker/build-push-action@0adf9959216b96bec444f325f1e493d4aa344497
        id: docker_build_release
        with:
          context: ${{ matrix.docker-context }}
          file: ${{ matrix.docker-context }}/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            quay.io/isovalent/${{ steps.check-changes.outputs.cee-image }}-ubi:${{ steps.check-changes.outputs.version }}
          build-args: |
            BASE_IMAGE=${{ matrix.base-image }}
            UPSTREAM_IMAGE=${{ steps.check-changes.outputs.repo }}:${{ steps.check-changes.outputs.version }}@${{ steps.check-changes.outputs.digest }}
            ${{ matrix.build-args }}
