name: Trigger build images external to isovalent/cilium

# Any change in triggers needs to be reflected in the concurrency group.
on:
  schedule:
    # Every day at 00:00
    - cron: "0 0 * * *"
  merge_group:
  push:
    branches:
      - main-ce
      - v1.[0-9]+-ce
    paths:
      - install/kubernetes/Makefile.values
  # Allow to run manually
  workflow_dispatch: {}

permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.event.after || github.event.merge_group && github.run_id }}

jobs:
  check-and-build:
    name: Trigger build images external workflow
    strategy:
      fail-fast: false
      matrix:
        include:
          - component: CERTGEN
            image-name: certgen-ubi-ci
            docker-context: enterprise/images/certgen
            dockerfile: enterprise/images/certgen/Dockerfile
            # renovate: datasource=docker
            base-image: registry.redhat.io/ubi9/ubi-micro:9.6@sha256:647c02b5b6d4760b019a468ff620ec53009d8453679bee3b7e5a676499edb1c3
            build-from-source: false

          - component: CILIUM_NODEINIT
            image-name: startup-script-ubi-ci
            docker-context: enterprise/images/startup-script
            dockerfile: enterprise/images/startup-script/Dockerfile
            # renovate: datasource=docker
            base-image: registry.redhat.io/ubi9/ubi-minimal:9.6@sha256:8d905a93f1392d4a8f7fb906bd49bf540290674b28d82de3536bb4d0898bf9d7
            build-from-source: false

          - component: CILIUM_ENVOY
            image-name: cilium-envoy-ubi-ci
            docker-context: enterprise/images/cilium-envoy
            dockerfile: enterprise/images/cilium-envoy/Dockerfile
            # renovate: datasource=docker
            base-image: registry.redhat.io/ubi9/ubi-minimal:9.6@sha256:8d905a93f1392d4a8f7fb906bd49bf540290674b28d82de3536bb4d0898bf9d7
            build-from-source: false

          - component: HUBBLE_UI_BACKEND
            image-name: hubble-ui-backend-ubi-ci
            docker-context: hubble-ui-backend/backend
            dockerfile: hubble-ui-backend/backend/Dockerfile
            # renovate: datasource=docker
            base-image: registry.redhat.io/ubi9/ubi-micro:9.6@sha256:647c02b5b6d4760b019a468ff620ec53009d8453679bee3b7e5a676499edb1c3
            build-from-source: true
            source-repo: isovalent/hubble-ui-enterprise
            source-path: hubble-ui-backend

          - component: HUBBLE_UI_FRONTEND
            image-name: hubble-ui-frontend-ubi-ci
            docker-context: hubble-ui-frontend
            dockerfile: hubble-ui-frontend/Dockerfile
            # renovate: datasource=docker
            base-image: quay.io/isovalent-dev/nginx-unprivileged-ubi:1754712783-48bbfc6@sha256:911d90b5ec8397b783a35cade1f6b4d7147bc812d1e4f4adb4cb62df90a74dac
            build-from-source: true
            source-repo: isovalent/hubble-ui-enterprise
            source-path: hubble-ui-frontend

          - component: KUBECTL
            image-name: kubectl-ubi-ci
            docker-context: enterprise/images/kubectl
            dockerfile: enterprise/images/kubectl/Dockerfile
            # renovate: datasource=docker
            base-image: registry.redhat.io/ubi9/ubi-minimal:9.6@sha256:8d905a93f1392d4a8f7fb906bd49bf540290674b28d82de3536bb4d0898bf9d7
            build-from-source: false

    uses: ./.github/workflows/enterprise-external-images.yaml
    secrets: inherit
    with:
      component: ${{ matrix.component }}
      image-name: ${{ matrix.image-name }}
      docker-context: ${{ matrix.docker-context }}
      dockerfile: ${{ matrix.dockerfile }}
      base-image: ${{ matrix.base-image }}
      build-from-source: ${{ matrix.build-from-source }}
      source-repo: ${{ matrix.source-repo }}
      source-path: ${{ matrix.source-path }}
