name: Enterprise External Image retagging

on:
  workflow_dispatch: {}
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+-*
  pull_request:
    # all external images are listed in install/kubernetes/Makefile.values
    # and are used in the install/kubernetes/cilium/values.yaml
    # file, so we only need to check for changes in the Makefile.values
    # file to trigger the workflow for PRs targeting v*-ce
    branches:
      - v[0-9]+.[0-9]+-ce
    paths:
      - install/kubernetes/Makefile.values

permissions:
  # To be able to access the repository with `actions/checkout`
  contents: read
  # Required to generate OIDC tokens for `sigstore/cosign-installer` authentication
  id-token: write

jobs:
  generate-variants:
    name: Generate Variants for retagging
    runs-on: ubuntu-24.04
    outputs:
      variants: ${{ steps.set-tag.outputs.variants }}
    steps:
      - name: Set Tag
        id: set-tag
        run: |
          if [[ "${{ github.event_name }}" == "push" ]]; then
            echo "variants=[\"preserve-tag\",\"retag-version\"]" >> $GITHUB_OUTPUT
          else
            echo "variants=[\"preserve-tag\"]" >> $GITHUB_OUTPUT
          fi

  retag-and-push:
    needs: generate-variants
    timeout-minutes: 45
    name: Retag and Push Images
    runs-on: ubuntu-24.04
    strategy:
      max-parallel: 4
      fail-fast: false
      matrix:
        variant: ${{ fromJson(needs.generate-variants.outputs.variants) }}
        image:
          - startup-script
          - cilium-envoy
          - busybox
          - spire-agent
          - spire-server
          - certgen
        include:
          - image: startup-script
            destination-repo: quay.io/isovalent/startup-script
            source-repo: quay.io/cilium/startup-script
            yq-path: nodeinit.image
          - image: cilium-envoy
            destination-repo: quay.io/isovalent/cilium-envoy
            source-repo: quay.io/cilium/cilium-envoy
            yq-path: envoy.image
          - image: busybox
            destination-repo: quay.io/isovalent/busybox
            source-repo: docker.io/library/busybox
            yq-path: authentication.mutual.spire.install.initImage
          - image: spire-agent
            destination-repo: quay.io/isovalent/spire-agent
            source-repo: ghcr.io/spiffe/spire-agent
            yq-path: authentication.mutual.spire.install.agent.image
          - image: spire-server
            destination-repo: quay.io/isovalent/spire-server
            source-repo: ghcr.io/spiffe/spire-server
            yq-path: authentication.mutual.spire.install.server.image
          - image: certgen
            destination-repo: quay.io/isovalent/certgen
            source-repo: quay.io/cilium/certgen
            yq-path: certgen.image

    steps:
      - name: Checkout main branch to access local actions
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          ref: ${{ github.event.repository.default_branch }}
          persist-credentials: false

      - name: Set Environment Variables
        uses: ./.github/actions/set-env-variables

      - name: Checkout Source Code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: Install Skopeo
        uses: warjiang/setup-skopeo@71776e03c10d767c04af8924fe5a67763f9b3d34 # v0.1.3

      - name: Login to quay.io
        run: skopeo login -u ${{ secrets.QUAY_USERNAME_RELEASE_USERNAME }} -p ${{ secrets.QUAY_PASSWORD_RELEASE_PASSWORD }} quay.io

      - name: Get Tag of Docker Image
        id: image-tag
        uses: mikefarah/yq@6251e95af8df3505def48c71f3119836701495d6 # v4.47.2
        with:
          cmd: yq eval '.${{ matrix.yq-path }}.tag' install/kubernetes/cilium/values.yaml

      - name: Get Digest of Docker Image
        id: image-digest
        uses: mikefarah/yq@6251e95af8df3505def48c71f3119836701495d6 # v4.47.2
        with:
          cmd: yq eval '.${{ matrix.yq-path }}.digest' install/kubernetes/cilium/values.yaml

      - name: Determine destination tags
        id: destination-tag
        run: |
          if [[ "${{ matrix.variant }}" == "preserve-tag" ]]; then
            DESTINATION_TAG=${{ steps.image-tag.outputs.result }}
          else
            DESTINATION_TAG=v$(cat VERSION)
          fi
          echo "retagging as ${{ matrix.destination-repo }}:${DESTINATION_TAG}"
          echo  "result=${DESTINATION_TAG}" >> $GITHUB_OUTPUT


      - name: Copy Image from Source to Target
        run: |
          skopeo copy --all --preserve-digests docker://${{ matrix.source-repo }}:${{ steps.image-tag.outputs.result }} \
            docker://${{ matrix.destination-repo }}:${{ steps.destination-tag.outputs.result }}

      - name: Login to quay.io
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME_RELEASE_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD_RELEASE_PASSWORD }}

      - name: Install Cosign
        uses: sigstore/cosign-installer@d7543c93d881b35a8faa02e8e3605f69b7a1ce62 # v3.10.0

      - name: Sign Container Image
        if: false # cosign signing is disabled for now
        run: cosign sign -y ${{ matrix.destination-repo }}@${{ steps.image-digest.outputs.result }}

      - name: Generate SBOM
        uses: anchore/sbom-action@f8bdd1d8ac5e901a77a92f111440fdb1b593736b # v0.20.6
        with:
          artifact-name: sbom_${{ matrix.image }}_${{ steps.destination-tag.outputs.result }}.spdx.json
          output-file: ./sbom_${{ matrix.image }}_${{ steps.destination-tag.outputs.result }}.spdx.json
          image: ${{ matrix.destination-repo }}:${{ steps.destination-tag.outputs.result }}
          upload-release-assets: false

      - name: Attach SBOM attestation to container image
        if: false # cosign signing is disabled for now
        run: |
          cosign attest -y --predicate sbom_${{ matrix.image }}_${{ steps.destination-tag.outputs.result }}.spdx.json \
            --type spdxjson ${{ matrix.destination-repo }}@${{ steps.image-digest.outputs.result }}

      - name: Image Release Digest
        shell: bash
        run: |
          mkdir -p image-digest/
          job_name=${{ matrix.image }}
          job_name_capital=${job_name^^}
          job_name_underscored=${job_name_capital//-/_}
          echo "${job_name_underscored}_DIGEST := \"${{ steps.image-digest.outputs.result }}\"" > image-digest/makefile-digest.txt
          echo "### ${{ matrix.image }}" > image-digest/${{ matrix.image }}.txt
          echo "" >> image-digest/${{ matrix.image }}.txt
          echo "\`quay.io/isovalent/${{ matrix.image }}:${{ steps.destination-tag.outputs.result }}@${{ steps.image-digest.outputs.result }}\`" >> image-digest/${{ matrix.image }}.txt
          echo "" >> image-digest/${{ matrix.image }}.txt

      # Upload artifact digests
      - name: Upload artifact digests
        if: ${{ matrix.variant == 'retag-version' }}
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: image-digest ${{ matrix.image }}
          path: image-digest

  image-digests:
    name: Display Digests
    runs-on: ubuntu-24.04
    if: ${{ github.event_name == 'push' }}
    needs: retag-and-push
    steps:
      - name: Getting image tag
        id: tag
        run: |
          echo tag=${GITHUB_REF##*/} >> $GITHUB_OUTPUT

      - name: Downloading Image Digests
        shell: bash
        run: |
          mkdir -p image-digest/

      - name: Download digests of all images built
        uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5.0.0
        with:
          path: image-digest/
          pattern: "*image-digest *"

      - name: Image Digests Output
        shell: bash
        run: |
          cd image-digest/
          echo "## Docker Manifests" > ../image-digest-output.txt
          echo "" >> ../image-digest-output.txt
          find -type f -regex ".*image-digest .*" -not -name "makefile-digest.txt" | sort | xargs -d '\n' cat >> ../image-digest-output.txt

      - name: Image Makefile Digests
        shell: bash
        run: |
          cd image-digest/
          echo "# File generated by .github/workflows/build-images-releases.yaml; DO NOT EDIT." > ../Makefile.digests
          echo "# Copyright $(date +'%Y') Authors of Cilium" >> ../Makefile.digests
          echo "# SPDX-License-Identifier: Apache-2.0" >> ../Makefile.digests
          echo "" >> ../Makefile.digests
          # shellcheck disable=SC2016
          find -type f  -name "makefile-digest.txt" | sort | xargs -d '\n' awk '{print "export " $0}' >> ../Makefile.digests

      # Upload artifact digests
      - name: Upload artifact digests
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: image-digest-output.txt-${{ steps.tag.outputs.tag }}
          path: image-digest-output.txt

      # Upload artifact digests
      - name: Upload artifact digests
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: Makefile.digests-${{ steps.tag.outputs.tag }}
          path: Makefile.digests
