name: Build images external to isovalent/cilium

# Any change in triggers needs to be reflected in the concurrency group.
on:
  push:
    branches:
      - main-ce

permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.event.after || github.event.merge_group && github.run_id }}

jobs:
  check_changes:
    name: Deduce required images from changes
    runs-on: ubuntu-24.04
    outputs:
      certgen: ${{ steps.certgen-changes.outputs.changed }}
      certgen_version: ${{ steps.certgen-changes.outputs.version }}
      startup: ${{ steps.startup-changes.outputs.changed }}
      startup_version: ${{ steps.startup-changes.outputs.version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ github.event.push.after }}
          persist-credentials: false
          fetch-depth: 0

      - name: Check certgen code changes
        id: certgen-changes
        run: |
          if git diff --unified=0 ${{ github.event.push.before }} -- install/kubernetes/Makefile.values | grep CERTGEN ; then
            echo "changed=true" >> $GITHUB_OUTPUT
            echo "version=$(cat install/kubernetes/Makefile.values| grep CERTGEN_VERSION | awk -F '=' '{print $2}')" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Check startup code changes
        id: startup-changes
        run: |
          if git diff --unified=0 ${{ github.event.push.before }} -- install/kubernetes/Makefile.values | grep CILIUM_NODEINIT ; then
            echo "changed=true" >> $GITHUB_OUTPUT
            echo "version=$(cat install/kubernetes/Makefile.values| grep CILIUM_NODEINIT_VERSION | awk -F '=' '{print $2}')" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

  build-certgen-image:
    needs: check_changes
    runs-on: ubuntu-24.04
    name: Build isovalent/certgen images
    environment: release
    if: ${{ needs.check_changes.outputs.certgen == 'true' }}
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f7ce87c1d6bead3e36075b2ce75da1f6cc28aaca

      - name: Login to quay.io
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME_RELEASE_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD_RELEASE_PASSWORD }}

      - name: Login to registry.redhat.io for pulling images
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567
        with:
          registry: registry.redhat.io
          username: ${{ secrets.REDHAT_USERNAME_CI }}
          password: ${{ secrets.REDHAT_PASSWORD_CI }}

      - name: Checkout Source Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          repository: cilium/certgen
          persist-credentials: false
          path: certgen
          fetch-tags: true
          fetch-depth: 0

      - name: Getting image tag
        id: tag
        run: |
          cd certgen
          tag=${{ needs.check_changes.outputs.certgen_version }}
          echo "tag=$tag" >> $GITHUB_OUTPUT # get latest tag on main
          git checkout $tag

      - name: Release Build isovalent/certgen
        uses: docker/build-push-action@0adf9959216b96bec444f325f1e493d4aa344497
        id: docker_build_release
        with:
          context: certgen
          file: certgen/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            quay.io/isovalent/certgen-ubi:${{ steps.tag.outputs.tag }}
          build-args: |
            BASE_IMAGE=registry.redhat.io/ubi9/ubi-micro@sha256:d115f8aad9c4ae7ee21ae75bbcb3dc2c5dbf9b57bf6dad6dcb5aac5c02003bde

  build-startup-image:
    needs: check_changes
    runs-on: ubuntu-24.04
    name: Build isovalent/startup-script images
    environment: release
    if: ${{ needs.check_changes.outputs.startup == 'true' }}
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f7ce87c1d6bead3e36075b2ce75da1f6cc28aaca

      - name: Login to quay.io
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME_RELEASE_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD_RELEASE_PASSWORD }}

      - name: Login to registry.redhat.io for pulling images
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567
        with:
          registry: registry.redhat.io
          username: ${{ secrets.REDHAT_USERNAME_CI }}
          password: ${{ secrets.REDHAT_PASSWORD_CI }}

      - name: Getting image tag
        id: tag
        run: |
          tag=${{ needs.check_changes.outputs.startup_version }}
          echo "tag=$tag" >> $GITHUB_OUTPUT # get latest tag on main

      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ github.event.push.after }}

      - name: Release Build isovalent/startup-script
        uses: docker/build-push-action@0adf9959216b96bec444f325f1e493d4aa344497
        id: docker_build_release
        with:
          context: enterprise/images/startup-script
          file: enterprise/images/startup-script/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            quay.io/isovalent/startup-script-ubi:${{ steps.tag.outputs.tag }}
          build-args: |
            BASE_IMAGE=registry.redhat.io/ubi9/ubi-minimal@sha256:14f14e03d68f7fd5f2b18a13478b6b127c341b346c86b6e0b886ed2b7573b8e0
            STARTUP_VERSION=c54c7edeab7fde4da68e59acd319ab24af242c3f
