name: EnterpriseKind

# Any change in triggers needs to be reflected in the concurrency group.
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths-ignore:
      - 'Documentation/**'
      - 'test/**'

permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.event.after }}
  cancel-in-progress: true

env:
  helm_chart_repo: oci://quay.io/isovalent-charts-dev/cilium
  kind_config: .github/kind-config-enterprise-dual.yaml
  # renovate: datasource=github-releases depName=yannh/kubeconform
  kubeconform_version: v0.7.0

jobs:
  installation-and-connectivity:
    name: Installation and connectivity
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    steps:
      - name: Collect Workflow Telemetry
        uses: catchpoint/workflow-telemetry-action@94c3c3d9567a0205de6da68a76c428ce4e769af1 # v2.0.0
        with:
          comment_on_pr: false

      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          # checkout pull request head ref so that print-chart-version.sh prints the correct chart version.
          ref: ${{ github.event.pull_request.head.ref }}
          # required for git describe
          fetch-depth: 0

      - name: Set Environment Variables
        uses: ./.github/actions/set-env-variables

      - name: Set up job variables
        id: vars
        run: |
          version=$(bash contrib/scripts/print-chart-version.sh)
          echo "version=${version}" >> $GITHUB_OUTPUT
          echo ${version}

          SHA="${{ github.event.pull_request.head.sha }}"

          echo sha=${SHA} >> $GITHUB_OUTPUT

      - name: Create kind cluster
        uses: helm/kind-action@92086f6be054225fa813e0a4b13787fc9088faab # v1.13.0
        with:
          version: ${{ env.KIND_VERSION }}
          node_image: ${{ env.KIND_K8S_IMAGE }}
          kubectl_version: ${{ env.KIND_K8S_VERSION }}
          config: ${{ env.kind_config }}
          wait: 0 # The control-plane never becomes ready, since no CNI is present

      - name: Install Cilium CLI
        uses: cilium/cilium-cli@eb32911890466ddec93da63cf83f5bcb2ae23e26 # v0.19.0
        with:
          skip-build: ${{ env.CILIUM_CLI_SKIP_BUILD }}
          image-repo: ${{ env.CILIUM_CLI_IMAGE_REPO }}
          image-tag: ${{ steps.vars.outputs.sha }}
          repository: ${{ env.CILIUM_CLI_RELEASE_REPO }}
          release-version: ${{ env.CILIUM_CLI_VERSION }}

      - name: Install kubeconform
        run: |
          wget -qO- https://github.com/yannh/kubeconform/releases/download/${{ env.kubeconform_version }}/kubeconform-linux-amd64.tar.gz | tar xvz -C /tmp
          sudo mv /tmp/kubeconform /usr/local/bin

      - name: Lint FQDN Proxy Helm chart
        run: |
          cd enterprise/fqdn-proxy/installation
          ./test.sh

      - name: Wait for Helm dev chart to be available
        timeout-minutes: 30
        shell: bash
        run: |
          echo ${{ secrets.QUAY_CHARTS_DEV_PASSWORD }} | helm registry login quay.io -u ${{ secrets.QUAY_CHARTS_DEV_USERNAME }} --password-stdin
          until helm pull ${{ env.helm_chart_repo }} --version ${{ steps.vars.outputs.version }}; do sleep 30s; done

      - name: Install Cilium
        run: |
          helm install -n kube-system cilium ${{ env.helm_chart_repo }} \
            --version ${{ steps.vars.outputs.version }} \
            --set-string extraConfig.external-dns-proxy=true \
            --set=enterprise.featureGate.strict=true \
            --set='enterprise.featureGate.approved={DatapathIPModeDualStack}' \
            --set=ipv6.enabled=true
          kubectl rollout status -n kube-system ds/cilium --watch

      - name: Install FQDN proxy
        run: |
          helm install -n kube-system cilium-dnsproxy ./enterprise/fqdn-proxy/installation \
            --set image.repository=quay.io/${{ env.QUAY_ORGANIZATION_DEV }}/cilium-dnsproxy-ci \
            --set image.tag=${{ steps.vars.outputs.sha }} \
            --set metrics.enabled=true \
            --set debug=true
          kubectl rollout status -n kube-system ds/cilium-dnsproxy --watch

      - name: Run enterprise tests
        run: |
          cilium version
          cilium connectivity test \
            --log-code-owners --code-owners=${CILIUM_CLI_CODE_OWNERS_PATHS} \
            --exclude-code-owners=${CILIUM_CLI_EXCLUDE_OWNERS} \
            --debug --collect-sysdump-on-failure

      - name: Run common post steps
        if: ${{ always() }}
        uses: ./.github/actions/post-logic
        with:
          artifacts_suffix: "enterprise-kind"
          job_status: "${{ job.status }}"
