name: Enterprise container vulnerability scan
on:
  schedule:
    - cron: "0 4 * * 1-5"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  container-scan:
    name: scan-container
    runs-on: ubuntu-24.04
    continue-on-error: true
    outputs:
      scan_result: ${{ steps.failure-flag.outputs.scan_result }}
    strategy:
      matrix:
        image: [cilium, clustermesh-apiserver, docker-plugin, hubble-relay, operator-generic, operator-aws,
                operator-alibabacloud, operator-azure]
        # We don't scan Enterprise images for maintained OSS branches, because
        # OSS syncs don't happen frequently enough to give an accurate picture
        # of the dependencies used by Cilium. We only scan the Enterprise images
        # for the oldest maintained Enterprise version, which does not receive
        # OSS dependency updates.
        branch: [v1.16, v1.17, v1.18]
        include:
          - image: cilium
            branch: v1.17-ce
          - image: cilium
            branch: v1.18-ce
    steps:
      - name: Checkout latest VEX data
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          sparse-checkout: |
            .github/enterprise/.openvex.json
            .github/enterprise/.grype.yaml
          sparse-checkout-cone-mode: false
          path: vex
      - name: Download Grype
        id: grype
        uses: anchore/scan-action/download-grype@3aaf50d765cfcceafa51d322ccb790e40f6cd8c5 # v7.2.0
      - name: Scan image
        id: scan
        run: |
          # shellcheck disable=SC2193
          if [[ "${{ matrix.branch }}" == *"-ce" ]]; then
            org="isovalent-dev"
          else
            org="cilium"
          fi
          ${{ steps.grype.outputs.cmd }} quay.io/"$org"/${{ matrix.image }}-ci:${{ matrix.branch }} \
            --output json=results.json --output table=results.txt --fail-on medium \
            --vex vex/.github/enterprise/.openvex.json \
            --config vex/.github/enterprise/.grype.yaml
      - name: Set failure flag if necessary
        id: failure-flag
        if: ${{ failure() }}
        run: echo "scan_result=failure" >> $GITHUB_OUTPUT
      - name: Extract scan results
        if: ${{ failure() }}
        run: |
          jq '[.matches[]
              | select(.vulnerability.severity == "Medium" or .vulnerability.severity == "High" or .vulnerability.severity == "Critical")
              | {id: .vulnerability.id,
                image: "${{ matrix.image }}-${{ matrix.branch }}",
                severity: .vulnerability.severity,
                name: .artifact.name,
                version: .artifact.version,
                purl: .artifact.purl,
                paths: [.artifact.locations[].path]}]' \
              results.json > ${{ matrix.image }}-${{ matrix.branch }}.json
      - name: Output scan results
        if: ${{ failure() }}
        run: |
          cat ${{ matrix.image }}-${{ matrix.branch }}.json
          exit 1
      - name: Upload result summary
        if: ${{ failure() }}
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: ${{ matrix.image }}-${{ matrix.branch }}.json
          path: ${{ matrix.image }}-${{ matrix.branch }}.json
          if-no-files-found: ignore

  check-scan-results:
    # Fails the entire workflow if any scanning job run has failed, despite the
    # use of `continue-on-error` in the previous job.
    name: Check Scan Results
    runs-on: ubuntu-24.04
    needs: container-scan
    steps:
      - name: Check if any scans failed
        run: |
          if [ "${{ needs.container-scan.outputs.scan_result }}" = "failure" ]; then
            echo "One or more container scans failed. Check the uploaded artifacts to" \
            "view the CVEs causing the failures."
            exit 1
          else
            echo "All container scans succeeded."
          fi

  summarize-scan-results:
    name: Summarize Scan Results
    runs-on: ubuntu-24.04
    needs: container-scan
    steps:
      - name: Download all scan results
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6
        with:
          path: scan-results
      - name: Combine JSON results
        run: |
          find scan-results -type f -name '*.json' -exec cat {} + | jq -s '.' > combined-results.json
      - name: Summarize CVE Data
        id: summarize
        run: |
          cat combined-results.json | jq 'reduce (.[][]) as $item ({};
            .[$item.id].name += [$item.name] |
            .[$item.id].images += [$item.image] |
            .[$item.id].severity = $item.severity |
            .[$item.id].link = "https://www.cve.org/CVERecord?id=" + $item.id
          ) | to_entries | map({
            id: .key,
            name: (.value.name | unique),
            severity: .value.severity,
            affected_images: (.value.images | unique),
            link: .value.link
          }) | sort_by(.severity) | reverse' > summary.json
      - name: Output summary
        run: |
          cat summary.json
      - name: Upload summary
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5
        with:
          name: summary.json
          path: summary.json
