name: Enterprise Image Release Build

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
      - v[0-9]+.[0-9]+.[0-9]+-*

permissions:
  # To be able to access the repository with `actions/checkout`
  contents: read
  # Required to generate OIDC tokens for `sigstore/cosign-installer` authentication
  id-token: write

jobs:
  build-and-push-external-images:
    timeout-minutes: 45
    name: Build and push external images
    environment: release
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        include:
          - component: CERTGEN
            image-name: certgen-ubi
            docker-context: enterprise/images/certgen
            dockerfile: enterprise/images/certgen/Dockerfile
            # renovate: datasource=docker
            base-image: registry.redhat.io/ubi9/ubi-micro:9.6@sha256:647c02b5b6d4760b019a468ff620ec53009d8453679bee3b7e5a676499edb1c3
            build-from-source: false

          - component: CILIUM_NODEINIT
            image-name: startup-script-ubi
            docker-context: enterprise/images/startup-script
            dockerfile: enterprise/images/startup-script/Dockerfile
            # renovate: datasource=docker
            base-image: registry.redhat.io/ubi9/ubi-minimal:9.6@sha256:8d905a93f1392d4a8f7fb906bd49bf540290674b28d82de3536bb4d0898bf9d7
            build-from-source: false

          - component: CILIUM_ENVOY
            image-name: cilium-envoy-ubi
            docker-context: enterprise/images/cilium-envoy
            dockerfile: enterprise/images/cilium-envoy/Dockerfile
            # renovate: datasource=docker
            base-image: registry.redhat.io/ubi9/ubi-minimal:9.6@sha256:8d905a93f1392d4a8f7fb906bd49bf540290674b28d82de3536bb4d0898bf9d7
            build-from-source: false

          - component: HUBBLE_UI_BACKEND
            image-name: hubble-ui-backend-ubi
            docker-context: hubble-ui-backend/backend
            dockerfile: hubble-ui-backend/backend/Dockerfile
            # renovate: datasource=docker
            base-image: registry.redhat.io/ubi9/ubi-minimal:9.6@sha256:8d905a93f1392d4a8f7fb906bd49bf540290674b28d82de3536bb4d0898bf9d7
            build-from-source: true
            source-repo: isovalent/hubble-ui-enterprise
            directory: hubble-ui-backend

          - component: HUBBLE_UI_FRONTEND
            image-name: hubble-ui-frontend-ubi
            docker-context: hubble-ui-frontend
            dockerfile: hubble-ui-frontend/Dockerfile
            # TODO: Renovate won't help here if the tag is pinning a single version
            # renovate: datasource=docker
            base-image: quay.io/isovalent-dev/nginx-unprivileged-ubi:1754712783-48bbfc6@sha256:911d90b5ec8397b783a35cade1f6b4d7147bc812d1e4f4adb4cb62df90a74dac
            build-from-source: true
            source-repo: isovalent/hubble-ui-enterprise
            directory: hubble-ui-frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          ref: ${{ github.event.push.after }}
          persist-credentials: false
          fetch-depth: 0

      - name: Get and check version
        id: version
        run: |
          tag=${GITHUB_REF##*/}
          echo version=$tag >> $GITHUB_OUTPUT
          upstream_version=$(cat install/kubernetes/Makefile.values | grep ${{ matrix.component }}_VERSION | awk -F '=' '{print $2}')
          echo "upstream_version=${upstream_version}" >> $GITHUB_OUTPUT
          echo "upstream_repo=$(cat install/kubernetes/Makefile.values | grep ${{ matrix.component }}_REPO | awk -F '=' '{print $2}')" >> $GITHUB_OUTPUT
          echo "upstream_digest=$(cat install/kubernetes/Makefile.values | grep ${{ matrix.component }}_DIGEST | awk -F '=' '{print $2}')" >> $GITHUB_OUTPUT
          # Don't build if the image reference does not exist in Makefile.values
          # This is a workaround as etcd-operator, for instance, should not be part of the matrix in the -trigger workflow for newer releases
          if [[ -z "${upstream_version}" ]]; then
             echo "No version available for ${{ matrix.component }} in install/kubernetes/Makefile.values. Build skipped."
             echo "rebuild=false" >> $GITHUB_OUTPUT
          elif docker manifest inspect quay.io/isovalent/${{ matrix.image-name }}:${version} >/dev/null; then
            echo "Image already exists! Build skipped."
            echo "rebuild=false" >> $GITHUB_OUTPUT
          else
            echo "rebuild=true" >> $GITHUB_OUTPUT
          fi

      - name: Set up Docker Buildx
        if: ${{ steps.version.outputs.rebuild == 'true' }}
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1

      - name: Login to quay.io
        if: ${{ steps.version.outputs.rebuild == 'true' }}
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME_RELEASE_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD_RELEASE_PASSWORD }}

      - name: Login to registry.redhat.io for pulling UBI images
        if: ${{ steps.version.outputs.rebuild == 'true' }}
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          registry: registry.redhat.io
          username: ${{ secrets.REDHAT_USERNAME_CI }}
          password: ${{ secrets.REDHAT_PASSWORD_CI }}

      - name: Get GitHub Token [read-only]
        if: ${{ matrix.build-from-source == true }}
        id: gh-ro-token
        uses: getsentry/action-github-app-token@d4b5da6c5e37703f8c3b3e43abb5705b46e159cc # v3.0.0
        with:
          app_id: ${{ secrets.ISOVALENT_READONLY_GH_APP_ID }}
          private_key: ${{ secrets.ISOVALENT_READONLY_GH_APP_PEM }}

      - name: Checkout source repo
        if: ${{ matrix.build-from-source == true }}
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          repository: ${{ matrix.source-repo }}
          token: ${{ steps.gh-ro-token.outputs.token }}
          persist-credentials: false
          path: ${{ matrix.directory }}
          fetch-tags: true
          fetch-depth: 0

      - name: Checkout source version
        if: ${{ matrix.build-from-source == true }}
        working-directory: ${{ matrix.directory }}
        run: |
            git checkout ${{ steps.version.outputs.upstream_version }}

      - name: Build and push ${{ matrix.component }} image
        if: ${{ steps.version.outputs.rebuild == 'true' }}
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          context: ${{ matrix.docker-context }}
          file: ${{ matrix.dockerfile }}
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            quay.io/isovalent/${{ matrix.image-name }}:${{ steps.version.outputs.version }}
          build-args: |
            # renovate: datasource=docker
            BASE_IMAGE=${{ matrix.base-image }}
            UPSTREAM_VERSION=${{ steps.version.outputs.upstream_version }}
            UPSTREAM_IMAGE=${{ steps.version.outputs.upstream_repo }}:${{ steps.version.outputs.upstream_version }}@${{ steps.version.outputs.upstream_digest }}
            VERSION=${{ steps.version.outputs.version }}

      - name: Release ${{ matrix.component }} digest
        id: docker_digest
        shell: bash
        run: |
          digest=$(images/scripts/get-image-digest.sh quay.io/isovalent/${{ matrix.image-name }}:${{ steps.version.outputs.version }})
          echo digest=${digest} >> $GITHUB_OUTPUT

      - name: Install Cosign
        if: ${{ steps.version.outputs.rebuild == 'true' }}
        uses: sigstore/cosign-installer@faadad0cce49287aee09b3a48701e75088a2c6ad # v4.0.0

      - name: Sign Container Images
        if: ${{ steps.version.outputs.rebuild == 'true' }}
        run: |
          cosign sign -y quay.io/isovalent/${{ matrix.image-name }}:${{ steps.version.outputs.version }}@${{ steps.docker_digest.outputs.digest }}

      - name: Generate SBOM
        if: ${{ steps.version.outputs.rebuild == 'true' }}
        uses: anchore/sbom-action@8e94d75ddd33f69f691467e42275782e4bfefe84 # v0.20.9
        with:
          artifact-name: sbom_${{ matrix.image-name }}_${{ steps.version.outputs.version }}.spdx.json
          output-file: ./sbom_${{ matrix.image-name }}_${{ steps.version.outputs.version }}.spdx.json
          image: quay.io/isovalent/${{ matrix.image-name }}:${{ steps.version.outputs.version }}
          upload-release-assets: false

      - name: Attach SBOM attestation to container image
        if: ${{ steps.version.outputs.rebuild == 'true' }}
        run: |
          cosign attest -y --predicate sbom_${{ matrix.image-name }}_${{ steps.version.outputs.version }}.spdx.json --type spdxjson quay.io/isovalent/${{ matrix.image-name }}:${{ steps.version.outputs.version }}

      - name: Image Release Digest
        shell: bash
        run: |
          mkdir -p image-digest/
          echo "### ${{ matrix.image-name }}" > image-digest/${{ matrix.image-name }}.txt
          echo "" >> image-digest/${{ matrix.image-name }}.txt
          echo "\`quay.io/isovalent/${{ matrix.image-name }}:${{ steps.version.outputs.version }}@${{ steps.docker_digest.outputs.digest }}\`" >> image-digest/${{ matrix.image-name }}.txt
          echo "" >> image-digest/${{ matrix.image-name }}.txt

      # Upload artifact digests
      - name: Upload artifact digests
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: image-digest ${{ matrix.image-name }}
          path: image-digest

  build-and-push:
    timeout-minutes: 45
    name: Build and Push Images
    environment: release
    runs-on: ubuntu-24.04
    # This needs to happen sequentially as the cilium-envoy image is used for building the image of the Cilium agent
    needs: build-and-push-external-images
    strategy:
      matrix:
        include:
          - name: cilium
            dockerfile: ./enterprise/images/cilium/Dockerfile
            # renovate: datasource=docker
            base_image: quay.io/isovalent-dev/cilium-runtime-ubi:0b93fa268c14630391e3eafd244040465dbb2be2
            postfix: ubi
            image_name: cilium

          - name: operator
            dockerfile: ./enterprise/images/operator/Dockerfile
            # renovate: datasource=docker
            base_image: registry.redhat.io/ubi9/ubi-micro:9.6@sha256:647c02b5b6d4760b019a468ff620ec53009d8453679bee3b7e5a676499edb1c3
            postfix: ubi
            image_name: operator-generic

          - name: hubble-relay
            dockerfile: ./enterprise/images/hubble-relay/Dockerfile
            # renovate: datasource=docker
            base_image: registry.redhat.io/ubi9/ubi-micro:9.6@sha256:647c02b5b6d4760b019a468ff620ec53009d8453679bee3b7e5a676499edb1c3
            postfix: ubi
            image_name: hubble-relay

          - name: clustermesh-apiserver
            dockerfile: ./enterprise/images/clustermesh-apiserver/Dockerfile
            # renovate: datasource=docker
            base_image: registry.redhat.io/ubi9/ubi-micro:9.6@sha256:647c02b5b6d4760b019a468ff620ec53009d8453679bee3b7e5a676499edb1c3
            postfix: ubi
            image_name: clustermesh-apiserver

    steps:
      - name: Checkout main branch to access local actions
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          ref: ${{ github.event.repository.default_branch }}
          persist-credentials: false

      - name: Cleanup Disk space in runner
        uses: ./.github/actions/disk-cleanup

      - name: Set Environment Variables
        uses: ./.github/actions/set-env-variables

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1

      - name: Login to quay.io
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME_RELEASE_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD_RELEASE_PASSWORD }}

      - name: Login to registry.redhat.io for pull of UBI images
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          registry: registry.redhat.io
          username: ${{ secrets.REDHAT_USERNAME_CI }}
          password: ${{ secrets.REDHAT_PASSWORD_CI }}

      - name: Getting image tag
        id: tag
        run: |
          tag=${GITHUB_REF##*/}
          echo tag=$tag >> $GITHUB_OUTPUT
          echo image_tag=quay.io/${{ env.QUAY_ORGANIZATION }}/${{ matrix.image_name }}-${{ matrix.postfix }}:$tag >> $GITHUB_OUTPUT

      - name: Checkout Source Code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: Release Build ${{ matrix.name }} UBI based
        id: docker_build_release_ubi
        shell: bash
        working-directory: ./enterprise/images
        run: |
          IMAGE_TAG=${{ steps.tag.outputs.tag }} \
          SUFFIX="" \
          REGISTRIES=quay.io/${{ env.QUAY_ORGANIZATION }} \
          PUSH=true \
          RUNTIME_IMAGE=${{ matrix.base_image }} \
          UBI_IMAGE=${{ matrix.base_image }} \
          OPERATOR_VARIANT=${{ matrix.image_name }} \
          PLATFORMS=linux/amd64,linux/arm64 \
          EXTRA_ARGS="--provenance=false" \
          make ${{ matrix.name }}-image

      - name: Release ${{ matrix.name }} digest
        id: docker_digest
        shell: bash
        run: |
          digest=$(images/scripts/get-image-digest.sh "${{ steps.tag.outputs.image_tag }}")
          echo digest=${digest} >> $GITHUB_OUTPUT

      - name: Install Cosign
        uses: sigstore/cosign-installer@faadad0cce49287aee09b3a48701e75088a2c6ad # v4.0.0

      - name: Sign Container Images
        run: |
          cosign sign -y ${{ steps.tag.outputs.image_tag }}@${{ steps.docker_digest.outputs.digest }}

      - name: Generate SBOM
        uses: anchore/sbom-action@8e94d75ddd33f69f691467e42275782e4bfefe84 # v0.20.9
        with:
          artifact-name: sbom_${{ matrix.name }}_${{ matrix.postfix }}_${{ steps.tag.outputs.tag }}.spdx.json
          output-file: ./sbom_${{ matrix.name }}_${{ matrix.postfix }}_${{ steps.tag.outputs.tag }}.spdx.json
          image: ${{ steps.tag.outputs.image_tag }}
          upload-release-assets: false

      - name: Attach SBOM attestation to container image
        run: |
          cosign attest -y --predicate sbom_${{ matrix.name }}_${{ matrix.postfix }}_${{ steps.tag.outputs.tag }}.spdx.json --type spdxjson ${{ steps.tag.outputs.image_tag }}

      - name: Image Release Digest
        shell: bash
        run: |
          mkdir -p image-digest/
          job_name=${{ matrix.name }}
          job_name_capital=${job_name^^}
          job_name_underscored=${job_name_capital//-/_}
          echo "${job_name_underscored}_DIGEST := \"${{ steps.docker_digest.outputs.digest }}\"" > image-digest/makefile-digest.txt

          echo "### ${{ matrix.name }}" > image-digest/${{ matrix.name }}.txt
          echo "" >> image-digest/${{ matrix.name }}.txt
          echo "\`${{ steps.tag.outputs.image_tag }}@${{ steps.docker_digest.outputs.digest }}\`" >> image-digest/${{ matrix.name }}.txt
          echo "" >> image-digest/${{ matrix.name }}.txt

      # Upload artifact digests
      - name: Upload artifact digests
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: image-digest ${{ matrix.name }}-${{ matrix.postfix }}
          path: image-digest


  build-and-push-clife:
    timeout-minutes: 45
    name: Build and Push OLM Images
    environment: release
    runs-on: ubuntu-24.04
    needs: build-and-push

    steps:
      - name: Checkout main branch to access local actions
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          ref: ${{ github.event.repository.default_branch }}
          persist-credentials: false

      - name: Cleanup Disk space in runner
        uses: ./.github/actions/disk-cleanup

      - name: Set Environment Variables
        uses: ./.github/actions/set-env-variables

      - name: Setup go
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
        with:
          cache: false
          # renovate: datasource=golang-version depName=go
          go-version: 1.25.4

      - name: Getting image tag
        id: tag
        run: |
          tag=${GITHUB_REF##*/}
          echo tag=$tag >> $GITHUB_OUTPUT
          echo image_tag_base=quay.io/${{ env.QUAY_ORGANIZATION }}/clife >> $GITHUB_OUTPUT
          echo image_tag=quay.io/${{ env.QUAY_ORGANIZATION }}/clife:$tag >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1

      - name: Login to quay.io
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME_RELEASE_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD_RELEASE_PASSWORD }}

      - name: Login to registry.redhat.io for pull of UBI images
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          registry: registry.redhat.io
          username: ${{ secrets.REDHAT_USERNAME_CI }}
          password: ${{ secrets.REDHAT_PASSWORD_CI }}

      - name: Checkout Source Code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: CLife Build and Push
        id: docker_build_clife
        shell: bash
        env:
          IMG: "${{ steps.tag.outputs.image_tag }}"
          CL_TAG: "${{ steps.tag.outputs.tag }}"
          CL_REGISTRY: "quay.io/${{ env.QUAY_ORGANIZATION }}"
          CL_IS_CI: false
        working-directory: ./enterprise/olm
        run: |
          make docker-buildx VERSION=${{ steps.tag.outputs.tag }}

      - name: OLM Bundle Build and Push
        working-directory: ./enterprise/olm
        env:
          CL_TAG: "${{ steps.tag.outputs.tag }}"
          CL_REGISTRY: "quay.io/${{ env.QUAY_ORGANIZATION }}"
          CL_IS_CI: false
          VERSION: "${{ steps.tag.outputs.tag }}"
          IMG: "${{ steps.tag.outputs.image_tag }}"
          IMAGE_TAG_BASE: "${{ steps.tag.outputs.image_tag_base }}"
        run: |
          VERSION="${VERSION#v}"
          make bundle
          make bundle-build
          make bundle-push

      - name: Add bundle image to catalog and publish
        working-directory: ./enterprise/olm
        env:
          # renovate: datasource=github-releases depName=mikefarah/yq
          yq_version: 4.48.2
          # renovate: datasource=github-releases depName=operator-framework/operator-registry
          opm_version: 1.61.0
          VERSION: "${{ steps.tag.outputs.tag }}"
          CATALOG_TAG: "1.0.0"
          IMAGE_TAG_BASE: "${{ steps.tag.outputs.image_tag_base }}"
        run: |
          VERSION="${VERSION#v}"
          channel="${VERSION}"
          # separate channels per minor version
          channel=$(cut -d '.' -f 1,2 <<< "${channel}")
          if [[ ${VERSION} =~ "beta" ]]; then
            channel="${channel}-beta"
          fi
          make catalog-dev-build CHANNEL=${channel} DEFAULT_CHANNEL="1.17"
          make catalog-dev-push

      - name: Clife digests
        id: clife_docker_digests
        shell: bash
        run: |
          digest=$(images/scripts/get-image-digest.sh "${{ steps.tag.outputs.image_tag }}")
          echo clife=${digest} >> $GITHUB_OUTPUT
          digest=$(images/scripts/get-image-digest.sh "${{ steps.tag.outputs.image_tag_base }}-bundle:${{ steps.tag.outputs.tag }}")
          echo bundle=${digest} >> $GITHUB_OUTPUT
          digest=$(images/scripts/get-image-digest.sh "${{ steps.tag.outputs.image_tag_base }}-catalog:1.0.0")
          echo catalog=${digest} >> $GITHUB_OUTPUT

      - name: Install Cosign
        uses: sigstore/cosign-installer@faadad0cce49287aee09b3a48701e75088a2c6ad # v4.0.0

      - name: Sign Container Images
        run: |
          cosign sign -y ${{ steps.tag.outputs.image_tag }}@${{ steps.clife_docker_digests.outputs.clife }}
          cosign sign -y ${{ steps.tag.outputs.image_tag_base }}-bundle:${{ steps.tag.outputs.tag }}@${{ steps.clife_docker_digests.outputs.bundle }}
          cosign sign -y ${{ steps.tag.outputs.image_tag_base }}-catalog:1.0.0@${{ steps.clife_docker_digests.outputs.catalog }}

      - name: Generate SBOM for CLife
        uses: anchore/sbom-action@8e94d75ddd33f69f691467e42275782e4bfefe84 # v0.20.9
        with:
          artifact-name: sbom_clife_${{ steps.tag.outputs.tag }}.spdx.json
          output-file: ./sbom_clife_${{ steps.tag.outputs.tag }}.spdx.json
          image: ${{ steps.tag.outputs.image_tag }}
          upload-release-assets: false

      - name: Attach SBOM attestation to CLife container image
        run: |
          cosign attest -y --predicate sbom_clife_${{ steps.tag.outputs.tag }}.spdx.json --type spdxjson ${{ steps.tag.outputs.image_tag }}

      - name: Generate SBOM for the bundle
        uses: anchore/sbom-action@8e94d75ddd33f69f691467e42275782e4bfefe84 # v0.20.9
        with:
          artifact-name: sbom_clife_bundle_${{ steps.tag.outputs.tag }}.spdx.json
          output-file: ./sbom_clife_bundle_${{ steps.tag.outputs.tag }}.spdx.json
          image: "${{ steps.tag.outputs.image_tag_base }}-bundle:${{ steps.tag.outputs.tag }}"
          upload-release-assets: false

      - name: Attach SBOM attestation to the bundle container image
        run: |
          cosign attest -y --predicate sbom_clife_bundle_${{ steps.tag.outputs.tag }}.spdx.json --type spdxjson ${{ steps.tag.outputs.image_tag_base }}-bundle:${{ steps.tag.outputs.tag }}

      - name: Generate SBOM for the catalog
        uses: anchore/sbom-action@8e94d75ddd33f69f691467e42275782e4bfefe84 # v0.20.9
        with:
          artifact-name: sbom_clife_catalog_${{ steps.tag.outputs.tag }}.spdx.json
          output-file: ./sbom_clife_catalog_${{ steps.tag.outputs.tag }}.spdx.json
          image: "${{ steps.tag.outputs.image_tag_base }}-catalog:1.0.0"
          upload-release-assets: false

      - name: Attach SBOM attestation to the catalog container image
        run: |
          cosign attest -y --predicate sbom_clife_catalog_${{ steps.tag.outputs.tag }}.spdx.json --type spdxjson ${{ steps.tag.outputs.image_tag_base }}-catalog:1.0.0

      - name: Image Release Digests
        shell: bash
        run: |
          mkdir -p image-digest/
          echo "### clife" > image-digest/clife.txt
          echo "" >> image-digest/clife.txt
          echo "\`${{ steps.tag.outputs.image_tag }}@${{ steps.clife_docker_digests.outputs.clife }}\`" >> image-digest/clife.txt
          echo "" >> image-digest/clife.txt

          echo "### clife bundle" > image-digest/clife-bundle.txt
          echo "" >> image-digest/clife-bundle.txt
          echo "\`${{ steps.tag.outputs.image_tag_base }}-bundle:${{ steps.tag.outputs.tag }}@${{ steps.clife_docker_digests.outputs.bundle }}\`" >> image-digest/clife-bundle.txt
          echo "" >> image-digest/clife-bundle.txt

          echo "### clife catalog" > image-digest/clife-catalog.txt
          echo "" >> image-digest/clife-catalog.txt
          echo "\`${{ steps.tag.outputs.image_tag_base }}-catalog:1.0.0@${{ steps.clife_docker_digests.outputs.catalog }}\`" >> image-digest/clife-catalog.txt
          echo "" >> image-digest/clife-catalog.txt

      # Upload artifact digests
      - name: Upload artifact digests
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: image-digest clife
          path: image-digest

  image-digests:
    name: Display Digests
    runs-on: ubuntu-24.04
    needs: [build-and-push-external-images, build-and-push, build-and-push-clife]

    steps:
      - name: Prepare image digests download
        shell: bash
        run: |
          mkdir -p image-digest/

      - name: Download digests of all images built
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
        with:
          path: image-digest/
          pattern: "*image-digest *"

      - name: Image Digests Output
        shell: bash
        run: |
          cd image-digest/
          find -type f | sort | xargs -d '\n' cat
