name: Enterprise Image Release Build

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
      - v[0-9]+.[0-9]+.[0-9]+-*

permissions:
  # To be able to access the repository with `actions/checkout`
  contents: read
  # Required to generate OIDC tokens for `sigstore/cosign-installer` authentication
  id-token: write

jobs:
  # Envoy needs a special treatment as it is used for building the Cilium agent
  # and although it is a 1-1 copy of OSS, its version is changed at release time.
  build-and-push-envoy:
    timeout-minutes: 45
    name: Build and push cilium-envoy image
    environment: release
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ github.event.push.after }}
          persist-credentials: false
          fetch-depth: 0

      - name: Get and check version
        id: version
        run: |
          version=$(cat install/kubernetes/Makefile.values | grep CILIUM_ENVOY_VERSION | awk -F '=' '{print $2}')
          echo "version=${version}" >> $GITHUB_OUTPUT
          echo "upstream_repo=$(cat install/kubernetes/Makefile.values | grep CILIUM_ENVOY_REPO | awk -F '=' '{print $2}')" >> $GITHUB_OUTPUT
          echo "upstream_digest=$(cat install/kubernetes/Makefile.values | grep CILIUM_ENVOY_DIGEST | awk -F '=' '{print $2}')" >> $GITHUB_OUTPUT
          if docker manifest inspect quay.io/isovalent/cilium-envoy-ubi:${version} >/dev/null; then
            echo "exist=true" >> $GITHUB_OUTPUT
          else
            echo "exist=false" >> $GITHUB_OUTPUT
          fi

      - name: Set up Docker Buildx
        if: ${{ steps.version.outputs.exist == 'false' }}
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0

      - name: Login to quay.io
        if: ${{ steps.version.outputs.exist == 'false' }}
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME_RELEASE_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD_RELEASE_PASSWORD }}

      - name: Login to registry.redhat.io for pulling UBI images
        if: ${{ steps.version.outputs.exist == 'false' }}
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          registry: registry.redhat.io
          username: ${{ secrets.REDHAT_USERNAME_CI }}
          password: ${{ secrets.REDHAT_PASSWORD_CI }}

      - name: Build and push cilium-envoy image
        if: ${{ steps.version.outputs.exist == 'false' }}
        uses: docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4 # v6.15.0
        with:
          context: enterprise/images/cilium-envoy
          file: enterprise/images/cilium-envoy/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            quay.io/isovalent/cilium-envoy-ubi:${{ steps.version.outputs.version }}
          build-args: |
            BASE_IMAGE=registry.redhat.io/ubi9/ubi-minimal@sha256:14f14e03d68f7fd5f2b18a13478b6b127c341b346c86b6e0b886ed2b7573b8e0
            UPSTREAM_VERSION=${{ steps.version.outputs.version }}
            UPSTREAM_IMAGE=${{ steps.version.outputs.upstream_repo }}:${{ steps.version.outputs.version }}@${{ steps.version.outputs.upstream_digest }}
            VERSION=${{ steps.version.outputs.version }}

  build-and-push:
    timeout-minutes: 45
    name: Build and Push Images
    environment: release
    runs-on: ubuntu-24.04
    needs: build-and-push-envoy
    strategy:
      matrix:
        include:
          - name: cilium
            dockerfile: ./enterprise/images/cilium/Dockerfile
            base_image: quay.io/isovalent-dev/cilium-runtime-ubi:2cb77fcd0ab601fcf31597a6127d3b554db796da
            postfix: ubi
            image_name: cilium

          - name: operator
            dockerfile: ./enterprise/images/operator/Dockerfile
            base_image: registry.redhat.io/ubi9/ubi-micro:9.5-1741861735@sha256:8a6071b01366611fd9433bf9688f5c3150de819874fa2c06c4fcd4c25ea26f03
            postfix: ubi
            image_name: operator-generic

          - name: hubble-relay
            dockerfile: ./enterprise/images/hubble-relay/Dockerfile
            base_image: registry.redhat.io/ubi9/ubi-micro:9.5-1741861735@sha256:8a6071b01366611fd9433bf9688f5c3150de819874fa2c06c4fcd4c25ea26f03
            postfix: ubi
            image_name: hubble-relay

          - name: clustermesh-apiserver
            dockerfile: ./enterprise/images/clustermesh-apiserver/Dockerfile
            base_image: registry.redhat.io/ubi9/ubi-micro:9.5-1741861735@sha256:8a6071b01366611fd9433bf9688f5c3150de819874fa2c06c4fcd4c25ea26f03
            postfix: ubi
            image_name: clustermesh-apiserver

    steps:
      - name: Checkout main branch to access local actions
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ github.event.repository.default_branch }}
          persist-credentials: false

      - name: Cleanup Disk space in runner
        uses: ./.github/actions/disk-cleanup

      - name: Set Environment Variables
        uses: ./.github/actions/set-env-variables

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0

      - name: Login to quay.io
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME_RELEASE_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD_RELEASE_PASSWORD }}

      - name: Login to registry.redhat.io for pull of UBI images
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          registry: registry.redhat.io
          username: ${{ secrets.REDHAT_USERNAME_CI }}
          password: ${{ secrets.REDHAT_PASSWORD_CI }}

      - name: Getting image tag
        id: tag
        run: |
          tag=${GITHUB_REF##*/}
          echo tag=$tag >> $GITHUB_OUTPUT
          echo image_tag=quay.io/${{ env.QUAY_ORGANIZATION }}/${{ matrix.image_name }}-${{ matrix.postfix }}:$tag >> $GITHUB_OUTPUT

      - name: Checkout Source Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Release Build ${{ matrix.name }}
        id: docker_build_release
        shell: bash
        working-directory: ./enterprise/images
        run: |
          IMAGE_TAG=${{ steps.tag.outputs.tag }} \
          SUFFIX="" \
          REGISTRIES=quay.io/${{ env.QUAY_ORGANIZATION }} \
          PUSH=true \
          RUNTIME_IMAGE=${{ matrix.base_image }} \
          UBI_IMAGE=${{ matrix.base_image }} \
          OPERATOR_VARIANT=${{ matrix.image_name }} \
          PLATFORMS=linux/amd64,linux/arm64 \
          EXTRA_ARGS="--provenance=false" \
          make ${{ matrix.name }}-image

      - name: Release ${{ matrix.name }} digest
        id: docker_digest
        shell: bash
        run: |
          digest=$(images/scripts/get-image-digest.sh "${{ steps.tag.outputs.image_tag }}")
          echo digest=${digest} >> $GITHUB_OUTPUT

      - name: Install Cosign
        uses: sigstore/cosign-installer@d7d6bc7722e3daa8354c50bcb52f4837da5e9b6a # v3.8.1

      - name: Sign Container Images
        run: |
          cosign sign -y ${{ steps.tag.outputs.image_tag }}@${{ steps.docker_digest.outputs.digest }}

      - name: Generate SBOM
        uses: anchore/sbom-action@f325610c9f50a54015d37c8d16cb3b0e2c8f4de0 # v0.18.0
        with:
          artifact-name: sbom_${{ matrix.name }}_${{ steps.tag.outputs.tag }}.spdx.json
          output-file: ./sbom_${{ matrix.name }}_${{ steps.tag.outputs.tag }}.spdx.json
          image: ${{ steps.tag.outputs.image_tag }}
          upload-release-assets: false

      - name: Attach SBOM attestation to container image
        run: |
          cosign attest -r -y --predicate sbom_${{ matrix.name }}_${{ steps.tag.outputs.tag }}.spdx.json --type spdxjson ${{ steps.tag.outputs.image_tag }}

      - name: Image Release Digest
        shell: bash
        run: |
          mkdir -p image-digest/
          job_name=${{ matrix.name }}
          job_name_capital=${job_name^^}
          job_name_underscored=${job_name_capital//-/_}
          echo "${job_name_underscored}_DIGEST := \"${{ steps.docker_digest.outputs.digest }}\"" > image-digest/makefile-digest.txt

          echo "### ${{ matrix.name }}" > image-digest/${{ matrix.name }}.txt
          echo "" >> image-digest/${{ matrix.name }}.txt
          echo "\`${{ steps.tag.outputs.image_tag }}@${{ steps.docker_digest.outputs.digest }}\`" >> image-digest/${{ matrix.name }}.txt
          echo "" >> image-digest/${{ matrix.name }}.txt

      # Upload artifact digests
      - name: Upload artifact digests
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: image-digest ${{ matrix.name }}
          path: image-digest
          retention-days: 10

  image-digests:
    name: Display Digests
    runs-on: ubuntu-24.04
    needs: build-and-push

    steps:
      - name: Prepare image digests download
        shell: bash
        run: |
          mkdir -p image-digest/

      - name: Download digests of all images built
        uses: actions/download-artifact@95815c38cf2ff2164869cbab79da8d1f422bc89e # v4.2.1
        with:
          path: image-digest/
          pattern: "*image-digest *"

      - name: Image Digests Output
        shell: bash
        run: |
          cd image-digest/
          find -type f | sort | xargs -d '\n' cat
