name: Enterprise Lint
on:
  # Check mindfulness on each PR (when applicable per filter below)
  pull_request:
    branches:
      - main-ce
  # Validate mindfulness for each pushed commit
  push:
    branches:
      - main-ce
  # Additionally run once a day at midnight
  schedule:
    - cron:  '0 0 * * *'
  # Allow to run manually via GitHub UI
  workflow_dispatch: {}

permissions: read-all

jobs:
  mindfulness:
    name: Mindfulness
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@71cf2267d89c5cb81562390fa70a37fa40b1305e
        with:
          persist-credentials: false
          fetch-depth: '0'
      - name: Fetch OSS branch
        id: checkout-oss
        env:
          UPSTREAM: "https://github.com/cilium/cilium"
        run: |
          git remote add upstream "$UPSTREAM"
          git fetch --no-write-fetch-head upstream "refs/heads/main:refs/remotes/upstream/main"
      - name: Diff against upstream tree for files that should not diverge from OSS
        if: ${{ always() && steps.checkout.outcome == 'success' && steps.checkout-oss.outcome == 'success' }}
        run: |
          contrib/scripts/enterprise-meditation.sh \
            --repo cilium/cilium --debug
          contrib/scripts/enterprise-meditation.sh \
            --repo cilium/cilium --stat --exit-code
      - name: Diff against upstream tree for files that may diverge from OSS
        if: ${{ always() && steps.checkout.outcome == 'success' && steps.checkout-oss.outcome == 'success' }}
        run: |
          # Note: This does not fail when encountering a diff!
          contrib/scripts/enterprise-meditation.sh \
            --repo cilium/cilium --debug \
            --noisy
          contrib/scripts/enterprise-meditation.sh \
            --repo cilium/cilium --stat \
            --noisy

  codeowners:
    name: CODEOWNERS
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          persist-credentials: false

      - name: Check TESTOWNERS.enterprise is up to date
        run: |
          ./contrib/scripts/enterprise-testowners.sh
          if ! git diff --exit-code; then
            echo "Run './contrib/scripts/enterprise-testowners.sh' and submit your changes"
            exit 1
          fi
      - name: Check that all enterprise files are covered in CODEOWNERS
        run: |
          ./contrib/scripts/enterprise-codeowners.sh

  generate-enterprise-api:
    runs-on: ubuntu-24.04
    name: Generate Enterprise API
    steps:
      - name: Checkout code
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          persist-credentials: false

      - name: Check api generated files
        run: |
          contrib/scripts/enterprise-check-api-code-gen.sh

  gomod-override:
    runs-on: ubuntu-24.04
    name: go.mod
    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: Set up Go
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
        with:
          go-version-file: 'go.mod'

      - name: Check generated go.mod
        run: |
          contrib/scripts/enterprise-gomod-override.sh
