name: OLM Sync
on:
  # Allow to run manually
  workflow_dispatch: {}
  # Additionally run once a week at 3am on Monday
  schedule:
    - cron:  '0 3 * * MON'

permissions:
  # To be able to access the repository with `actions/checkout`
  contents: read
  pull-requests: write

# TODO: doing main-ce branch first. It will need to be extended to release branches
jobs:
  olm-sync:
    # This job copies the latest version of the helm charts into enterprise/olm/manifests
    name: sync manifests for OLM deployment
    if: github.repository == 'isovalent/cilium'
    runs-on: ubuntu-24.04
    steps:
      - name: Get Token
        id: get_token
        uses: getsentry/action-github-app-token@d4b5da6c5e37703f8c3b3e43abb5705b46e159cc # v3
        with:
            app_id: ${{ secrets.ISOVALENT_MIRROR_UPSTREAM_BOT_APP_ID }}
            private_key: ${{ secrets.ISOVALENT_MIRROR_UPSTREAM_BOT_APP_PEM }}

      - name: Authenticate with GH CLI
        run: |
          gh auth login --with-token <<< "${{ steps.get_token.outputs.token }}"

      - name: Checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          ref: ${{ github.event.repository.default_branch }}
          persist-credentials: false

      - name: Sync enterprise/olm/manifests
        working-directory: ./enterprise/olm
        run: |
          make sync-helm-manifests
          make set-images

      - name: Create PR
        run: |
          git config --global user.email "isovalent-bot@isovalent.com"
          git config --global user.name "isovalent-bot"
          git remote set-url origin https://x-access-token:${{ steps.get_token.outputs.token }}@github.com/isovalent/cilium.git
          if [[ ! $(git status --porcelain) ]]; then
            # No changes
            echo "No changes"
            exit 0
          fi
          git checkout -b pr/ci-wf/olm-sync
          git add ./enterprise/olm/manifests
          git commit -m "chore: Sync OLM manifests"
          git push --set-upstream origin pr/ci-wf/olm-sync
          echo -e "Created by GitHub action: OLM Sync.\n
          The Controller and its permissions need to be amended when new resources types are introduced.\n
          If new images are introduced their references need to be added for disconnected installations.\n" \
           | gh pr create -B "${{ github.event.repository.default_branch }}" --title 'chore: Sync OLM manifests' -l 'release-note/ignore' \
           --body-file -
