name: Conformance ILB OpenShift (ci-ilb-openshift)

# Usage with Ariane (GitHub issue comment):
# `/ci-ilb-openshift {"ocp_version":"4.17.14", "region":"us-east-1"}`
# The json parameters are optional. The default region is us-east-1.

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths:
        - 'enterprise/olm/**'
  workflow_dispatch:
    inputs:
      PR-number:
        description: "Pull request number."
        required: true
      context-ref:
        description: "Not used (enterprise only wf). Context in which the workflow runs. If PR is from a fork, will be the PR target branch (general case). If PR is NOT from a fork, will be the PR branch itself (this allows committers to test changes to workflows directly from PRs)."
        required: false
      SHA:
        description: "SHA under test (head of the PR branch)."
        required: true
      base-SHA:
        description: "SHA of the base branch (target branch of the PR)."
        required: false
      extra-args:
        description: "[JSON object] Arbitrary arguments passed from the trigger comment via regex capture group. Parse with 'fromJson(inputs.extra-args).argName' in workflow."
        required: false
        default: '{}'
  # For the purpose of testing the workflow
  # push:
  #   branches:
  #     - 'yourbranch'

# By specifying the access of one of the scopes, all of those that are not
# specified are set to 'none'.
permissions:
  # To read actions state with catchpoint/workflow-telemetry-action.
  actions: read
  # To be able to access the repository with actions/checkout.
  contents: read
  # To allow retrieving information from the PR API.
  pull-requests: read
  # To be able to set commit status
  statuses: write
  # To be able to request the JWT from GitHub's OIDC provider.
  id-token: write

concurrency:
  # Structure:
  # - Workflow name
  # - Event type
  # - A unique identifier depending on event type:
  #   - schedule: SHA
  #   - pull_request: SHA
  #   - workflow_dispatch: PR number
  #
  # This structure ensures a unique concurrency group name is generated for each
  # type of testing, such that re-runs will cancel the previous run.
  group: |
    ${{ github.workflow }}
    ${{ github.event_name }}
    ${{
      (github.event_name == 'schedule' && github.sha) ||
      (github.event_name == 'pull_request' && github.sha) ||
      (github.event_name == 'workflow_dispatch' && github.event.inputs.PR-number)
    }}
  cancel-in-progress: true

env:
  clusterName: ${{ github.run_id }}-${{ github.run_attempt }}
  # renovate: datasource=docker depName=quay.io/openshift-release-dev/ocp-release
  ocp_version_multi: 4.18.20-multi
  pod_cidr: 10.244.0.0/16
  pod_cidr_host_prefix: 23
  test_vm_tunnel_port: 8888

jobs:
  commit-status-start:
    name: Commit Status Start
    runs-on: ubuntu-24.04
    steps:
      - name: Echo Workflow Dispatch Inputs
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          echo '${{ tojson(inputs) }}'

      - name: Set initial commit status
        uses: myrotvorets/set-commit-status-action@3730c0a348a2ace3c110851bed53331bc6406e9f # v2.0.1
        with:
          sha: ${{ inputs.SHA || github.sha }}

  images:
    name: Prepare images
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    steps:
      - name: Checkout Cilium
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          ref: ${{ inputs.SHA || github.event.pull_request.head.sha }}
          persist-credentials: false

      - name: Cleanup Disk space in runner
        uses: ./.github/actions/disk-cleanup

      - name: Set up job variables
        id: vars
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            sha="${{ inputs.SHA }}"
          elif [ "${{ github.event_name }}" == 'schedule' ]; then
            sha="${{ github.sha }}"
          else
            sha="${{ github.event.pull_request.head.sha }}"
          fi
          echo sha=${sha} >> $GITHUB_OUTPUT

      - name: Wait for images to be available
        id: wait_images
        timeout-minutes: 30
        shell: bash
        run: |
          for image in cilium-ubi-ci operator-generic-ubi-ci hubble-relay-ubi-ci clustermesh-apiserver-ubi-ci; do
            until docker manifest inspect quay.io/isovalent-dev/$image:${{ steps.vars.outputs.sha }} &> /dev/null; do sleep 45s; done
          done
          echo "images available"
          # Some special handling is needed for clife as it does not get built for every push / PR, per default
          # only when enterprise/olm is modified.
          i=0
          until docker manifest inspect quay.io/isovalent-dev/clife-ci:${{ steps.vars.outputs.sha }} &> /dev/null || [[ "${i}" -gt 10 ]]; do sleep 30s; i=$((i + 1)); done
          if [[ "${i}" -gt 10 ]]; then
            echo "CLife rebuild needed"
            echo rebuild_clife='true' >> $GITHUB_OUTPUT
          else
            echo "Clife image available"
            echo rebuild_clife='false' >> $GITHUB_OUTPUT
          fi

      - name: Login to quay.io
        if: ${{ steps.wait_images.outputs.rebuild_clife  == 'true' }}
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME_CI }}
          password: ${{ secrets.QUAY_PASSWORD_CI }}

      - name: Login to registry.redhat.io for pulling images
        if: ${{ steps.wait_images.outputs.rebuild_clife  == 'true' }}
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          registry: registry.redhat.io
          username: ${{ secrets.REDHAT_USERNAME_CI }}
          password: ${{ secrets.REDHAT_PASSWORD_CI }}

      - name: Setup go
        if: ${{ steps.wait_images.outputs.rebuild_clife  == 'true' }}
        uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
        with:
          cache: false
          # renovate: datasource=golang-version depName=go
          go-version: 1.25.5

      - name: Build and Push CLife image
        if: ${{ steps.wait_images.outputs.rebuild_clife  == 'true' }}
        env:
          IMG: "quay.io/isovalent-dev/clife-ci:${{ steps.vars.outputs.sha }}"
          CL_TAG: "${{ steps.vars.outputs.sha }}"
        working-directory: ./enterprise/olm
        run: |
          make docker-buildx VERSION=${{ steps.vars.outputs.sha }}

  installation-and-connectivity:
    name: Installation and Connectivity Test
    runs-on: ubuntu-24.04
    needs: [images]
    timeout-minutes: 240
    steps:
      - name: Collect Workflow Telemetry
        uses: catchpoint/workflow-telemetry-action@94c3c3d9567a0205de6da68a76c428ce4e769af1 # v2.0.0
        with:
          comment_on_pr: false

      - name: Checkout Cilium
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          ref: ${{ inputs.SHA || github.event.pull_request.head.sha }}
          persist-credentials: false

      - name: Cleanup Disk space in runner
        uses: ./.github/actions/disk-cleanup

      - name: Set Environment Variables
        uses: ./.github/actions/set-env-variables

      - name: Set up job variables
        id: vars
        run: |
          if [ "${{ github.event_name }}" == 'workflow_dispatch' ]; then
            OWNER="${{ inputs.PR-number }}"
          else
            OWNER="${{ github.ref_name }}"
            OWNER="${OWNER//[.\/]/-}"
          fi
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            sha="${{ inputs.SHA }}"
          elif [ "${{ github.event_name }}" == 'schedule' ]; then
            sha="${{ github.sha }}"
          else
            sha="${{ github.event.pull_request.head.sha }}"
          fi
          extra_args=${{ inputs.extra-args }}
          ocp_version=$(echo $extra_args | jq -r '.ocp_version')
          if [[ "${ocp_version}" == "null" || "${ocp_version}" == "" ]]; then
            ocp_version=$(echo ${{ env.ocp_version_multi }} | cut -f1 -d "-")
          fi
          region=$(echo $extra_args | jq -r '.region')
          if [[ "${region}" == "null" || "${region}" == "" ]]; then
            region="us-east-1"
          fi
          zone=$(echo $extra_args | jq -r '.zone')
          if [[ "${zone}" == "null" || "${zone}" == "" ]]; then
            zone="${region}a"
          fi
          build_cilium_cli=$(echo $extra_args | jq -r '.buildCiliumCli')
          ocp_minor_version=$(echo ${ocp_version} | cut -d '.' -f 1,2)
          echo "ocp_version=${ocp_version}" | tee -a $GITHUB_OUTPUT
          echo "ocp_minor_version=${ocp_minor_version}" | tee -a $GITHUB_OUTPUT
          echo "sha=${sha}" | tee -a $GITHUB_OUTPUT
          echo "owner=${OWNER}" | tee -a $GITHUB_OUTPUT
          echo "region=${region}" | tee -a $GITHUB_OUTPUT
          echo "zone=${zone}" | tee -a $GITHUB_OUTPUT
          echo "build_cilium_cli=${build_cilium_cli}" | tee -a $GITHUB_OUTPUT

      - name: Install kubectl
        run: |
          curl -sLO "https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/latest-${{ steps.vars.outputs.ocp_minor_version }}/openshift-client-linux.tar.gz"
          curl -sLO "https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/latest-${{ steps.vars.outputs.ocp_minor_version }}/sha256sum.txt"
          echo "$(cat sha256sum.txt | grep 'openshift-client-linux-4' | cut -f1 -d ' ') openshift-client-linux.tar.gz" | sha256sum --check
          tar -zxvf openshift-client-linux.tar.gz oc
          sudo install -o root -g root -m 0755 oc /usr/local/bin/kubectl
          sudo mv oc /usr/local/bin/
          kubectl version --client
          mkdir -p /home/runner/.kube
          touch /home/runner/.kube/config

      - name: Set up AWS CLI credentials
        uses: aws-actions/configure-aws-credentials@61815dcd50bd041e203e49132bacad1fd04d2708 # v5.1.1
        with:
          role-to-assume: ${{ secrets.AWS_PR_ASSUME_ROLE }}
          aws-region: ${{ steps.vars.outputs.region }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
        with:
          terraform_version: "^1.10.4"
          terraform_wrapper: false

      - name: Install Cilium CLI
        if: ${{ steps.vars.outputs.build_cilium_cli != 'true' }}
        run: |
          curl -LO https://github.com/isovalent/cilium-cli-releases/releases/latest/download/cilium-linux-amd64.tar.gz
          sudo tar xzvfC cilium-linux-amd64.tar.gz /usr/local/bin
          rm cilium-linux-amd64.tar.gz

      - name: Install Go
        if: ${{ steps.vars.outputs.build_cilium_cli == 'true' }}
        uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
        with:
          # renovate: datasource=golang-version depName=go
          go-version: 1.25.5

      - name: Build Cilium CLI CEE
        if: ${{ steps.vars.outputs.build_cilium_cli == 'true' }}
        run: |
          go build -o cilium ./cilium-cli/enterprise/cmd/cilium
          sudo mv cilium /usr/local/bin

      - name: Checkout the OpenShift CuTE repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          repository: isovalent/cute-openshift-aws
          token: ${{ secrets.ISOVALENT_BOT_READ_PRIVATE_REPOSITORIES }}
          path: cute

      - name: Generate SSH key
        run: |
          ssh-keygen -b 2048 -t rsa -f /home/runner/.ssh/ci_key -q -N ""
          cat /home/runner/.ssh/ci_key | base64

      - name: Configuration for the OpenShift cluster installation
        id: cute_config
        working-directory: ./cute
        run: |
          cute_dir=ocp-$(echo ${{ steps.vars.outputs.ocp_minor_version }} | tr '.' '-')
          echo dir="${cute_dir}" >> $GITHUB_OUTPUT
          cd "${cute_dir}"
          # Generation of the terraform configuration.
          echo "${{ secrets.OPENSHIFT_PULL_SECRET }}" | base64 -d > .pullsecret.json
          cat > terraform.tfvars << EOF
          cluster_name="${{ env.clusterName }}"
          owner="${{ steps.vars.outputs.owner }}"
          ssh_public_key_path="/home/runner/.ssh/ci_key.pub"
          region="${{ steps.vars.outputs.region }}"
          availability_zones = ["${{ steps.vars.outputs.zone }}"]
          pull_secret_path="${PWD}/.pullsecret.json"
          base_domain="${{ vars.AWS_BASE_DOMAIN }}"
          pod_cidr="${{ env.pod_cidr }}"
          pod_cidr_host_prefix="${{ env.pod_cidr_host_prefix }}"
          cilium_kpr_enabled="true"
          cilium_olm_repo_type="clife"
          cilium_olm_repo="dir:$(pwd)/../.."
          cilium_olm_repo_branch="${{ steps.vars.outputs.sha }}"
          cilium_version="${{ steps.vars.outputs.sha }}"
          cilium_path_to_ciliumconfig_file="clife-ciliumconfig.yaml"
          openshift_version="${{ steps.vars.outputs.ocp_version }}"
          masters_source_dest_check = false
          worker_instance_type="m5.xlarge"
          workers_count=4
          workers_source_dest_check=false
          EOF
          cat terraform.tfvars
          cp ../../enterprise/olm/config/samples/openshift_ci_ciliumconfig_ilb.yaml clife-ciliumconfig.yaml

      # replace git SSH by HTTPS and use a private access token so that `terraform get`
      # can download modules from private repositories.
      - name: Git config for terraform
        run: |
          git config --global url."https://oauth2:${{ secrets.ISOVALENT_BOT_READ_PRIVATE_REPOSITORIES }}@github.com".insteadOf ssh://git@github.com

      - name: Provision the OpenShift cluster
        id: cluster
        timeout-minutes: 60
        working-directory: "./cute/${{ steps.cute_config.outputs.dir }}"
        run: |
          make apply AUTO_APPROVE=true

      - name: Kubeconfig Setup
        if: always() && steps.cluster.outcome != 'skipped'
        id: kubeconfig
        working-directory: "./cute/${{ steps.cute_config.outputs.dir }}"
        run: |
          eval "$(make kubeconfig | grep KUBECONFIG)"
          [[ ! "$KUBECONFIG" =~ ^/.* ]] && KUBECONFIG="$(pwd)/$KUBECONFIG"
          echo "base64 encoded kubeconfig:"
          cat $KUBECONFIG | base64 # useful for troubleshooting
          # required by the Cilium CLI container
          cp $KUBECONFIG /home/runner/.kube/config

      - name: Cluster state
        if: always() && steps.cluster.outcome != 'skipped'
        run: |
          function retry {
            local retries=$1
            shift
            local count=0
            until "$@"; do
              exit=$?
              wait=$((2 ** count))
              count=$((count + 1))
              if [ $count -lt "${retries}" ]; then
                echo "Retry $count/$retries exited $exit, retrying in $wait seconds..."
                sleep $wait
              else
                echo "Retry $count/$retries exited $exit, no more retries left."
                return $exit
              fi
            done
            return 0
          }

          retry 3 kubectl get pods -A -o wide
          retry 3 kubectl get nodes
          retry 3 kubectl get co
          retry 3 kubectl get ciliumconfig -o yaml
          retry 3 kubectl get events -n cilium
          retry 3 kubectl get pods -n cilium -o yaml
          retry 3 kubectl logs -n cilium deployment/clife-controller-manager
          retry 3 kubectl logs -n cilium daemonset/cilium --all-containers=true

      - name: Read environment props
        id: aws-env
        run: |
          # Read worker nodes security group IDs
          # The following schellcheck disabled because AWS CLI --query requires single quotes.
          # shellcheck disable=SC2016
          workersSGId=$(aws ec2 describe-security-groups --region ${{ steps.vars.outputs.region }} \
                                                         --query 'SecurityGroups[?starts_with(GroupName, `${{ env.clusterName }}`) == `true` && ends_with(GroupName, `workers`) == `true`]|[].GroupId' \
                                                         --no-cli-pager \
                                                         --output text)
          # Read SSH key pair name
          # The following schellcheck disabled because AWS CLI --query requires single quotes.
          # shellcheck disable=SC2016
          keyPairName=$(aws ec2 describe-key-pairs --region ${{ steps.vars.outputs.region }} \
                                                   --query 'KeyPairs[?starts_with(KeyName, `${{ env.clusterName }}`) == `true`]|[].[KeyName]' \
                                                   --no-cli-pager \
                                                   --output text)
          # Read private subnet ID
          privateSubnetId=$(aws ec2 describe-subnets --region ${{ steps.vars.outputs.region }} \
                                                     --filters 'Name=tag:Name,Values=${{ env.clusterName }}*private*' \
                                                     --query 'Subnets[*].SubnetId' \
                                                     --no-cli-pager \
                                                     --output text)
          # Read all security group IDs
          # The following schellcheck disabled because AWS CLI --query requires single quotes.
          # shellcheck disable=SC2016
          allSecurityGroupIds=$(aws ec2 describe-security-groups --region ${{ steps.vars.outputs.region }} \
                                                                 --query 'SecurityGroups[?starts_with(GroupName, `${{ env.clusterName }}`) == `true`]|[].GroupId' \
                                                                 --no-cli-pager \
                                                                 --output text)
          echo "workersSGId=${workersSGId}" | tee -a $GITHUB_OUTPUT
          echo "keyPairName=${keyPairName}" | tee -a $GITHUB_OUTPUT
          echo "privateSubnetId=${privateSubnetId}" | tee -a $GITHUB_OUTPUT
          echo "allSecurityGroupIds=${allSecurityGroupIds}" | tee -a $GITHUB_OUTPUT

      - name: Test VM pre-install script
        run: |
          cat > test-vm-setup.sh << EOF
          #!/bin/bash

          # install docker
          sudo apt-get update
          sudo apt-get install -y ca-certificates curl unzip
          sudo install -m 0755 -d /etc/apt/keyrings
          sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
          sudo chmod a+r /etc/apt/keyrings/docker.asc
          echo \
            "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
            $(. /etc/os-release && echo "${UBUNTU_CODENAME:-$VERSION_CODENAME}") stable" | \
            sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
          sudo apt-get update
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
          sudo usermod -aG docker ubuntu
          newgrp docker

          # install kubectl
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/bin

          # install Cilium CLI
          curl -LO https://github.com/isovalent/cilium-cli-releases/releases/latest/download/cilium-linux-amd64.tar.gz
          sudo tar xzvfC cilium-linux-amd64.tar.gz /usr/local/bin
          rm cilium-linux-amd64.tar.gz
          EOF

      - name: Provision test VM
        id: test-vm
        run: |
          output=$(aws ec2 run-instances --region ${{ steps.vars.outputs.region }} \
                                         --image-id ami-020cba7c55df1f615 \
                                         --user-data file://./test-vm-setup.sh \
                                         --key-name ${{ steps.aws-env.outputs.keyPairName }} \
                                         --instance-type t3.micro \
                                         --subnet-id ${{ steps.aws-env.outputs.privateSubnetId }} \
                                         --tag-specifications 'ResourceType=instance,Tags=[{Key=Name,Value=${{ env.clusterName }}-test-vm}]' \
                                         --security-group-ids ${{ steps.aws-env.outputs.allSecurityGroupIds }} \
                                         --no-cli-pager)
          instanceId=$(echo "${output}" | jq -r '.Instances[].InstanceId')
          echo "id=${instanceId}" | tee -a $GITHUB_OUTPUT

      - name: Allow ILB test CIDR
        run: |
          aws ec2 authorize-security-group-ingress --region ${{ steps.vars.outputs.region }} \
                                                   --group-id ${{ steps.aws-env.outputs.workersSGId }} \
                                                   --protocol -1 \
                                                   --port -1 \
                                                   --cidr 100.64.0.0/16 \
                                                   --no-cli-pager

      - name: Provision AWS endpoint
        id: aws-endpoint
        timeout-minutes: 15
        run: |
          endpointID=$(aws ec2 create-instance-connect-endpoint --region ${{ steps.vars.outputs.region }} \
                                                                --security-group-ids ${{ steps.aws-env.outputs.allSecurityGroupIds }} \
                                                                --subnet-id ${{ steps.aws-env.outputs.privateSubnetId }} \
                                                                --no-cli-pager \
                                                                --output json | \
                       jq .InstanceConnectEndpoint.InstanceConnectEndpointId -r)
          while true
          do
            status=$(aws ec2 describe-instance-connect-endpoints --region ${{ steps.vars.outputs.region }} \
                                                                 --instance-connect-endpoint-ids $endpointID \
                                                                 --query InstanceConnectEndpoints[*].State \
                                                                 --no-cli-pager \
                                                                 --output text || true)
            if [ "${status}" == "create-complete" ]
            then
              echo "Endpoint is ready!"
              break
            fi
            echo "Endpoint is not ready yet: ${status} ..."
            sleep 10
          done
          echo "id=${endpointID}" | tee -a $GITHUB_OUTPUT

      - name: Wait for Cluster operators to be ready
        if: ${{ steps.cluster.outcome == 'success' }}
        id: wait-for-co
        timeout-minutes: 15
        run: |
          set +e
          while true; do
            if ! co_status=$(kubectl get co -o jsonpath="{range .items[*]}{.status.conditions[?(@.type=='Available')].status}{'\n'}{end}"); then
              sleep 30s
              continue
            fi
            if echo "$co_status" | grep False; then
              sleep 30s
              continue
            fi
            break
          done
          set -e

      - name: Disable OpenShift ingress router
        timeout-minutes: 10
        run: |
          # The OpenShift HA ingress router uses TCP port 80 which might cause the following error for the ILB E2E tests:
          # "Error adding/updating listener(s) <listener-name>: cannot bind '<node-ip>:80': Address already in use"
          kubectl patch -n openshift-ingress-operator ingresscontroller default \
                        --type merge \
                        --patch '{"spec":{"replicas":0}}'
          while true; do
            count=$(kubectl -n openshift-ingress get po --no-headers --ignore-not-found=true | wc -l || true)
            if [ $count -eq 0 ]
            then
              break
            fi
            echo "waiting for termination: ${count}"
            sleep 10s
          done

      - name: Cluster operators not ready
        if: ${{ steps.cluster.outcome != 'skipped' && steps.wait-for-co.outcome == 'failure' }}
        run: |
          kubectl get co -o yaml
          kubectl get events -n cilium
          kubectl get pods -n cilium -o yaml
          kubectl logs -n cilium deployment/clife-controller-manager
          kubectl logs -n cilium daemonset/cilium --all-containers=true

      - name: Retrieve cluster info
        id: cluster-info
        run: |
          api_server="$(kubectl config view --minify | yq -r '.clusters[0].cluster.server')"
          echo "k8s_service_host=$(echo $api_server | awk -F '/' '{print $3}' | awk -F ':' '{print $1}')" >> $GITHUB_OUTPUT
          echo "k8s_service_port=$(echo $api_server | awk -F '/' '{print $3}' | awk -F ':' '{print $2}')" >> $GITHUB_OUTPUT

      - name: Verify OpenShift kube-proxy removed
        run: |
          count="$(kubectl get pods -A -l app=kube-proxy | wc -l)"
          if [[ $count -gt 0 ]]
          then
            echo "OpenShift kube-proxy was not removed!"
            exit 1
          fi

      - name: Display Cilium status
        run: |
          cilium status -n cilium --wait --wait-duration=10m

      - name: Label ILB nodes
        run: |
          function retry {
            local retries=$1
            shift
            local count=0
            until "$@"; do
              exit=$?
              wait=$((2 ** count))
              count=$((count + 1))
              if [ $count -lt "${retries}" ]; then
                echo "Retry $count/$retries exited $exit, retrying in $wait seconds..."
                sleep $wait
              else
                echo "Retry $count/$retries exited $exit, no more retries left."
                return $exit
              fi
            done
            return 0
          }

          nodes=$(kubectl get nodes -l node-role.kubernetes.io/worker --no-headers -o custom-columns=":metadata.name")
          i=1
          for node in $nodes
          do
            tier=1
            if [[ $i -gt 2 ]]
            then
              tier=2
            fi
            echo "Labeling ${node} as tier: ${tier}"
            retry 3 kubectl label node $node service.cilium.io/node=t$tier
            ((i++))
          done

      - name: Wait for Cilium status to be ready
        run: |
          cilium status -n cilium --wait --wait-duration=10m

      - name: Display ILB status
        run: |
          cilium lb status -n cilium

      - name: Open tunnel to test VM
        id: aws-tunnel
        run: |
          aws ec2-instance-connect open-tunnel --region ${{ steps.vars.outputs.region }} \
                                               --instance-id ${{ steps.test-vm.outputs.id }} \
                                               --local-port ${{ env.test_vm_tunnel_port }} &
          pid=$!
          echo "pid=${pid}" >> $GITHUB_OUTPUT

      - name: Copy kubeconfig to test VM
        run: |
          scp -i ~/.ssh/ci_key \
              -P ${{ env.test_vm_tunnel_port }} \
              -o stricthostkeychecking=no \
              ~/.kube/config ubuntu@localhost:.

      - name: Copy Cilium CLI CEE to test VM
        if: ${{ steps.vars.outputs.build_cilium_cli == 'true' }}
        run: |
          zip -j cilium.zip /usr/local/bin/cilium
          scp -i ~/.ssh/ci_key \
              -P ${{ env.test_vm_tunnel_port }} \
              -o stricthostkeychecking=no \
              cilium.zip ubuntu@localhost:.

      - name: Run ILB tests
        uses: appleboy/ssh-action@823bd89e131d8d508129f9443cad5855e9ba96f0 # v1.2.4
        env:
          KUBECONFIG: "/home/ubuntu/config"
        with:
          host: localhost
          port: ${{ env.test_vm_tunnel_port }}
          username: ubuntu
          key_path: "/home/runner/.ssh/ci_key"
          command_timeout: 60m
          envs: KUBECONFIG
          script: |
            if [[ "${{ steps.vars.outputs.build_cilium_cli }}" == "true" ]]
            then
              unzip cilium.zip
              sudo mv cilium /usr/local/bin
            fi
            cilium version
            cilium lb status -n cilium
            cilium lb test -n cilium \
                           --mode=single-node \
                           --sysdump-on-failure \
                           --sysdump-output-filename ilb-sysdump \
                           --verbose

      - name: Download sysdump
        if: ${{ !success() && steps.cluster.outcome != 'skipped' }}
        shell: bash
        working-directory: ./cute/${{ steps.cute_config.outputs.dir }}
        run: |
          mkdir -p ./test-results
          cilium status -n cilium
          scp -i ~/.ssh/ci_key \
              -P ${{ env.test_vm_tunnel_port }} \
              -o stricthostkeychecking=no \
              ubuntu@localhost:ilb-sysdump.zip ./test-results/ilb-sysdump.zip

      # This is to work around the fact that relative paths in actions/upload-artifact@v3 are rooted
      # against the workspace, which causes an "Invalid pattern" if the CuTE repo dir is ".".
      - name: Prepare upload
        if: always() && steps.wait-for-co.outcome != 'skipped'
        id: upload_dir
        working-directory: "./cute/${{ steps.cute_config.outputs.dir }}"
        run: |
          if test -d ./test-results; then
            echo path="$(realpath ./test-results)" >> $GITHUB_OUTPUT
          else
            echo path=nothingtoupload >> $GITHUB_OUTPUT
          fi

      - name: Upload Artifacts
        if: always() && steps.wait-for-co.outcome != 'skipped'
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: output-ilb-tests
          path: ${{ steps.upload_dir.outputs.path }}
          if-no-files-found: ignore
          retention-days: 3

      # refresh credentials
      - name: Set up AWS CLI credentials
        if: always() && steps.cluster.outcome != 'skipped'
        uses: aws-actions/configure-aws-credentials@61815dcd50bd041e203e49132bacad1fd04d2708 # v5.1.1
        with:
          role-to-assume: ${{ secrets.AWS_PR_ASSUME_ROLE }}
          aws-region: ${{ steps.vars.outputs.region }}

      # Happens independently of the success or the failure of the provisioning and tests
      - name: Terminate test VM
        if: always() && steps.test-vm.outcome != 'skipped'
        run: |
          echo "terminating test VM: ${{ steps.test-vm.outputs.id }} ..."
          aws ec2 terminate-instances --region ${{ steps.vars.outputs.region }} \
                                      --instance-ids ${{ steps.test-vm.outputs.id }} \
                                      --no-cli-pager

      # Happens independently of the success or the failure of the provisioning and tests
      - name: Close endpoint tunnel
        if: always() && steps.aws-tunnel.outcome != 'skipped'
        run: |
          echo "terminating AWS tunnel process: ${{ steps.aws-tunnel.outputs.pid }} ..."
          kill -9 ${{ steps.aws-tunnel.outputs.pid }} || true

      # Happens independently of the success or the failure of the provisioning and tests
      - name: Terminate AWS endpoint
        if: always() && steps.aws-endpoint.outcome != 'skipped'
        run: |
          echo "terminating AWS endpoint: ${{ steps.aws-endpoint.outputs.id }} ..."
          aws ec2 delete-instance-connect-endpoint --region ${{ steps.vars.outputs.region }} \
                                                   --instance-connect-endpoint-id ${{ steps.aws-endpoint.outputs.id }} \
                                                   --no-cli-pager

      # Happens independently of the success or the failure of the provisioning and tests
      - name: Clean up Cluster
        if: always() && steps.cluster.outcome != 'skipped'
        timeout-minutes: 60
        working-directory: "./cute/${{ steps.cute_config.outputs.dir }}"
        run: |
          echo "killing terraform processes ..."
          pkill -9 terraform || true
          if [ -f .terraform.tfstate.lock.info ]; then
            echo "unlocking terraform state ..."
            LOCK_ID=$(jq -r '.ID' .terraform.tfstate.lock.info)
            terraform force-unlock -force "$LOCK_ID" || true
          fi
          echo "destroying infra ..."
          make destroy AUTO_APPROVE=true

  termination:
    if: ${{ always() }}
    name: Commit Status Final
    needs: installation-and-connectivity
    runs-on: ubuntu-24.04
    steps:
      - name: Set final commit status
        if: ${{ needs.installation-and-connectivity.result != 'skipped' }}
        uses: myrotvorets/set-commit-status-action@3730c0a348a2ace3c110851bed53331bc6406e9f # v2.0.1
        with:
          sha: ${{ inputs.SHA || github.sha }}
          status: ${{ needs.installation-and-connectivity.result }}

      - name: Set final commit status
        if: ${{ needs.installation-and-connectivity.result == 'skipped' }}
        uses: myrotvorets/set-commit-status-action@3730c0a348a2ace3c110851bed53331bc6406e9f # v2.0.1
        with:
          sha: ${{ inputs.SHA || github.sha }}
          status: ${{ github.event_name != 'schedule' && 'success' || 'failure' }}
          description: 'Skipped'
