name: Publish release to Red Hat catalogs
run-name: Publish the ${{ inputs.version }} release to Red Hat catalogs

# This workflow:
# - Run the preflight checks for the component images and publish the results to Red Hat
# - Create a pull request with the required manifests for publishing a new bundle against Red Hat repository for certified operators
# - Create a pull request with the new installation archive against the documentation repository for Isovalent Networking for Kubernetes

on:
  workflow_dispatch:
    inputs:
      version:
        description: "The release version, also git tag, e.g. v1.17.5-cee.1"
        required: true
      submit:
        description: "Whether results are to be submitted to Red Hat"
        required: true
        default: 'false'
        type: choice
        options:
         - 'true'
         - 'false'

permissions:
  # To be able to access the repository with actions/checkout.
  contents: read
  # To be able to request the JWT from GitHub's OIDC provider.
  id-token: write

env:
  OPERATOR_NAME: isovalent-networking
  PR_BRANCH: pr/isovalent-networking/${{ inputs.version }}
  VERSION: ${{ inputs.version }}

jobs:
  publish-to-redhat:
    name: Publish to Red Hat
    runs-on: ubuntu-24.04
    steps:
      - name: Echo Workflow Dispatch Inputs
        run: |
          echo '${{ tojson(inputs) }}'

      - name: Checkout Cilium
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          path: cilium

      - name: Run preflight checks and publish results
        env:
          CL_TAG: "${{ env.VERSION }}"
          CL_PYXIS_TOKEN: "${{ secrets.RH_API_PYXIS_TOKEN }}"
          CL_SUBMIT: "${{ inputs.submit }}"
        working-directory: ${{ github.workspace }}/cilium/enterprise/olm
        run: |
          ./scripts/publish-img-checks-to-redhat.sh

      - name: Get Isovalent Bot Token (Operator PR)
        uses: hashicorp/vault-action@4c06c5ccf5c0761b6029f56cfb1dcf5565918a3b # v3.4.0
        with:
          url: ${{ vars.VAULT_URL }}
          method: jwt
          namespace: ${{ github.repository_owner }}/github-actions
          secrets: |
            secret/data/release-mgmt/${{ github.repository_owner }} isovalent_bot_token  | CERTIFIED_OPERATORS_PR_TOKEN;

      - name: Checkout certified-operators
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          repository: redhat-openshift-ecosystem/certified-operators
          token: ${{ env.CERTIFIED_OPERATORS_PR_TOKEN }}
          path: certified-operators

      - name: Create and Sync the fork
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        with:
          github-token: ${{ env.CERTIFIED_OPERATORS_PR_TOKEN }}
          script: |
            const { data: fork } = await github.rest.repos.createFork({
              owner: 'isovalent-bot',
              repo: 'certified-operators',
              default_branch_only: true,
            });

            await github.rest.repos.mergeUpstream({
              owner: 'isovalent-bot',
              repo: 'certified-operators',
              branch: fork.default_branch,
            });
            core.exportVariable('DOWNSTREAM_REPO_URL', fork.clone_url);
            core.exportVariable('UPSTREAM_DEFAULT_BRANCH', fork.default_branch);

      - name: Configure Fork
        working-directory: ${{ github.workspace }}/certified-operators
        run: |
          git remote get-url upstream || \
          git remote rename origin upstream && \
          git remote add origin ${DOWNSTREAM_REPO_URL}
          git remote -v

      - name: Create PR branch
        working-directory: ${{ github.workspace }}/certified-operators
        run: |
          git checkout -b ${PR_BRANCH}

      - name: Generate bundle
        env:
          CL_TAG: "${{ env.VERSION }}"
          CL_RH_REPO: ${{ github.workspace }}/certified-operators
        working-directory: ${{ github.workspace }}/cilium/enterprise/olm
        run: |
          ./scripts/generate-bundle-4-redhat.sh

      - name: Generate release-config.yaml
        env:
          CL_TAG: "${{ env.VERSION }}"
          CL_RH_REPO: ${{ github.workspace }}/certified-operators
        working-directory: ${{ github.workspace }}/cilium/enterprise/olm
        run: |
          ./scripts/generate-release-cfg-4-redhat.sh

      - name: Push Bundle to certified-operators
        working-directory: ${{ github.workspace }}/certified-operators
        id: push-bundle
        run: |
          git config --global user.email "isovalent-operator[bot]@users.noreply.github.com"
          git config --global user.name "isovalent-operator[bot]"

          # Commit and push
          COMMIT_MESSAGE="Add operator ${OPERATOR_NAME} ${VERSION}"
          git add operators
          git commit -m "${COMMIT_MESSAGE}"
          git push -u origin ${PR_BRANCH}

          # Set title and body
          echo "title=${COMMIT_MESSAGE}" >> $GITHUB_OUTPUT
          PULL_REQUEST_MESSAGE="Created by the *${{ github.job }}* for ${OPERATOR_NAME} ${VERSION}."
          echo "body=${PULL_REQUEST_MESSAGE}" >> $GITHUB_OUTPUT

      - name: Create PR
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        with:
          github-token: ${{ env.CERTIFIED_OPERATORS_PR_TOKEN }}
          script: |
            const { data: pr } = await github.rest.pulls.create({
              owner: 'redhat-openshift-ecosystem',
              repo: 'certified-operators',
              head: 'isovalent-bot:${{ env.PR_BRANCH }}',
              base: '${{ env.UPSTREAM_DEFAULT_BRANCH }}',
              body: '${{ steps.push-bundle.outputs.body }}',
              title: '${{ steps.push-bundle.outputs.title }}',
            });

            console.log(`PR created: ${pr.html_url}`);

  publish-to-doc:
    name: Publish to doc site
    runs-on: ubuntu-24.04
    env:
      DOC_BRANCH: main # Target branch in the isovalent/cilium-enterprise-docs repository
    steps:
      - name: Echo Workflow Dispatch Inputs
        run: |
          echo '${{ tojson(inputs) }}'

      - name: Checkout Cilium
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          path: cilium

      - name: Get Release Management Github App Credentials
        uses: hashicorp/vault-action@4c06c5ccf5c0761b6029f56cfb1dcf5565918a3b # v3.4.0
        with:
          url: ${{ vars.VAULT_URL }}
          method: jwt
          namespace: ${{ github.repository_owner }}/github-actions
          secrets: |
            secret/data/devops/${{ github.repository_owner }} github_app_pem | GH_READWRITE_APP_PEM;
            secret/data/devops/${{ github.repository_owner }} github_app_id | GH_READWRITE_APP_ID;

      - id: generate-token
        name: Generate Token
        uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2.2.1
        with:
          app-id: ${{ env.GH_READWRITE_APP_ID }}
          private-key: ${{ env.GH_READWRITE_APP_PEM }}
          owner: ${{ github.repository_owner }}
          repositories: |
            cilium-enterprise-docs

      - name: Checkout Enterprise Docs
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          token: ${{ steps.generate-token.outputs.token }}
          repository: isovalent/cilium-enterprise-docs
          path: enterprise-docs
          ref: ${{ env.DOC_BRANCH }}

      - name: Create docs release archives
        working-directory: cilium/enterprise/olm
        env:
          CL_TAG: "${{ env.VERSION }}"
          IMG_REPO: "quay.io/isovalent/clife"
        run: |
          digest=$(../../images/scripts/get-image-digest.sh ${IMG_REPO}:${CL_TAG})
          export IMG=${IMG_REPO}:${CL_TAG}@${digest}
          make release-archive

      - name: Commit and push release archives and links
        working-directory: enterprise-docs
        run: |
          # upload the archive and SHA
          cp ../cilium/enterprise/olm/.docs/* docs/_static/public/clife
          # update doc link
          version="$(echo "${{ env.VERSION }}" | cut -d - -f -1 | cut -d \+ -f -1)"
          version="${version#v}"
          echo "${version}" > docs/CLIFE_VERSION
          message="Update Enterprise Docs with CLife Release for Isovalent Networking for Kubernetes ${{ env.VERSION }}"
          echo "TITLE=${message}" >> "$GITHUB_ENV"
          git config --global user.email "release-management[bot]@users.noreply.github.com"
          git config --global user.name "release-management[bot]"
          git add docs
          git commit docs -m "${message}"
          git push origin HEAD:pr/clife-release/${{ env.VERSION }}

      - name: Create PR
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        with:
          github-token: ${{ steps.generate-token.outputs.token }}
          script: |
            const { data: pr } = await github.rest.pulls.create({
              owner: '${{ github.repository_owner }}',
              repo: 'cilium-enterprise-docs',
              title: '${{ env.TITLE }}',
              head: '${{ github.repository_owner }}:pr/clife-release/${{ env.VERSION }}',
              base: '${{ env.DOC_BRANCH }}',
              body: 'CLife Release for Isovalent Networking for Kubernetes ${{ env.VERSION }}',
            });
            console.log(pr.html_url);
