name: Enterprise LoadBalancer (ci-lb)

# Any change in triggers needs to be reflected in the concurrency group.
on:
  workflow_dispatch:
    inputs:
      PR-number:
        description: "Pull request number."
        required: true
      context-ref:
        description: "Context in which the workflow runs. If PR is from a fork, will be the PR target branch (general case). If PR is NOT from a fork, will be the PR branch itself (this allows committers to test changes to workflows directly from PRs)."
        required: true
      SHA:
        description: "SHA under test (head of the PR branch)."
        required: true
      base-SHA:
        description: "SHA of the base branch (target branch of the PR)."
        required: false
      extra-args:
        description: "[JSON object] Arbitrary arguments passed from the trigger comment via regex capture group. Parse with 'fromJson(inputs.extra-args).argName' in workflow."
        required: false
        default: "{}"
  # Run every 8 hours
  schedule:
    - cron: "0 2/8 * * *"

# By specifying the access of one of the scopes, all of those that are not
# specified are set to 'none'.
permissions:
  # To read actions state with catchpoint/workflow-telemetry-action
  actions: read
  # To be able to access the repository with actions/checkout
  contents: read
  # To allow retrieving information from the PR API
  pull-requests: read
  # To be able to set commit status
  statuses: write

concurrency:
  # Structure:
  # - Workflow name
  # - Event type
  # - A unique identifier depending on event type:
  #   - schedule: SHA
  #   - workflow_dispatch: PR number
  #
  # This structure ensures a unique concurrency group name is generated for each
  # type of testing, such that re-runs will cancel the previous run.
  group: |
    ${{ github.workflow }}
    ${{ github.event_name }}
    ${{
      (github.event_name == 'schedule' && github.sha) ||
      (github.event_name == 'workflow_dispatch' && github.event.inputs.PR-number)
    }}
  cancel-in-progress: true

env:
  cilium_cli_ci_version:

jobs:
  echo-inputs:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    name: Echo Workflow Dispatch Inputs
    runs-on: ubuntu-24.04
    steps:
      - name: Echo Workflow Dispatch Inputs
        run: |
          echo '${{ tojson(inputs) }}'

  commit-status-start:
    name: Commit Status Start
    runs-on: ubuntu-24.04
    steps:
      - name: Set initial commit status
        uses: myrotvorets/set-commit-status-action@3730c0a348a2ace3c110851bed53331bc6406e9f # v2.0.1
        with:
          sha: ${{ inputs.SHA || github.sha }}

  setup-and-test:
    runs-on: ${{ vars.GH_RUNNER_EXTRA_POWER }}
    name: "Setup & Test"
    env:
      job_name: "Setup & Test"
    strategy:
      fail-fast: false
      max-parallel: 10
      matrix:
        include:
          - name: "0"
            mode: "multi-node"
            kind-ip-family: "ipv4"
            kernel: "6.1-20240710.064909"
            use-remote-address: "true"
            xff-num-trusted-hops: 0
            nr-of-worker-nodes: 4
            t1-nodes: "kind-control-plane kind-worker"
            t2-nodes: "kind-worker2 kind-worker3 kind-worker4"
            run-tests: ""
          - name: "1"
            mode: "single-node"
            kind-ip-family: "ipv4"
            kernel: "6.1-20240710.064909"
            use-remote-address: "true"
            xff-num-trusted-hops: 0
            nr-of-worker-nodes: 4
            t1-nodes: "kind-control-plane kind-worker"
            t2-nodes: "kind-worker2 kind-worker3 kind-worker4"
            run-tests: ""
          - name: "2"
            mode: "single-node"
            kind-ip-family: "ipv4"
            kernel: "6.1-20240710.064909"
            use-remote-address: "false"
            xff-num-trusted-hops: 2
            nr-of-worker-nodes: 4
            t1-nodes: "kind-control-plane kind-worker"
            t2-nodes: "kind-worker2 kind-worker3 kind-worker4"
            run-tests: ""
          - name: "3" # in-cluster where all nodes are T1 & T2
            mode: "multi-node"
            kind-ip-family: "ipv4"
            kernel: "6.1-20240710.064909"
            use-remote-address: "true"
            xff-num-trusted-hops: 0
            nr-of-worker-nodes: 4
            t1t2-nodes: "kind-control-plane kind-worker kind-worker2 kind-worker3 kind-worker4"
            run-tests: ""
          - name: "4" # single k8s node deployment where the single node is T1 & T2
            mode: "multi-node"
            kind-ip-family: "ipv4"
            kernel: "6.1-20240710.064909"
            use-remote-address: "true"
            xff-num-trusted-hops: 0
            nr-of-worker-nodes: 0
            t1t2-nodes: "kind-control-plane"
            run-tests: ""
          - name: "5"
            mode: "multi-node"
            kind-ip-family: "dual"
            kernel: "6.1-20240710.064909"
            use-remote-address: "true"
            xff-num-trusted-hops: 0
            nr-of-worker-nodes: 4
            t1-nodes: "kind-control-plane kind-worker"
            t2-nodes: "kind-worker2 kind-worker3 kind-worker4"
            run-tests: ""
          - name: "6"
            mode: "multi-node"
            kind-ip-family: "ipv6"
            kernel: "6.1-20240710.064909"
            use-remote-address: "true"
            xff-num-trusted-hops: 0
            nr-of-worker-nodes: 4
            t1-nodes: "kind-control-plane kind-worker"
            t2-nodes: "kind-worker2 kind-worker3 kind-worker4"
            # Only execute ipv6 only tests (vip & backend).
            # Most tests still use ipv4 addresses.
            run-tests: ".*IPv6VIPIPv6Backend.*"

    timeout-minutes: 120

    steps:
      - name: Collect Workflow Telemetry
        uses: catchpoint/workflow-telemetry-action@94c3c3d9567a0205de6da68a76c428ce4e769af1 # v2.0.0
        with:
          comment_on_pr: false

      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          ref: ${{ inputs.SHA || 'main-ce' }}
          persist-credentials: false

      - name: Set Environment Variables
        uses: ./.github/actions/set-env-variables

      - name: Set up job variables
        id: vars
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            SHA="${{ inputs.SHA }}"
          else
            SHA="${{ github.sha }}"
          fi
          echo sha=${SHA} >> $GITHUB_OUTPUT

          echo kind-params="--xdp \"\" ${{ matrix.nr-of-worker-nodes }} \"\" \"\" \"none\" \"${{ matrix.kind-ip-family }}\"" >> $GITHUB_OUTPUT

      - name: Install Cilium CLI
        uses: cilium/cilium-cli@e875161a362b9092ff3e1110eccf52a9fdb17c0a # v0.18.9
        with:
          skip-build: ${{ env.CILIUM_CLI_SKIP_BUILD }}
          image-repo: ${{ env.CILIUM_CLI_IMAGE_REPO }}
          image-tag: ${{ steps.vars.outputs.sha }}
          repository: ${{ env.CILIUM_CLI_RELEASE_REPO }}
          release-version: ${{ env.CILIUM_CLI_VERSION }}

      - name: Provision K8s control-plane on LVH VM
        uses: ./.github/actions/lvh-kind
        with:
          test-name: enterprise-lb
          kernel: ${{ matrix.kernel }}
          kind-params: "${{ steps.vars.outputs.kind-params }}"
          kind-image: ${{ env.KIND_K8S_IMAGE }}
          port-forward: "6443:6443,22375:2375,22376:22376"

      - name: Label T1 nodes
        if: ${{ matrix.t1-nodes != '' }}
        shell: bash
        run: |
          export DOCKER_HOST="tcp://127.0.0.1:22375"
          kubectl label node ${{ matrix.t1-nodes }} service.cilium.io/node=t1

      - name: Label T2 nodes
        if: ${{ matrix.t2-nodes != '' }}
        shell: bash
        run: |
          export DOCKER_HOST="tcp://127.0.0.1:22375"
          kubectl label node ${{ matrix.t2-nodes }} service.cilium.io/node=t2

      - name: Label T1&T2 nodes
        if: ${{ matrix.t1t2-nodes != '' }}
        shell: bash
        run: |
          export DOCKER_HOST="tcp://127.0.0.1:22375"
          kubectl label node ${{ matrix.t1t2-nodes }} service.cilium.io/node=t1-t2

      - name: Configure unprivileged port range
        shell: bash
        run: |
          export DOCKER_HOST="tcp://127.0.0.1:22375"
          kind get nodes --name kind  | xargs -I container_name docker exec container_name sysctl -w net.ipv4.ip_unprivileged_port_start=0

      - name: Create testing host (single-node)
        id: single-node
        if: ${{ matrix.mode == 'single-node' }}
        shell: bash
        run: |
          export DOCKER_HOST="tcp://127.0.0.1:22375"

          # Create DIND container to simulate the testing host
          docker run -d --name testing-host --env DOCKER_TLS_CERTDIR="" -p 22376:2375 --privileged --network ${{ env.KIND_EXPERIMENTAL_DOCKER_NETWORK }} docker:27.3.1-dind
          ip=$(docker inspect '--format={{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' testing-host)
          echo ip=${ip} >> $GITHUB_OUTPUT

      - name: Wait for images to be available
        timeout-minutes: 30
        shell: bash
        run: |
          for image in cilium-ci operator-generic-ci hubble-relay-ci ; do
            until docker manifest inspect quay.io/${{ env.QUAY_ORGANIZATION_DEV }}/$image:${{ steps.vars.outputs.sha }} &> /dev/null; do sleep 45s; done
          done

      - name: Install Isovalent LB
        shell: bash
        run: |
          EXTRA=""
          if [ "${{ matrix.use-remote-address }}" != "" ]; then
            EXTRA+=" --helm-set-string=extraConfig.use-remote-address=${{ matrix.use-remote-address }}"
          fi

          if [ "${{ matrix.xff-num-trusted-hops }}" != "" ]; then
            EXTRA+=" --helm-set-string=extraConfig.loadbalancer-cp-t2-xff-num-trusted-hops=${{ matrix.xff-num-trusted-hops }}"
          fi

          if [[ "${{ matrix.kind-ip-family }}" == "ipv6" || "${{ matrix.kind-ip-family }}" == "dual" ]]; then
            EXTRA+=" --helm-set=enableIPv6Masquerade=true"
            EXTRA+=" --helm-set=ipv6NativeRoutingCIDR=fd99::0/64"
            EXTRA+=" --helm-set=ipv6.enabled=true"
          fi

          if [[ "${{ matrix.kind-ip-family }}" == "ipv4" || "${{ matrix.kind-ip-family }}" == "dual" ]]; then
            EXTRA+=" --helm-set=enableIPv4Masquerade=true"
            EXTRA+=" --helm-set=ipv4NativeRoutingCIDR=10.244.0.0/16"
            EXTRA+=" --helm-set=ipv4.enabled=true"
          fi

          if [[ "${{ matrix.kind-ip-family }}" == "ipv6" ]]; then
            EXTRA+=" --helm-set=ipv4.enabled=false" # explicitly disable ipv4
          fi

          cilium install \
             --wait --chart-directory=./install/kubernetes/cilium \
             --helm-set=image.repository=quay.io/isovalent-dev/cilium-ci \
             --helm-set=image.useDigest=false \
             --helm-set=image.tag=${{ steps.vars.outputs.sha }} \
             --helm-set=operator.image.repository=quay.io/isovalent-dev/operator \
             --helm-set=operator.image.suffix=-ci \
             --helm-set=operator.image.tag=${{ steps.vars.outputs.sha }} \
             --helm-set=operator.image.useDigest=false \
             --helm-set=hubble.relay.image.repository=quay.io/isovalent-dev/hubble-relay-ci \
             --helm-set=hubble.relay.image.tag=${{ steps.vars.outputs.sha }} \
             --helm-set=hubble.relay.image.useDigest=false \
             --helm-set=enterprise.loadbalancer.enabled=true \
             --helm-set=enterprise.bgpControlPlane.enabled=true \
             --helm-set=enterprise.bgpControlPlane.enableServiceHealthChecking=true \
             --helm-set=enterprise.bgpControlPlane.nodeMaintenance.withdrawTime=1ms \
             --helm-set=enterprise.bfd.enabled=true \
             --helm-set=enterprise.featureGate.minimumMaturity=Alpha \
             --helm-set=debug.enabled=true \
             --helm-set=debug.verbose="envoy datapath" \
             --helm-set=envoy.dnsPolicy=ClusterFirstWithHostNet \
             --helm-set=envoy.startupProbe.enabled=false \
             --helm-set=envoy.livenessProbe.enabled=false \
             --helm-set=envoyConfig.enabled=true \
             --helm-set=bpf.monitorAggregation=none \
             --helm-set=bpf.lbAlgorithmAnnotation=true \
             --helm-set=bpf.lbModeAnnotation=true \
             --helm-set=bpf.masquerade=true \
             --helm-set=kubeProxyReplacement=true \
             --helm-set=routingMode=native \
             --helm-set=autoDirectNodeRoutes=true \
             --helm-set=loadBalancer.acceleration=native \
             --helm-set=loadBalancer.dsrDispatch=ipip \
             --helm-set-string=extraConfig.loadbalancer-cp-accesslog-enable-hc=true \
             --helm-set-string=extraConfig.loadbalancer-cp-accesslog-file-path=/var/log/envoy-accesslog.log \
             --helm-set-string=extraConfig.loadbalancer-cp-t1-hc-probe-timeout-seconds=10 \
             --helm-set-string=extraConfig.loadbalancer-flow-logs-enabled=true \
             --helm-set-string=extraConfig.loadbalancer-flow-logs-sender=stdout \
             $EXTRA

          cilium status --wait
          kubectl get pods --all-namespaces -o wide
          kubectl -n kube-system exec daemonset/cilium -- cilium-dbg status

      - name: Run tests
        shell: bash
        run: |
          PARAMS="--sysdump-on-failure=true"
          PARAMS+=" --sysdump-output-filename=cilium-sysdump-${{ matrix.name }}.zip"
          if [ "${{ matrix.mode }}" == "single-node" ]; then
            export DOCKER_HOST="tcp://127.0.0.1:22376"
            PARAMS+=" --mode=single-node"
          else
            export DOCKER_HOST="tcp://127.0.0.1:22375"
          fi

          if [ "${{ matrix.use-remote-address }}" != "" ]; then
            PARAMS+=" --use-remote-address=${{ matrix.use-remote-address }}"
          fi

          if [ "${{ matrix.xff-num-trusted-hops }}" != "" ]; then
            PARAMS+=" --xff-num-trusted-hops=${{ matrix.xff-num-trusted-hops }}"
          fi
          PARAMS+=" --network-name=${{ env.KIND_EXPERIMENTAL_DOCKER_NETWORK }}"

          if [ -n "${{ matrix.run-tests }}" ]; then
            runTests="${{ matrix.run-tests }}"
            runTests=${runTests//;/$'\n'}
            for test in $runTests
            do
              PARAMS+=" --run=$test"
            done
          fi

          DOCKER_API_VERSION=1.45 cilium lb test --verbose=true $PARAMS

      - name: Download T2 Envoy accesslogs from Pods
        if: ${{ !success() }}
        shell: bash
        run: |
          for pod in $(kubectl -n kube-system get pods -l app.kubernetes.io/name=cilium-envoy --no-headers -o custom-columns=NAME:metadata.name); do
            echo "Downloadinmg accesslog from Pod $pod..."
            kubectl -n kube-system cp $pod:/var/log/envoy-accesslog.log "cilium-envoy-accesslog-$pod.log"
          done

      - name: Upload T2 Envoy accesslogs
        if: ${{ !success() }}
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: cilium-envoy-accesslogs-${{ matrix.name }}
          path: cilium-envoy-accesslog-*.log
          retention-days: 5

      - name: Run common post steps
        if: ${{ always() }}
        uses: ./.github/actions/post-logic
        with:
          artifacts_suffix: "${{ matrix.name }}"
          job_status: "${{ job.status }}"

  merge-upload-and-status:
    name: Merge Upload and Status
    if: ${{ always() }}
    needs: setup-and-test
    uses: ./.github/workflows/common-post-jobs.yaml
    secrets: inherit
    with:
      context-ref: ${{ inputs.context-ref || github.sha }}
      sha: ${{ inputs.SHA || github.sha }}
      success: ${{ needs.setup-and-test.result == 'success' }}
