name: Panda Scale Test (ci-panda-scale)

on:
#  schedule:
#    - cron: '39 0 * * 1-5'

  workflow_dispatch:
    inputs:
      PR-number:
        description: "Pull request number."
        required: true
      context-ref:
        description: "Context in which the workflow runs. If PR is from a fork, will be the PR target branch (general case). If PR is NOT from a fork, will be the PR branch itself (this allows committers to test changes to workflows directly from PRs)."
        required: true
      SHA:
        description: "SHA under test (head of the PR branch)."
        required: true
      extra-args:
        description: "[JSON object] Arbitrary arguments passed from the trigger comment via regex capture group. Parse with 'fromJson(inputs.extra-args).argName' in workflow."
        required: false
        default: '{}'

permissions:
  # To be able to access the repository with actions/checkout
  contents: read
  # To be able to request the JWT from GitHub's OIDC provider
  id-token: write
  # To allow retrieving information from the PR API
  pull-requests: read
  # To be able to set commit status
  statuses: write

concurrency:
  # Structure:
  # - Workflow name
  # - Event type
  # - A unique identifier depending on event type:
  #   - schedule: SHA
  #   - workflow_dispatch: PR number
  #
  # This structure ensures a unique concurrency group name is generated for each
  # type of testing, such that re-runs will cancel the previous run.
  group: |
    ${{ github.workflow }}
    ${{ github.event_name }}
    ${{
      (github.event_name == 'schedule' && github.sha) ||
      (github.event_name == 'workflow_dispatch' && github.event.inputs.PR-number)
    }}
  cancel-in-progress: false

env:
  # renovate: datasource=golang-version depName=go
  go_version: 1.23.2
  cilium_cli_ci_version:
  # Adding k8s.local to the end makes kops happy-
  # has stricter DNS naming requirements.
  test_name: panda-scale
  cluster_name: ${{ github.run_id }}-${{ github.run_attempt }}
  # Domain name for GCP nodes. Used for TLS auth in the kvstore.
  # Project is set up with zonal DNS, but reverse lookups on IPs
  # return global DNS names without the zone. Since etcd will perform
  # a reverse lookup on connecting peers to check if their DNS name
  # matches a SAN wildcard, the zone is left off of the domain.
  # For more information, see
  # https://cloud.google.com/compute/docs/internal-dns and
  # https://etcd.io/docs/v3.4/op-guide/security/ (search
  # 'server supports reverse-lookup on wildcard DNS SAN').
  domain: c.${{ secrets.GCP_PERF_PROJECT_ID }}.internal
  # renovate: datasource=docker depName=google/cloud-sdk
  gcloud_version: 504.0.1

  # renovate: datasource=github-releases depName=cert-manager/cert-manager
  cert_manager_version: v1.16.2
  # renovate: datasource=github-releases depName=cert-manager/trust-manager
  trust_manager_version: v0.14.0

jobs:
  echo-inputs:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    name: Echo Workflow Dispatch Inputs
    runs-on: ubuntu-24.04
    steps:
      - name: Echo Workflow Dispatch Inputs
        run: |
          echo '${{ tojson(inputs) }}'

  commit-status-start:
    name: Commit Status Start
    runs-on: ubuntu-latest
    steps:
      - name: Set initial commit status
        uses: myrotvorets/set-commit-status-action@3730c0a348a2ace3c110851bed53331bc6406e9f # v2.0.1
        with:
          sha: ${{ inputs.SHA || github.sha }}

  install-and-scaletest:
    runs-on: ubuntu-latest
    name: Install and Scale Test
    timeout-minutes: 150
    steps:
      - name: Checkout context ref (trusted)
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ inputs.context-ref || github.sha }}
          persist-credentials: false

      - name: Set Environment Variables
        uses: ./.github/actions/set-env-variables

      - name: Set up job variables
        id: vars
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ] ; then
            SHA="${{ inputs.SHA }}"
          else
            SHA="${{ github.sha }}"
          fi

          # Adding k8s.local to the end makes kops happy
          # has stricter DNS naming requirements.
          CLUSTER_NAME="${{ env.test_name }}-${{ env.cluster_name }}.k8s.local"

          cat<<'EOF' > values-export-aggregation.yaml
          extraConfig:
            export-aggregation: connection
            export-aggregation-ignore-source-port: "true"
            export-aggregation-state-filter: new closed established error
            export-flow-allowlist: |-
              {"verdict":["DROPPED", "ERROR"]}
              {"event_type":[{"type":5}]}
              {"destination_identity":[2]}
            export-flow-denylist: |-
              {"reply":[true], "event_type":[{"type":4}]}
              {"source_label":["reserved:health"]}
              {"destination_label":["reserved:health"]}
              {"dns_query":[".*\\.local\\.$", ".*\\.internal\\.$"]}
              {"verdict":["DROPPED"],"event_type":[{"type":1,"match_sub_type":true,"sub_type":139}]}
              {"destination_ip":["10.0.0.0/8"]}
              {"source_label":["k8s:app.kubernetes.io/name=cloudprober"]}
              {"source_label":["reserved:host"]}
              {"source_label":["k8s:app.kubernetes.io/name=network-monitor"]}
              {"source_label":["k8s:app=victoriametrics"]}
          EOF

          cat<<'EOF' > values-hubble-metrics.yaml
          hubble:
            metrics:
              enabled:
              - policy:labelsContext=source_namespace,source_workload,source_app,destination_namespace,destination_workload,destination_app,traffic_direction;sourceContext=dns|reserved-identity;destinationContext=dns|reserved-identity
              - drop:labelsContext=source_namespace,source_workload,source_app,destination_namespace,destination_workload,destination_app,traffic_direction;sourceContext=dns|reserved-identity;destinationContext=dns|reserved-identity
              - httpV2:exemplars=true;labelsContext=source_namespace,source_workload,source_app,destination_namespace,destination_workload,destination_app,traffic_direction;sourceContext=dns|reserved-identity;destinationContext=dns|reserved-identity
          EOF

          CILIUM_INSTALL_DEFAULTS="--chart-directory=install/kubernetes/cilium \
            --helm-set=pprof.enabled=true \
            --helm-set=prometheus.enabled=true \
            --helm-set=operator.prometheus.enabled=true \
            --helm-set=envoy.prometheus.enabled=true \
            --helm-set=cluster.name=${{ env.cluster_name }} \
            --helm-set=k8sServiceHost=api.internal.${CLUSTER_NAME} \
            --helm-set=k8sServicePort=443 \
            --helm-set=kubeProxyReplacement=true \
            --helm-set=healthChecking=false \
            --helm-set=monitor.enabled=false \
            --helm-set=routingMode=tunnel \
            --helm-set=operator.replicas=1 \
            --helm-set=envoyConfig.enabled=true \
            --helm-set=envoy.enabled=true \
            --helm-set=envoy.updateStrategy.rollingUpdate.maxUnavailable=10% \
            --helm-set-string=extraConfig.external-dns-proxy=true \
            --helm-set-string=extraConfig.kvstore-pod-network-support=false \
            --helm-set-string=extraConfig.monitor-aggregation-interval=10m \
            --helm-set-string=extraConfig.use-full-tls-context=false \
            --helm-set=localRedirectPolicy=true \
            --helm-set=operator.extraArgs[0]="--k8s-client-qps=100" \
            --helm-set=operator.extraArgs[1]="--k8s-client-burst=100" \
            --helm-set=dnsProxy.proxyResponseMaxDelay=250ms \
            --helm-set=bpf.policyMapMax=65536 \
            --helm-set=dnsProxy.minTtl=300 \
            --helm-set=hubble.enabled=true \
            --helm-set=hubble.eventBufferCapacity=65535 \
            --helm-set=updateStrategy.rollingUpdate.maxUnavailable=10% \
            --values=values-export-aggregation.yaml \
            --values=values-hubble-metrics.yaml \
            --wait=false"

          CILIUM_INSTALL_DEFAULTS+=" --helm-set=image.repository=quay.io/${{ env.QUAY_ORGANIZATION_DEV }}/cilium-ci \
          --helm-set=image.useDigest=false \
          --helm-set=image.tag=${SHA} \
          --helm-set=operator.image.repository=quay.io/${{ env.QUAY_ORGANIZATION_DEV }}/operator \
          --helm-set=operator.image.suffix=-ci \
          --helm-set=operator.image.tag=${SHA} \
          --helm-set=operator.image.useDigest=false \
          --helm-set=clustermesh.apiserver.image.repository=quay.io/${{ env.QUAY_ORGANIZATION_DEV }}/clustermesh-apiserver-ci \
          --helm-set=clustermesh.apiserver.image.tag=${SHA} \
          --helm-set=clustermesh.apiserver.image.useDigest=false \
          --helm-set=hubble.relay.image.repository=quay.io/${{ env.QUAY_ORGANIZATION_DEV }}/hubble-relay-ci \
          --helm-set=hubble.relay.image.tag=${SHA} \
          --helm-set=hubble.relay.image.useDigest=false"

          echo SHA=${SHA} >> $GITHUB_OUTPUT
          echo cilium_install_defaults=${CILIUM_INSTALL_DEFAULTS} >> $GITHUB_OUTPUT
          echo CLUSTER_NAME=${CLUSTER_NAME} >> $GITHUB_OUTPUT

      - name: Wait for images to be available
        timeout-minutes: 30
        shell: bash
        run: |
          for image in cilium-ci operator-generic-ci hubble-relay-ci cilium-dnsproxy-ci; do
            until docker manifest inspect quay.io/${{ env.QUAY_ORGANIZATION_DEV }}/$image:${{ steps.vars.outputs.SHA }} &> /dev/null; do sleep 45s; done
          done

      - name: Install Go
        uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed # v5.1.0
        with:
          go-version: ${{ env.go_version }}

      - name: Install Kops
        uses: cilium/scale-tests-action/install-kops@d3ecfd83003f3e9c98ba125ca14933401d44918f # main

      - name: Setup gcloud credentials
        uses: google-github-actions/auth@6fc4af4b145ae7821d527454aa9bd537d1f2dc5f # v2.1.7
        with:
          workload_identity_provider: ${{ secrets.GCP_PERF_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_PERF_SA }}
          create_credentials_file: true
          export_environment_variables: true

      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@6189d56e4096ee891640bb02ac264be376592d6a # v2.1.2
        with:
          project_id: ${{ secrets.GCP_PERF_PROJECT_ID }}
          version: ${{ env.gcloud_version }}

      - name: Clone ClusterLoader2
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          repository: kubernetes/perf-tests
          # Avoid using renovate to update this dependency because: (1)
          # perf-tests does not tag or release, so renovate will pull
          # all updates to the default branch and (2) continually
          # updating CL2 may impact the stability of the scale test
          # results.
          ref: ce821d6232cee6719dd86e7e68eee361e337e92a
          persist-credentials: false
          sparse-checkout: clusterloader2
          path: perf-tests

      - name: Setup CL2
        run: |
          # CL2 needs ssh access to control plane nodes
          gcloud compute config-ssh

          # Copy the custom configs to the folder where CL2 expects them.
          cp -r .github/actions/cl2-modules ./perf-tests/clusterloader2/testing/custom

          cd ./perf-tests/clusterloader2

          go build ./cmd/clusterloader.go

      - name: Install Cilium CLI
        uses: cilium/cilium-cli@6977c4a640ad45da3a95eb12054497f2bdd22c48 # v0.16.19
        with:
          repository: ${{ env.CILIUM_CLI_RELEASE_REPO }}
          release-version: ${{ env.CILIUM_CLI_VERSION }}
          ci-version: ${{ env.cilium_cli_ci_version }}

      - name: Display version info of installed tools
        run: |
          echo "--- go ---"
          go version
          echo "--- cilium-cli ---"
          cilium version --client
          echo "--- kops ---"
          ./kops version
          echo "--- gcloud ---"
          gcloud version

      - name: Deploy cluster
        id: deploy-cluster
        uses: cilium/scale-tests-action/create-cluster@d3ecfd83003f3e9c98ba125ca14933401d44918f # main
        timeout-minutes: 30
        with:
          cluster_name: ${{ steps.vars.outputs.cluster_name }}
          control_plane_size: n1-standard-8
          control_plane_count: 1
          node_size: e2-standard-8
          node_count: 1
          kops_state: ${{ secrets.GCP_PERF_KOPS_STATE_STORE }}
          project_id: ${{ secrets.GCP_PERF_PROJECT_ID }}
          kube_proxy_enabled: false

      - name: Create instance group for etcd
        uses: cilium/scale-tests-action/create-instance-group@d3ecfd83003f3e9c98ba125ca14933401d44918f # main
        timeout-minutes: 30
        with:
          cluster_name: ${{ steps.vars.outputs.cluster_name }}
          kops_state: ${{ secrets.GCP_PERF_KOPS_STATE_STORE }}
          node_size: e2-standard-8
          node_count: 3
          ig_name: etcd
          node_volume_size: 50

      - name: Setup firewall rules
        uses: cilium/scale-tests-action/setup-firewall@d3ecfd83003f3e9c98ba125ca14933401d44918f # main
        with:
          cluster_name: ${{ steps.vars.outputs.cluster_name }}
          create_native_routing_firewall: 'false'

      - name: Wait for etcd nodes to join the cluster
        timeout-minutes: 30
        shell: bash
        run: |
          set -x

          # "catch exit status 1" grep wrapper
          # https://stackoverflow.com/questions/6550484/prevent-grep-returning-an-error-when-input-doesnt-match/49627999#49627999
          c1grep() { grep "$@" || test $? = 1; }

          while true; do
            n="$(kubectl get nodes | c1grep etcd | wc -l)"
            if [ "$n" != "3" ]; then
              kubectl get nodes -o wide
              sleep 5
            else
              break
            fi
          done

      # This step is based off of .github/actions/kvstore/action.yaml but with
      # some changes, since we're not deploying to kind and we're not using clustermesh.
      - name: Create etcd Certificates
        shell: bash
        run: |
          set -x
          DIR=$(mktemp -d)

          # Generate the TLS certificates
          openssl genrsa 4096 >$DIR/kvstore-ca-key.pem
          openssl genrsa 4096 >$DIR/kvstore-server-key.pem
          openssl genrsa 4096 >$DIR/kvstore-client-key.pem

          openssl req -new -x509 -nodes -days 1 -subj "/CN=KVStore CA/" \
            -key $DIR/kvstore-ca-key.pem -out $DIR/kvstore-ca-crt.pem

          # The SAN used here is based off of the DNS names assigned to
          # the internal IPs of the GCP nodes which will run etcd.
          # Since we're running on the host network, these names can be
          # reused here.
          openssl req -new -x509 -nodes -days 1 -subj "/CN=etcd/" \
            -addext "subjectAltName=DNS:*.${{ env.domain }}" \
            -key $DIR/kvstore-server-key.pem -out $DIR/kvstore-server-crt.pem \
            -CA $DIR/kvstore-ca-crt.pem -CAkey $DIR/kvstore-ca-key.pem

          # For the client cert, set the CN to "root" to enable easy RBAC.
          # See https://etcd.io/docs/v3.5/op-guide/authentication/rbac/.
          openssl req -new -x509 -nodes -days 1 -subj "/CN=root/" \
            -key $DIR/kvstore-client-key.pem -out $DIR/kvstore-client-crt.pem \
            -CA $DIR/kvstore-ca-crt.pem -CAkey $DIR/kvstore-ca-key.pem

          # The client files are named based off of what cilium expects.
          kubectl create secret generic -n kube-system cilium-etcd-secrets \
            --from-file etcd-client-ca.crt=$DIR/kvstore-ca-crt.pem \
            --from-file etcd-client.crt=$DIR/kvstore-client-crt.pem \
            --from-file etcd-client.key=$DIR/kvstore-client-key.pem
          # This is just for etcd, but follows the same naming pattern.
          kubectl create secret generic -n kube-system etcd-server-secrets \
            --from-file etcd-server-ca.crt=$DIR/kvstore-ca-crt.pem \
            --from-file etcd-server.crt=$DIR/kvstore-server-crt.pem \
            --from-file etcd-server.key=$DIR/kvstore-server-key.pem

      - name: Deploy etcd
        id: etcd
        shell: bash
        run: |
          set -x

          # This is for brevity in the blocks below.
          domain="${{ env.domain }}"

          # Passed to etcd's --initial-cluster argument.
          etcd_initial_cluster=""
          # Extra arguments to pass to the cilium install command.
          helm_args=""

          i=0
          for name in $(kubectl get nodes -o custom-columns=NAME:.metadata.name --no-headers | grep etcd); do

            # Build the cluster list for the advertise urls.
            if [ -n "$etcd_initial_cluster" ]; then
              etcd_initial_cluster+=","
            fi
            etcd_initial_cluster+="${name}=https://${name}.${domain}:2380"

            # Build the helm arguments for cilium.
            helm_args+="--helm-set=etcd.endpoints[${i}]=https://${name}.${domain}:2379 "

            # Label and taint the node to reserve it for etcd.
            kubectl label node $name cilium.io/no-schedule=true app=etcd
            kubectl taint node $name etcd-ig:NoSchedule

            i=$((i+1))
          done

          echo "helm_args=${helm_args}" >> $GITHUB_OUTPUT

          # Deploy etcd.
          cat ./.github/actions/cl2-modules/panda/kvstore/etcd-pod.yaml | \
            sed "s|#REPLACE_ME_INITIAL_CLUSTER|${etcd_initial_cluster}|g" | \
            sed "s/#REPLACE_ME_DOMAIN/${domain}/g" | \
            kubectl apply -f -

      - name: Wait for the etcd cluster to be ready
        shell: bash
        run: |
          set -x
          if ! kubectl rollout status --timeout=30m -n kube-system statefulset/etcd; then
            kubectl get pods -A -o yaml
            kubectl describe -n kube-system statefulset/etcd -o yaml
            kubectl logs -n kube-system statefulset/etcd
            exit 1
          fi

      - name: Install Cilium
        run: |
          cilium_install_args="${{ steps.vars.outputs.cilium_install_defaults }} \
            --helm-set=identityAllocationMode=kvstore \
            --helm-set=etcd.enabled=true \
            --helm-set=etcd.ssl=true \
            ${{ steps.etcd.outputs.helm_args }}"

          cilium install --dry-run-helm-values $cilium_install_args
          cilium install $cilium_install_args

      - name: Install Cilium DNS proxy
        run: |
          helm install -n kube-system cilium-dnsproxy ./enterprise/fqdn-proxy/installation \
            --set image.repository=quay.io/${{ env.QUAY_ORGANIZATION_DEV }}/cilium-dnsproxy-ci \
            --set image.tag=${{ steps.vars.outputs.sha }} \
            --set metrics.enabled=true
          kubectl rollout status -n kube-system ds/cilium-dnsproxy --watch

      - name: Wait for cluster to be ready
        uses: cilium/scale-tests-action/validate-cluster@d3ecfd83003f3e9c98ba125ca14933401d44918f # main
        timeout-minutes: 20
        with:
          cluster_name: ${{ steps.vars.outputs.cluster_name }}
          kops_state: ${{ secrets.GCP_PERF_KOPS_STATE_STORE }}
          interval: 10s

      - name: Wait for Cilium status to be ready
        run: |
          cilium status --wait

      - name: Install cert-manager and trust-manager
        run: |
          helm repo add jetstack https://charts.jetstack.io

          helm install cert-manager \
            jetstack/cert-manager \
            --namespace cert-manager \
            --create-namespace \
            --version ${{ env.cert_manager_version }} \
            --set crds.enabled=true \
            --wait

          helm install trust-manager \
            jetstack/trust-manager \
            --namespace cert-manager \
            --version ${{ env.trust_manager_version }} \
            --set secretTargets.enabled=true \
            --set secretTargets.authorizedSecrets\[0]=tls-origination \
            --wait

      - name: Run CL2 to setup prometheus
        shell: bash
        working-directory: ./perf-tests/clusterloader2
        env:
          CL2_PROMETHEUS_PVC_ENABLED: "false"
          CL2_PROMETHEUS_SCRAPE_CILIUM_OPERATOR: "true"
          CL2_PROMETHEUS_SCRAPE_CILIUM_AGENT: "true"
          CL2_PROMETHEUS_MEMORY_SCALE_FACTOR: 4.0
        timeout-minutes: 10
        run: |
          # Don't run any tasks at this point, just setup the monitoring stack
          ./clusterloader \
            -v=2 \
            --prometheus-additional-monitors-path=./testing/custom/panda/monitors/ \
            --testconfig=./testing/custom/common/setup.yaml \
            --testoverrides=./testing/prometheus/not-scrape-kube-proxy.yaml \
            --provider=gce \
            --enable-exec-service=false \
            --enable-prometheus-server \
            --prometheus-scrape-kubelets=true \
            --prometheus-scrape-master-kubelets=true \
            --tear-down-prometheus-server=false \
            --kubeconfig=$HOME/.kube/config \
            2>&1 | tee cl2-setup.txt

      - name: Setup LRP
        run: |
          kubedns=$(kubectl get svc kube-dns -n kube-system -o jsonpath={.spec.clusterIP}) && sed -i "s/__PILLAR__DNS__SERVER__/$kubedns/g;" ./examples/kubernetes-local-redirect/node-local-dns.yaml
          kubectl apply -f ./examples/kubernetes-local-redirect/node-local-dns.yaml
          kubectl rollout status daemonset node-local-dns -n kube-system
          kubectl apply -f ./examples/kubernetes-local-redirect/node-local-dns-lrp.yaml

      - name: Setup Certificates and Cloudprober
        run: |
          kubectl apply -f ./perf-tests/clusterloader2/testing/custom/panda/manifests/certificates.yaml
          kubectl wait --for=condition=Ready -n cilium-secrets certificate/tls-termination
          kubectl wait --for=condition=Synced bundle/tls-origination
          kubectl wait --for=condition=Synced bundle/tls-interception

          kubectl apply -f ./perf-tests/clusterloader2/testing/custom/panda/manifests/policy.yaml
          kubectl create configmap cloudprober-config --from-file=cloudprober.cfg=./perf-tests/clusterloader2/testing/custom/panda/manifests/cloudprober.cfg
          kubectl apply -f ./perf-tests/clusterloader2/testing/custom/panda/manifests/cloudprober.yaml
          kubectl rollout status daemonset cloudprober
          kubectl apply -f ./perf-tests/clusterloader2/testing/custom/panda/manifests/cloudprober-host.yaml
          kubectl rollout status daemonset cloudprober-host

      - name: Create Instance Group for workload deployments
        uses: cilium/scale-tests-action/create-instance-group@d3ecfd83003f3e9c98ba125ca14933401d44918f # main
        timeout-minutes: 30
        with:
          cluster_name: ${{ steps.vars.outputs.cluster_name }}
          node_size: e2-medium
          node_count: 100
          ig_name: workloads
          kops_state: ${{ secrets.GCP_PERF_KOPS_STATE_STORE }}

      - name: Wait for cluster to be ready
        uses: cilium/scale-tests-action/validate-cluster@d3ecfd83003f3e9c98ba125ca14933401d44918f # main
        timeout-minutes: 20
        with:
          cluster_name: ${{ steps.vars.outputs.cluster_name }}
          kops_state: ${{ secrets.GCP_PERF_KOPS_STATE_STORE }}
          interval: 10s

      # Need to rerun this action, as the firewall rule is reset after
      # an instance group is created.
      - name: Setup firewall rules
        uses: cilium/scale-tests-action/setup-firewall@d3ecfd83003f3e9c98ba125ca14933401d44918f # main
        with:
          cluster_name: ${{ steps.vars.outputs.cluster_name }}
          create_native_routing_firewall: 'false'

      - name: Wait for Cilium status to be ready
        run: |
          cilium status --wait
          kubectl rollout status -n kube-system ds/cilium-dnsproxy --watch
          kubectl rollout status daemonset cloudprober-host
          kubectl rollout status daemonset cloudprober
          kubectl rollout status daemonset node-local-dns -n kube-system

      - name: Run CL2
        id: run-cl2
        working-directory: ./perf-tests/clusterloader2
        shell: bash
        timeout-minutes: 60
        env:
          CL2_PROMETHEUS_PVC_ENABLED: "false"
          CL2_PROMETHEUS_SCRAPE_CILIUM_OPERATOR: "true"
          CL2_PROMETHEUS_SCRAPE_CILIUM_AGENT: "true"
          CL2_PROMETHEUS_MEMORY_SCALE_FACTOR: 4.0
          CL2_DELETE_AUTOMANAGED_NAMESPACES: "false"
        run: |
          ./clusterloader \
            -v=2 \
            --prometheus-additional-monitors-path=./testing/panda/monitors/ \
            --testconfig=./testing/custom/panda/config.yaml \
            --testoverrides=./testing/prometheus/not-scrape-kube-proxy.yaml \
            --provider=gce \
            --enable-prometheus-server \
            --prometheus-scrape-kubelets=true \
            --prometheus-scrape-master-kubelets=true \
            --tear-down-prometheus-server=false \
            --nodes=100 \
            --report-dir=./report \
            --experimental-prometheus-snapshot-to-report-dir=true \
            --kubeconfig=$HOME/.kube/config \
            2>&1 | tee cl2-output.txt

      - name: Get sysdump
        if: ${{ always() && steps.run-cl2.outcome != 'skipped' && steps.run-cl2.outcome != 'cancelled' }}
        run: |
          cilium status
          cilium sysdump --output-filename cilium-sysdump-final
          sudo chmod +r cilium-sysdump-final.zip

      - name: Cleanup cluster
        if: ${{ always() && steps.deploy-cluster.outcome != 'skipped' }}
        uses: cilium/scale-tests-action/cleanup-cluster@d3ecfd83003f3e9c98ba125ca14933401d44918f # main
        with:
          cluster_name: ${{ steps.vars.outputs.cluster_name }}
          kops_state: ${{ secrets.GCP_PERF_KOPS_STATE_STORE }}

      - name: Export results and sysdump to GS bucket
        if: ${{ always() && steps.run-cl2.outcome != 'skipped' && steps.run-cl2.outcome != 'cancelled' }}
        uses: cilium/scale-tests-action/export-results@d3ecfd83003f3e9c98ba125ca14933401d44918f # main
        with:
          test_name: ${{ env.test_name }}
          results_bucket: ${{ env.GCP_PERF_RESULTS_BUCKET }}
          artifacts: ./perf-tests/clusterloader2/report/*
          other_files: cilium-sysdump-final.zip ./perf-tests/clusterloader2/cl2-output.txt ./perf-tests/clusterloader2/cilium-sysdump-middle.zip

  commit-status-final:
    if: ${{ always() }}
    name: Commit Status Final
    needs: install-and-scaletest
    runs-on: ubuntu-latest
    steps:
      - name: Set final commit status
        uses: myrotvorets/set-commit-status-action@3730c0a348a2ace3c110851bed53331bc6406e9f # v2.0.1
        with:
          sha: ${{ inputs.SHA || github.sha }}
          status: ${{ needs.install-and-scaletest.result }}
