name: Conformance OpenShift (ci-openshift)

# Usage with Ariane (GitHub issue comment):
# `/ci-openshift {"kubevirt":"true", "ocp_version":"4.17.14", "kpr":"true", "ossm":"true", "hcp":"true", "region":"us-east-1"}`
# The json parameters are optional. By default no KubeVirt and no OpenShift Service Mesh conformance tests are launched.
# Bare-metal nodes get provisioned for running KubeVirt conformance tests, which is expensive.
# The default region is us-east-1.
#
# TODO: Possibility to test with IPSec enabled: --helm-set encryption.enabled=true --helm-set encryption.type=ipsec.
# IPSec keys would need to get generated.
# TODO: Run scheduled workflows for the head of each supported release branch
# TODO: Possibility to test with dual stack
# TODO: Make multi-arch builds and provision arm64 nodes
# TODO: Send notifications for scheduled runs (cf enterprise-cute.yaml)
# TODO: Provision a node with labels and annotations so that it runs without Cilium. It activates additional tests, e.g. BGP.

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths:
        - 'enterprise/olm/**'
        - 'install/kubernetes/**'
  workflow_dispatch:
    inputs:
      PR-number:
        description: "Pull request number."
        required: true
      context-ref:
        description: "Not used (enterprise only wf). Context in which the workflow runs. If PR is from a fork, will be the PR target branch (general case). If PR is NOT from a fork, will be the PR branch itself (this allows committers to test changes to workflows directly from PRs)."
        required: false
      SHA:
        description: "SHA under test (head of the PR branch)."
        required: true
      base-SHA:
        description: "SHA of the base branch (target branch of the PR)."
        required: false
      extra-args:
        description: "[JSON object] Arbitrary arguments passed from the trigger comment via regex capture group. Parse with 'fromJson(inputs.extra-args).argName' in workflow."
        required: false
        default: '{}'
  # Additionally run once a week at 4am on Monday
  # Scheduled workflows run for the head of main-ce
  schedule:
    - cron:  '0 4 * * MON,THU'
  # For the purpose of testing the workflow
  # push:
  #   branches:
  #     - 'yourbranch'

# By specifying the access of one of the scopes, all of those that are not
# specified are set to 'none'.
permissions:
  # To read actions state with catchpoint/workflow-telemetry-action.
  actions: read
  # To be able to access the repository with actions/checkout.
  contents: read
  # To allow retrieving information from the PR API.
  pull-requests: read
  # To be able to set commit status
  statuses: write
  # To be able to request the JWT from GitHub's OIDC provider.
  id-token: write

concurrency:
  # Structure:
  # - Workflow name
  # - Event type
  # - A unique identifier depending on event type:
  #   - schedule: SHA
  #   - pull_request: SHA
  #   - workflow_dispatch: PR number
  #
  # This structure ensures a unique concurrency group name is generated for each
  # type of testing, such that re-runs will cancel the previous run.
  group: |
    ${{ github.workflow }}
    ${{ github.event_name }}
    ${{
      (github.event_name == 'schedule' && github.sha) ||
      (github.event_name == 'pull_request' && github.sha) ||
      (github.event_name == 'workflow_dispatch' && github.event.inputs.PR-number)
    }}
  cancel-in-progress: true

env:
  clusterName: ${{ github.run_id }}-${{ github.run_attempt }}
  # renovate: datasource=docker depName=quay.io/openshift-release-dev/ocp-release
  ocp_version_multi: 4.19.11-multi
  pod_cidr: 10.244.0.0/16
  pod_cidr_host_prefix: 23

jobs:
  commit-status-start:
    name: Commit Status Start
    runs-on: ubuntu-24.04
    steps:
      - name: Echo Workflow Dispatch Inputs
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          echo '${{ tojson(inputs) }}'

      - name: Set initial commit status
        uses: myrotvorets/set-commit-status-action@3730c0a348a2ace3c110851bed53331bc6406e9f # v2.0.1
        with:
          sha: ${{ inputs.SHA || github.sha }}

  images:
    name: Prepare images
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    steps:
      - name: Checkout Cilium
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          ref: ${{ inputs.SHA || github.event.pull_request.head.sha }}
          persist-credentials: false

      - name: Cleanup Disk space in runner
        uses: ./.github/actions/disk-cleanup

      - name: Set up job variables
        id: vars
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            sha="${{ inputs.SHA }}"
          elif [ "${{ github.event_name }}" == 'schedule' ]; then
            sha="${{ github.sha }}"
          else
            sha="${{ github.event.pull_request.head.sha }}"
          fi
          echo sha=${sha} >> $GITHUB_OUTPUT

      - name: Wait for images to be available
        id: wait_images
        timeout-minutes: 30
        shell: bash
        run: |
          for image in cilium-ubi-ci operator-generic-ubi-ci hubble-relay-ubi-ci clustermesh-apiserver-ubi-ci; do
            until docker manifest inspect quay.io/isovalent-dev/$image:${{ steps.vars.outputs.sha }} &> /dev/null; do sleep 45s; done
          done
          echo "images available"
          # Some special handling is needed for clife as it does not get built for every push / PR, per default
          # only when enterprise/olm is modified.
          i=0
          until docker manifest inspect quay.io/isovalent-dev/clife-ci:${{ steps.vars.outputs.sha }} &> /dev/null || [[ "${i}" -gt 10 ]]; do sleep 30s; i=$((i + 1)); done
          if [[ "${i}" -gt 10 ]]; then
            echo "CLife rebuild needed"
            echo rebuild_clife='true' >> $GITHUB_OUTPUT
          else
            echo "Clife image available"
            echo rebuild_clife='false' >> $GITHUB_OUTPUT
          fi

      - name: Login to quay.io
        if: ${{ steps.wait_images.outputs.rebuild_clife  == 'true' }}
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME_CI }}
          password: ${{ secrets.QUAY_PASSWORD_CI }}

      - name: Login to registry.redhat.io for pulling images
        if: ${{ steps.wait_images.outputs.rebuild_clife  == 'true' }}
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          registry: registry.redhat.io
          username: ${{ secrets.REDHAT_USERNAME_CI }}
          password: ${{ secrets.REDHAT_PASSWORD_CI }}

      - name: Setup go
        if: ${{ steps.wait_images.outputs.rebuild_clife  == 'true' }}
        uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
        with:
          cache: false
          # renovate: datasource=golang-version depName=go
          go-version: 1.25.5

      - name: Build and Push CLife image
        if: ${{ steps.wait_images.outputs.rebuild_clife  == 'true' }}
        env:
          IMG: "quay.io/isovalent-dev/clife-ci:${{ steps.vars.outputs.sha }}"
          CL_TAG: "${{ steps.vars.outputs.sha }}"
        working-directory: ./enterprise/olm
        run: |
          make docker-buildx VERSION=${{ steps.vars.outputs.sha }}

  installation-and-connectivity:
    name: Installation and Connectivity Test
    runs-on: ubuntu-24.04
    needs: [images]
    timeout-minutes: 360
    steps:
      - name: Collect Workflow Telemetry
        uses: catchpoint/workflow-telemetry-action@94c3c3d9567a0205de6da68a76c428ce4e769af1 # v2.0.0
        with:
          comment_on_pr: false

      - name: Checkout Cilium
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          ref: ${{ inputs.SHA || github.event.pull_request.head.sha }}
          persist-credentials: false

      - name: Cleanup Disk space in runner
        uses: ./.github/actions/disk-cleanup

      - name: Set Environment Variables
        uses: ./.github/actions/set-env-variables

      - name: Get connectivity test flag
        id: e2e_config
        uses: ./.github/actions/cli-test-config
        with:
          hubble: false

      - name: Set up job variables
        id: vars
        run: |
          if [ "${{ github.event_name }}" == 'workflow_dispatch' ]; then
            OWNER="${{ inputs.PR-number }}"
          else
            OWNER="${{ github.ref_name }}"
            OWNER="${OWNER//[.\/]/-}"
          fi
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            sha="${{ inputs.SHA }}"
          elif [ "${{ github.event_name }}" == 'schedule' ]; then
            sha="${{ github.sha }}"
          else
            sha="${{ github.event.pull_request.head.sha }}"
          fi
          extra_args=${{ inputs.extra-args }}
          kpr=$(echo $extra_args | jq -r '.kpr')
          if [[ "${kpr}" == "null" || "${kpr}" == "" ]]; then
            kpr="true"
          fi
          kubevirt=$(echo $extra_args | jq -r '.kubevirt')
          ossm=$(echo $extra_args | jq -r '.ossm')
          hcp=$(echo $extra_args | jq -r '.hcp')
          ocp_version=$(echo $extra_args | jq -r '.ocp_version')
          if [ "${{ github.event_name }}" == 'schedule' ]; then
            echo kubevirt='true' >> $GITHUB_OUTPUT
            echo ossm='true' >> $GITHUB_OUTPUT
            echo hcp='true' >> $GITHUB_OUTPUT
          elif [ "${{ github.event_name }}" == 'pull_request_target' ]; then
            echo kubevirt='false' >> $GITHUB_OUTPUT
            echo ossm='false' >> $GITHUB_OUTPUT
            echo hcp='false' >> $GITHUB_OUTPUT
          else
            echo kubevirt=${kubevirt} >> $GITHUB_OUTPUT
            echo ossm=${ossm} >> $GITHUB_OUTPUT
            echo hcp=${hcp} >> $GITHUB_OUTPUT
          fi
          if [[ "${ocp_version}" == "null" || "${ocp_version}" == "" ]]; then
            ocp_version=$(echo ${{ env.ocp_version_multi }} | cut -f1 -d "-")
          fi
          region=$(echo $extra_args | jq -r '.region')
          if [[ "${region}" == "null" || "${region}" == "" ]]; then
            region="eu-central-1"
          fi
          ocp_minor_version=$(echo ${ocp_version} | cut -d '.' -f 1,2)
          echo ocp_version=${ocp_version} | tee -a $GITHUB_OUTPUT
          echo ocp_minor_version=${ocp_minor_version} | tee -a $GITHUB_OUTPUT
          echo sha=${sha} | tee -a $GITHUB_OUTPUT
          echo owner=${OWNER} | tee -a $GITHUB_OUTPUT
          echo kpr=${kpr} | tee -a $GITHUB_OUTPUT
          echo region=${region} | tee -a $GITHUB_OUTPUT

      - name: Setup go
        uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
        with:
          cache: false
          # renovate: datasource=golang-version depName=go
          go-version: 1.25.5

      - name: Generate installation manifests
        working-directory: ./enterprise/olm
        env:
          IMG: "quay.io/isovalent-dev/clife-ci:${{ steps.vars.outputs.sha }}"
        run: make build-installer

      - name: Install kubectl
        run: |
          curl -sLO "https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/latest-${{ steps.vars.outputs.ocp_minor_version }}/openshift-client-linux.tar.gz"
          curl -sLO "https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/latest-${{ steps.vars.outputs.ocp_minor_version }}/sha256sum.txt"
          echo "$(cat sha256sum.txt | grep 'openshift-client-linux-4' | cut -f1 -d ' ') openshift-client-linux.tar.gz" | sha256sum --check
          tar -zxvf openshift-client-linux.tar.gz oc
          sudo install -o root -g root -m 0755 oc /usr/local/bin/kubectl
          sudo install -o root -g root -m 0755 oc /usr/local/bin/oc
          kubectl version --client
          oc version --client
          mkdir -p /home/runner/.kube
          touch /home/runner/.kube/config

      - name: Set up AWS CLI credentials
        uses: aws-actions/configure-aws-credentials@61815dcd50bd041e203e49132bacad1fd04d2708 # v5.1.1
        with:
          role-to-assume: ${{ secrets.AWS_PR_ASSUME_ROLE }}
          aws-region: ${{ steps.vars.outputs.region }}

      - name: Install Cilium CLI
        uses: cilium/cilium-cli@e875161a362b9092ff3e1110eccf52a9fdb17c0a # v0.18.9
        with:
          repository: ${{ env.CILIUM_CLI_RELEASE_REPO }}
          release-version: ${{ env.CILIUM_CLI_VERSION }}

      - name: Checkout the openshift-ci repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          repository: isovalent/openshift-ci
          token: ${{ secrets.ISOVALENT_BOT_READ_PRIVATE_REPOSITORIES }}
          path: openshift-ci

      - name: Install OpenShift installer
        working-directory: ./openshift-ci/aws-ipi
        run: |
          URL=https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/${{ steps.vars.outputs.ocp_version }}/openshift-install-linux-${{ steps.vars.outputs.ocp_version }}.tar.gz
          curl -fsSL -o openshift-install.tar.gz ${URL}
          tar zxvf openshift-install.tar.gz
          sudo install -o root -g root -m 0755 openshift-install /usr/local/bin/openshift-install
          rm openshift-install.tar.gz

      - name: Configuration for the OpenShift cluster installation
        id: openshift_ci_config
        working-directory: ./openshift-ci/aws-ipi
        run: |
          # Generation of the installation configuration.
          echo "${{ secrets.OPENSHIFT_PULL_SECRET }}" | base64 -d > .pullsecret.json
          # exclude 0 from the random range to avoid conflicts with the pod CIDR 10.0.0.0/16
          range=$(shuf -i 1-255 -n 1)
          cat > setup.conf << EOF
          CLUSTER_NAME="${{ env.clusterName }}"
          OWNER="${{ steps.vars.outputs.owner }}"
          REGION="${{ steps.vars.outputs.region }}"
          PULL_SECRET_PATH="${PWD}/.pullsecret.json"
          BASE_DOMAIN="${{ vars.AWS_BASE_DOMAIN }}"
          POD_IPV4_CIDR="${{ env.pod_cidr }}"
          POD_IPV4_HOST_PREFIX="${{ env.pod_cidr_host_prefix }}"
          KPR_ENABLED="${{ steps.vars.outputs.kpr }}"
          MACHINE_IPV4_CIDR="10.${range}.0.0/16"
          MANIFESTS_DIR="${{ github.workspace }}/enterprise/olm/dist/manifests"
          CREDENTIALS_MODE="Manual"
          EOF
          # TODO: make WORKERS_INSTANCE_TYPE and COUNT configurable: .compute.platform.aws.type .compute.replicas
          if [ "${{ steps.vars.outputs.kubevirt }}" != "true" ]; then
            cat >> setup.conf << EOF
          WORKERS_INSTANCE_TYPE="m5.xlarge"
          WORKERS_INSTANCE_COUNT=3
          EOF
          fi
          cat setup.conf
          # Use the CI CiliumConfig
          if [[ "${{ steps.vars.outputs.kpr }}" == "true" ]]
          then
            cp ../../enterprise/olm/config/samples/openshift_ci_ciliumconfig_kpr.yaml ${{ github.workspace }}/enterprise/olm/dist/manifests/ciliumconfig.yaml
          else
            cp ../../enterprise/olm/config/samples/openshift_ci_ciliumconfig.yaml ${{ github.workspace }}/enterprise/olm/dist/manifests/ciliumconfig.yaml
          fi

      - name: Provision the OpenShift cluster
        id: provisioning
        timeout-minutes: 120
        working-directory: "./openshift-ci/aws-ipi"
        run: |
          ./scripts/provision.sh

      - name: Kubeconfig Setup
        if: always() && steps.provisioning.outcome != 'skipped'
        id: kubeconfig
        working-directory: "./openshift-ci/aws-ipi"
        run: |
          source .workdir/current.properties
          export KUBECONFIG=${PWD}/.workdir/${CLUSTER_NAME}/auth/kubeconfig
          echo "base64 encoded kubeconfig:"
          cat $KUBECONFIG | base64 # useful for troubleshooting
          # required by the Cilium CLI container
          cp $KUBECONFIG /home/runner/.kube/config

      - name: Cluster state
        if: always() && steps.provisioning.outcome != 'skipped'
        run: |
          kubectl get pods -A -o wide
          kubectl get nodes
          kubectl get co
          kubectl get ciliumconfig -o yaml
          kubectl get events -n cilium
          kubectl get pods -n cilium -o yaml
          kubectl logs -n cilium deployment/clife-controller-manager
          kubectl logs -n cilium daemonset/cilium --all-containers=true

      - name: Wait for Cluster operators to be ready
        if: ${{ !cancelled() && steps.provisioning.outcome == 'success' }}
        id: wait-for-co
        run: |
          oc adm wait-for-stable-cluster --timeout=15m0s --minimum-stable-period=1m

      - name: Cluster operators not ready
        if: ${{ !cancelled() && steps.provisioning.outcome != 'skipped' && steps.wait-for-co.outcome == 'failure' }}
        run: |
          kubectl get co -o yaml
          kubectl get events -n cilium
          kubectl get pods -n cilium -o yaml
          kubectl logs -n cilium deployment/clife-controller-manager
          kubectl logs -n cilium daemonset/cilium --all-containers=true

      - name: Retrieve cluster info
        id: cluster-info
        run: |
          api_server="$(kubectl config view --minify | yq -r '.clusters[0].cluster.server')"
          echo "k8s_service_host=$(echo $api_server | awk -F '/' '{print $3}' | awk -F ':' '{print $1}')" >> $GITHUB_OUTPUT
          echo "k8s_service_port=$(echo $api_server | awk -F '/' '{print $3}' | awk -F ':' '{print $2}')" >> $GITHUB_OUTPUT

      - name: Verifying KPR [if enabled]
        if: ${{ steps.vars.outputs.kpr == 'true' }}
        run: |
          kpr_status="$(kubectl -n cilium exec ds/cilium -c cilium-agent -- cilium-dbg status -o json | jq --raw-output '."kube-proxy-replacement".mode')"
          if [ ${kpr_status} != "True" ]
          then
            echo "KPR is not enabled [status: $kpr_status]"
            exit 1
          fi

      - name: Verify OpenShift kube-proxy removed
        if: ${{ steps.vars.outputs.kpr == 'true' }}
        run: |
          count="$(kubectl get pods -A -l app=kube-proxy | wc -l)"
          if [[ $count -gt 0 ]]
          then
            echo "OpenShift kube-proxy was not removed!"
            exit 1
          fi

      - name: Provision a node without Cilium
        working-directory: ./openshift-ci/aws-ipi
        run: |
          ./scripts/no-cilium-nodes.sh

      - name: Features tested
        uses: ./.github/actions/feature-status
        with:
          title: "Summary of all features"
          json-filename: "OpenShift"

      - name: Cilium connectivity tests
        if: ${{ !cancelled() && steps.wait-for-co.outcome == 'success' }}
        timeout-minutes: 60
        working-directory: ./openshift-ci/aws-ipi
        run: |
          cp ${{ github.workspace }}/CODEOWNERS .
          cp ${{ github.workspace }}/TESTOWNERS.enterprise .
          mkdir -p test-results
          mkdir -p cilium-junits
          export CILIUM_TEST_RESULTS_DIR=${PWD}/test-results
          # Disable history expansion because of the exclamation mark in the flags
          set +H
          export CILIUM_TEST_FLAGS="${{ steps.e2e_config.outputs.test_flags }}
            --test=\"!check-log-errors\"
            --junit-file ${PWD}/cilium-junits/openshift-1.xml
            --junit-property github_job_step=\"Cilium connectivity tests\""
          ./scripts/cilium-cli-tests.sh

      # Remove the node without Cilium as it may interfer with other tests, i.e. OSSM
      - name: Remove nodes without Cilium
        if: ${{ !cancelled() && steps.wait-for-co.outcome == 'success' }}
        working-directory: ./openshift-ci/aws-ipi
        run: |
          ./scripts/destroy-no-cilium-nodes.sh

      - name: CNI conformance tests
        if: ${{ !cancelled() && steps.wait-for-co.outcome == 'success' }}
        timeout-minutes: 60
        working-directory: ./openshift-ci/aws-ipi
        run: |
          mkdir -p test-results
          export CNI_TEST_RESULTS_DIR=${PWD}/test-results
          ./scripts/cni-tests.sh

      - name: KubeVirt conformance tests
        # Please create a comment with /ci-openshift {\"kubevirt\":\"true\"} if you want to run them
        if: ${{ !cancelled() && steps.wait-for-co.outcome == 'success' && steps.vars.outputs.kubevirt == 'true' }}
        timeout-minutes: 60
        working-directory: ./openshift-ci/aws-ipi
        run: |
          mkdir -p test-results
          export KUBEVIRT_TEST_RESULTS_DIR=${PWD}/test-results
          ./scripts/kubevirt-tests.sh

      - name: Checkout sail-operator repo for Service Mesh conformance tests
        if: ${{ !cancelled() && steps.wait-for-co.outcome == 'success' && steps.vars.outputs.ossm == 'true' }}
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          repository: openshift-service-mesh/sail-operator
          path: ./openshift-ci/aws-ipi/.workdir/${{ env.clusterName }}/sail-operator
          persist-credentials: false
          fetch-depth: 0
          fetch-tags: true

      - name: OpenShift Service Mesh conformance tests
        # Please create a comment with /ci-openshift {\"ossm\":\"true\"} if you want to run them
        if: ${{ !cancelled() && steps.wait-for-co.outcome == 'success' && steps.vars.outputs.ossm == 'true' }}
        timeout-minutes: 60
        working-directory: ./openshift-ci/aws-ipi
        run: |
          mkdir -p test-results
          export MESH_TEST_RESULTS_DIR=${PWD}/test-results
          ./scripts/mesh-tests.sh

      - name: Collect sysdumps
        if: ${{ !success() && steps.provisioning.outcome != 'skipped' }}
        shell: bash
        working-directory: ./openshift-ci/aws-ipi
        run: |
          mkdir -p ./test-results
          cilium status -n cilium
          cilium sysdump -n cilium --output-filename ./test-results/cilium-sysdump.dmp

      - name: Hosted control planes deployment
        # Please create a comment with /ci-openshift {\"hcp\":\"true\"} if you want to run test on hosted clusters
        if: ${{ !cancelled() && steps.wait-for-co.outcome == 'success' && steps.vars.outputs.hcp == 'true' }}
        working-directory: ./openshift-ci/aws-ipi
        run: |
          ./hcp/scripts/management-provision.sh

      - name: Install hcp CLI
        if: ${{ !cancelled() && steps.wait-for-co.outcome == 'success' && steps.vars.outputs.hcp == 'true' }}
        working-directory: ./openshift-ci/aws-ipi
        run: |
          ./hcp/scripts/cli-dowload.sh

      - name: Refresh AWS CLI credentials for getting VPC information for the hosted cluster
        if: ${{ !cancelled() && steps.wait-for-co.outcome == 'success' && steps.vars.outputs.hcp == 'true' }}
        id: hcp-creds
        uses: aws-actions/configure-aws-credentials@61815dcd50bd041e203e49132bacad1fd04d2708 # v5.1.1
        with:
          role-to-assume: ${{ secrets.AWS_PR_ASSUME_ROLE }}
          aws-region: ${{ steps.vars.outputs.region }}

      # credentials shared during installation (limited permission)
      - name: Get AWS credentials for hosted control planes
        if: ${{ !cancelled() && steps.wait-for-co.outcome == 'success' && steps.vars.outputs.hcp == 'true' }}
        uses: hashicorp/vault-action@4c06c5ccf5c0761b6029f56cfb1dcf5565918a3b # v3.4.0
        with:
          url: ${{ vars.VAULT_URL }}
          method: jwt
          namespace: ${{ vars.VAULT_NAMESPACE }}
          secrets: |
            secret/data/devops/${{ github.repository_owner }} aws_pr_hcp_access_key_id | AWS_PR_HCP_ACCESS_KEY_ID;
            secret/data/devops/${{ github.repository_owner }} aws_pr_hcp_secret_access_key | AWS_PR_HCP_SECRET_ACCESS_KEY;

      - name: Generated hosted credentials file
        working-directory: "./openshift-ci/aws-ipi"
        env:
          AWS_ACCESS_KEY_ID: ${{ env.AWS_PR_HCP_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ env.AWS_PR_HCP_SECRET_ACCESS_KEY }}
        run: |
          unset AWS_SESSION_TOKEN
          aws sts get-session-token > credentials.json

      - name: Hosted cluster creation
        id: hcp-create
        if: ${{ !cancelled() && steps.wait-for-co.outcome == 'success' && steps.vars.outputs.hcp == 'true' }}
        timeout-minutes: 120
        working-directory: "./openshift-ci/aws-ipi"
        env:
          HCP_AWS_ACCESS_KEY_ID: ${{ env.AWS_PR_HCP_ACCESS_KEY_ID }}
          HCP_AWS_SECRET_ACCESS_KEY: ${{ env.AWS_PR_HCP_SECRET_ACCESS_KEY }}
          HCP_DEPLOYER_ROLE_ARN: ${{ vars.AWS_HCP_DEPLOYER_ROLE_ARN }}
          MANIFESTS_DIR: ${{ github.workspace }}/enterprise/olm/dist/manifests
          PULL_SECRET_PATH: ${{ github.workspace }}/openshift-ci/aws-ipi/.pullsecret.json
        run: |
          export AWS_CREDENTIALS_FILE="${PWD}/credentials.json"
          ./hcp/scripts/create-cluster.sh
          source .workdir/current.properties
          cluster_dir=${PWD}/.workdir/${CLUSTER_NAME}
          source ${cluster_dir}/hosted-current.properties
          echo hosted_kubeconfig="${cluster_dir}/${CLUSTER_NAME}/auth/kubeconfig" >> $GITHUB_OUTPUT

      - name: Wait for cluster to be ready
        timeout-minutes: 15
        id: wait-for-hosted
        env:
          KUBECONFIG: ${{ steps.hcp-create.outputs.hosted_kubeconfig }}
        run: |
          i=0
          until kubectl get daemonset cilium -n cilium || [[ "${i}" -gt 30 ]]; do echo "Waiting for cilium daemonset to be created"; sleep 20s; i=$((i + 1)); done
          kubectl rollout status daemonset cilium -n cilium --timeout 600s
          nodes=$(kubectl get nodes -o name)
          for node in ${nodes}; do
             kubectl wait --for=condition=Ready=true --timeout=5m ${node}
          done
          oc adm wait-for-stable-cluster --timeout=15m0s --minimum-stable-period=1m

      - name: Hosted cluster not ready
        if: ${{ !cancelled() && steps.hcp-create.outcome != 'skipped' && steps.wait-for-hosted.outcome == 'failure' }}
        run: |
          kubectl get co -o yaml
          kubectl get events -n cilium
          kubectl get pods -n cilium -o yaml
          kubectl logs -n cilium deployment/clife-controller-manager
          kubectl logs -n cilium daemonset/cilium --all-containers=true

      - name: Cilium connectivity tests on hosted cluster
        if: ${{ !cancelled() && steps.wait-for-hosted.outcome == 'success' && steps.vars.outputs.hcp == 'true' }}
        timeout-minutes: 60
        working-directory: ./openshift-ci/aws-ipi
        env:
          KUBECONFIG: ${{ steps.hcp-create.outputs.hosted_kubeconfig }}
        run: |
          cp ${{ github.workspace }}/CODEOWNERS .
          cp ${{ github.workspace }}/TESTOWNERS.enterprise .
          mkdir -p test-results
          mkdir -p cilium-junits
          export CILIUM_TEST_RESULTS_DIR=${PWD}/test-results
          export CILIUM_TEST_RESULTS_FILE="cilium-cli-hosted-results.txt"
          # Disable history expansion because of the exclamation mark in the flags
          set +H
          export CILIUM_TEST_FLAGS="${{ steps.e2e_config.outputs.test_flags }}
            --test=\"!check-log-errors\"
            --junit-file ${PWD}/cilium-junits/openshift-hosted-1.xml
            --junit-property github_job_step=\"Cilium connectivity tests\""
          ./scripts/cilium-cli-tests.sh

      - name: CNI conformance tests on hosted cluster
        if: ${{ !cancelled() && steps.wait-for-hosted.outcome == 'success' && steps.vars.outputs.hcp == 'true' }}
        timeout-minutes: 60
        working-directory: ./openshift-ci/aws-ipi
        env:
          KUBECONFIG: ${{ steps.hcp-create.outputs.hosted_kubeconfig }}
          # Hosted clusters don't expose their OpenShift version through the oc command
          OCP_VERSION: ${{ steps.vars.outputs.ocp_version }}
        run: |
          mkdir -p test-results
          export CNI_TEST_RESULTS_DIR=${PWD}/test-results
          export CNI_TEST_RESULTS_FILE="cni-hosted-results.txt"
          ./scripts/cni-tests.sh

      # This is to work around the fact that relative paths in actions/upload-artifact@v3 are rooted
      # against the workspace, which causes an "Invalid pattern" if the repo dir is ".".
      - name: Prepare upload
        if: always() && steps.provisioning.outcome != 'skipped'
        id: upload_dir
        working-directory: ./openshift-ci/aws-ipi
        run: |
          if test -d ./test-results; then
            echo path="$(realpath ./test-results)" >> $GITHUB_OUTPUT
          else
            echo path=nothingtoupload >> $GITHUB_OUTPUT
          fi
          if test -d ./cilium-junits; then
            mv ./cilium-junits ${GITHUB_WORKSPACE}/.
          fi
          mv cilium-sysdump-*.zip ${GITHUB_WORKSPACE}/. || true

      - name: Upload Artifacts
        if: always() && steps.provisioning.outcome != 'skipped'
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: test-results
          path: ${{ steps.upload_dir.outputs.path }}
          if-no-files-found: ignore
          retention-days: 3

      # Happens independently of the success or the failure of the provisioning and tests
      - name: Destroy the hosted cluster
        if: ${{ always() && steps.vars.outputs.hcp == 'true' && steps.hcp-create.outcome != 'skipped' }}
        timeout-minutes: 60
        working-directory: "./openshift-ci/aws-ipi"
        env:
          KUBECONFIG: /home/runner/.kube/config
          AWS_CREDENTIALS_FILE: ${{ github.workspace }}/openshift-ci/aws-ipi/credentials.json
          HCP_DEPLOYER_ROLE_ARN: ${{ vars.AWS_HCP_DEPLOYER_ROLE_ARN }}
        run: |
          echo "destroying hosted cluster ..."
          ./hcp/scripts/destroy-cluster.sh

      # refresh credentials
      - name: Set up AWS CLI credentials
        if: always() && steps.provisioning.outcome != 'skipped'
        uses: aws-actions/configure-aws-credentials@61815dcd50bd041e203e49132bacad1fd04d2708 # v5.1.1
        with:
          role-to-assume: ${{ secrets.AWS_PR_ASSUME_ROLE }}
          aws-region: ${{ steps.vars.outputs.region }}

      # Happens independently of the success or the failure of the provisioning and tests
      - name: Destroy the cluster
        if: always() && steps.provisioning.outcome != 'skipped'
        timeout-minutes: 60
        working-directory: "./openshift-ci/aws-ipi"
        env:
          KUBECONFIG: /home/runner/.kube/config
        run: |
          echo "destroying cluster ..."
          scripts/destroy.sh

      - name: Run common post steps
        if: ${{ always() }}
        uses: ./.github/actions/post-logic
        with:
          artifacts_suffix: "openshift"
          job_status: "${{ job.status }}"
          capture_features_tested: false
          capture_sysdump: false

  merge-upload-and-status:
    name: Merge Upload and Status
    if: ${{ always() }}
    needs: installation-and-connectivity
    uses: ./.github/workflows/common-post-jobs.yaml
    secrets: inherit
    with:
      context-ref: ${{ inputs.context-ref || github.sha }}
      sha: ${{ inputs.SHA || github.sha }}
      success: ${{ needs.installation-and-connectivity.result == 'success' }}
