name: FIPs Image Build

on:
  push:
    branches:
      - main-ce
      - ft/main-ce/**
      - v1.[0-9]+-ce
    tags:
      - v[0-9]+.[0-9]+.[0-9]+-*
  workflow_dispatch:
    inputs:
      tag:
        description: A tag to build images for.
        type: string
        required: false
      build-cilium:
        type: boolean
        default: false
      build-hubble-relay:
        type: boolean
        default: false
      build-operator-aws:
        type: boolean
        default: false
      build-operator-azure:
        type: boolean
        default: false
      build-operator-alibabacloud:
        type: boolean
        default: false
      build-operator-generic:
        type: boolean
        default: false

permissions:
  # To be able to access the repository with `actions/checkout`
  contents: read
  # Required to generate OIDC tokens for `sigstore/cosign-installer` authentication
  id-token: write

# Avoid building/pushing images for the same ref concurrently.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ inputs.tag }}

env:
  # renovate: datasource=golang-version depName=go
  go_version: 1.25.5

# This workflow builds each platform as part of separate jobs and then merges the
# built images into a manifest before pushing. This is done for two reasons:
# 1. Before pushing, it must be confirmed for each platform-specific image that the
#    crypto libraries the images are using are correct,.
# 2. Before pushing, an SBOM must be created and attached to each platform-specific
#    image.

jobs:
  sanity-checks:
    timeout-minutes: 10
    name: Sanity Checks
    runs-on: ubuntu-24.04
    steps:
      - name: Sanity checks
        run: |
          if [ "${{ github.event_name }}" != "push" ] && [ "${{ github.event_name }}" != "workflow_dispatch" ]; then
            echo "Sanity check failed, should only build on pushes and workfow_dispatch"
            exit 1
          fi

          if [ "${{ github.repository }}" != "isovalent/cilium" ]; then
            echo "Sanity check failed, should only run in isovalent/cilium"
            exit 1
          fi

  build-image-list:
    timeout-minutes: 1
    name: Build image list
    runs-on: ubuntu-24.04
    outputs:
      images: ${{ steps.images.outputs.images }}
      image_names: ${{ steps.images.outputs.image_names }}
      image_tag: ${{ steps.tag.outputs.tag }}
    env:
      BUILD_CILIUM: ${{ github.event_name == 'push' || inputs.build-cilium }}
      BUILD_HUBBLE_RELAY: ${{ github.event_name == 'push' || inputs.build-hubble-relay }}
      BUILD_OPERATOR_AWS: ${{ github.event_name == 'push' || inputs.build-operator-aws }}
      BUILD_OPERATOR_AZURE: ${{ github.event_name == 'push' || inputs.build-operator-azure }}
      BUILD_OPERATOR_ALIBABACLOUD: ${{ github.event_name == 'push' || inputs.build-operator-alibabacloud }}
      BUILD_OPERATOR_GENERIC: ${{ github.event_name == 'push' || inputs.build-operator-generic }}
    steps:
      - name: Build image list
        id: images
        run: |
          images=()
          if [ "${BUILD_CILIUM}" = "true" ]; then
            images+=('{"name": "cilium", "dockerfile": "./images/cilium/Dockerfile", "binaries": "cilium-agent"}')
          fi
          if [ "${BUILD_HUBBLE_RELAY}" = "true" ]; then
            images+=('{"name": "hubble-relay", "dockerfile": "./images/hubble-relay/Dockerfile", "binaries": "hubble-relay"}')
          fi
          if [ "${BUILD_OPERATOR_AWS}" = "true" ]; then
            images+=('{"name": "operator-aws", "dockerfile": "./images/operator/Dockerfile", "binaries": "cilium-operator-aws"}')
          fi
          if [ "${BUILD_OPERATOR_AZURE}" = "true" ]; then
            images+=('{"name": "operator-azure", "dockerfile": "./images/operator/Dockerfile", "binaries": "cilium-operator-azure"}')
          fi
          if [ "${BUILD_OPERATOR_ALIBABACLOUD}" = "true" ]; then
            images+=('{"name": "operator-alibabacloud", "dockerfile": "./images/operator/Dockerfile", "binaries": "cilium-operator-alibabacloud"}')
          fi
          if [ "${BUILD_OPERATOR_GENERIC}" = "true" ]; then
            images+=('{"name": "operator-generic", "dockerfile": "./images/operator/Dockerfile", "binaries": "cilium-operator-generic"}')
          fi

          images_json=$(echo "${images[@]}" | jq -s -c)
          image_names=$(echo "${images_json}" | jq -c '[.[].name]')
          echo "Images:"
          echo "${images_json}" | jq
          echo "images=$images_json" >> $GITHUB_OUTPUT
          echo "image_names=$image_names" >> $GITHUB_OUTPUT

      - name: Getting image tag
        id: tag
        run: |
          if [ "${{ inputs.tag != '' }}" = "true" ]; then
            tag=${{ inputs.tag }}-fips
          elif [ "${{ startsWith(github.ref, 'refs/tags/v') }}" = "true" ]; then
            ref=${{ github.ref }}
            tag=${ref##*/}-fips
          else
            tag=${{ github.sha }}-fips
          fi
          echo tag=$tag >> $GITHUB_OUTPUT

  build-and-push:
    timeout-minutes: 45
    name: Build and Push Image (${{ matrix.name }}, ${{ matrix.platform }})
    environment: ${{ (startsWith(github.ref, 'refs/tags/v') || inputs.tag != '') && 'release' || '' }}
    runs-on: ubuntu-24.04
    needs: [sanity-checks, build-image-list]
    if: ${{ needs.build-image-list.outputs.images != '[]' }}
    strategy:
      # Use matrix.include to provide a dynamically built list of image objects
      # containing build attributes. Because of the way matrix.include works, we
      # also need to have each image name listed in the matrix for include to
      # correctly match. We choose not to include platform as part of the image
      # list so that we can re-use the same outputs in the create-manifest job
      # below, which should only execute once per image.
      matrix:
        name: ${{ fromJSON(needs.build-image-list.outputs.image_names) }}
        platform:
          - amd64
          - arm64
        include: ${{ fromJSON(needs.build-image-list.outputs.images) }}
    outputs:
      # The digests of the per-platform images are combined in the next job with the
      # manifest tag(s), so they need to be made available. As a result, the variables
      # here must be synced with the next job.
      # Parallelizing builds has two advantages:
      # 1. Speedup
      # 2. Avoids build cache interference. This workflow used to look like this:
      #    (1) build amd64 image, (2) build arm64 image, (3) check FIPs libraries
      #    are in use for each platform-specific image, (4) build and push amd64
      #    image, (5) build and push arm64 image. The images from steps one and two
      #    would have different digests than the images in steps four in five. This
      #    is because the Dockerfiles use cache mounts in some RUN instructions, which
      #    are taken into consideration in determining the digest.
      image_cilium_amd64: ${{ steps.pass_image.outputs.cilium-amd64 }}
      image_cilium_arm64: ${{ steps.pass_image.outputs.cilium-arm64 }}
      manifest_cilium_primary: ${{ steps.pass_image.outputs.cilium-primary }}
      manifest_cilium_secondary: ${{ steps.pass_image.outputs.cilium-secondary }}
      image_hubble_relay_amd64: ${{ steps.pass_image.outputs.hubble-relay-amd64 }}
      image_hubble_relay_arm64: ${{ steps.pass_image.outputs.hubble-relay-arm64 }}
      manifest_hubble_relay_primary: ${{ steps.pass_image.outputs.hubble-relay-primary }}
      manifest_hubble_relay_secondary: ${{ steps.pass_image.outputs.hubble-relay-secondary }}
      image_operator_aws_amd64: ${{ steps.pass_image.outputs.operator-aws-amd64 }}
      image_operator_aws_arm64: ${{ steps.pass_image.outputs.operator-aws-arm64 }}
      manifest_operator_aws_primary: ${{ steps.pass_image.outputs.operator-aws-primary }}
      manifest_operator_aws_secondary: ${{ steps.pass_image.outputs.operator-aws-secondary }}
      image_operator_azure_amd64: ${{ steps.pass_image.outputs.operator-azure-amd64 }}
      image_operator_azure_arm64: ${{ steps.pass_image.outputs.operator-azure-arm64 }}
      manifest_operator_azure_primary: ${{ steps.pass_image.outputs.operator-azure-primary }}
      manifest_operator_azure_secondary: ${{ steps.pass_image.outputs.operator-azure-secondary }}
      image_operator_alibabacloud_amd64: ${{ steps.pass_image.outputs.operator-alibabacloud-amd64 }}
      image_operator_alibabacloud_arm64: ${{ steps.pass_image.outputs.operator-alibabacloud-arm64 }}
      manifest_operator_alibabacloud_primary: ${{ steps.pass_image.outputs.operator-alibabacloud-primary }}
      manifest_operator_alibabacloud_secondary: ${{ steps.pass_image.outputs.operator-alibabacloud-secondary }}
      image_operator_generic_amd64: ${{ steps.pass_image.outputs.operator-generic-amd64 }}
      image_operator_generic_arm64: ${{ steps.pass_image.outputs.operator-generic-arm64 }}
      manifest_operator_generic_primary: ${{ steps.pass_image.outputs.operator-generic-primary }}
      manifest_operator_generic_secondary: ${{ steps.pass_image.outputs.operator-generic-secondary }}

    steps:
      - name: Checkout main branch to access local actions
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          ref: ${{ github.event.repository.default_branch }}
          persist-credentials: false
          sparse-checkout: |
            .github/actions

      - name: Cleanup Disk space in runner
        uses: ./.github/actions/set-env-variables

      - name: Set Environment Variables
        uses: ./.github/actions/set-env-variables

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1

        # Required outputs for the 'tags' step:
        # - target: The name of the image that is being built (ie cilium, operator-generic)
        # - base_image_name: The image name, including the registry and org, without any tags.
        # - tag: A single image tag to uniquely identiy the build.
        # - image_tag_primary: Full image name, including a tag, for the final manifest list.
        # - image_tag_secondary: A second full image name, including a tag, for the final manifest list. Can be blank.
        # - image_tag_platform: Full image name, including a tag, for the platform-specific build.

      - name: Get image information based on the trigger
        id: tags
        run: |
          tag=${{ needs.build-image-list.outputs.image_tag }}
          if [ "${{ startsWith(github.ref, 'refs/tags/v') || inputs.tag != '' }}" == "true" ]; then
            target=${{ matrix.name }}
            echo target=$target >> $GITHUB_OUTPUT

            base_image_name="quay.io/${{ env.QUAY_ORGANIZATION }}/${target}"
            echo base_image_name=$base_image_name >> $GITHUB_OUTPUT

            # Need one for each platform and a generic one for the manifest at the end
            echo "image_tag_primary=${base_image_name}:${tag}" >> $GITHUB_OUTPUT
            echo image_tag_secondary="" >> $GITHUB_OUTPUT
            echo "image_tag_platform=${base_image_name}:${tag}-${{ matrix.platform }}" >> $GITHUB_OUTPUT
          else
            # Create two image tags: one 'floating' tag which is based on the stable branch name
            # or "latest" for main-ce, and a standard tag which contains the commit SHA.
            target=${{ matrix.name }}-ci
            echo target=$target >> $GITHUB_OUTPUT

            base_image_name="quay.io/${{ env.QUAY_ORGANIZATION_DEV }}/${target}"
            echo base_image_name=$base_image_name >> $GITHUB_OUTPUT

            if [ "${{ github.ref_name }}" == "main-ce" ]; then
              floating_tag="latest-fips"
            else
              ft="${{ github.ref_name }}"
              # Replace all occurrences of "/" with "-"
              floating_tag="${ft//\//-}-fips"
            fi

            # Sanity check
            if [ "${floating_tag}" == "" ]; then
              echo "Sanity check failed, floating tag is empty"
              exit 1
            fi

            echo "image_tag_primary=${base_image_name}:${tag}" >> $GITHUB_OUTPUT
            echo "image_tag_secondary=${base_image_name}:${floating_tag}" >> $GITHUB_OUTPUT
            echo "image_tag_platform=${base_image_name}:${tag}-${{ matrix.platform }}" >> $GITHUB_OUTPUT
          fi

      - name: Print image tag information
        run: |
          echo "base_image_name"
          echo "${{ steps.tags.outputs.base_image_name }}"
          echo "tag"
          echo "${{ steps.tags.outputs.tag }}"
          echo "image_tag_primary"
          echo "${{ steps.tags.outputs.image_tag_primary }}"
          echo "image_tag_secondary"
          echo "${{ steps.tags.outputs.image_tag_secondary }}"
          echo "image_tag_platform"
          echo "${{ steps.tags.outputs.image_tag_platform }}"

      - name: Login to quay.io - release
        if: ${{ startsWith(github.ref, 'refs/tags/v') || inputs.tag != '' }}
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME_RELEASE_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD_RELEASE_PASSWORD }}

      - name: Login to quay.io - non-release
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        if: ${{ ! (startsWith(github.ref, 'refs/tags/') || inputs.tag != '') }}
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME_CI }}
          password: ${{ secrets.QUAY_PASSWORD_CI }}

      - name: Install Go
        uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
        with:
          go-version: ${{ env.go_version }}

      - name: Checkout Source Code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          # will fallback to default ref if tag is empty
          ref: ${{ inputs.tag }}
          persist-credentials: false

      - name: Fail if fips.go is not present
        run: |
          if ! [ -f ./enterprise/fips/fips.go ]; then
            exit 1
          fi

      - name: Build ${{ matrix.name }}
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        id: docker_build
        with:
          provenance: false
          context: .
          file: ${{ matrix.dockerfile }}
          push: false
          load: true
          platforms: linux/${{ matrix.platform }}
          tags: ${{ steps.tags.outputs.image_tag_platform }}
          target: release
          build-args: |
            OPERATOR_VARIANT=${{ matrix.name }}
            MODIFIERS=FIPS=1\ NOSTRIP=1

      - name: Ensure binaries are using the correct crypto libraries
        shell: bash
        # Use /tmp so we don't touch the build context.
        working-directory: /tmp
        run: |
          set -xeo pipefail
          # "catch exit status 1" grep wrapper
          # https://stackoverflow.com/questions/6550484/prevent-grep-returning-an-error-when-input-doesnt-match/49627999#49627999
          c1grep() { grep "$@" || test $? = 1; }

          image="${{ steps.tags.outputs.image_tag_platform }}"

          if ! docker image inspect $image; then
            echo "Image ${image} was not put into local store"
            docker image ls --digests
            exit 1
          fi
          container_name=$(uuidgen | cut -d'-' -f1)

          mkdir -p ./binaries
          touch ./symbols.txt
          docker create --name $container_name $image
          for binary in ${{ matrix.binaries }}; do
            docker cp $container_name:/usr/bin/$binary ./binaries/$binary
            echo "$binary" >> ./symbols.txt
            go tool nm ./binaries/$binary | grep -E "sig\.(BoringCrypto|FIPSOnly|StandardCrypto)" >> ./symbols.txt
          done
          docker rm $container_name

          cat ./symbols.txt

          nstandard="$(cat ./symbols.txt | c1grep 'sig.StandardCrypto' | wc -l)"
          nboring="$(cat ./symbols.txt | c1grep 'sig.BoringCrypto' | wc -l)"
          nfips="$(cat ./symbols.txt | c1grep 'sig.FIPSOnly' | wc -l)"

          if [ "${nstandard}" != "0" ]; then
            echo "Fail for image ${image}, standard crypto is used in ${nstandard} binaries"
            exit 1
          fi

          if [ "${nboring}" != "${nfips}" ]; then
            echo "Fail for image ${image}, mismatch between number of FIPSOnly binaries and BoringCrypto binaries: ${nfips} != ${nboring}"
            exit 1
          fi

      - name: Push verified image
        id: docker_push
        run: |
          docker push ${{ steps.tags.outputs.image_tag_platform }}
          docker image ls --digests
          output=$(docker image inspect ${{ steps.tags.outputs.image_tag_platform }} | jq -r '.[] | "image=\(.RepoDigests[0])"')
          echo $output
          echo "$output" >> $GITHUB_OUTPUT

      - name: Install Cosign
        uses: sigstore/cosign-installer@faadad0cce49287aee09b3a48701e75088a2c6ad # v4.0.0

      - name: Sign Container Images
        run: |
          cosign sign -y ${{ steps.docker_push.outputs.image }}

      - name: Generate SBOM
        uses: anchore/sbom-action@fbfd9c6c189226748411491745178e0c2017392d # v0.20.10
        with:
          artifact-name: sbom_${{ steps.tags.outputs.target }}_${{ steps.tags.outputs.tag }}_${{ matrix.platform }}.spdx.json
          output-file: ./sbom_${{ steps.tags.outputs.target }}_${{ steps.tags.outputs.tag }}_${{ matrix.platform }}.spdx.json
          image: ${{ steps.docker_push.outputs.image }}
          # Use an older version of Syft so the boring crypto experiment is displayed.
          # Do not upgrade without verifying the goexperiment is placed into the SBOM!
          syft-version: v1.4.1
          upload-release-assets: false

      - name: Attach SBOM attestation to container image
        run: |
          cosign attest -y --predicate sbom_${{ steps.tags.outputs.target }}_${{ steps.tags.outputs.tag }}_${{ matrix.platform }}.spdx.json --type spdxjson ${{ steps.docker_push.outputs.image }}

      - name: Pass image to next job
        id: pass_image
        run: |
          echo "${{ matrix.name }}-${{ matrix.platform }}=${{ steps.docker_push.outputs.image }}" >> $GITHUB_OUTPUT
          echo "${{ matrix.name }}-primary=${{ steps.tags.outputs.image_tag_primary }}" >> $GITHUB_OUTPUT
          echo "${{ matrix.name }}-secondary=${{ steps.tags.outputs.image_tag_secondary }}" >> $GITHUB_OUTPUT

  create-manifest:
    timeout-minutes: 45
    name: Create final manifest ${{ matrix.name }}
    environment: ${{ (startsWith(github.ref, 'refs/tags/v') || inputs.tag != '') && 'release' || '' }}
    runs-on: ubuntu-24.04
    needs: [build-image-list, build-and-push]
    if: ${{ needs.build-image-list.outputs.images != '[]' }}
    strategy:
      matrix:
        name: ${{ fromJSON(needs.build-image-list.outputs.image_names) }}
        include: ${{ fromJSON(needs.build-image-list.outputs.images) }}
    steps:
      - name: Login to quay.io - release
        if: ${{ startsWith(github.ref, 'refs/tags/v') || inputs.tag != '' }}
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME_RELEASE_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD_RELEASE_PASSWORD }}

      - name: Login to quay.io - non-release
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        if: ${{ ! (startsWith(github.ref, 'refs/tags/') || inputs.tag != '') }}
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME_CI }}
          password: ${{ secrets.QUAY_PASSWORD_CI }}

      - name: Create manifest
        id: docker_manifest
        shell: bash
        run: |
          set -xeo pipefail

          # TODO: There's probably a smarter way to do this...
          image_name="${{ matrix.name }}"
          if [ "${image_name}" == "cilium" ]; then
            platform_tags="${{ needs.build-and-push.outputs.image_cilium_amd64 }} ${{ needs.build-and-push.outputs.image_cilium_arm64 }}"
            primary_tag="${{ needs.build-and-push.outputs.manifest_cilium_primary }}"
            image_tags="-t ${{ needs.build-and-push.outputs.manifest_cilium_primary }}"
            if [ -n "${{ needs.build-and-push.outputs.manifest_cilium_secondary }}" ]; then
              image_tags+=" -t ${{ needs.build-and-push.outputs.manifest_cilium_secondary }}"
            fi
          elif [ "${image_name}" == "hubble-relay" ]; then
            platform_tags="${{ needs.build-and-push.outputs.image_hubble_relay_amd64 }} ${{ needs.build-and-push.outputs.image_hubble_relay_arm64 }}"
            primary_tag="${{ needs.build-and-push.outputs.manifest_hubble_relay_primary }}"
            image_tags="-t ${{ needs.build-and-push.outputs.manifest_hubble_relay_primary }}"
            if [ -n "${{ needs.build-and-push.outputs.manifest_hubble_relay_secondary }}" ]; then
              image_tags+=" -t ${{ needs.build-and-push.outputs.manifest_hubble_relay_secondary }}"
            fi
          elif [ "${image_name}" == "operator-aws" ]; then
            platform_tags="${{ needs.build-and-push.outputs.image_operator_aws_amd64 }} ${{ needs.build-and-push.outputs.image_operator_aws_arm64 }}"
            primary_tag="${{ needs.build-and-push.outputs.manifest_operator_aws_primary }}"
            image_tags="-t ${{ needs.build-and-push.outputs.manifest_operator_aws_primary }}"
            if [ -n "${{ needs.build-and-push.outputs.manifest_operator_aws_secondary }}" ]; then
              image_tags+=" -t ${{ needs.build-and-push.outputs.manifest_operator_aws_secondary }}"
            fi
          elif [ "${image_name}" == "operator-alibabacloud" ]; then
            platform_tags="${{ needs.build-and-push.outputs.image_operator_alibabacloud_amd64 }} ${{ needs.build-and-push.outputs.image_operator_alibabacloud_arm64 }}"
            primary_tag="${{ needs.build-and-push.outputs.manifest_operator_alibabacloud_primary }}"
            image_tags="-t ${{ needs.build-and-push.outputs.manifest_operator_alibabacloud_primary }}"
            if [ -n "${{ needs.build-and-push.outputs.manifest_operator_alibabacloud_secondary }}" ]; then
              image_tags+=" -t ${{ needs.build-and-push.outputs.manifest_operator_alibabacloud_secondary }}"
            fi
          elif [ "${image_name}" == "operator-azure" ]; then
            platform_tags="${{ needs.build-and-push.outputs.image_operator_azure_amd64 }} ${{ needs.build-and-push.outputs.image_operator_azure_arm64 }}"
            primary_tag="${{ needs.build-and-push.outputs.manifest_operator_azure_primary }}"
            image_tags="-t ${{ needs.build-and-push.outputs.manifest_operator_azure_primary }}"
            if [ -n "${{ needs.build-and-push.outputs.manifest_operator_azure_secondary }}" ]; then
              image_tags+=" -t ${{ needs.build-and-push.outputs.manifest_operator_azure_secondary }}"
            fi
          elif [ "${image_name}" == "operator-generic" ]; then
            platform_tags="${{ needs.build-and-push.outputs.image_operator_generic_amd64 }} ${{ needs.build-and-push.outputs.image_operator_generic_arm64 }}"
            primary_tag="${{ needs.build-and-push.outputs.manifest_operator_generic_primary }}"
            image_tags="-t ${{ needs.build-and-push.outputs.manifest_operator_generic_primary }}"
            if [ -n "${{ needs.build-and-push.outputs.manifest_operator_generic_secondary }}" ]; then
              image_tags+=" -t ${{ needs.build-and-push.outputs.manifest_operator_generic_secondary }}"
            fi
          else
            echo "Invalid image name from matrix: ${image_name}"
            exit 1
          fi

          docker buildx imagetools create \
            $image_tags \
            $platform_tags

          # Wait for the image to appear.
          while ! docker buildx imagetools inspect $primary_tag; do
            sleep 1
          done

          # For some reason, if you just use {{ .Manifest.Digest }} in the go template, it'll just print
          # its normal text output. In this command, we format the variable output as `digest=<digest>` which can
          # then be piped directly to $GITHUB_OUTPUT.
          output="$(docker buildx imagetools inspect $primary_tag --format 'digest={{ .Manifest.Digest }}')"
          echo $output >> $GITHUB_OUTPUT

          echo primary_tag=$primary_tag >> $GITHUB_OUTPUT

      - name: Image Release Digest
        shell: bash
        run: |
          mkdir -p image-digest/
          job_name=${{ matrix.name }}
          job_name_capital=${job_name^^}
          job_name_underscored=${job_name_capital//-/_}
          echo "${job_name_underscored}_DIGEST := \"${{ steps.docker_manifest.outputs.digest }}\"" > image-digest/makefile-digest.txt

          echo "### ${{ matrix.name }}" > image-digest/${{ matrix.name }}.txt
          echo "" >> image-digest/${{ matrix.name }}.txt
          echo "\`${{ steps.docker_manifest.outputs.primary_tag }}@${{ steps.docker_manifest.outputs.digest }}\`" >> image-digest/${{ matrix.name }}.txt
          echo "" >> image-digest/${{ matrix.name }}.txt

      # Upload artifact digests
      - name: Upload artifact digests
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: image-digest ${{ matrix.name }}
          path: image-digest

  image-digests:
    name: Display Digests
    runs-on: ubuntu-24.04
    needs: [build-image-list, create-manifest]
    steps:
      - name: Downloading Image Digests
        shell: bash
        run: |
          mkdir -p image-digest/

      - name: Download digests of all images built
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
        with:
          path: image-digest/
          pattern: "*image-digest *"

      - name: Image Digests Output
        shell: bash
        run: |
          cd image-digest/
          echo "## Docker Manifests" > ../image-digest-output.txt
          echo "" >> ../image-digest-output.txt
          find -type f -not -name "makefile-digest.txt" | sort | xargs -d '\n' cat >> ../image-digest-output.txt

      - name: Image Makefile Digests
        shell: bash
        run: |
          cd image-digest/
          echo "# File generated by .github/workflows/enterprise-build-images-releases-fips.yaml; DO NOT EDIT." > ../Makefile.digests
          echo "# Copyright (C) Isovalent, Inc. - All Rights Reserved." >> ../Makefile.digests
          echo "" >> ../Makefile.digests
          # shellcheck disable=SC2016
          find -type f  -name "makefile-digest.txt" | sort | xargs -d '\n' awk '{print "export " $0}' >> ../Makefile.digests

      # Upload artifact digests
      - name: Upload artifact digests
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: image-digest-output.txt-${{ needs.build-image-list.outputs.image_tag }}
          path: image-digest-output.txt

      # Upload artifact digests
      - name: Upload artifact digests
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: Makefile.digests-${{ needs.build-image-list.outputs.image_tag }}
          path: Makefile.digests
