on:
  pull_request:
    branches:
      - 'main-ce'
  push:
    tags:
      - 'enterprise/cilium-cli/v[0-9]+.[0-9]+.[0-9]+-cee.[0-9]+'

name: Create cilium-cli CEE release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1

      - name: Cleanup Disk space in runner
        uses: ./.github/actions/disk-cleanup

      - name: Get image tag
        id: tag
        run: |
          tag=${GITHUB_REF##*/}
          oss_tag=$(echo $tag | cut -d "-" -f 1)
          echo "tag=$tag" >> $GITHUB_OUTPUT
          echo "oss_tag=$oss_tag" >> $GITHUB_OUTPUT

      - name: Set up Go
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
        with:
          go-version-file: 'go.mod'

      - name: Generate artifacts
        run: |
          git config --global url."https://${{ secrets.ISOVALENT_BOT_READ_PRIVATE_REPOSITORIES }}:@github.com/".insteadOf "https://github.com/"
          git config --global --add url."https://${{ secrets.ISOVALENT_BOT_READ_PRIVATE_REPOSITORIES }}:@github.com/".insteadOf "git@github.com:"
          cd cilium-cli
          make release

      - name: Create a Release
        if: github.event_name == 'push'
        uses: softprops/action-gh-release@5be0e66d93ac7ed76da52eca8bb058f665c3a5fe # v2
        with:
          repository: isovalent/cilium-cli-releases
          name: ${{ steps.tag.outputs.tag }}
          tag_name: ${{ steps.tag.outputs.tag }}
          # Need to use PAT with "repo" access to create a release in another repo.
          token: ${{ secrets.ISOVALENT_RELEASE_BOT_TOKEN }}
          draft: true
          files: |
            cilium-cli/release/*
          body: |
            # cilium-cli ${{ steps.tag.outputs.tag }} release

            This release is based on ${{ steps.tag.outputs.oss_tag }} cilium-cli
            and adds sysdump collectors and connectivity tests that are specific
            to Isovalent Enterprise for Cilium.

            Future releases might see additional enterprise-specific features.
