on:
  workflow_dispatch:
    inputs:
      ref_name:
        description: 'git reference'
        required: true
  push:
    tags:
      - 'v*'

name: Create a Hubble CLI Release

env:
  # renovate: datasource=golang-version depName=go
  go_version: 1.23.3

jobs:
  build:
    name: Create a Hubble CLI Release
    runs-on: ubuntu-24.04
    environment: release-hubble-cli
    steps:
      - name: Checkout Code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          ref: ${{ inputs.ref_name || github.sha }}
          persist-credentials: false

      - name: Set up Go
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version: ${{ env.go_version }}

      - name: Generate Artifacts
        run: |
          make -C hubble release

      - name: Get token
        id: get_token
        uses: cilium/actions-app-token@61a6271ce92ba02f49bf81c755685d59fb25a59a # v0.21.1
        with:
          APP_ID: ${{ secrets.HUBBLE_READ_WRITE_BOT_APP_ID }}
          APP_PEM: ${{ secrets.HUBBLE_READ_WRITE_BOT_APP_PEM_KEY }}

      - name: Publish a Draft Release
        uses: softprops/action-gh-release@c062e08bd532815e2082a85e87e3ef29c3e6d191 # v2.0.8
        with:
          repository: ${{ vars.HUBBLE_RELEASES_REPO }}
          name: ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          token: ${{ steps.get_token.outputs.app_token }}
          draft: true
          files: |
            hubble/release/*
          body: |
            TODO: Replace with actual release notes.
