on:
  workflow_dispatch:
    inputs:
      ref_name:
        description: 'git reference'
        required: true
  push:
    tags:
      - 'v*'

name: Create a Hubble CLI Release

permissions:
  contents: read
  id-token: write

env:
  # renovate: datasource=golang-version depName=go
  go_version: 1.23.3

jobs:
  build:
    name: Create a Hubble CLI Release
    runs-on: ubuntu-24.04
    environment: release-hubble-cli
    steps:
      - name: Checkout Code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          ref: ${{ inputs.ref_name || github.sha }}
          persist-credentials: false

      - name: Set up Go
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version: ${{ env.go_version }}

      - name: Generate Artifacts
        run: |
          make -C hubble release

      - name: Get Github App Credentials from Vault
        uses: hashicorp/vault-action@7709c609789c5e27b757a85817483caadbb5939a # v3.3.0
        with:
          url: ${{ vars.VAULT_URL }}
          method: jwt
          namespace: ${{ vars.VAULT_NAMESPACE }}
          secrets: |
            secret/data/observability/${{ github.repository_owner }} github_app_pem | HUBBLE_READ_WRITE_BOT_APP_PEM;
            secret/data/observability/${{ github.repository_owner }} github_app_id | HUBBLE_READ_WRITE_BOT_APP_ID;

      - name: Generate Token for Hubble Releases Repo
        id: generate-token
        uses: actions/create-github-app-token@3ff1caaa28b64c9cc276ce0a02e2ff584f3900c5 # v2.0.2
        with:
          app-id: ${{ env.HUBBLE_READ_WRITE_BOT_APP_ID }}
          private-key: ${{ env.HUBBLE_READ_WRITE_BOT_APP_PEM }}
          owner: ${{ github.repository_owner }}
          repositories: |
            ${{ vars.HUBBLE_RELEASES_REPO_NAME }}
          permissions-contents: write
          permissions-workflows: write

      - name: Publish a Draft Release
        uses: softprops/action-gh-release@c062e08bd532815e2082a85e87e3ef29c3e6d191 # v2.0.8
        with:
          repository: ${{ github.repository_owner }}/${{ vars.HUBBLE_RELEASES_REPO_NAME }}
          name: ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          token: ${{ steps.generate-token.outputs.token }}
          draft: true
          files: |
            hubble/release/*
          body: |
            TODO: Replace with actual release notes.
