{{- if and .Values.operator.enabled .Values.serviceAccounts.operator.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: enterprise-cilium-operator
  labels:
    app.kubernetes.io/part-of: cilium
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
rules:
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - update
  resourceNames:
  - isovalentmulticastgroups.isovalent.com
  - isovalentmulticastnodes.isovalent.com
  - isovalentegressgatewaypolicies.isovalent.com
  - isovalentfqdngroups.isovalent.com
  - isovalentpodnetworks.isovalent.com
  - isovalentsrv6egresspolicies.isovalent.com
  - isovalentsrv6sidmanagers.isovalent.com
  - isovalentsrv6locatorpools.isovalent.com
  - isovalentvrfs.isovalent.com
  - isovalentbfdprofiles.isovalent.com
  - isovalentbfdnodeconfigs.isovalent.com
  - isovalentbfdnodeconfigoverrides.isovalent.com
  - isovalentclusterwideencryptionpolicies.isovalent.com
  - isovalentnetworkpolicies.isovalent.com
  - isovalentclusterwidenetworkpolicies.isovalent.com
{{- if .Values.enterprise.bgpControlPlane.enabled }}
  - isovalentbgpclusterconfigs.isovalent.com
  - isovalentbgppeerconfigs.isovalent.com
  - isovalentbgpadvertisements.isovalent.com
  - isovalentbgpnodeconfigs.isovalent.com
  - isovalentbgpnodeconfigoverrides.isovalent.com
  - isovalentbgpvrfconfigs.isovalent.com
  - isovalentvrfs.isovalent.com
{{- end }}
{{- if .Values.enterprise.loadbalancer.enabled }}
  - lbservices.isovalent.com
  - lbbackendpools.isovalent.com
  - lbvips.isovalent.com
  - lbdeployments.isovalent.com
{{- end }}
{{- if .Values.enterprise.privateNetworks.enabled }}
  - clusterwideprivatenetworks.isovalent.com
  - privatenetworkendpointslices.isovalent.com
  - privatenetworkexternalendpoints.isovalent.com
{{- end }}
{{- if .Values.enterprise.loadbalancer.gatewayAPI.enabled }}
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - gatewayclasses
  - gateways
  - httproutes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - gatewayclasses
  verbs:
  - patch
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - gatewayclasses/status
  - gateways/status
  - httproutes/status
  verbs:
  - update
  - patch
- apiGroups:
  - cilium.io
  resources:
  - ciliumgatewayclassconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cilium.io
  resources:
  - ciliumgatewayclassconfigs/status
  verbs:
  - update
  - patch
{{- end }}
- apiGroups:
  - isovalent.com
  resources:
  - isovalentsrv6locatorpools
  - isovalentfqdngroups
  verbs:
  - get
  - list
  - watch
{{- if .Values.enterprise.loadbalancer.enabled }}
- apiGroups:
  - isovalent.com
  resources:
  - lbservices/status
  - lbservices/finalizers
  - lbbackendpools/status
  - lbbackendpools/finalizers
  - lbvips/status
  - lbvips/finalizers
  - lbdeployments/status
  verbs:
  - get
  - list
  - watch
  - update
{{- end }}
- apiGroups:
  - isovalent.com
  resources:
  - isovalentsrv6sidmanagers
{{- if .Values.enterprise.loadbalancer.enabled }}
  - lbservices
  - lbbackendpools
  - lbvips
  - lbdeployments
{{- end }}
  verbs:
  - get
  - list
  - watch
{{- if or .Values.enterprise.srv6.locatorPoolEnabled }}
  - create
  - update
  - delete
  - patch
{{- end }}
{{- if or .Values.enterprise.bgpControlPlane.enabled }}
- apiGroups:
  - isovalent.com
  resources:
  - isovalentbgpclusterconfigs
  - isovalentbgppeerconfigs
  - isovalentbgpadvertisements
  - isovalentbgpnodeconfigs
  - isovalentbgpnodeconfigoverrides
  - isovalentbgpvrfconfigs
  - isovalentvrfs
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
  - patch
# Cilium BGP CRDs are managed by Isovalent BGP Operator, so we require the following permissions
# to modify them.
- apiGroups:
  - cilium.io
  resources:
  - ciliumbgpclusterconfigs
  - ciliumbgppeerconfigs
  - ciliumbgpadvertisements
  - ciliumbgpnodeconfigoverrides
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
  - patch
- apiGroups:
  - isovalent.com
  resources:
  - isovalentbgpclusterconfigs/status
  - isovalentbgppeerconfigs/status
  verbs:
  - update
{{- end }}
{{- if or .Values.enterprise.bfd.enabled }}
- apiGroups:
  - isovalent.com
  resources:
  - isovalentbfdnodeconfigs
  - isovalentbfdnodeconfigoverrides
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
- apiGroups:
  - isovalent.com
  resources:
  - isovalentbfdprofiles
  verbs:
  - get
  - list
  - watch
{{- end }}
- apiGroups:
  - cilium.io
  resources:
  - ciliumcidrgroups
  verbs:
  - create
  - patch
  - delete
- apiGroups:
  - isovalent.com
  resources:
  - isovalentegressgatewaypolicies
  verbs:
  # to allow IEGP watcher
  - watch
  - list
- apiGroups:
  - isovalent.com
  resources:
  - isovalentegressgatewaypolicies/status
  verbs:
  # to allow IEGPs status.groupStatus updates
  - update
{{- if .Values.enterprise.multiNetwork.enabled }}
- apiGroups:
    - isovalent.com
  resources:
    - isovalentpodnetworks
  verbs:
    - create
{{- end }}
# TODO: Wrap within Helm value for L7LB CRD and LBFrontend
{{- if .Values.enterprise.loadbalancer.enabled }}
- apiGroups:
  - ""
  resources:
  - services
  - endpoints
  verbs:
  - create
  - update
  - delete
- apiGroups:
  - "discovery.k8s.io"
  resources:
  - endpointslices
  - endpointslices/restricted
  verbs:
  - create
  - update
  - delete
- apiGroups:
  - ""
  resources:
  # Read all Secrets for Secret Sync into Envoy Secret Namespace
  - secrets
  verbs:
  - get
  - list
  - watch
{{- end }}
- apiGroups:
  - cilium.io
  resources:
  - ciliumenvoyconfigs
  verbs:
  - watch
  - get
  - list
  - create
  - update
  - delete
{{- if .Values.enterprise.loadbalancer.enabled }}
- apiGroups:
  - ""
  resources:
  - pods/exec
  verbs:
  - create
{{- end }}
- apiGroups:
  - isovalent.com
  resources:
  - isovalentnetworkpolicies
  - isovalentclusterwidenetworkpolicies
  verbs:
  # Create auto-generated INPs and ICNPs from Policies that have 'toGroups'
  - create
  - update
  - deletecollection
  # To update the status of the INPs and ICNPs
  - patch
  - get
  - list
  - watch
- apiGroups:
  - isovalent.com
  resources:
  - isovalentnetworkpolicies/status
  - isovalentclusterwidenetworkpolicies/status
  verbs:
  # Update the auto-generated INPs and ICNPs status.
  - patch
  - update
{{- end }}
