// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: extensions.proto

package extensions

import (
	aggregation "github.com/cilium/cilium/enterprise/pkg/hubble/aggregation/api/aggregation"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetFlowsRequestExtension struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Aggregation   *aggregation.Aggregation `protobuf:"bytes,1,opt,name=aggregation,proto3" json:"aggregation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFlowsRequestExtension) Reset() {
	*x = GetFlowsRequestExtension{}
	mi := &file_extensions_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFlowsRequestExtension) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFlowsRequestExtension) ProtoMessage() {}

func (x *GetFlowsRequestExtension) ProtoReflect() protoreflect.Message {
	mi := &file_extensions_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFlowsRequestExtension.ProtoReflect.Descriptor instead.
func (*GetFlowsRequestExtension) Descriptor() ([]byte, []int) {
	return file_extensions_proto_rawDescGZIP(), []int{0}
}

func (x *GetFlowsRequestExtension) GetAggregation() *aggregation.Aggregation {
	if x != nil {
		return x.Aggregation
	}
	return nil
}

var File_extensions_proto protoreflect.FileDescriptor

const file_extensions_proto_rawDesc = "" +
	"\n" +
	"\x10extensions.proto\x12\x14isovalent.extensions\x1a\x1daggregation/aggregation.proto\"e\n" +
	"\x18GetFlowsRequestExtension\x12I\n" +
	"\vaggregation\x18\x01 \x01(\v2'.isovalent.flow.aggregation.AggregationR\vaggregationB4Z2github.com/cilium/cilium/enterprise/api/extensionsb\x06proto3"

var (
	file_extensions_proto_rawDescOnce sync.Once
	file_extensions_proto_rawDescData []byte
)

func file_extensions_proto_rawDescGZIP() []byte {
	file_extensions_proto_rawDescOnce.Do(func() {
		file_extensions_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_extensions_proto_rawDesc), len(file_extensions_proto_rawDesc)))
	})
	return file_extensions_proto_rawDescData
}

var file_extensions_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_extensions_proto_goTypes = []any{
	(*GetFlowsRequestExtension)(nil), // 0: isovalent.extensions.GetFlowsRequestExtension
	(*aggregation.Aggregation)(nil),  // 1: isovalent.flow.aggregation.Aggregation
}
var file_extensions_proto_depIdxs = []int32{
	1, // 0: isovalent.extensions.GetFlowsRequestExtension.aggregation:type_name -> isovalent.flow.aggregation.Aggregation
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_extensions_proto_init() }
func file_extensions_proto_init() {
	if File_extensions_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_extensions_proto_rawDesc), len(file_extensions_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_extensions_proto_goTypes,
		DependencyIndexes: file_extensions_proto_depIdxs,
		MessageInfos:      file_extensions_proto_msgTypes,
	}.Build()
	File_extensions_proto = out.File
	file_extensions_proto_goTypes = nil
	file_extensions_proto_depIdxs = nil
}
